### ISSUE TITLE
rewrite sql error when using keyGenerator and encrypt together

### ISSUE THREAD

**Issue by wangkang09** [apache/shardingsphere#10105]
shardingjdbc 4.1.1

Logic SQL: INSERT INTO rs_order  ( member_id,billno,email )  VALUES  ( ?,?,? )  

Actual SQL: db1 ::: INSERT INTO rs_order_1  ( member_id,billno,email, email_hash, email_plain , id)  VALUES  (?, ?, ?, ?, ?, ?) ::: 
[1, 1, UTJNS0lVSmdLa0R4WEtHUcDbeXenQrmrOnpZHD32TYA=, 2021041605424943106, 4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb32062c08170a05eeb8, 11]

but, expected actual sql parameter value is [1, 1, UTJNS0lVSmdLa0R4WEtHUcDbeXenQrmrOnpZHD32TYA=, ,4fc82b26aecb47d2868c4efbe3581732a3e7cbcc6c2efb32062c08170a05eeb8, 11, 2021041605424943106]

sorted sqlTokens:
![image](https://user-images.githubusercontent.com/41175635/114967974-00337a00-9ea8-11eb-8052-3427beb315ab.png)
parameters:
![image](https://user-images.githubusercontent.com/41175635/114968004-0cb7d280-9ea8-11eb-8d76-8f0f5e43fb33.png)

**Comment by tristaZero** [comment]
Could you try the 5.0.0-alpha?  I suppose we fixed it already.

**Comment by wangkang09** [comment]
alpha version can be used in production? could you give same  related information to help me persuade my leader

**Comment by wangkang09** [comment]
> Could you try the 5.0.0-alpha? I suppose we fixed it already.

alpha version can be used in production? could you give same related information to help me persuade my leader

**Comment by wangkang09** [comment]
> Hi we suggest users to try 5.0.0-alpha, since it fixed many issues of 4.x releases and supported more complex SQLs. Besides, more maintenance work will be done on this series.
think you for reply~
i wonder why this version has not been released。Is it because of advanced features, such as Scaling、 sidecar。or have some other reasons? and how long will it take to release?

**Comment by tristaZero** [comment]
Hi 5.0.0-alpha has been released for a long time. Maybe you have no interests on Scaling etc. But this issue was fixed from 5.x release.

**Comment by wangkang09** [comment]
> Hi 5.0.0-alpha has been released for a long time. Maybe you have no interests on Scaling etc. But this issue was fixed from 5.x release.
sorry, what i mean is how long will 5.0.0 version take to release。not 5.0.0-alpha, not 5.0.0-beta。and i wonder what is the diff between them

**Comment by wangkang09** [comment]
> Hi 5.0.0-alpha has been released for a long time. Maybe you have no interests on Scaling etc. But this issue was fixed from 5.x release.

recently I started using 5.0.0-alpha，it really better than 4.1.1。and i want to persuade my leader to use 5.0.0-alpha。so，I need to collect some useful information about 5.0.0

**Comment by wangkang09** [comment]
> Hi we suggest users to try 5.0.0-alpha, since it fixed many issues of 4.x releases and supported more complex SQLs. Besides, more maintenance work will be done on this series.

i use 5.0.0-alpha,it has this problem too。
my config:
spring:
  shardingsphere:
    datasource:
      names: db0,db1,db0-slave,db1-slave
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        username: sa
        password: ""
        initialSize: 5
        minIdle: 5
        maxActive: 500
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 20000
        minEvictableIdleTimeMillis: 200000
        maxEvictableIdleTimeMillis: 200000
      db0:
        url: jdbc:h2:mem:db0;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db0-slave:
        url: jdbc:h2:mem:db0-slave;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db1:
        url: jdbc:h2:mem:db1;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db1-slave:
        url: jdbc:h2:mem:db1-slave;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
    rules:
      sharding:
        tables:
          rs_order:
            actual-data-nodes: db0.rs_order_0,db0.rs_order_2,db1.rs_order_1,db1.rs_order_3
          rs_order_hint:
            actual-data-nodes: db0.rs_order_0,db0.rs_order_2,db1.rs_order_1,db1.rs_order_3
            table-strategy:
              complex:
                sharding-columns: member_id,billno
                sharding-algorithm-name: table-hint
            database-strategy:
              complex:
                sharding-columns: member_id,billno
                sharding-algorithm-name: db-hint
        default-database-strategy:
          complex:
            sharding-columns: member_id,billno
            sharding-algorithm-name: db-complex
        default-table-strategy:
          complex:
            sharding-columns: member_id,billno
            sharding-algorithm-name: table-complex
        default-key-generate-strategy:
          column: id
          key-generator-name: rs-order-generator
        #sharding 中的 key generator 配置
        key-generators:
          # rs-order-generator 为 generator 的名字。供上面的 key-generator-name 使用
          rs-order-generator:
            type: DbSnowflakeKeyGenerator
            props:
              key.snow.type: rs_order # 传入 DbSnowflakeKeyGenerator 对应的 generator 实例
        sharding-algorithms:
          table-complex:
            type: tableComplex
            props:
              xx: xx # https://github.com/apache/shardingsphere/pull/8331
          db-complex:
            type: dbComplex
            props:
              xx: xx
          table-hint:
            type: tableHint
            props:
              xx: xx
          db-hint:
            type: dbHint
            props:
              xx: xx
      replica-query:
        data-sources:
          db0:
            primary-data-source-name: db0
            replica-data-source-names: db0-slave
            load-balancer-name: round-robin
          db1:
            primary-data-source-name: db1
            replica-data-source-names: db1-slave
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              xx: xx # https://github.com/apache/shardingsphere/pull/8331
      encrypt:
        tables:
          rs_order:
            columns:
              email:
                plain-column: email_plain
                cipher-column: email
                assisted-query-column: email_hash
                encryptor-name: my-aes
        encryptors:
          my-aes:
            type: my-AssistQuery
            props:
              business-key: 'privateDWK'
          my-aes1:
            type: my-AssistQuery
            props:
              business-key: 'privateDWK'
#      shadow:
#        column: shadow
#        source-data-source-names: db0,db1
#        shadow-data-source-names: db0-shadow,db1-shadow
    props:
      sql-show: true
      query-with-cipher-column: true # 是否使用密文查询

**Comment by wangkang09** [comment]
> Hi 5.0.0-alpha has been released for a long time. Maybe you have no interests on Scaling etc. But this issue was fixed from 5.x release.

i use 5.0.0-alpha. it has this problem too.
```yaml
spring:
  shardingsphere:
    datasource:
      names: db0,db1,db0-slave,db1-slave
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        username: sa
        password: ""
        initialSize: 5
        minIdle: 5
        maxActive: 500
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 20000
        minEvictableIdleTimeMillis: 200000
        maxEvictableIdleTimeMillis: 200000
      db0:
        url: jdbc:h2:mem:db0;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db0-slave:
        url: jdbc:h2:mem:db0-slave;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db1:
        url: jdbc:h2:mem:db1;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
      db1-slave:
        url: jdbc:h2:mem:db1-slave;DB_CLOSE_ON_EXIT=FALSE;database_to_upper=false
    rules:
      sharding:
        tables:
          rs_order:
            actual-data-nodes: db0.rs_order_0,db0.rs_order_2,db1.rs_order_1,db1.rs_order_3
          rs_order_hint:
            actual-data-nodes: db0.rs_order_0,db0.rs_order_2,db1.rs_order_1,db1.rs_order_3
            table-strategy:
              complex:
                sharding-columns: member_id,billno
                sharding-algorithm-name: table-hint
            database-strategy:
              complex:
                sharding-columns: member_id,billno
                sharding-algorithm-name: db-hint
        default-database-strategy:
          complex:
            sharding-columns: member_id,billno
            sharding-algorithm-name: db-complex
        default-table-strategy:
          complex:
            sharding-columns: member_id,billno
            sharding-algorithm-name: table-complex
        default-key-generate-strategy:
          column: id
          key-generator-name: rs-order-generator
        #sharding 中的 key generator 配置
        key-generators:
          # rs-order-generator 为 generator 的名字。供上面的 key-generator-name 使用
          rs-order-generator:
            type: DbSnowflakeKeyGenerator
            props:
              key.snow.type: rs_order # 传入 DbSnowflakeKeyGenerator 对应的 generator 实例
        sharding-algorithms:
          table-complex:
            type: tableComplex
            props:
              xx: xx # https://github.com/apache/shardingsphere/pull/8331
          db-complex:
            type: dbComplex
            props:
              xx: xx
          table-hint:
            type: tableHint
            props:
              xx: xx
          db-hint:
            type: dbHint
            props:
              xx: xx
      replica-query:
        data-sources:
          db0:
            primary-data-source-name: db0
            replica-data-source-names: db0-slave
            load-balancer-name: round-robin
          db1:
            primary-data-source-name: db1
            replica-data-source-names: db1-slave
            load-balancer-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              xx: xx # https://github.com/apache/shardingsphere/pull/8331
      encrypt:
        tables:
          rs_order:
            columns:
              email:
                plain-column: email_plain
                cipher-column: email
                assisted-query-column: email_hash
                encryptor-name: my-aes
        encryptors:
          my-aes:
            type: my-AssistQuery
            props:
              business-key: 'privateDWK'
          my-aes1:
            type: my-AssistQuery
            props:
              business-key: 'privateDWK'
#      shadow:
#        column: shadow
#        source-data-source-names: db0,db1
#        shadow-data-source-names: db0-shadow,db1-shadow
    props:
      sql-show: true
      query-with-cipher-column: true # 是否使用密文查询
```
