### ISSUE TITLE
read-write-splitting doesn't work

### ISSUE THREAD

**Issue by enoera00** [apache/shardingsphere#10127]
I use spring-boot 2.2.9.RELEASE , mybatis 2.1.3 and sharding-sphere 5.0.0-alpha, below is my config file:
**application.yml**
```
server:
  port: 8080
spring:
  profiles:
    active: rw
  application: sharding-sphere-demo
  shardingsphere:
    props:
      sql-show: true
      sql-simple: true
mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.x.demo.sharding.sphere.model
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
```
**application-rw.yml**
```
spring:
  shardingsphere:
    datasource:
      names: master,slave,slavf
      common:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: 123456
      master:
        jdbc-url: jdbc:mysql://localhost:3306/ssds?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
      slave:
        jdbc-url: jdbc:mysql://localhost:3307/ssds?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
      slavf:
        jdbc-url: jdbc:mysql://localhost:3308/ssds?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
    rules:
      read-write-splitting:
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
        data-sources:
          ssds:
            write-data-source-name: master
            read-data-source-names: slave,slavf
            load-balancer-name: round-robin
```
but when i run a query api, sql always execute in master db, i have checked my config many times, they are correct. I really don't know what went wrong, please help me, thanks.

**Comment by tristaZero** [comment]
Hi could you set `sql-show` = `true`? That way, we can get the routing details. BTW, what's your query SQL?

**Comment by hilton1977** [comment]
you can see 5.0.0-alpha [expample ](https://github.com/apache/shardingsphere/blob/5.0.0-alpha/examples/shardingsphere-jdbc-example/sharding-example/sharding-spring-boot-mybatis-example/src/main/resources/application-replica-query.properties)
5.0.0-alpha version properties had change 
~~write-data-source-name~~  -> **primary-data-source-name**  
~~replica-data-source-names~~ -> **replica-data-source-names**  

you can change it and try again

**Comment by tristaZero** [comment]
Thanks for your comment @hilton1977

**Comment by kxw07** [comment]
Not work.
And it always uses spring.shardingsphere.datasource.names the first value for query.

My yaml file content:
```yaml
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
      names: write, read1, read2
      write:
        jdbc-url: jdbc:mysql://localhost:3316/java_course
        username: root
        password:
      read1:
        jdbc-url: jdbc:mysql://localhost:3316/java_course
        username: root
        password:
      read2:
        jdbc-url: jdbc:mysql://localhost:3326/java_course
        username: root
        password:
    rules:
      readwrite-splitting:
        dataSources:
          group1:
            primary-data-source-name: write
            replica-data-source-names: read1, read2
            load-balancer-name: round_robin
          load-balancers:
            round_robin:
              type: ROUND_ROBIN
```

**Comment by kxw07** [comment]
Updated:

Using sharding-sphere 5.0.0-beta with yaml below load-balancer works.

```yaml
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      names: write,read1,read2
      write:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3316/java_course
        username: root
        password: ''
      read1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3316/java_course
        username: root
        password: ''
      read2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://localhost:3326/java_course
        username: root
        password: ''
    rules:
      readwrite-splitting:
        dataSources:
          group1:
            writeDataSourceName: write
            readDataSourceNames: read1, read2
            load-balancer-name: round_robin
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
```
