### ISSUE TITLE
Exception occurred when inserting values into a table with varchar primary key

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#10131]
### Which version of ShardingSphere did you use?
master branch.
But I think this issue exists in previous versions.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior

```yaml
rules:
- !SHARDING
  tables:
    t_config:
      actualDataNodes: hello_ss_0.t_config_0
  defaultTableStrategy:
    none:
```

```sql
create table t_config (
  config_name varchar(100) primary key,
  config_value varchar(100)
);
insert into t_config (config_name, config_value) values ('key1', 'value1');
```

### Actual behavior
```
Bad value for type long : key1
```
