### ISSUE TITLE
[API Change]  Move the user configuration to authority rule

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#10251]
Hi, community,

This issue is to do API change of `server.yaml` of ShardingProxy. More precisely to say, we plan to move the `user` configuration to the `authority` rule module. Hope you can have a try and get 👍 .

### Target
Please change the configuration of `server.yaml` from
```yaml
users:
  - root@%:root
  - sharding@:sharding
rules:
  - !AUTHORITY
    provider:
      type: NATIVE
```
**TO**
```yaml
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: NATIVE
```

### How?
There are two necessary sections to achieve it. 

#### The refactoring of Yaml configuration
1 Move `users` from `YamlProxyServerConfiguration` to `YamlAuthorityRuleConfiguration`
2 Move `YamlUsersConfigurationConverter` handling from `YamlProxyConfigurationSwapper` to `AuthorityRuleConfigurationYamlSwapper`
3 Move `users` from `ProxyConfiguration` to `AuthorityRuleConfiguration`
4 Remove `persistUsers(users, isOverwrite);` of `RegistryCenter`
5 Move the relevant Unit test classes to corresponding packages.

#### The change of User and authority initialization
1 Remove `users`, which has been stored in `AuthorityRuleConfiguration` from `MetaDataContextsBuilder`
2 Remove `users` from the signature of `ShardingSphereRulesBuilder.buildGlobalRules()` 
3 Put `users` into `AuthorityRule` from `AuthorityRuleConfiguration`
4 Fix the Unit tests
