### ISSUE TITLE
YAML GlobalRuleConfiguration is incorrect in registry center after create user executed

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#10659]
```
[zk: localhost:2181(CONNECTED) 9] get /governance_ds/rules
!!map
- !AUTHORITY
  provider:
    type: NATIVE
  users:
  - test@%:test
  - sharding@%:sharding
  - test4@%:'test4'

```
The user `test4` should be `- test4@%:test4`
