### ISSUE TITLE
PostgreSQL Proxy doesn't support Parse & Describe only

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#10814]
### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy

### Expected behavior

Expected server response:
```
PostgreSQL
    Type: Parse completion
    Length: 4
PostgreSQL
    Type: Parameter description
    Length: 10
    Parameters: 1
        Type OID: 20
PostgreSQL
    Type: Row description
    Length: 143
    Field count: 5
        Column name: order_id
            Table OID: 24623
            Column index: 1
            Type OID: 20
            Column length: 8
            Type modifier: -1
            Format: Text (0)
        Column name: create_time
            Table OID: 24623
            Column index: 2
            Type OID: 1114
            Column length: 8
            Type modifier: -1
            Format: Text (0)
        Column name: user_id
            Table OID: 24623
            Column index: 3
            Type OID: 20
            Column length: 8
            Type modifier: -1
            Format: Text (0)
        Column name: order_name
            Table OID: 24623
            Column index: 4
            Type OID: 1043
            Column length: -1
            Type modifier: 1004
            Format: Text (0)
        Column name: amount
            Table OID: 24623
            Column index: 5
            Type OID: 23
            Column length: 4
            Type modifier: -1
            Format: Text (0)
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: Idle (73)
```
### Actual behavior

Client sent:
```
PostgreSQL
    Type: Parse
    Length: 42
    Statement: 
    Query: select * from t_order limit $1
    Parameters: 1
        Type OID: 0
PostgreSQL
    Type: Describe
    Length: 6
    Statement: 
PostgreSQL
    Type: Sync
    Length: 4
```

Proxy replied:
```
PostgreSQL
    Type: Parse completion
    Length: 4
PostgreSQL
    Type: Ready for query
    Length: 5
    Status: Idle (73)
```

The client sent `Describe`, but the proxy didn't reply the `RowDescription` or `NoData` packet.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```java
PreparedStatement preparedStatement = connection.prepareStatement("select * from t_order limit ?");
ResultSetMetaData metaData = preparedStatement.getMetaData();
```
