### ISSUE TITLE
Support encrypt route when config multiple data sources

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#10996]
## Background

Now encrypt can be used alone or in combination with other features, like sharding, readwrite-splitting, etc. When encrypt is used alone, it only supports a single data source, and does not support multiple data sources. When encrypt is used in combination, it does not support separate configuration of data sources, it must needs to rely on data sources that configured by other features.

Since `DistSQL` separates resources (data sources) and rules, there must be scenarios where there are multiple data sources when creating encrypt rules. Therefore, it is necessary to support multiple data sources and add routing logic to support multiple data source routing.

The new encrypt configuration is as follows:

```yaml
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000

rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptorName: aes_encryptor
        order_id:
          cipherColumn: order_cipher
          encryptorName: md5_encryptor
```

SS will route internally according to the single table rule and decide which data source to route to.

## Task

- [x] Encrypt configuration modification
- [x] Extract SingleTableRule load and route logic to infra module
- [x] Optimize routing logic when multiple features are used in combination
- [x] Add more test case to ensure correct routing logic
- [x] remove CreateTableEvent and DropTableEvent
- [x] enhance single table rule data source aggregation
- [x] Adjust the loading order and routing order of different rules
