### ISSUE TITLE
could shardingsphere provide the support for prometheus exporter

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#11167]
for the mojority, the proxy config may looks like following : 

```
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_0?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 10
    minPoolSize: 2
    maintenanceIntervalMilliseconds: 30000
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_1?serverTimezone=UTC&useSSL=false&characterEncoding=utf-8
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 10
    minPoolSize: 2
    maintenanceIntervalMilliseconds: 30000
```

and we could manipulate these datasource through proxy, that's really cool.however , if we want to export some other info to prometheus, seems proxy will not work .

just like mysql_exporter, this process will try to access the tables in shcema `information_schema` and `performance_schema` , if we launch the mysql_exporter , it will print the error like followings

```
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.589Z caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.file_events err="Error 1999: Unknown exception: [Can not get metaData by schemaName [performance_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.589Z caller=exporter.go:174 msg="Error from scraper" scraper=info_schema.innodb_cmp err="Error 1999: Unknown exception: [Can not get metaData by schemaName [information_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.590Z caller=exporter.go:174 msg="Error from scraper" scraper=global_status err="Error 1046: No database selected"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.590Z caller=exporter.go:174 msg="Error from scraper" scraper=info_schema.innodb_cmpmem err="Error 1999: Unknown exception: [Can not get metaData by schemaName [information_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.592Z caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.indexiowaits err="Error 1999: Unknown exception: [Can not get metaData by schemaName [performance_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.594Z caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.tableiowaits err="Error 1999: Unknown exception: [Can not get metaData by schemaName [performance_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.595Z caller=exporter.go:174 msg="Error from scraper" scraper=binlog_size err="Error 1999: Unknown exception: [Can not get metaData by schemaName [null].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.646Z caller=exporter.go:174 msg="Error from scraper" scraper=auto_increment.columns err="Error 1999: Unknown exception: [Can not get metaData by schemaName [information_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.649Z caller=exporter.go:174 msg="Error from scraper" scraper=perf_schema.tablelocks err="Error 1999: Unknown exception: [Can not get metaData by schemaName [performance_schema].]"
7月 06 10:04:48 ss-proxy mysqld_exporter[24084]: level=error ts=2021-07-06T02:04:48.654Z caller=exporter.go:174 msg="Error from scraper" scraper=slave_status err="Error 1999: Unknown exception: [null]"
```

so , does the sphere team have that plan to support the prometheus exporter for proxy ? so that the proxy could be easily to monitor. 

thank you.
