### ISSUE TITLE
Use SPI to introduce DistMetaDataPersistRepository

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11499]
- [x] Add SPI interface of DistMetaDataPersistRepository
- [x] Make LocalDistMetaDataPersistRepository as default one, the code hook is in `DistMetaDataPersistRepositoryFactory`, please search `TODO`
- [x] Consider about add more DistMetaDataPersistRepository type, such as: Database, Ceph etc...

This issue is depended on #11498

**Comment by menghaoranss** [comment]
Hi, @terrymanu 

I just consider defining the user API of dist meta data persist as a global rule as follows:
```
- !DIST_METADATA_PERSIST(or DIST_METADATA_PERSISTENCE)
    type: Local
    props:
      path: xxxx
```
We can also define other types such as Database:
```
- !DIST_METADATA_PERSIST(or DIST_METADATA_PERSISTENCE)
    type: Database
    props:
      url: xxxx
      username:xxx
      ...
```

any suggestions?
