### ISSUE TITLE
Make governance from independent config to plugged rules

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11669]
Governance module is the main feature of the product for now. 
I just consider about refactor it to plugged features by the plugged architecture.

The tasks are:

- [x] Proxy YAML configuration change

The current YAML configuration for proxy is:

```yaml
governance:
  registryCenter:
    type: ZooKeeper
    namespace: governance_ds
    serverLists: localhost:2181
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:root
    provider:
      type: NATIVE
```

It should be changed to:

```yaml
rules:
  - !AUTHORITY
    users:
      - root@%:root
    provider:
      type: NATIVE
  
  - !GOVERNANCE
    registryCenter:
      type: ZooKeeper
      namespace: governance_ds
      serverLists: localhost:2181
    overwrite: false
```

- [ ] JDBC YAML configuration change
- [ ] JDBC java API change
- [ ] JDBC spring namespace change
- [ ] JDBC spring boot starter change
- [ ] Move governance module from top level to the submodule of feature
- [ ] Adjust DistMetadataPersistService as plugged rule
- [ ] Resolve conflict if independent DistMetadataPersistService rule and governance rule in the same config file

After finish all tasks, I prefer to discuss about change governance module name to cluster.
