### ISSUE TITLE
Consider about redesign DistMetaDataPersistRule and governance module 

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#11709]
The governance module is depend on DistMetaDataPersistRule which is the kernel rule.
The relationship of DistMetaDataPersistRule and governance module are little mess, the current config in YAML is:

```yaml
rules:
  - !DIST_METADATA_PERSIST
    type: Local
    props:
      xxx: xxx
    overwrite: false

  - !GOVERNANCE
    registryCenter:
      type: ZooKeeper
      namespace: governance_ds
      serverLists: localhost:2181
      props:
        retryIntervalMilliseconds: 500
        timeToLiveSeconds: 60
        maxRetries: 3
        operationTimeoutMilliseconds: 500
    overwrite: false
```

It is conflict If `!DIST_METADATA_PERSIST` and `!GOVERNANCE` in same YAML file, and we need to resolve as `!GOVERNANCE` as high priority and ignore `!DIST_METADATA_PERSIST`.
It is difficult to understand.

![image](https://user-images.githubusercontent.com/5516298/128639496-62a9998a-a068-4867-9499-9baf000996d6.png)

I prefer to discuss the new design. How about to create a new rule interface `PersistRule`, there are 3 type `none`, `stand-alone` and `cluster`, `stand-alone` is  mapped to `DistMetaDataPersistRule`, and `cluster` is  mapped to `GovernanceRule`.

It is better to push down `DistMetaDataPersistRule` and `GovernanceRule` to type of `PersistRule`, and we just provide storage strategy for `Zookeeper`, `Etcd` and `LocalFile`.
In the other words, there a 3 level of the configuration, which are `rule (PersistRule)`, `type(none | stand-alone | cluster)` and `storage strategy(Zookeeper | Etcd | LocalFile)`

the modified config in YAML should be:

```yaml
rules:
  - !PERSIST
    type: Standalone
    storage-strategy:
      type: LocalFile
      props:
        xxx: xxx
    overwrite: false
```

or 

```yaml
rules:
  - !PERSIST
    type: Cluster
    storage-strategy:
      type: ZooKeeper
      namespace: governance_ds
      serverLists: localhost:2181
      props:
        retryIntervalMilliseconds: 500
        timeToLiveSeconds: 60
        maxRetries: 3
        operationTimeoutMilliseconds: 500
    overwrite: false
```

or 

```yaml
rules:
  - !PERSIST
    type: None
```

![image](https://user-images.githubusercontent.com/5516298/128640007-75b8cac3-6d6d-43d2-a009-f5abad79c04c.png)

Please advice me, thank you.

**Comment by terrymanu** [comment]
Another solution is use running mode to instead of unified rule (PreConditionRule).
There are 3 mode `Memory`, `Standalone` and `Cluster` to map original `None`, `stand-alone` and `cluster` types.

The YAML config is like:


```yaml
mode:
    type: Memory
```

or

```yaml
mode:
    type: Standalone
    storage-strategy:
      type: LocalFile
      props:
        xxx: xxx
    overwrite: false
```

or

```yaml
mode:
    type: Cluster
    storage-strategy:
      type: ZooKeeper
      namespace: governance_ds
      serverLists: localhost:2181
      props:
        retryIntervalMilliseconds: 500
        timeToLiveSeconds: 60
        maxRetries: 3
        operationTimeoutMilliseconds: 500
    overwrite: false
```

Which one is your favorite?
