### ISSUE TITLE
SchemaBuilder#build performance improvement

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#11718]
### Is your feature request related to a problem?
Yes, some users have reported the metadata loading has performance issues.

### Background
Some users reported that the metadata loading performance is poor.
So I analyzed the MetaDataContextBuilder#build method's time-consuming.
First, I have this config
```rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
```
When proxy start. I got this time-consuming.
```
# Generate rule object
ShardingSphereRulesBuilder.buildSchemaRules time:552
# Load table metadata
SchemaBuilder.build time:109
optimizeContextFactory time:1426
# Total time-consuming method
MetaDataContextsBuilder#build time:2145
```
Then, I add 100 single tables.And not change the rule config. I got this time-consuming. Seems the time-consuming is not increased.
```
ShardingSphereRulesBuilder.buildSchemaRules time:571
SchemaBuilder.build time:131
optimizeContextFactory time:1322
MetaDataContextsBuilder#build time:2074
```
Then, I make these single tables have rules. Like this.
```
t_user_item_0:
  actualDataNodes: ds_0.t_user_item_0
t_user_item_1:
  actualDataNodes: ds_0.t_user_item_1
t_user_item_2:
  actualDataNodes: ds_0.t_user_item_2
t_user_item_3:
  actualDataNodes: ds_0.t_user_item_3
t_user_item_4:
  actualDataNodes: ds_0.t_user_item_4
t_user_item_5:
  actualDataNodes: ds_0.t_user_item_5
t_user_item_6:
  actualDataNodes: ds_0.t_user_item_6
t_user_item_7:
  actualDataNodes: ds_0.t_user_item_7
t_user_item_8:
  actualDataNodes: ds_0.t_user_item_8
t_user_item_9:
  actualDataNodes: ds_0.t_user_item_9
  ...
```
I got this time-consuming.
```
ShardingSphereRulesBuilder.buildSchemaRules time:1597
SchemaBuilder.build time:1670
optimizeContextFactory time:1474
MetaDataContextsBuilder#build time:4793
```
We can see `SchemaBuilder.build` and `ShardingSphereRulesBuilder.buildSchemaRules` time-consuming obviously increased.
Through code analysis, these 100 tables are loaded separately because they are configured with rules. This is why the time-consuming increase.
The essential reason for the slower metadata loading performance is that the rule tables are loaded one by one, and there are multiple IO operations in the process of loading each table.
### Program
```private static Map<String, TableMetaData> buildActualTableMetaDataMap(final SchemaBuilderMaterials materials) throws SQLException {
    Map<String, TableMetaData> result = new HashMap<>(materials.getRules().size(), 1);
    // replace to RuleBasedTableMetaDataBuilder's singleTable implement
    appendRemainTables(materials, result);
    // change to multi thread load and batch tables and dialect load
    for (ShardingSphereRule rule : materials.getRules()) {
        if (rule instanceof TableContainedRule) {
            for (String table : ((TableContainedRule) rule).getTables()) {
                if (!result.containsKey(table)) {
                    TableMetaDataBuilder.load(table, materials).map(optional -> result.put(table, optional));
                }
            }
        }
    }
    return result;
}
```
- Load single table by RuleBasedTableMetaDataBuilder's single table implement.
- Load rule table by using multi thread, batch load and using dialect load to decrease the IO operations.
### Task

- [ ] Load single table by RuleBasedTableMetaDataBuilder's single table implement.

- [ ] Load rule table by using multi thread, batch load and using dialect load.

Thanks for @Beyondeclipse ideas and suggestions
