### ISSUE TITLE
Question about logic table and actualTable

### ISSUE THREAD

**Issue by CodingBingo** [apache/shardingsphere#11880]
Hi, this is bingo. These days, I am trying to use shardingsphere to replace mycat in our system.
But I found a question about useing it. I have config a config-sharding-socialalbum.yaml, when I connect with mysql command line, and show tables, It shows not only what I configed in config file, but also actual table in my first datasource. I am pretty confused about this feature, if this is a feature, why not show actual tables in the second datasource. Hope any one who can explain the reason of this "feature", waiting for reply.
```yaml
schemaName: sharding_feeds

dataSources:
  ds_feed_0:
    url: jdbc:mysql://******:3306/feeds?serverTimezone=UTC&useSSL=false
    username: ******
    password: ******
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_feed_1:
    url: jdbc:mysql:/******:3306/taskengine?serverTimezone=UTC&useSSL=false
    username: ******
    password: ******
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_feed_visible_0:
    url: jdbc:mysql://******:3306/feeds_0?serverTimezone=UTC&useSSL=false
    username: ******
    password: ******
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_feed_visible_1:
    url: jdbc:mysql://******:3306/feeds_50_99?serverTimezone=UTC&useSSL=false
    username: ******
    password: ******
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      feed_visiable:
        actualDataNodes: ds_feed_visible_${0..1}.feed_visiable_${(0..99).collect{t -> t.toString().padLeft(2, '0')}}
        databaseStrategy:
          standard:
            shardingColumn: userId
            shardingAlgorithmName: feed_visiable_db_sharding
        tableStrategy:
          standard:
            shardingColumn: userId
            shardingAlgorithmName: feed_visiable_tb_sharding
      organization_feed:
        actualDataNodes: ds_feed_${0..1}.organization_feed_${(0..99).collect{t -> t.toString().padLeft(2, '0')}}
        databaseStrategy:
          standard:
            shardingColumn: organization
            shardingAlgorithmName: organization_feed_db_sharding
        tableStrategy:
          standard:
            shardingColumn: organization
            shardingAlgorithmName: organization_feed_tb_sharding

    shardingAlgorithms:
      feed_visiable_db_sharding:
        type: INLINE
        props:
          algorithm-expression: feed_visiable_${((userId.toInteger) % 100).intdiv(50)}
      feed_visiable_tb_sharding:
        type: INLINE
        props:
          algorithm-expression: feed_visiable_${((userId.toInteger) % 100).toString().padLeft(2, '0')}
      organization_feed_db_sharding:
        type: INLINE
        props:
          algorithm-expression: organization_feed_${((organization.toInteger) % 100).intdiv(50)}
      organization_feed_tb_sharding:
        type: INLINE
        props:
          algorithm-expression: organization_feed_${((organization.toInteger) % 100).toString().padLeft(2, '0')}
```
