### ISSUE TITLE
SQLParsingException: Unsupported SQL of `drop sequence if exists hibernate_sequence`

### ISSUE THREAD

**Issue by rfscouto** [apache/shardingsphere#11960]
Hi everyone,

Wondering if anyone could help with my current setup. I get a SQLParsingException. I am on version 4.1.1 (core) and h2 is version 1.4.199.
The yml:

```
#############################################
### Spring
#############################################
spring:
  main:
    allow-bean-definition-overriding: true
    #datasource:
    #url: jdbc:h2:mem:events;DB_CLOSE_ON_EXIT=FALSE
    #driver-class-name: org.h2.Driver
    #platform: org.hibernate.dialect.H2Dialect
  liquibase:
    enabled: false
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: org.apache.commons.dbcp2.BasicDataSource
        driver-class-name: org.h2.Driver
        url: "jdbc:h2:mem:events;DB_CLOSE_ON_EXIT=FALSE;DATABASE_TO_UPPER=false;MODE=MYSQL"
    sharding:
      tables:
        partner:
          actual-data-nodes: ds.test$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: test$->{id}
          key-generator:
            column: id
            type: UUID
```
