### ISSUE TITLE
Question about key generate when useing sharding-jdbc

### ISSUE THREAD

**Issue by CodingBingo** [apache/shardingsphere#12307]
I am develop on master branch these days. when I transfer from mycat to ShardignSphere, I found that if I insert a record into my table, it will return a very large id.
In our case, we want to control all database config in one place, so, we put different tables in one file, some of them are just single table in single database, we prefer use mysql auto increment id. I am wandering if ShardingSphere can add an arguments to determine if using keyGenerate or not.
```
INSERT INTO `food` (`gmt_create`, `gmt_modified`, `name`, `photo`, `unit`, `school_id`)
VALUES( '2020-03-31 21:51:58', '2020-03-31 21:51:58', 'egg', NULL, NULL, 100082);
```

**Comment by strongduanmu** [comment]
@CodingBingo Single table will not use id generator.

**Comment by CodingBingo** [comment]
> @CodingBingo Single table will not use id generator.
I have a configuration file like this:
```
schemaName: feedDataSource
default: true

dataSources:
  ds_feed_0:
    url: jdbc:mysql://*******/feeds
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    username: ****
    password: ****
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      food:
        actualDataNodes: ds_feed_0.food

    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:
    defaultKeyGenerateStrategy:
      column: none
      keyGeneratorName: none
props:
  sql-show: true
```
I enumerated all single tables in this config file to have full control of every table. I know that **ShardingSphere** can auto load table from physical database.
