### ISSUE TITLE
How to use Navicat in shardingsphere-proxy

### ISSUE THREAD

**Issue by jlcon** [apache/shardingsphere#12444]
## Question
Environment: 
shardingsphere-proxy-5.0.0-beta
Navicat 15.0.18

config-readwrite-splitting.yaml

```
schemaName: readwrite_splitting_db

dataSources:
 write_ds:
   url: jdbc:mysql://192.168.100.57:3306/xxxx?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
   username: dev_user
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 read_ds_0:
   url: jdbc:mysql://192.168.100.150:3306/xxxxx?useUnicode=true&allowMultiQueries=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&useSSL=false&serverTimezone=Asia/Shanghai&&allowPublicKeyRetrieval=true
   username: dev_user
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !READWRITE_SPLITTING
 dataSources:
   pr_ds:
     writeDataSourceName: write_ds
     readDataSourceNames:
       - read_ds_0
```

I can not use navicat connect to proxy! error is : **no database selected**

![微信截图_20210915170605](http://tvax2.sinaimg.cn/large/0022gwZrly1guhfdtd931j609u05naa902.jpg)

If the latest version does not support Navicat 15 and workbench 8, it is recommended to modify the document

![微信截图_20210915170605](http://tvax3.sinaimg.cn/large/0022gwZrly1guhfoazgkxj61gz0o4dqo02.jpg)
