### ISSUE TITLE
java.sql.SQLException: javax.transaction.SystemException: There is no registered resource that can recover the given XAResource instance. Either enable automatic resource registration, or register a corresponding resource.

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12484]
I don't know what happened

**Comment by menghaoranss** [comment]
please provide your version and configuration.

**Comment by CrackerSuperior** [comment]
> please provide your version and configuration.

5.0.0-RC1

```
mode:
 type: Cluster
 repository:
   type: ZooKeeper
   props:
     namespace: governance_ds
     server-lists: 172.18.40.128:2181
     retryIntervalMilliseconds: 1000
     timeToLiveSeconds: 60
     maxRetries: 3
     operationTimeoutMilliseconds: 1000
 overwrite: true
  
rules:
 - !AUTHORITY
   users:
     - root@%:root
     - sharding@:sharding
   provider:
     type: ALL_PRIVILEGES_PERMITTED 
 - !TRANSACTION
  defaultType: XA
  #providerType: Bitronix

scaling:
 blockQueueSize: 10000
 workerThread: 40
 clusterAutoSwitchAlgorithm:
   type: IDLE
   props:
     incremental-task-idle-minute-threshold: 30

props:
 max-connections-size-per-query: 1
 executor-size: 16  # Infinite by default.
 proxy-frontend-flush-threshold: 128  # The default value is 128.
 proxy-opentracing-enabled: false
 proxy-hint-enabled: false
 sql-show: true
 check-table-metadata-enabled: false
 lock-wait-timeout-milliseconds: 50000 # The maximum time to wait for a lock
   # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
   # The default value is -1, which means set the minimum value for different JDBC drivers.
 proxy-backend-query-fetch-size: -1
 check-duplicate-table-enabled: false
```
