### ISSUE TITLE
Caused by: org.yaml.snakeyaml.error.YAMLException: Unable to find property 'inlineShardingStrategy' on class: org.apache.shardingsphere.sharding.yaml.config.YamlShardingRuleConfiguration

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12534]
This is my configuration：
```
schemaName: sqltest

dataSources:
 sqltest_0:
   url: jdbc:mysql://172.18.40.129:3306/sqltest?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 sqltest_1:
   url: jdbc:mysql://172.18.40.131:3306/sqltest?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 sqltest_2:
   url: jdbc:mysql://172.18.40.164:3306/sqltest?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !SHARDING
 tables:
   t_sql:
     actualDataNodes: sqltest_${0..2}.t_sql
     keyGenerateStrategy:
       column: user_id
       keyGeneratorName: snowflake
   t_sql2:
     actualDataNodes: sqltest_${0..2}.t_sql2_${0..1}
     tableStrategy:
       standard:
         shardingColumn: sql2_id
         shardingAlgorithmName: sql2_inline
     keyGenerateStrategy:
       column: user_id
       keyGeneratorName: snowflake
 bindingTables:
   - t_sql,t_sql2
 inlineShardingStrategy:
   allow-range-query-with-inline-sharding: true
 defaultDatabaseStrategy:
   standard:
     shardingColumn: sql_id
     shardingAlgorithmName: database_inline
 defaultTableStrategy:
   none:
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: sqltest_${sql_id % 3}
   sql2_inline:
     type: INLINE
     props:
       algorithm-expression: t_sql2_${sql2_id % 2}
 
 keyGenerators:
   snowflake:
     type: SNOWFLAKE
     props:
       worker-id: 123
```

so,how do I use allow-range-query-with-inline-sharding?thanks
