### ISSUE TITLE
How does autotable recognize the use of sharding algorithms?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12754]
In the official example, I am a little confused, the configuration file is as follows:
``` yaml
schemaName: logic_db

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: jdbc_${0..1}.t_order_${0..1}
    t_order_item:
      actualDataNodes: jdbc_${0..1}.t_order_item_${0..1}
      keyGenerateStrategy:
        column: item_id
        keyGeneratorName: increment
    t_config:
      actualDataNodes: jdbc_${0..1}.t_config
    t_user:
      actualDataNodes: jdbc_0.t_user_${0..1}
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: reset_increment
  autoTables:
    t_order_auto:
      actualDataSources: jdbc_0, jdbc_1
      shardingStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: mod
    t_order_item_auto:
      shardingStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: mod
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_config
  defaultTableStrategy:
    standard:
      shardingColumn: order_id
      shardingAlgorithmName: standard_test
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: standard_test
  
  shardingAlgorithms:
    standard_test:
        type: STANDARD_TEST
    table_inline:
      type: INLINE
      props:
        algorithm-expression: t_user_${id % 2}
    mod:
      type: MOD
      props:
        sharding-count: 2
  
  keyGenerators:
    increment:
      type: INCREMENT
    reset_increment:
      type: RESET_INCREMENT
```
I don't understand how this t_order uses t_order_auto. Does it just use name recognition?

**Comment by yx9o** [comment]
@CaymanHK Hi, please refer here: https://mp.weixin.qq.com/s/fDYqW-yJIVpkcUDNT-gsuA.

**Comment by CrackerSuperior** [comment]
> @CrackerSuperior Hi, please refer here: https://mp.weixin.qq.com/s/fDYqW-yJIVpkcUDNT-gsuA.

``` yaml
autoTables:
  t_order:
    # 指定使用的数据源
    actualDataSources: ds_${0..7}
    shardingStrategy:
      standard:
        shardingColumn: order_id
        shardingAlgorithmName: mod
shardingAlgorithms:
  mod:
    type: MOD
    props:
      # 指定分片数量
      sharding-count: 32
```
The example in the article also has "shardingAlgorithmName:mod" to refer to the "shardingAlgorithm" of "mod", but the above example does not seem to have this
