### ISSUE TITLE
The tables in the logic library do not use the default sub-library rules

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12784]
Version：5.0.0-RC1

The configuration file is as follows:
``` yaml
schemaName: frag6

dataSources:
 f6_0:
   url: jdbc:mysql://172.18.40.129:3306/frag6?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 f6_1:
   url: jdbc:mysql://172.18.40.131:3306/frag6?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 f6_2:
   url: jdbc:mysql://172.18.40.164:3306/frag6?serverTimezone=UTC&useSSL=false
   username: pcloud
   password: pcloud
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !SHARDING
 defaultDatabaseStrategy:
   standard:
    #  shardingColumn: user_id
     shardingAlgorithmName: database_inline
 
 shardingAlgorithms:
   database_inline:
     type: INLINE
     props:
       algorithm-expression: f6_0

```

I want to put all the tables that are not fragmented under the logic library into the first data source, but they do not take effect. I wonder if there is a problem with my configuration?
