### ISSUE TITLE
insert into single table throw NoSuchElementException.

### ISSUE THREAD

**Issue by justbk2015** [apache/shardingsphere#12804]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
I can insert values by sql:
insert into t2 values (0,1)
### Actual behavior
 throw java.util.NoSuchElementException
### Reason analyze (If you can)
1. create single table's column name info not saved. So if I insert values with no column names, errors occur.
the position is : InsertClaseShardingConditionEngine::createShardingCondition : String columnName = columnNames.next(); this throw NPE error.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I have two database in sharding, the single table will random create in one database.
1.  create table t2(tt int primary key, data int); -- t2 not define in config-sharding.yaml, it's a single table
2.  inert into t2 values (0, 1); --throw java.util.NoSuchElementException
3. insert into t2 (tt, data) values (0, 1); -- success
### Example codes for reproduce this issue (such as a github link).
No Need.

**Comment by strongduanmu** [comment]
@justbk2015 Thank you for your feedback, I will investigate this issue.

**Comment by strongduanmu** [comment]
Hi @justbk2015, I hava test this sql, but no exception occur.

![image](https://user-images.githubusercontent.com/10829171/135195435-09d3c64b-31e9-487d-96cd-3daaa0577d42.png)

![image](https://user-images.githubusercontent.com/10829171/135195373-89e3a913-6305-4e64-8243-9df33635d7d3.png)

**Comment by justbk2015** [comment]
> Hi @justbk2015, I hava test this sql, but no exception occur.
> 
> ![image](https://user-images.githubusercontent.com/10829171/135195435-09d3c64b-31e9-487d-96cd-3daaa0577d42.png)
> 
> ![image](https://user-images.githubusercontent.com/10829171/135195373-89e3a913-6305-4e64-8243-9df33635d7d3.png)

I have two database in backend , Is it affected by this？

**Comment by strongduanmu** [comment]
@justbk2015 This is my test configuration file, which also contains two data sources.

```yaml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123

```

**Comment by justbk2015** [comment]
> @justbk2015 This is my test configuration file, which also contains two data sources.
> 
> ```yaml
> schemaName: sharding_db
> 
> dataSources:
>   ds_0:
>     url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
>     username: root
>     password: 123456
>     connectionTimeoutMilliseconds: 30000
>     idleTimeoutMilliseconds: 60000
>     maxLifetimeMilliseconds: 1800000
>     maxPoolSize: 50
>     minPoolSize: 1
>   ds_1:
>     url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
>     username: root
>     password: 123456
>     connectionTimeoutMilliseconds: 30000
>     idleTimeoutMilliseconds: 60000
>     maxLifetimeMilliseconds: 1800000
>     maxPoolSize: 50
>     minPoolSize: 1
> 
> rules:
> - !SHARDING
>   tables:
>     t_order:
>       actualDataNodes: ds_${0..1}.t_order_${0..1}
>       tableStrategy:
>         standard:
>           shardingColumn: order_id
>           shardingAlgorithmName: t_order_inline
>       keyGenerateStrategy:
>         column: order_id
>         keyGeneratorName: snowflake
>     t_order_item:
>       actualDataNodes: ds_${0..1}.t_order_item_${0..1}
>       tableStrategy:
>         standard:
>           shardingColumn: order_id
>           shardingAlgorithmName: t_order_item_inline
>       keyGenerateStrategy:
>         column: order_item_id
>         keyGeneratorName: snowflake
>   bindingTables:
>     - t_order,t_order_item
>   defaultDatabaseStrategy:
>     standard:
>       shardingColumn: user_id
>       shardingAlgorithmName: database_inline
>   defaultTableStrategy:
>     none:
> 
>   shardingAlgorithms:
>     database_inline:
>       type: INLINE
>       props:
>         algorithm-expression: ds_${user_id % 2}
>     t_order_inline:
>       type: INLINE
>       props:
>         algorithm-expression: t_order_${order_id % 2}
>     t_order_item_inline:
>       type: INLINE
>       props:
>         algorithm-expression: t_order_item_${order_id % 2}
> 
>   keyGenerators:
>     snowflake:
>       type: SNOWFLAKE
>       props:
>         worker-id: 123
> ```

which you server.yaml? is you use zookeeper?, this is my server.yaml:
scaling:
  blockQueueSize: 10000
  workerThread: 40
  clusterAutoSwitchAlgorithm:
    type: IDLE
    props:
      incremental-task-idle-minute-threshold: 1
  dataConsistencyCheckAlgorithm:
    type: DEFAULT

mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false


rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED
  - !TRANSACTION
    defaultType: XA
    providerType: Atomikos

props:
  max-connections-size-per-query: 1
  executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-opentracing-enabled: false
----this is my config-sharding.yaml:
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:opengauss://127.0.0.1:44000/ds_0?serverTimezone=UTC&useSSL=false
    username: test
    password: Huawei@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 10
  ds_1:
    url: jdbc:opengauss://127.0.0.1:44000/ds_1?serverTimezone=UTC&useSSL=false
    username: test
    password: Huawei@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 10

rules:
- !SHARDING
  tables:
    t1:
      actualDataNodes: ds_${0..1}.t1_${0..1}
      tableStrategy:
        standard:
          shardingColumn: ts_id
          shardingAlgorithmName: ts_t1_inline
  defaultDatabaseStrategy:
    standard:
      shardingColumn: ds_id
      shardingAlgorithmName: ds_default_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    ds_default_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${ds_id % 2}
    ts_t1_inline:
      type: INLINE
      props:
        algorithm-expression: t1_${ts_id % 2}

**Comment by strongduanmu** [comment]
I am not using zk, I will turn it on and test again.

**Comment by strongduanmu** [comment]
I also opened the mode test, and there is still no exception.

```yaml
tables:
  t_order_item:
    columns:
      item_id:
        caseSensitive: false
        dataType: 4
        generated: false
        name: item_id
        primaryKey: false
      order_id:
        caseSensitive: false
        dataType: 4
        generated: false
        name: order_id
        primaryKey: false
      user_id:
        caseSensitive: false
        dataType: 4
        generated: false
        name: user_id
        primaryKey: false
      content:
        caseSensitive: false
        dataType: 12
        generated: false
        name: content
        primaryKey: false
  t_order:
    columns:
      order_id:
        caseSensitive: false
        dataType: 4
        generated: true
        name: order_id
        primaryKey: false
      user_id:
        caseSensitive: false
        dataType: 4
        generated: false
        name: user_id
        primaryKey: false
      content:
        caseSensitive: false
        dataType: 12
        generated: false
        name: content
        primaryKey: false
  t2:
    columns:
      tt:
        caseSensitive: false
        dataType: 4
        generated: false
        name: tt
        primaryKey: true
      data:
        caseSensitive: false
        dataType: 4
        generated: false
        name: data
        primaryKey: false
    indexes:
      primary:
        name: PRIMARY
```
