### ISSUE TITLE
Does Dist SQL provide statements such as "create user" or "grant permissions"?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#12838]
Version: 5.0.0-RC1

``` sql
mysql> create user 'test'@'%' identified by 'test';
ERROR 1396 (HY000): Operation CREATE USER failed for 'test'@'%'
```

Are there any examples of "sharding agent" user management or user permissions? I configured which logic libraries the user can use according to the 4.x version, but it seems to be invalid.

**Comment by RaigorJiang** [comment]
Please provide configuration information:
What is the provider type of AUTHORITY in server.yaml?

**Comment by CrackerSuperior** [comment]
> Please provide configuration information: What is the provider type of AUTHORITY in server.yaml?

``` yaml
rules:
 - !AUTHORITY
   users:
     - root@%:root
     - sharding@:sharding
   provider:
     type: ALL_PRIVILEGES_PERMITTED
```
In version 5.0.0-RC1, where should I restrict the databases that users can use？
