### ISSUE TITLE
zookeeper persist table meta data name is always lower case.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#13021]
# What is the bug?
In master branch, I found zk's table name is always lower case.
Because we use ShardingSphereSchema's key to persist to zookeeper. But the key is lower case, I don't know why is need lower case in key.
# What will this bug cause?
When I altered table in Oracle. Then the zookeeper changed, send event, rebuild the federateMetaData, but we lost the case about upper or lower in table name. Then, we use federate query will cause an error.
# How to resolve this bug?
I want to add a table name in zk to record the actual case. Like this:
```
t_order:
    columns:
      order_id:
        caseSensitive: false
        dataType: 2
        generated: false
        name: ORDER_ID
        primaryKey: true
      user_id:
        caseSensitive: false
        dataType: 2
        generated: false
        name: USER_ID
        primaryKey: false
      status:
        caseSensitive: false
        dataType: 12
        generated: false
        name: STATUS
        primaryKey: false
      col2:
        caseSensitive: false
        dataType: 2
        generated: false
        name: COL2
        primaryKey: false
    indexes:
      sys_c0010140:
        name: SYS_C0010140
    name: T_ORDER_0
```
Is it a good solution?
