### ISSUE TITLE
If my data source itself has many tables, but these tables are not configured in the configuration file, but they can be viewed through "show tables"?

### ISSUE THREAD

**Issue by CrackerSuperior** [apache/shardingsphere#13162]
Version : master

Configuration file：
``` yaml
schemaName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://172.18.40.243:3310/db01?serverTimezone=UTC&useSSL=false
    username: hotdb_datasource
    password: hotdb_datasource
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://172.18.40.243:3311/db01?serverTimezone=UTC&useSSL=false
    username: hotdb_datasource
    password: hotdb_datasource
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://172.18.40.244:3310/db02?serverTimezone=UTC&useSSL=false
    username: hotdb_datasource
    password: hotdb_datasource
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_3:
    url: jdbc:mysql://172.18.40.244:3311/db02?serverTimezone=UTC&useSSL=false
    username: hotdb_datasource
    password: hotdb_datasource
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    acct_retn_evt_c_lxy:
      actualDataNodes: ds_${0..3}.acct_retn_evt_c_lxy
      keyGenerateStrategy:
        column: acct_retn_detl_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: acct_retn_detl_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${acct_retn_detl_id % 4}
  
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
```

My intention is to let it only see the "acct_retn_evt_c_lxy" table, but it found many other tables through "show tables"
