### ISSUE TITLE
When db-discovery and readwrite-splitting are integrated, the routing result is wrong

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#13285]
### Which version of ShardingSphere did you use?

master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Read and write routing correctly

### Actual behavior

select statement is routed to the write datasource

![image](https://user-images.githubusercontent.com/10829171/138836203-d0a6c7a7-283d-4145-b879-f7f46cccb5ca.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

First, configure db-discovery and readwrite-splitting according to the following configuration file.

```yaml
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:mysql://xxx/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: xxx
    password: xxx
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://xxx/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: xxx
    password: xxx
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !READWRITE_SPLITTING
    dataSources:
      rd_rs:
        autoAwareDataSourceName: pr_ds

  - !DB_DISCOVERY
    dataSources:
      pr_ds:
        dataSourceNames:
          - ds_0
          - ds_2
        discoveryTypeName: mgr
    discoveryTypes:
      mgr:
        type: MGR
        props:
          groupName: b13df29e-90b6-11e8-8d1b-525400fc3996
          zkServerLists: 'localhost:2181'
          keepAliveCron: '0/50 * * * * ?'
```
Then execute the following statement, you will get the wrong routing result.
```sql
select * from t_address;
```
