### ISSUE TITLE
implements StandardShardingAlgorithm doSharding doesn't work

### ISSUE THREAD

**Issue by happy89lgk** [apache/shardingsphere#13658]
## Bug Report

**For English only**, other languages will not accept.

### Which version of ShardingSphere did you use?
4.0.0-RC2   Upgrade to  5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
 entry doSharding method ,  Insert into the correct table (2021_sys_login_log)
### Actual behavior
No entry doSharding method , Insert into wrong table (sys_login_log)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
4.0.0-RC2  
![image](https://user-images.githubusercontent.com/34465209/142156677-7c8754c0-9d6e-4fe2-ace8-a727d984f8a4.png)
![image](https://user-images.githubusercontent.com/34465209/142156759-6be91020-bf15-4e40-ab2e-06d10ee42141.png)

5.0.0
![image](https://user-images.githubusercontent.com/34465209/142157014-7950c9d0-6e66-4ab4-b9e2-9455532f1e4e.png)
![image](https://user-images.githubusercontent.com/34465209/142157108-3f59c1e5-061d-45f1-97d8-6f2193961232.png)

**Comment by menghaoranss** [comment]
Please use `CLASS_BASED` type to configure custom sharding algorithm in 5.0.0 version:
```
rules:
- !SHARDING
  tables:
    t_order: 
      actualDataNodes: ds_${0..1}.t_order
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  bindingTables:
    - t_order,t_order_item
  broadcastTables:
    - t_address
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_classbased
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    database_classbased:
      type: CLASS_BASED
      props:
        strategy: standard
        algorithmClassName: org.apache.shardingsphere.example.extension.sharding.algortihm.classbased.fixture.ClassBasedStandardShardingAlgorithmFixture
    
```
