### ISSUE TITLE
Only sub-database, no table, do not want to configure each table one by one strategy

### ISSUE THREAD

**Issue by liujiling1** [apache/shardingsphere#13660]
To achieve multi-tenancy, the structure of each data source table is completely the same, and there are many tables. I don’t want to configure each table again. Is there a solution?

**Comment by CrackerSuperior** [comment]
Do you mean that it only divides the database without dividing the table?

**Comment by liujiling1** [comment]
Yes, can I set a unified default rule without configuring the rules for each table?




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月17日(星期三) 下午4:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [apache/shardingsphere] Only sub-database, no table, do not want to configure each table one by one strategy (Issue #13660)





 
Do you mean that it only divides the database without dividing the table?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CrackerSuperior** [comment]
> Yes, can I set a unified default rule without configuring the rules for each table?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年11月17日(星期三) 下午4:23 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [apache/shardingsphere] Only sub-database, no table, do not want to configure each table one by one strategy (Issue #13660) Do you mean that it only divides the database without dividing the table? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

Yes, if your table structure is the same, you only need to configure the default sub-database rules.

**Comment by CrackerSuperior** [comment]
like this:
``` yaml
rules:
  - !SHARDING
    tables:
      insert3:
        actualDataNodes: ds_${0..1}.insert3
        keyGenerateStrategy:
          column: sharding
          keyGeneratorName: snowflake
      insert4:
        actualDataNodes: ds_${0..1}.insert4
        keyGenerateStrategy:
          column: sharding
          keyGeneratorName: snowflake
    defaultDatabaseStrategy:
      standard:
        shardingColumn: sharding
        shardingAlgorithmName: database_inline
    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${sharding % 2}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123
```
