### ISSUE TITLE
table metadata didn't refresh after add column or drop column on table

### ISSUE THREAD

**Issue by roodkcab** [apache/shardingsphere#13711]
### Which version of ShardingSphere did you use?
master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
table metadata should be refreshed after alter table

### Actual behavior
when using serverside preparestatement, prepare statement return wrong number of columns after add column or drop column on a table, which leading to empty result or segment fault on PDO client.

### Reason analyze (If you can)
table metadata didn't refresh. The mode is memory, and I execute alter table statement directly on database.

**Comment by roodkcab** [comment]
should use cluster mode.
add flowing config in server.yaml
```
mode:
  type: cluster
  repository:
    type: etcd
    props:
      namespace: shardingsphere/ali_manager
      server-lists: etcd1:2379,etcd2:2379:etcd3:2379
```
solve the problem
