### ISSUE TITLE
Execute show readwrite_splitting rules from database_discovery_db command,  result not right.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13737]
### Which version of ShardingSphere did you use?

`master`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Actual behavior

show right static Readwrite Splitting Rules And Dynamic Readwrite Splitting Rules

### Expected behavior

![image](https://user-images.githubusercontent.com/33742097/142834241-6b9c7b98-b7e7-43fa-b8ab-a8cf8296ba35.png)

### Configuration

```
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:13306/primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:13307/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:13308/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !READWRITE_SPLITTING
    dataSources:
      rd_rs:
        autoAwareDataSourceName: pr_ds

  - !DB_DISCOVERY
    dataSources:
      pr_ds:
        dataSourceNames:
          - ds_0
          - ds_1
          - ds_2
        discoveryTypeName: mgr
    discoveryTypes:
      mgr:
        type: MGR
        props:
          groupName: b13df29e-90b6-11e8-8d1b-525400fc3996
          zkServerLists: 'localhost:2181'
          keepAliveCron: '0/50 * * * * ?'
```

### Result

```
mysql> show readwrite_splitting rules from database_discovery_db;
+-------+-----------------------------+------------------------+------------------------+--------------------+---------------------+
| name  | auto_aware_data_source_name | write_data_source_name | read_data_source_names | load_balancer_type | load_balancer_props |
+-------+-----------------------------+------------------------+------------------------+--------------------+---------------------+
| rd_rs | pr_ds                       | NULL                   |                        | NULL               |                     |
+-------+-----------------------------+------------------------+------------------------+--------------------+---------------------+
1 row in set (3.11 sec)
```
