### ISSUE TITLE
Plan to adjust shardingsphere-db-discovery-provider and change db-discover api.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13800]
Hi, community

  Now, The `db-discovery` module integrates MYSQL MGR and openGuass, they get master-slave relation through timed task polling, and about job code are duplicat. So we plan to strip job code out of s`hardingsphere-db-discovery-provider` module, move it to `shardingsphere-db-discovery-core` management. `shardingsphere-db-discovery-provider` module is only provide master-slave relation. In order to achieve the purpose mentioned before, we will adjust `db-discovery` module api.

`Before adjustment` :

```
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:13306/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1.18:13307/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:13308/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
  dataSources:
    primary_replica_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
  discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
        zkServerLists: 'localhost:2181'
        keepAliveCron: '0/5 * * * * ?'

```

`After adjustment` :

```
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_replica_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/demo_replica_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
  dataSources:
    primary_replica_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
      discoverySchedulerName: mgr-job

 discoverySchedulers:
    mgr-job:
      type: elastic-job
      props:
        zkServerLists: 'localhost:2181'
        keepAliveCron: '0/5 * * * * ?'

  discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
```

**Comment by terrymanu** [comment]
I have question for new config of discoverySchedulers:

Does `type` of discoverySchedulers is necessary, is there any other job can inline in to ShardingSphere? If we use elastic-job for the only one solution, could we consider about remove the type, do not let user know the new concept.

And the zkServerLists maybe use same one with ShardingSphere.

The config maybe change to:

```yaml
  discoverySchedulers:
    mgr-job:
      keepAliveCron: '0/5 * * * * ?'
```

What do you think?

**Comment by menghaoranss** [comment]
> I have question for new config of discoverySchedulers:
> 
> Does `type` of discoverySchedulers is necessary, is there any other job can inline in to ShardingSphere? If we use elastic-job for the only one solution, could we consider about remove the type, do not let user know the new concept.
> 
> And the zkServerLists maybe use same one with ShardingSphere.
> 
> The config maybe change to:
> 
> ```yaml
>   discoverySchedulers:
>     mgr-job:
>       keepAliveCron: '0/5 * * * * ?'
> ```
> 
> What do you think?

@terrymanu I agree to use elastic-job as the default scheduler in `ShardingSphere`, and don't consider integrating other solutions.

**Comment by zjcnb** [comment]
```
rules:
- !DB_DISCOVERY
 dataSources:
    primary_replica_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
      discoveryHeartBeatName: mgr-job

 discoveryHeartBeat:
    mgr-job:
      type: elastic-job
      props:
        keepAliveCron: '0/5 * * * * ?'

 discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
```

@terrymanu @menghaoranss  Hi, according to your suggestion, I adjusted the api. We can confirm it.

**Comment by menghaoranss** [comment]
> ```
> rules:
> - !DB_DISCOVERY
>  dataSources:
>     primary_replica_ds:
>       dataSourceNames:
>         - ds_0
>         - ds_1
>         - ds_2
>       discoveryTypeName: mgr
>       discoveryHeartBeatName: mgr-heartbeat
> 
>  discoveryHeartBeat:
>     mgr-heartbeat:
>       props:
>         keepAliveCron: '0/5 * * * * ?'
> 
>  discoveryTypes:
>     mgr:
>       type: MGR
>       props:
>         groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
> ```
> 
> 
>     
>   
> 
> @terrymanu @menghaoranss  Hi, according to your suggestion, I adjusted the api. We can confirm it.

I suggest  `discoveryHeartbeatName` and `discoveryHeartbeats ` is better.

```
rules:
- !DB_DISCOVERY
 dataSources:
    primary_replica_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
      discoveryHeartbeatName: mgr-heartbeat

 discoveryHeartbeats:
    mgr-heartbeat:
      props:
        keepAliveCron: '0/5 * * * * ?'

 discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
```
