### ISSUE TITLE
using shadingjdbc5.0.0 ,there is a problem about No qualifying bean of type 'org.apache.shardingsphere.infra.config.mode.ModeConfiguration' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

### ISSUE THREAD

**Issue by legendyman** [apache/shardingsphere#13887]
in my application, i use springboot 2.3.2、 shardingjdbc5.0.0 and mybatisplus 3.4.0.
![619335CA-9B83-42f0-9190-FC086E4B0EF8](https://user-images.githubusercontent.com/95357724/144247635-9946dc24-1fed-4d6d-b836-00eb13bf5fc9.png)
this is my configuration,
in my configuration, i use druid data source , i also have excluded druid data source in springboot runner class. 
when the application starting, the problem is still occuring.
![image](https://user-images.githubusercontent.com/95357724/144247903-590a63da-99a8-415b-9314-9b1300726bca.png)

**Comment by tuichenchuxin** [comment]
@legendyman You can refer to this [example](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-sample/shardingsphere-jdbc-sample/shardingsphere-jdbc-memory-example/shardingsphere-jdbc-memory-local-example/shardingsphere-jdbc-memory-local-sharding-example/shardingsphere-jdbc-memory-local-sharding-springboot-starter-mybatis-example/src/main/java/org/apache/shardingsphere/example/sharding/springboot/starter/mybatis/MemoryLocalShardingSpringbootStarterMybatisExample.java)

**Comment by zjcnb** [comment]
@legendyman Hi, you can look this:


```
## mybatis的配置
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.example

server:
  port: 8899
spring:
  shardingsphere:
    props:
      sql-show: true
      sql-comment-parse-enabled: true
    datasource:
      ds0:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test0
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      ds1:
        username: root
        password: 123456
        jdbc-url: jdbc:mysql://127.0.0.1:3306/test1
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
      names: ds0, ds1
    rules:
      readwrite-splitting:
        data-sources:
          master-slave:
            write-data-source-name: ds0
            read-data-source-names: ds1
            load-balancer-name: load
        load-balancers:
          load:
            type: ROUND_ROBIN


```
