### ISSUE TITLE
Adjust discovery api feature.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#13902]
Hi community,

After discussion, it final discovery module api can be refer to  #13800 

`task list :`

- [x] Change discovery api, support ShardingSphere-Proxy.
- [x]  Change discovery api, support springboot.
- [x] Design DistSQL about new discovery api.
- [x] Move job to `shardingsphere-db-discovery-core` module.
- [x] Adjust `shardingsphere-db-discovery-mgr` and `shardingsphere-db-discovery-opengauss` module, remove job.
- [x]  Discovery api, support namespace.
- [ ]  Sync cron properties to scheduler.
- [x] Update document about User Manual.

**Comment by zjcnb** [comment]
`New discovery api:`

```
schemaName: database_discovery_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_primary_ds?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_replica_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/demo_replica_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !DB_DISCOVERY
 dataSources:
    primary_replica_ds:
      dataSourceNames:
        - ds_0
        - ds_1
        - ds_2
      discoveryTypeName: mgr
      discoveryHeartbeatName: mgr-heartbeat

 discoveryHeartbeats:
    mgr-heartbeat:
      props:
        keepAliveCron: '0/5 * * * * ?'

 discoveryTypes:
    mgr:
      type: MGR
      props:
        groupName: 92504d5b-6dec-11e8-91ea-246e9612aaf1
```
