### ISSUE TITLE
the ShardingAlgorithm  disagree in  sharding-jdbc and sharding-proxy 

### ISSUE THREAD

**Issue by happyi** [apache/shardingsphere#13960]
### Which version of ShardingSphere did you use?
sharding-jdbc:5.0.0
sharding-proxy:5.0.0 
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
both 
### Expected behavior

get the same table in sharding-jdbc and  sharding-proxy

### Actual behavior
the config is the same as follow

```
dataSources:
  ds_0:
    url: jdbc:mysql://192.168.1.101:3306/test_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  ds_1:
    url: jdbc:mysql://192.168.1.102:3306/test_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password:123456
#
rules:
- !SHARDING
  tables:
    s_customer_asset:
      actualDataNodes: ds_${0..1}.nx_customer_asset_s${0..7}
      databaseStrategy:
        standard:
          shardingColumn: customer_id
          shardingAlgorithmName: db_sharding_algorithm
      tableStrategy:
        standard:
          shardingColumn: customer_id
          shardingAlgorithmName: table_sharding_algorithm
  shardingAlgorithms:
     db_sharding_algorithm:
        type: HASH_MOD
        props:
           sharding-count: 2
     table_sharding_algorithm:
        type: HASH_MOD
        props:
           sharding-count: 8
```
2 database and 8 table  at the sharding-jdbc it will get  
```
ds_0.nx_customer_asset_s0
ds_0.nx_customer_asset_s1
ds_0.nx_customer_asset_s2
ds_0.nx_customer_asset_s3
ds_1.nx_customer_asset_s0
ds_1.nx_customer_asset_s1
ds_1.nx_customer_asset_s2
ds_1.nx_customer_asset_s3
```

2 database and 8 table  at the sharding-proxy it will get  
```
ds_0.nx_customer_asset_s0
ds_0.nx_customer_asset_s2
ds_0.nx_customer_asset_s4
ds_0.nx_customer_asset_s6
ds_1.nx_customer_asset_s1
ds_1.nx_customer_asset_s3
ds_1.nx_customer_asset_s5
ds_1.nx_customer_asset_s7
```

**Comment by strongduanmu** [comment]
Hi @happyi, I noticed that you are using the automatic sharding algorithm. The automatic sharding algorithm cannot be configured in the tables attribute. Please refer to the documentation for the correct configuration method——https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/.

```yaml
rules:
- !SHARDING
  autoTables: # 自动分片表规则配置
    t_order_auto: # 逻辑表名称
      actualDataSources (?): # 数据源名称
      shardingStrategy: # 切分策略
        standard: # 用于单分片键的标准分片场景
          shardingColumn: # 分片列名称
          shardingAlgorithmName: # 自动分片算法名称
```
