### ISSUE TITLE
Encryptor name with Underline 

### ISSUE THREAD

**Issue by wuguowei19880907** [apache/shardingsphere#13966]
sharding-jdbc 5.0.0
yaml configs the encrypt rules like this:
```
rules:
- !ENCRYPT
  encryptors:
    part_p_name:
      props:
        sm4-key-value: '316F7F9689F35AB9710A9718A190BE93'
      type: sm4
  tables:
    PART:
      columns:
        P_NAME:
          cipherColumn: P_NAME
          encryptorName: part_p_name
          logicColumn: P_NAME
```
It gives me error like this
![image](https://user-images.githubusercontent.com/19338820/144960247-b1ed4cfb-6585-4dee-ab26-3248da15bded.png)
 The error means i cannot get the `props ` in the `encryptors`.If i change the encryptor name without underline, it works good:
```
rules:
- !ENCRYPT
  encryptors:
    part-p-name:
      props:
        sm4-key-value: '316F7F9689F35AB9710A9718A190BE93'
      type: sm4
  tables:
    PART:
      columns:
        P_NAME:
          cipherColumn: P_NAME
          encryptorName: part-p-name
          logicColumn: P_NAME
```
