### ISSUE TITLE
sharding Can you configure only the database branch policy but not the table branch policy？

### ISSUE THREAD

**Issue by 65725738** [apache/shardingsphere#14103]
The requirement is that I enter a different database based on a field in the SQL statement. There is only one rule. But I have thousands of tables, and I don't want to configure policies one by one. Can I configure only the database branch policy without the table branch policy? Is there an example?For example, id 1-10 goes to database1 and id 11-20 goes to database2 and id 21-30 goes to database3... all  database have exactly the same table structure

**Comment by tuichenchuxin** [comment]
You can use defaultDatabaseStrategy like 
```
rules:
- !SHARDING
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database-inline
  defaultTableStrategy:
    none:
```
