### ISSUE TITLE
[DistSQL] Add a syntax `SHOW AUTHORITY RULE` 

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14163]
Hi community,

At present, DistSQL can manage sharding, readwrite-splitting and other feature rules, but it has not yet provided support for global rules (authority and transaction).
So I suggest to add a syntax to query authority rule: `SHOW AUTHORITY RULE`.

And the content of authority rule should includes users and provider information:
#### ALL_PRIVILEGES_PERMITTED
```yaml
- !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED
```
#### SCHEMA_PRIVILEGES_PERMITTED
```yaml
  - !AUTHORITY
    users:
      - root@:root
      - user1@:user1
      - user1@127.0.0.1:user1
    provider:
      type: SCHEMA_PRIVILEGES_PERMITTED
      props: 
        user-schema-mappings: root@=test, user1@127.0.0.1=db_dal_admin, user1@=test, user1@=db_dal_admin
```

### Reference

`show sharding algorithms` is a good reference: https://github.com/apache/shardingsphere/pull/11609
