### ISSUE TITLE
[DistSQL] Add a syntax `SHOW TRANSACTION RULE`

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#14164]
Refer to #14163,
add a syntax to query transaction rule: `SHOW TRANSACTION RULE`.

And the content of transaction rule should includes `defaultType` and `providerType`:

```yaml
- !TRANSACTION
    defaultType: XA
    providerType: Atomikos
```
