### ISSUE TITLE
Support automatic generation of instanceId for Memory/Standalone/Cluster mode

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#14254]
We must manually configure the `work-id` for distributed key generator algorithm just as follows:

```
keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
```

For the cluster mode, we cannot specify different `work-id` for all instances. Therefore, we consider using the automatically generated `instance-id` instead of the manually configured `work-id`, and provide different generation algorithms for the Memory/Standalone/Cluster mode. After that, we no longer need to configure the `work-id`:

```
keyGenerators:
    snowflake:
      type: SNOWFLAKE
```
