### ISSUE TITLE
[New feature] Add new traffic rule to implement JDBC request forwarding to Proxy

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#14282]
In some scenarios, the application and the database may be deployed in different network regions. The application uses the JDBC adapter to connect to the database in another network region. Because the JDBC adapter consumes a lot of connections and more cross-network region connections will inevitably lead to a decrease in query performance. 

In addition, for some SQL that takes up a lot of memory and CPU resources, executing SQL on the JDBC adaptor will consume application resources, and the stability and performance of the application will be affected.

In order to improve the query performance in this scenario and ensure the stability of the application, we consider forwarding the request from the JDBC adapter to the Proxy adapter located in the same network area as the database, and the Proxy calculates the query results, and then return them to the JDBC adapter, and finally to the application program.

![image](https://user-images.githubusercontent.com/10829171/147303738-dbb14bde-d8bc-4554-be96-fa8a32a79fa5.png)

Traffic rule is used to determine whether the currently SQL statement needs to be forwarded. The following shows a configuration example of traffic rule. `TrafficStrategies` is used to declare the request forwarding strategy. When the user configures multiple forwarding strategies, they will be matched in sequence according to the configuration order, and the first successfully matched strategy will be used for request forwarding processing. Take `group_by_traffic` as an example to look at the forwarding strategy in detail, `group_by_traffic` is the name of the forwarding strategy, and it contains three attributes:
- `labels`: the label corresponding to the Proxy instance;
- `algorithmName`: request forwarding matching algorithm, for example, the matching operation type is select, and it contains a group by statement. If the matching is successful, it will find the forwarded Proxy instance according to labels;
- `loadBalancerName`: used to specify the load balancing strategy for forwarding, because the Proxy instance corresponding to labels may contain multiple instances, and the load balance strategy needs to be used to determine which instance to forward to;

```yaml
- !TRAFFIC
  trafficStrategies:
    group_by_traffic:
      labels: 
        - OLAP
        - OLTP
      algorithmName: group_by_match_algorithm
      loadBalancerName: random_load_balancer
    simple_hint_traffic:
      labels: ORDER_BY, GROUP_BY
      algorithmName: simple_hint_algorithm
      loadBalancerName: random_load_balancer
  trafficAlgorithms:
    group_by_match_algorithm:
      type: REGEX_MATCH
      props:
        operation: select
        column: user_id
        regex: "[1]"
    simple_hint_algorithm:
      type: SIMPLE_HINT
      props:
        condition: xxx
  loadBalancers:
    random_load_balancer:
      type: RANDOM
    round_robin_load_balancer:
      type: ROUND_ROBIN
```

In order to cooperate with the labels attribute in traffic rule, the Proxy adapter needs to support the label attribute setting and can store the ip and port information corresponding to the Proxy instance. Proxy server.yaml adds the following configuration.

```yaml
labels: OLTP, GROUP_BY
```

We will add the `shardingsphere-traffic` module under the kernel.

```
shardingsphere-traffic
├── shardingsphere-traffic-api
└── shardingsphere-traffic-core
```

From an overall point of view, the general flow is as follows.

![image](https://user-images.githubusercontent.com/10829171/147305784-6aa1b54b-c2be-4191-9c77-cedab4b9e470.png)

Task:

- [x] implement traffic rule configuration loading and initialization
- [x] add TrafficEngine for processing forwarding algorithm matching and proxy instance discovery
- [x] add TrafficEexcutor to process forwarding execution logic
- [x] support transaction statements in the traffic feature
- [x] add unit test and integration test
- [x] add document and example
