### ISSUE TITLE
How do I configure the dataSourceProperties of HikariDataSource 

### ISSUE THREAD

**Issue by goudai** [apache/shardingsphere#14350]
How do I configure the dataSourceProperties of HikariDataSource .
I use the following configuration can not take effect：

```yaml

ds_1:
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  driverClassName: com.mysql.cj.jdbc.Driver
  jdbcUrl: jdbc:mysql://10.195.7.55:3306/order_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true
  username: root
  password: ""
  connectionInitSql: "set names utf8mb4;"
  connectionTimeout: 3000
  dataSourceProperties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true

```

**Comment by RaigorJiang** [comment]
Hi @goudai 
Do you use ShardingSpehere-Proxy?

**Comment by goudai** [comment]
I use jdbc

**Comment by zjcnb** [comment]
@goudai Hi, you can refer to this :

```
      ds-0:
        jdbc-url: jdbc:mysql://127.0.0.1:13306/demo_primary_ds?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        connectionTimeout: 5000
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 1000
          prepStmtCacheSqlLimit: 2048
```

**Comment by goudai** [comment]
```yaml
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.195.7.55:3306/order_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true
    username: root
    password: ""
    connectionInitSql: "set names utf8mb4;"
    # ms
    connectionTimeout: 3000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 1000
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true
```

![image](https://user-images.githubusercontent.com/16605628/147519242-66e71081-c178-4888-8df7-b567b12cbdfc.png)

**Comment by zjcnb** [comment]
![image](https://user-images.githubusercontent.com/33742097/147519675-0f19c4b2-6290-4522-9b04-683c9febc8c5.png)

Can you show me your all properties? by the way, the createDataSource() method has problem. refer to : # 14357

**Comment by goudai** [comment]
I don't use spring-boot-starter

**Comment by goudai** [comment]
```java
        final DataSource dataSource = YamlShardingSphereDataSourceFactory.createDataSource(yamlFile);
```
# da.yaml
```yaml
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.195.7.55:3306/order_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true
    username: root
    password: ""
    connectionInitSql: "set names utf8mb4;"
    # ms
    connectionTimeout: 3000
#    data-source-properties: {cachePrepStmts: true, prepStmtCacheSize: 250, prepStmtCacheSqlLimit: 2048, useServerPrepStmts: true}
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 1000
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://10.195.7.55:3306/order_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useServerPrepStmts=true
    username: root
    password: ""
    connectionInitSql: "set names utf8mb4;"
    # ms
    connectionTimeout: 3000
    data-source-properties:
      cachePrepStmts: true
      prepStmtCacheSize: 1000
      prepStmtCacheSqlLimit: 2048
      useServerPrepStmts: true

```
