### ISSUE TITLE
Hope to support the inlining of the sharding algorithm instead of a separate definition

### ISSUE THREAD

**Issue by goudai** [apache/shardingsphere#14376]
### I use the following method to configure the sub-database and sub-table. For scenarios with too many tables, the readability is very unfriendly, because it forces my sharding algorithm to be separated from the actual library and table, which makes me uncomfortable.

```yaml

dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
rules:
- sharding:
    tables:
      t_order:
        actualDataNodes: ds_${0..1}.t_order_${0..3}
        databaseStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: order-sharding-ds
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: order-sharding-table
  shardingAlgorithms:
    order-sharding-ds:
      type: INLINE
      props:
        algorithm-expression: ds_${order_id % 2}
    order-sharding-table:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 4}
```
### If you can support the following configuration methods, I will be very grateful

```yaml
rules:
  - sharding:
      tables:
        t_order:
          actualDataNodes: ds_${0..1}.t_order_${0..3}
          databaseStrategy:
            standard:
              shardingColumn: order_id
              shardingAlgorithm:
                type: INLINE
                props:
                  algorithm-expression: ds_${order_id % 2}
          tableStrategy:
            standard:
              shardingColumn: order_id
              shardingAlgorithm:
                type: INLINE
                props:
                  algorithm-expression: t_order_${order_id % 4}
```
## or 

```yaml
rules:
  - sharding:
      tables:
        t_order:
          actualDataNodes: ds_${0..1}.t_order_${0..3}
          databaseStrategy:
            standard:
              column: order_id
              algorithm:
                type: INLINE
                props:
                  algorithm-expression: ds_${order_id % 2}
          tableStrategy:
            standard:
              column: order_id
              algorithm:
                type: INLINE
                props:
                  algorithm-expression: t_order_${order_id % 4}
```
