### ISSUE TITLE
Make It is easy to use with narayana

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#14508]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Describe the feature you would like.
when transaction config in sever.yaml like this:
```
rules:
  - !TRANSACTION
    defaultType: XA
    providerType: Narayana
```
we need to add `jbossts-properties.xml` file to config `Narayana`.
Now we want to simplify the configuration, just config a few key, then we can use.
Automatically generate `CoreEnvironmentBean.nodeIdentifier` and `JTAEnvironmentBean.xaRecoveryNodes` for `narayana`
```
- !TRANSACTION
  defaultType: XA
  providerType: Narayana
  props:
    databaseName: jbossts
    host: 127.0.0.1
    port: 3306
    user: root
    password: 12345678
```
