### ISSUE TITLE
If springboot + shardingSphere5.0 + dubbo2.7.x implements sub-database sub-table, the following exception is reported after + seata1.4.2 is integrated: Could not find any index in the table: xxx

### ISSUE THREAD

**Issue by jlovej** [apache/shardingsphere#14550]
Springboot + Seata1.4.2 + Dubbo2.7.x + shardingSphere5.0

Could not found any index in the table: XXX, looked at the source code, IO in seata1.4.2. Seata. Rm. The datasource. SQL. Struct. Cache. MysqlTableMetaCache# resultSetMetaToSchema method call org. Apache. Shardingsph Ere. Driver. JDBC. Core. The datasource. Metadata. ShardingSphereDatabaseMetaData# getIndexInfo when unable to get the primary key and index to the metadata information, If (tm.getallIndexes ().isEmpty()) is valid, an exception will be thrown.

**Comment by jlovej** [comment]
Is there no great god to answer this question

**Comment by strongduanmu** [comment]
Hi @jingshanglu, can you help check this issue?

**Comment by jingshanglu** [comment]
@jlovej Are you using `ShardingSphere-proxy` or `shardingsphere-jdbc`?

**Comment by jlovej** [comment]
> @jlovej Are you using `ShardingSphere-proxy` or `shardingsphere-jdbc`?

shardingsphere-jdbc

**Comment by jingshanglu** [comment]
@jlovej Can you give your use case? such as SQL from app to `sharding-jdbc` and others ?

**Comment by jlovej** [comment]
> @jlovej Can you give your use case? such as SQL from app to `sharding-jdbc` and others ?

If the application is not convenient, you can provide related logs，logsInfo:

Registering transaction synchronization for SqlSession [org.apache.ibatis.session.defaults.DefaultSqlSession@7b81283]
JDBC Connection [io.seata.rm.datasource.ConnectionProxy@2c673dec] will be managed by Spring
==>  Preparing: INSERT INTO t_order ( order_id,user_id,order_no,create_time ) VALUES( ?,?,?,? ) 
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -Logic SQL: SELECT * FROM t_order LIMIT 1
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -SQLStatement: MySQLSelectStatement(limit=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dml.pagination.limit.LimitSegment@4b9a2d73], lock=Optional.empty, window=Optional.empty)
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds0 ::: SELECT * FROM t_order0 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds0 ::: SELECT * FROM t_order1 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds0 ::: SELECT * FROM t_order2 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.732 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds0 ::: SELECT * FROM t_order3 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds1 ::: SELECT * FROM t_order0 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds1 ::: SELECT * FROM t_order1 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds1 ::: SELECT * FROM t_order2 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds1 ::: SELECT * FROM t_order3 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds2 ::: SELECT * FROM t_order0 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds2 ::: SELECT * FROM t_order1 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds2 ::: SELECT * FROM t_order2 ORDER BY order_id ASC  LIMIT 1
2022-01-06 16:33:25.733 [] [main] INFO  ShardingSphere-SQL -Actual SQL: ds2 ::: SELECT * FROM t_order3 ORDER BY order_id ASC  LIMIT 1

Do you need any more information

**Comment by jingshanglu** [comment]
@jlovej Can you give a simplified reproduction step？

**Comment by jlovej** [comment]
> @jlovej Can you give a simplified reproduction step？

About logic：
1、mall-order sevice create order
2、mall-goods service deductions inventory;

Order is divided into three databases and four tables，Goods is divided into three databases and four tables

Integration Seata1.4.2， implementation Global Transaction exception，reason：gain table meta primary key and index empty

**Comment by jlovej** [comment]
this question is why

**Comment by jingshanglu** [comment]
> this question is why
Can you leave your WeChat ID?

**Comment by jlovej** [comment]
> 



> > this question is why
> > Can you leave your WeChat ID?

OK，3ks,Direct messages to send you

**Comment by jlovej** [comment]
> > this question is why
> > Can you leave your WeChat ID?

WeChat ID：jlovej213

**Comment by jlovej** [comment]
Does anyone care about that

**Comment by jlovej** [comment]
Thks for @jingshanglu

**Comment by jlovej** [comment]
After confirmation, it should be org. Apache. Shardingsphere. Infra. Rewrite. SQLRewriteEntry# rewrite SQL rewriting has a problem, the Debug screenshots as follows：
![403b21139b40cbe2a15da4f95bc106c](https://user-images.githubusercontent.com/8819998/148873857-cabb51c3-f163-4b63-adcf-9e90316050fe.png)

**Comment by jingshanglu** [comment]
@strongduanmu Hey, it maybe a rewrite error. PTAL

**Comment by jingshanglu** [comment]
@strongduanmu Hey, it maybe a rewrite error, PTAL

**Comment by strongduanmu** [comment]
> @strongduanmu Hey, it maybe a rewrite error, PTAL

@jingshanglu Thank you for your remind, I will take a look at this bug.

**Comment by strongduanmu** [comment]
```sql
[INFO ] 2022-01-11 15:34:15.350 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: show index from `t_order` from `sharding_db`
[INFO ] 2022-01-11 15:34:15.351 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLShowIndexStatement(table=SimpleTableSegment(tableName=TableNameSegment(startIndex=16, stopIndex=24, identifier=IdentifierValue(value=t_order, quoteCharacter=BACK_QUOTE)), owner=Optional.empty, alias=Optional.empty), fromSchema=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dal.FromSchemaSegment@944aefb])
[INFO ] 2022-01-11 15:34:15.351 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: show index from `t_order_0` 
```

Hi @jlovej I have tested the `show index` statement using the `t_order` table and it works fine in version 5.0. Can you provide more information to help me reproduce this issue? For example, the configuration of the `t_order` table? `hl_mall_order_cluster_0` is the logical database?

**Comment by jlovej** [comment]
> ```sql
> [INFO ] 2022-01-11 15:34:15.350 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Logic SQL: show index from `t_order` from `sharding_db`
> [INFO ] 2022-01-11 15:34:15.351 [Connection-1-ThreadExecutor] ShardingSphere-SQL - SQLStatement: MySQLShowIndexStatement(table=SimpleTableSegment(tableName=TableNameSegment(startIndex=16, stopIndex=24, identifier=IdentifierValue(value=t_order, quoteCharacter=BACK_QUOTE)), owner=Optional.empty, alias=Optional.empty), fromSchema=Optional[org.apache.shardingsphere.sql.parser.sql.common.segment.dal.FromSchemaSegment@944aefb])
> [INFO ] 2022-01-11 15:34:15.351 [Connection-1-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: show index from `t_order_0` 
> ```
> 
> Hi @jlovej I have tested the `show index` statement using the `t_order` table and it works fine in version 5.0. Can you provide more information to help me reproduce this issue? For example, the configuration of the `t_order` table? `hl_mall_order_cluster_0` is the logical database?

`t_order`  is logical table，`hl_mall_order_cluster_0` is the physics database；
sharding config info:

```
spring:
  shardingsphere:
    # 展示修改后的SQL语句
    props:
      sql-show: true
    datasource:
      names: ds0,ds1,ds2
      ds0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://IP:3306/hl_mall_order_cluster_0?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useInformationSchema=false&serverTimezone=UTC
        username: xxx
        password: xxxx
      ds1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://IP:3306/hl_mall_order_cluster_1?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useInformationSchema=false&serverTimezone=UTC
        username: xxx
        password: xxxx
      ds2:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://IP:3306/hl_mall_order_cluster_2?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useInformationSchema=false&serverTimezone=UTC
        username: xxx
        password: xxxx
    rules:
      sharding:
        default-database-strategy:
          inline:
            sharding-column: order_id
            algorithm-expression: ds$->{order_id % 3}
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 1
        sharding-algorithms:
          order-inline:
            type: INLINE
            props:
              algorithm-expression: t_order$->{order_id % 4}
          order-item-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_item$->{order_id % 4}
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{order_id % 3}
        tables:
          t_order_item:
            actual-data-nodes: ds$->{0..2}.t_order_item$->{0..3}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: order-item-inline
            database-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: database-inline
          t_order:
            actual-data-nodes: ds$->{0..2}.t_order$->{0..3}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: order-inline
            database-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: database-inline
    enabled: true
```
