### ISSUE TITLE
insert into broadcasttable with longblob cause longblob break up to serveral part(the number of shards )  

### ISSUE THREAD

**Issue by ziliangzeng** [apache/shardingsphere#14670]
## Bug Report
      hi.
      example: i have 4 database . the broadcasttable was in 4 database.
      when I try to insert into broadcastTable with longblob. it inserts success.
      but interesting thing is that It segmentation 4 parts. each database have 1/4 longblob.
      in my mind . each data should have complete longblob .
      that was confuse.
      when I change the broadcasttable to sharding table .  the longblob do not spilt and successful insert. but sharding table is not the table type I want.
       
 broadcasttable:      
![1771kb](https://user-images.githubusercontent.com/27884890/148759782-0f260e13-c125-4ff6-ab7b-51ab67234f66.png)
![800kb](https://user-images.githubusercontent.com/27884890/148759795-c78a04e9-0b88-40e0-9b59-2c3121be9fc9.png)
sharding table:
![2171kb](https://user-images.githubusercontent.com/27884890/148759807-68664398-7b18-4f47-abd0-fb014bb5547d.png)

### Which version of ShardingSphere did you use?
       5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
         sharding - jdbc
### Expected behavior
        long blob insert into each broadcasttable success
### Actual behavior
       longblob was break up and insert into table

**Comment by strongduanmu** [comment]
@ziliangzeng Thank you for your feedback, I will track this issue.

**Comment by strongduanmu** [comment]
Hi @ziliangzeng, can you provide sql-show log? When ShardingSphere handle broadcast tables, there is no logic to split strings.

**Comment by ziliangzeng** [comment]
@strongduanmu  hi . is it what you want ? 
![image](https://user-images.githubusercontent.com/27884890/148865656-a80310c6-ebba-4c79-89f0-9252b24f3cdf.png)

**Comment by strongduanmu** [comment]
Hi @ziliangzeng, can you upload this demo? I can't reproduce this bug in master branch.

**Comment by ziliangzeng** [comment]
```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeout: 30000
    idleTimeout: 30000
    maximumPoolSize: 10
    maxLifetime: 1800000
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeout: 30000
    idleTimeout: 30000
    maximumPoolSize: 10
    maxLifetime: 1800000

rules:
  - !SHARDING
    tables:
      cf_api_parameter:
        actualDataNodes: ds_${0..1}.cf_api_parameter
      package_service_test_instance:
        actualDataNodes: ds_0.package_service_test_instance
        databaseStrategy:
          none:
    broadcastTables:
      [
          t_order0
      ]
    defaultDatabaseStrategy:
      standard:
        shardingColumn: order_id
        shardingAlgorithmName: database_inline
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${order_id % 2}

    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123

props:
  sql-show: true
```

```
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS `t_order0`;
CREATE TABLE `t_order0`  (
  `id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `blobtext` longblob NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
```
```
InputStream in = getClass().getClassLoader().getResourceAsStream("sharding.yaml");

        String sql = "INSERT INTO t_order0 (id, blobtext, name) VALUES (?, ?, ?)";
        confJdbcTemplate.update(sql, new Object[]{
                1, in, "test"});
```
```
`DROP TABLE IF EXISTS `cf_api_parameter`;
CREATE TABLE `cf_api_parameter`  (
  `ID` bigint NOT NULL COMMENT '标识',
  `API_ID` bigint NULL DEFAULT NULL COMMENT 'API标识',
  `CODE` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '编码',
  `NAME` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '名称',
  `TYPE` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '类型 API-IN/API-OUT',
  `IS_MUST` tinyint NOT NULL DEFAULT 0 COMMENT '是否必填 1-是，0-否',
  `RULE_CODE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '校验策略编码 校验策略编码',
  `RULE_BIND` varchar(3072) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '校验策略参数 校验策略参数',
  `RULE_EXP` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '约束策略表达式',
  `RELA_PROP_CODE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '关联属性编码',
  `STATE` tinyint NOT NULL COMMENT '状态 1-有效，0-无效',
  `REMARKS` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '说明备注',
  `CREATE_TIME` datetime NULL DEFAULT NULL COMMENT '创建时间',
  `PARTITION_CODE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '分区编码',
  `RELA_TYPE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL,
  `DATA_TYPE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '-1' COMMENT '数据类型',
  `OLD_VALUE_OPTION` int NULL DEFAULT NULL COMMENT '新旧值传递规则',
  `PATH_CODE` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_CAP_TYPE`(`TYPE`) USING BTREE,
  INDEX `IDX_CAP_CODE`(`CODE`) USING BTREE,
  INDEX `IDX_CAP_API_ID`(`API_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = 'API参数表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
```


```
DROP TABLE IF EXISTS `package_service_test_instance`;
CREATE TABLE `package_service_test_instance`  (
  `ID` bigint NOT NULL COMMENT '主键ID',
  `CUST_ORDER_CODE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '客户订单编码/测试单号',
  `SCENE_ID` bigint NOT NULL COMMENT '关联业务测试场景ID',
  `CUST_ORDER_MESSAGE` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '客户订单报文',
  `CREATE_DATE` datetime NOT NULL COMMENT '创建时间',
  `UPDATE_DATE` datetime NOT NULL COMMENT '更新时间',
  `ACC_NBR` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '业务号码',
  `IS_PASS` tinyint NOT NULL COMMENT '是否通过',
  `DESC` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL COMMENT '结果描述',
  `INFORM_ID` bigint NOT NULL COMMENT '关联业务包编码',
  `OPERUSER` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NULL DEFAULT NULL COMMENT '操作用户',
  PRIMARY KEY (`ID`) USING BTREE,
  INDEX `IDX_PSTI_INFORMID`(`INFORM_ID`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_bin COMMENT = '业务测试单实例表，单片表' ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
```
@strongduanmu
