### ISSUE TITLE
Configure skywalking tracking with opentracing:0.30.0 dependency error will make it unusable?

### ISSUE THREAD

**Issue by wl4g** [apache/shardingsphere#14724]
There is a very serious problem: I tried to configure `org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer` in the latest 5.1.1 for tracing, but the latest version `apm-toolkit-opentracing:8.8.0` only depends on `opentracing -api:0.30.0`, but `shardingsphere-agent-tracing-opentracing:5.1.0` does depend on 0.31.0, resulting in the error `NoClassDefFoundError: io/opentracing/ActiveSpan`, how to solve this? ? very worried about

**Comment by wl4g** [comment]
My agent.yaml is:
```yaml
applicationName: cn_south1_a1_shardingproxy_0
ignoredPluginNames: #[] # Otherwise a null pointer is reported when instantiating(5.1.0).
  #- Logging
  #- Prometheus
  - Zipkin
  - Jaeger
  #- Opentracing
  - OpenTelemetry

plugins:
  Logging:
    props:
      LEVEL: "DEBUG"
  Prometheus:
    host:  "localhost"
    port: 10108
    props:
      JVM_INFORMATION_COLLECTOR_ENABLED : "true"
  Opentracing:
    props:
      OPENTRACING_TRACER_CLASS_NAME: "org.apache.skywalking.apm.toolkit.opentracing.SkywalkingTracer"
  #OpenTelemetry:
  #  props:
  #    # Resource info of opentelemetry, multiple configurations can be separated by ','
  #    otel.resource.attributes: "service.name=cn-south1-a1-shardingproxy"
  #    otel.traces.exporter: "zipkin"
```
