### ISSUE TITLE
org.apache.shardingsphere.infra.exception.SchemaNotExistedException: Schema 'information_schema' doesn't exist.

### ISSUE THREAD

**Issue by dragonorant** [apache/shardingsphere#14728]
```xml
 <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
                <version>5.0.0</version>
            </dependency>
```

```yml
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://ip:port/db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
      slave:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: root
        jdbc-url: jdbc:mysql://ip:port/db?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    props:
      sql-show: true
    rules:
      readwrite_splitting:
        data-sources:
          sanyi_yoyo:
            auto-aware-data-source-name: master,slave
            write-data-source-name: master
            read-data-source-names: slave
            load-balancers-name: round-robin
        load-balancers:
          round-robin:
            type: ROUND_ROBIN
            props:
              workId: 1
```

```code
select count(*) from information_schema.TABLES where table_name = #{tableName}
```

I need to query whether the table name exists through such statements. How should I handle this exception when it is reported in the query process?
