### ISSUE TITLE
[shardingsphere-proxy] . The property set in server.yaml is inconsistent with the mysql variable query

### ISSUE THREAD

**Issue by newchendb** [apache/shardingsphere#14744]
shardingsphere-proxy version is 5.1.1。
server.yaml：
```
mode:
  type: Standalone

rules:
  - !AUTHORITY
    users:
      - root@%:123456
    provider:
      type: ALL_PRIVILEGES_PERMITTED
  - !TRANSACTION
    defaultType: BASE
    providerType: seata
```

But the query “show variable transaction_type” result is “LOCAL”。

What is the reason for this？

**Comment by zjcnb** [comment]
@newchendb Hi , thank you for your feedback, your `ShardingSphere-Proxy` are `5.1.1` version? I think this version are not exist. Can you confirm it? By the way, I use XA and Standalone mode is ok in master branch. I will check BASE.

**Comment by newchendb** [comment]
@zjcnb Hi，My packaged branch is 5.1.0-release，Packaging result display 5.1.1-SNAPSHOT 。

**Comment by zjcnb** [comment]
> 

@newchendb Can you try it with `master` branch? The 5.1.0-release unavailable now.

**Comment by newchendb** [comment]
I will try it with master branch

**Comment by newchendb** [comment]
@zjcnb It is strange that the modification of the configuration file does not take effect.Have you ever encountered this situation in agent mode.

**Comment by newchendb** [comment]
shardingsphere-5.0.0-beta is relatively normal, and higher versions always encounter various strange problems.

**Comment by zjcnb** [comment]
```
    mode:
      type: Standalone
      repository:
        type: File
      overwrite: true
```

Change overwrite is true and try it again.
