### ISSUE TITLE
Use PostgreSQL(AGE) as DataSource. ShardingSphere-Proxy can’t work normal as a PostgreSQL.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#14885]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere-Proxy 5.0.1 snapshot 
commit id f7b0bf90b7af2ac8ac0084561ff0e54971540d10
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
execute SQL without error
```
CREATE EXTENSION age;
```
### Actual behavior
```
[root@localhost shardingsphere-proxy-bin-0118]# psql -Uroot -p3307 -h IP -dtest
Password for user root:
psql (14.1, server 11.14 (Debian 11.14-1.pgdg90+1)-ShardingSphere-Proxy 5.0.1-SNAPSHOT-f7b0bf9)
Type "help" for help.

test=> CREATE EXTENSION age;
ERROR:  You have an error in your SQL syntax
test=> \q
```
### Reason analyze (If you can)
Maybe not support.
##### server.yaml
```
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: NATIVE
props:
  sql-show: true
```
##### config-sharding.yaml
```
schemaName: test

dataSources:
  ds_0:
    url: jdbc:postgresql://IP:5552/test
    username: test
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 3000
    minPoolSize: 1
  ds_1:
    url: jdbc:postgresql://IP:5552/test
    username: test
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 3000
    minPoolSize: 1



rules:
  - !SHARDING
    tables:
      sbtest1:
        actualDataNodes: ds_${0..1}.sbtest1_${0..9}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: table_inline_1
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    defaultDatabaseStrategy:
      standard:
        shardingColumn: id
        shardingAlgorithmName: database_inline

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${id & 1}
      table_inline_1:
        type: INLINE
        props:
          algorithm-expression: sbtest1_${id % 10}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123
```
### Example codes for reproduce this issue (such as a github link).
https://hub.docker.com/r/sorrell/agensgraph-extension
