### ISSUE TITLE
pg need to connect a database when proxy start up without a default schema

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#14968]
as we all know, DistSQL is a powerful tool in ShardingSphere, it really reduce a lot of configuration work for Proxy + MySQL combination.

however, there is a little bit issue for Proxy + PG, following is the steps to reproduce the issue:
1. start proxy with server.yaml
server.yaml
```yaml
mode:
 type: Cluster
 repository:
   type: ZooKeeper
   props:
     namespace: governance_ds
     server-lists: localhost:2181
     retryIntervalMilliseconds: 500
     timeToLiveSeconds: 60
     maxRetries: 3
     operationTimeoutMilliseconds: 500
 overwrite: false

rules:
 - !AUTHORITY
   users:
     - root@%:root
     - sharding@:sharding
   provider:
     type: ALL_PRIVILEGES_PERMITTED
```

2. connect proxy by pgsql client
```bash
psql -Uroot -h127.0.0.1  -p3307
```

and then you will get an promot like following, because pg need a "database name" to connect
![image](https://user-images.githubusercontent.com/4112856/150456352-d3edad79-ff2c-4651-84d8-41dce56dd613.png)

here is my suggestion, is it possible we create a default database named `shardingsphere` or something like that. and it stores the metadata of proxy , like version, os info, jvm info blabla... so that pgsql client could connect to proxy
