### ISSUE TITLE
[DistSQL] Add some new syntax to manage traffic rule configurations

### ISSUE THREAD

**Issue by lanchengx** [apache/shardingsphere#15018]
Hi community,

To make it easier for users to manage traffic rule configuration and instance labels, we will add some new DistSQL syntax.

The yaml configuration of the traffic rule is as follows:

```yaml
- !TRAFFIC
  trafficStrategies:
    sql_match_traffic:
      labels: OLTP
      algorithmName: sql_match_algorithm
      loadBalancerName: random_load_balancer
    sql_hint_traffic:
      labels: OLAP
      algorithmName: sql_hint_algorithm
      loadBalancerName: round_robin_load_balancer
  trafficAlgorithms:
    sql_match_algorithm:
      type: SQL_MATCH
      props:
        sql: SELECT * FROM t_order WHERE order_id = ?; UPDATE t_order SET order_id = ?;
    sql_hint_algorithm:
      type: SQL_HINT
      props:
        use_traffic: true
  loadBalancers:
    random_load_balancer:
      type: RANDOM
    round_robin_load_balancer:
      type: ROUND_ROBIN
```

For this configuration, we have designed the following syntax

- [x] **Create syntax**
```sql
CREATE TRAFFIC RULE sql_match_traffic (
    LABELS(OLTP),
    TRAFFIC_ALGORITHM(TYPE(NAME=SQL_MATCH,PROPERTIES("sql" = "SELECT * FROM t_order WHERE order_id = ?; UPDATE t_order SET order_id = ?;"))),
    LOAD_BALANCER(TYPE(NAME=RANDOM, PROPERTIES("key"="value")))
), sql_hint_traffic( 
    LABELS(OLAP, xxx),
    TRAFFIC_ALGORITHM(TYPE(NAME= SQL_HINT,PROPERTIES("use_traffic" = "true"))),
    LOAD_BALANCER(TYPE(NAME=ROUND_ROBIN, PROPERTIES("key"="value")))
);
```
- [x] **Modify syntax**
```mysql
ALTER TRAFFIC RULE sql_match_traffic (
    LABELS(OLTP),
    TRAFFIC_ALGORITHM(TYPE(NAME=SQL_MATCH,PROPERTIES("sql" = "SELECT * FROM t_order WHERE order_id = ?; UPDATE t_order SET order_id = ?;"))),
    LOAD_BALANCER(TYPE(NAME=RANDOM, PROPERTIES("key"="value")))
), sql_hint_traffic( 
    LABELS(OLAP, xxxx),
    TRAFFIC_ALGORITHM(TYPE(NAME= SQL_HINT,PROPERTIES("use_traffic" = "true"))),
    LOAD_BALANCER(TYPE(NAME=ROUND_ROBIN, PROPERTIES("key"="value")))
);
```
- [x] **Delete syntax**
```mysql
DROP TRAFFIC RULE sql_match_traffic, sql_hint_traffic
```

- [x] **Show syntax and show results**
```mysql
SHOW TRAFFIC RULES;
```

```
+-------------------+------------+---------------+--------------------------------------------------------------------------------------+---------------------+-----------------------+
| rule_name         | labels     | algorithm_type| algorithm_props                                                                      | load_balancer_type  | load_balancer_props   |
+-------------------+------------+---------------+--------------------------------------------------------------------------------------+---------------------+-----------------------+
| sql_match_traffic | OLTP       | SQL_MATCH     | "sql" = "SELECT * FROM t_order WHERE order_id = ?; UPDATE t_order SET order_id = ?;" | RANDOM              | "key"="value"         |
| sql_hint_traffic  | OLAP       | SQL_HINT      | "use_traffic" = "true"                                                               | ROUND_ROBIN         | "key"="value"         |
+-------------------+------------+---------------+--------------------------------------------------------------------------------------+---------------------+-----------------------+
```

In addition, we also need to add syntax to support label

- [x] #15059
```mysql
SHOW INSTANCE LIST
```
```
+-----------------+------------+------+--------+---------------+
| instance_id     | host       | port | status | labels        |
+-----------------+------------+------+--------+---------------+
| 127.0.0.1@3309  | 127.0.0.1  | 3309 | enable | OLTP,GROUP_BY |
| 127.0.0.1@3209  | 127.0.0.1  | 3209 | enable | OLAP          |
| 127.0.0.1@3109  | 127.0.0.1  | 3109 | enable |               |
+-----------------+------------+------+--------+---------------+
```
- [x] **Add labels to instance**
```mysql
-- add labels
LABEL INSTANCE 127.0.0.1@3309 WITH olap,group_by;

-- relable 
RELABEL INSTANCE 127.0.0.1@3309 WITH olap,group_by;
```

- [x] **Remove labels from instance**
```mysql
-- remove all labels
UNLABEL INSTANCE 127.0.0.1@3309;

--remove the specified lables
UNLABEL INSTANCE 127.0.0.1@3309 WITH olap;

```
