### ISSUE TITLE
Consider optimize the `schemaName` of `ShardingSphere-JDBC`.

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15016]
Hi community,

Consider optimizing the `schemaName` of `ShardingSphere-JDBC`. Currently, it 's read the logic database created by `ShardingSphere-Proxy` DistSQL. If we use `ShardingSphere` `Standalone` or `Cluster` mode. It configuration such as:

`Standalone mode:`

```
schemaName: test

mode:
  type: Standalone
  repository:
    type: File
  overwrite: false
```

`Cluster mode:`

```
schemaName: test

mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```

We think the `schemaName` configuration is not flexible, it cannot satisfy to dynamic switch to other databases created by `ShardingSphere-Proxy` DistSQL. So we plan to optimize it.

### How to adjust

If you use schemaName in your configuration file, `ShardingSphere` according your schemaName to load one. If you not configuration it, all schemaNames will be loaded. 

### How to use

We can use `use database xx` to choose database.
