### ISSUE TITLE
hash_mod Configuration fails to take effect , MOD  Configuration is ok

### ISSUE THREAD

**Issue by dragonorant** [apache/shardingsphere#15034]
```text
 <dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
    <version>5.0.0</version>
</dependency>
```

```yml
      sharding:
        tables:
          sanyi_account:
            actual-data-nodes: master.sanyi_account_$->{0..0}
            table-strategy:
              standard:
                sharding-column: account_id
                sharding-algorithm-name: account-inline
          sanyi_account_short:
            actual-data-nodes: master.sanyi_account_short_$->{0..0}
            table-strategy:
              standard:
                sharding-column: short_id
                sharding-algorithm-name: short-inline
        sharding-algorithms:
          account-inline:
            type: MOD
            props:
              sharding-count: 1
          short-inline:
            type: HASH_MOD
            props:
              sharding-count: 1
```

exception 
```text
Caused by: java.lang.NumberFormatException: null
	at java.lang.Integer.parseInt(Integer.java:542)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.apache.shardingsphere.sharding.algorithm.sharding.mod.HashModShardingAlgorithm.getShardingCount(HashModShardingAlgorithm.java:52)
```

```java
  HashModShardingAlgorithm.class
   private int getShardingCount() {
        Preconditions.checkArgument(props.containsKey(SHARDING_COUNT_KEY), "Sharding count cannot be null.");
// Presentation of exception
        return Integer.parseInt(props.getProperty(SHARDING_COUNT_KEY));
    }

Properties.class
// underlying code
    public String getProperty(String key) {
        Object oval = super.get(key);
        String sval = (oval instanceof String) ? (String)oval : null;
        return ((sval == null) && (defaults != null)) ? defaults.getProperty(key) : sval;
    }

// mod no problem
ModShardingAlgorithm.class
private int getShardingCount() {
        Preconditions.checkArgument(props.containsKey(SHARDING_COUNT_KEY), "Sharding count cannot be null.");
        return Integer.parseInt(props.get(SHARDING_COUNT_KEY).toString());
    }
```

**Comment by RaigorJiang** [comment]
Hi @dragonorant 
`Auto Sharding Algorithm` need some properties, you can refer to the [document](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/builtin-algorithm/sharding/#auto-sharding-algorithm) and [example](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-auto-tables.yaml)

**Comment by RaigorJiang** [comment]
Here is an article for auto table: https://mp.weixin.qq.com/s/fDYqW-yJIVpkcUDNT-gsuA

**Comment by dragonorant** [comment]
> 

But I have no problem with mod，successful sharding

**Comment by dragonorant** [comment]
> 嗨@dragonorant `Auto Sharding Algorithm`仅适用于 autoTables，您可以参考[文档](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/sharding/)和[示例](https://github.com/apache/shardingsphere/blob/master/examples/shardingsphere-jdbc-example/single-feature-example/sharding-example/sharding-raw-jdbc-example/src/main/resources/META-INF/sharding-auto-tables.yaml)

But I have no problem with mod，successful sharding

**Comment by RaigorJiang** [comment]
From the code, mod can't be used like this, we can investigate.

**Comment by dragonorant** [comment]
>

**Comment by dragonorant** [comment]
> 从代码来看，mod不能这样用，我们可以查一下。

The configuration becomes the following to run successfully and perform insert queries, etc
```yml
          short-inline:
            type: HASH_MOD
            props:
              sharding-count: '1'
```
