### ISSUE TITLE
incorrect readwrite-splitting configuration document

### ISSUE THREAD

**Issue by homeway88** [apache/shardingsphere#15164]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.0.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

* incorrect configuration document . 
According to the document, readwrite-splitting datasources, you should config `auto-aware-data-source-name`,`write-data-source-name` and `read-data-source-names` as the children of `props`.
 but in the configuration class file `ReadwriteSplittingDataSourceRuleConfiguration`,  they are in the same level of `type` and `loadBalancerName`. which means node `props` should be deleted.

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting/

```yaml
rules:
- !READWRITE_SPLITTING
  dataSources:
    <data-source-name> (+): # Logic data source name of readwrite-splitting
      type: 
      props: # should not have this node
        auto-aware-data-source-name: 
        write-data-source-name: 
        read-data-source-names: 
      loadBalancerName: 
  
```

```java
public final class ReadwriteSplittingDataSourceRuleConfiguration {
    private final String name;
    private final String autoAwareDataSourceName;
    private final String writeDataSourceName;
    private final List<String> readDataSourceNames;
    private final String loadBalancerName;
}
```
