### ISSUE TITLE
start sharding-proxy error

### ISSUE THREAD

**Issue by guoyzh** [apache/shardingsphere#15289]
![image](https://user-images.githubusercontent.com/19571804/152938339-5eeccc16-fe31-42b1-af13-82db289c2e46.png)
**server.yaml**
```
rules:
   users:
     - root@%:root
```

**config-sharding.yaml**
```
schemaName: hqzc_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/jjcsq?serverTimezone=UTC&useSSL=false
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  tables:
    rpt_new:
      actualDataNodes: ds_0.rpt_new_${0..50}
      tableStrategy:
        standard:
          shardingColumn: rpt_id
          shardingAlgorithmName: t_rpt_inline
      keyGenerateStrategy:
        column: rpt_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    t_rpt_inline:
      type: INLINE
      props:
        algorithm-expression: rpt_new_${rpt_id % 50}
  
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        worker-id: 123
```

**Comment by menghaoranss** [comment]
which version did you use?

**Comment by guoyzh** [comment]
> which version did you use?

5.0.0

**Comment by guoyzh** [comment]
After modification, it is still the same error. Can you provide a complete configuration file first

**Comment by TeslaCN** [comment]
Your `server.yaml` is also malformed. Try the following
```yaml
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - postgres@%:postgres
    provider:
      type: ALL_PRIVILEGES_PERMITTED
```
