### ISSUE TITLE
Using Add Resource causes loss of broadcast tables under the /metadata/schemaName/tables

### ISSUE THREAD

**Issue by ReyYang** [apache/shardingsphere#15532]
### Which version of ShardingSphere did you use?
master batch
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
 /metadata/schemaName/tables broadcast table metadata exist
### Actual behavior
 /metadata/schemaName/tables broadcast table metadata lost
### Reason analyze (If you can)
It may be because Debug finds
TableMetadataLoadRengine's LOAD method leads to the loss of the broadcast
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1、start ShardingSphere-proxy
2、perform distsql
3、Data loss found in ZK

**Comment by ReyYang** [comment]
before perform distsql
<img width="313" alt="image" src="https://user-images.githubusercontent.com/29473272/154883754-1b2a0dcf-3d7c-4f05-ae35-13e0aad7c293.png">
after perform distsql
<img width="328" alt="image" src="https://user-images.githubusercontent.com/29473272/154883823-dff1aa37-d7c1-4397-9d0f-51c57e058a70.png">

**Comment by tuichenchuxin** [comment]
I tried these steps, but didn't reproduced.
## FIREST 
server.ymal
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: agent
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 30000
  overwrite: true
#
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED

props:
  max-connections-size-per-query: 1
  executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-opentracing-enabled: false
  proxy-hint-enabled: true
  sql-show: false
  check-table-metadata-enabled: false
  lock-wait-timeout-milliseconds: 50000 # The maximum time to wait for a lock
  show-process-list-enabled: true
  # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
  # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  check-duplicate-table-enabled: false
```
## Second
```
CREATE DATABASE sharding_db;
```
## Third
```
ADD RESOURCE demo_ds_0 (
    HOST=127.0.0.1,
    PORT=3306,
    DB=demo_ds_0,
    USER=root,
    PASSWORD=123456
), demo_ds_1(
    HOST=127.0.0.1,
    PORT=3306,
    DB=demo_ds_0,
    USER=root,
    PASSWORD=123456
);
```
## Fourth
```
CREATE SHARDING BROADCAST TABLE RULES (t_config);
```
## final
I found broadcast tables are exist.
![image](https://user-images.githubusercontent.com/86938616/160739900-79eda776-bce3-4ad9-8037-68916f95b1f1.png)
