### ISSUE TITLE
Data source simplification

### ISSUE THREAD

**Issue by galaxylqx** [apache/shardingsphere#15881]
Problem description: Multiple data sources use the same database instance. For example, if the host is 127.0.0.1 and the port is 3306, multiple data sources need to be created. If the same database instance has 100 databases, 100 data sources need to be created.
```
schemaName: sharding_db
  dataSources:
    ds_0:
      url: jdbc:mysql://127.0.0.1:3306/order_db_0?serverTimezone=UTC&useSSL=false
      username: root
      password:
      connectionTimeoutMilliseconds: 30000
      idleTimeoutMilliseconds: 60000
      maxLifetimeMilliseconds: 1800000
      maxPoolSize: 50
      minPoolSize: 1
    ds_1:
      url: jdbc:mysql://127.0.0.1:3306/order_db_1?serverTimezone=UTC&useSSL=false
      username: root
      password:
      connectionTimeoutMilliseconds: 30000
      idleTimeoutMilliseconds: 60000
      maxLifetimeMilliseconds: 1800000
      maxPoolSize: 50
      minPoolSize: 1
 rules:
 - !SHARDING
   tables:
     t_order:
       actualDataNodes: ds_${0..1}.t_order_${0..1}
       tableStrategy:
         standard:
           shardingColumn: order_id
           shardingAlgorithmName: t_order_inline
```
Solution: The data source connection does not specify a specific database, the data source is only a database connection, and the real database corresponding to the data source is maintained through memory map mapping.
```
schemaName: sharding_db
dataSources:
  ds:
    url: jdbc:mysql://127.0.0.1:3306/?serverTimezone=UTC&useSSL=false
    username: root
    password:
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
 rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds.order_db_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
```
Add map in memory for data source and database mapping relationship

| key                       | value               |
| ---------------- | -------------- |
| ds.order_db_0    |  order_db_0    |
| ds.order_db_1     |  order_db_1    |
