### ISSUE TITLE
5.0.0+DruidDataSource+jpa get a Exception while run app

### ISSUE THREAD

**Issue by breezeLoganGithub** [apache/shardingsphere#15938]
myconfig:
server:
  # 服务器的HTTP端口，默认为80
  port: 8080

# Spring配置
spring:
  shardingsphere:
    # 数据源配置
    datasource:
      # 数据源名称，多数据源以逗号分隔
      names: db0 #
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.18.128:3307/shardingsphere?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    # 规则配置
    rules:
      sharding:
        tables:
          # 逻辑表名称
          t_order:
            # 行表达式标识符可以使用 ${...} 或 $->{...}，但前者与 Spring 本身的属性文件占位符冲突，因此在 Spring 环境中使用行表达式标识符建议使用 $->{...}
            actual-data-nodes: db0.t_order_$->{0..1}
            # 分表策略
            table-strategy:
              standard:
                # 分片列名称
                sharding-column: order_id
                # 分片算法名称
                sharding-algorithm-name: table-inline
            # 表主键算法
            key-generate-strategy:
              column: order_id
              key-generator-name: snowflake
        # 分片算法配置
        sharding-algorithms:
          table-inline:
            # 分片算法类型
            type: INLINE
            props:
              # 分片算法的行表达式
              algorithm-expression: t_order_$->{order_id % 2}
        # 分布式序列算法配置
        key-generators:
          snowflake:
            # 分布式序列算法（雪花算法：SNOWFLAKE； UUID：UUID）
            type: SNOWFLAKE
            # 分布式序列算法属性配置
            props:
              # 工作机器唯一标识
              worker-id: 123
    props:
      # 展示修改以后的sql语句
      sql-show: true

run app get a Exception:
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-03-09 18:19:59.750 ERROR 12308 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

Process finished with exit code 1

**Comment by zjcnb** [comment]
@breezeLoganGithub Hi, it 's work well when i use your cofiguratuin.

```
spring:
  shardingsphere:
    datasource:
      names: db0
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: db0.t_order_$->{0..1}
            table-strategy:
              standard:
                sharding-column: order_id
                sharding-algorithm-name: table-inline
            table-inline:
              type: INLINE
              algorithm-expression: t_order_$->{order_id % 2}
```

Btw, According your error message, i think your loss mysql or druid dependency.
