### ISSUE TITLE
[New Feature] Detect master-slave replication delay in `shardingsphere-db-discovery-provider` module

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#15967]
Hi community,
   
   We plan to monitor slave data source delay time when we use `readwrite-splitting`. We can set a threshold for the delay time for every slave data source, `ShardingSphere` will automatic offline this data source when slave data source delay time exceeded threshold, it is convenient for us to better route the read traffic. And we can use `DistSQL` to show all slave data source delay time.

   So, when we use` readwrite-splitting` and want to detect slave delay time. The config is :

```
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        type: Dynamic
        props:
          auto-aware-data-source-name: replication_delay_ds
  - !DB_DISCOVERY
    dataSources:
      replication_delay_ds:
        discoveryHeartbeatName: replication_delay_heartbeat
        discoveryTypeName: replication_delay
    discoveryHeartbeats:
      replication_delay_heartbeat:
        props:
          keep-alive-cron: '0/1 * * * * ?'
    discoveryTypes:
      replication_delay:
        type: Replication_delay
        props:
          write-data-source-name: write_ds
          read-data-source-names: read_ds_0,read_ds_1
          delay_milliseconds_threshold: 1000
```

By the way, if you don't want to enable the detection delay feature, the configuration is still the original. The config is :

```
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      type: Static
      props:
        write-data-source-name: write_ds
        read-data-source-names: read_ds_0, read_ds_1
```

`Task list:`

- [ ] `Rename shardingsphere-db-discovery-mgr` to `shardingsphere-db-discovery-mysql`.
- [ ]  Implement `DatabaseDiscoveryType` interface and complete the detect feature.
- [ ]  Adjust document.
- [ ]  Design `DistSQL` syntax. @lanchengx
