### ISSUE TITLE
Lost quotes for value in `PROPERTIES` when adding rules using DistSQL

### ISSUE THREAD

**Issue by wangzb105** [apache/shardingsphere#15970]
## Question
**Using Yaml**
```yaml
yaml config
shardingAlgorithms:
      db_sharding_by_area:
        type: INLINE
        props:
          algorithm-expression: seer_${area==0?'default':area}
```
result:
```shell
mysql> show sharding algorithms;
+------------------------------+--------+------------------------------------------------------------------+
| name                         | type   | props                                                            |
+------------------------------+--------+------------------------------------------------------------------+
| db_sharding_by_area          | INLINE | algorithm-expression=seer_${area==0?'default':area}              |
```
**Using DistSQL**

```shell
create sharding algorithm db_sharding_by_area (
    type(name=inline,properties("algorithm-expression"="seer_${area==0?'default':area}"))
);
```
result:
```
mysql> show sharding algorithms;
+------------------------------+--------+------------------------------------------------------------------+
| name                         | type   | props                                                            |
+------------------------------+--------+------------------------------------------------------------------+
| db_sharding_by_area          | INLINE | algorithm-expression=seer_${area==0?default:area}              |
```
use shardingsphere-proxy-5.1.0 version
The sharded database algorithm created using DistSql RDL does not recognize the default string in the expression
