### ISSUE TITLE
Consider refactor Register center storage node structure

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16217]
Hi community, 

### `Background`

Please refer to : #15967 

   We want to persistence slave-database delay time to register center. So we can use `DistSQL` to show all slave-database delay time. And still have a question with the current  storage node structure, When we have two groups of the same rule names under one schema, we cannot distinguish which group of datasources are disabled. 
   So, we need to adjustment it.

### `Old structure`

```
storage_nodes:
    disable: 
        readwrite_splitting_db.read_ds_0
```

### `New structure`

```
storage_nodes:
    attributes:
        schema_1.logic_ds.ds_0:
              role: primary
              status: enable
        schema_1.logic_ds.ds_1:
              role: member
              status: enable
              replication_delay_time: 1000
        schema_2.logic_ds.ds_0:
              role: primary
              status: enable
        schema_2.logic_ds.ds_1:
              role: member
              status: enable
              replication_delay_time: 1000
```
