### ISSUE TITLE
Can not be represented as java.sql.Timestamp

### ISSUE THREAD

**Issue by limengjia** [apache/shardingsphere#16425]
### Which version of ShardingSphere did you use?
ShardingSphere Version: 5.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Project:  ShardingSphere-Proxy

### Expected behavior
When I execute a sql which result contains timestamp , sharding-proxy returns an error message: 
mysql> select * from  app_mst  where app_id='test';
ERROR 2013 (HY000): Lost connection to MySQL server during query

### Actual behavior
mysql> select registration_time,app_name,app_id  from  app_mst  where app_id='test';
+---------------------+----------+----------+
| registration_time   | app_name | app_id   |
+---------------------+----------+----------+
| 0000-00-00 00:00:00 | test     | test|
+---------------------+----------+----------+

### Reason analyze (If you can)
Because the timestamp column does not conform to the strict sql_mode of mysql.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
CREATE TABLE `app_mst` (
  `update_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `registration_time` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '注册时间',
  `app_id` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '应用APPID',
  `app_name` varchar(32) COLLATE utf8_bin NOT NULL COMMENT '应用名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

insert into app_mst(app_id,app_name) values ('test','test');

select * from app_mst;

**Comment by TeslaCN** [comment]
@limengjia Thanks for your feedback!

**Comment by TeslaCN** [comment]
I found this issue is caused by MySQL Connector's default behaviour.
https://github.com/mysql/mysql-connector-j/blob/ad86f36e100e104cd926c6b81c8cab9565750116/src/com/mysql/jdbc/ConnectionPropertiesImpl.java#L1256-L1260

Add the `zeroDateTimeBehavior=round` to JDBC URL may avoid the error.

```yaml
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/freedom?zeroDateTimeBehavior=round
    username: root
    password: root
    connectionTimeoutMilliseconds: 1000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 128
    minPoolSize: 0
```
