### ISSUE TITLE
comment not worked shardingsphere-proxy

### ISSUE THREAD

**Issue by liuyibo123** [apache/shardingsphere#16457]
I did this works ,but its not route to write db.I want to make sure , does proxy not support comment ? 
1.  I added ```/* ShardingSphere hint: writeRouteOnly=true */``` before my sql 
2. seted `sql_comment_parse_enable` true
3. seted `proxy_hint_enabled` true  in server.yaml

I use `set readwrite_splitting hint source=write` works.

**Comment by TeslaCN** [comment]
If you are using `mysql` cli, you may need to add `-c` to enable sending comments.

**Comment by liuyibo123** [comment]
> If you are using `mysql` cli, you may need to add `-c` to enable sending comments.

I am using jdbc and the log  of shardingsphere-proxy is :
```sql
Logic SQL: /* ShardingSphere hint: writeRouteOnly=true */select * from co_item_invty where com_id = '11150101' and item_id = '40331000775481'
ShardingSphere-SQL - SQLStatement: MySQLSelectStatement(table=Optional.empty, limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
ShardingSphere-SQL - Actual SQL: ds0_slave0 ::: /* ShardingSphere hint: writeRouteOnly=true */select * from co_item_invty where com_id = '11150101' and item_id = '40331000775481'
```
comments is sended to proxy

server.yaml

```yaml
rules:
  - !AUTHORITY
    users:
      - root@:root
    provider:
      type: ALL_PRIVILEGES_PERMITTED

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-opentracing-enabled: false
  proxy-hint-enabled: true
  sql-show: true
  check-table-metadata-enabled: false
```
