### ISSUE TITLE
Logical replication slot created too late cause partial incremental data lost in openGauss scaling job

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#16768]
### Which version of ShardingSphere did you use?
master branch, commit 22e7fa81d5541f31a9ee5e69d55714005c138564

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy, backend database is MogDB (based on openGauss)

### Expected behavior
Incremental data (INSERT/UPDATE/DELETE during inventory data sync) could be synchronized to new shard.

### Actual behavior
Part of incremental data is lost.

### Reason analyze (If you can)
Logical replication slot is created too late (after inventory data sync done).

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Install MogDB in docker, and create initial DBs
SQLs, ( gsql -d postgres )
```
drop database if exists scaling_ds_0;
create database scaling_ds_0;

drop database if exists scaling_ds_1;
create database scaling_ds_1;
```

2. config-sharding.yaml of proxy
```
schemaName: scaling_db

dataSources:
  ds_0:
    url: jdbc:opengauss://127.0.0.1:15432/scaling_ds_0
    username: mogdb
    password: Enmo@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:opengauss://127.0.0.1:15432/scaling_ds_1
    username: mogdb
    password: Enmo@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    autoTables:
      t_order:
        actualDataSources: ds_0,ds_1
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: t_order_snowflake
        logicTable: t_order
        shardingStrategy:
          standard:
            shardingAlgorithmName: t_order_hash_mod
            shardingColumn: order_id
      t_order_item:
        actualDataSources: ds_0,ds_1
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: t_order_item_snowflake
        logicTable: t_order_item
        shardingStrategy:
          standard:
            shardingAlgorithmName: t_order_item_hash_mod
            shardingColumn: order_id
    bindingTables:
      - t_order,t_order_item
    keyGenerators:
      t_order_snowflake:
        type: snowflake
      t_order_item_snowflake:
        type: snowflake
    shardingAlgorithms:
      t_order_hash_mod:
        props:
          sharding-count: '4'
        type: hash_mod
      t_order_item_hash_mod:
        props:
          sharding-count: '4'
        type: hash_mod
    scalingName: scaling_name1
    scaling:
      scaling_name1:
        completionDetector:
          props:
            incremental-task-idle-second-threshold: '60'
          type: IDLE
        dataConsistencyChecker:
          props:
            chunk-size: '1000'
          type: DATA_MATCH
```

3. Start proxy, login by gsql. Create table and insert data, then emit scaling job:
SQLs in proxy ( gsql --host=host.docker.internal --port=3307 scaling_db root ):
```
CREATE TABLE t_order (order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, PRIMARY KEY (order_id));

CREATE TABLE t_order_item (item_id INT NOT NULL, order_id INT NOT NULL, user_id INT NOT NULL, status VARCHAR(45) NULL, creation_date DATE, PRIMARY KEY (item_id));

insert into t_order (order_id, user_id, status) values (1,2,'ok'),(2,4,'ok'),(3,6,'ok'),(4,1,'ok'),(5,3,'ok'),(6,5,'ok');

insert into t_order_item (item_id, order_id, user_id, status) values (1,1,2,'ok'),(2,2,4,'ok'),(3,3,6,'ok'),(4,4,1,'ok'),(5,5,3,'ok'),(6,6,5,'ok');
```

SQLs in MogDB:
```
drop database if exists scaling_ds_10;
create database scaling_ds_10;

drop database if exists scaling_ds_11;
create database scaling_ds_11;

drop database if exists scaling_ds_12;
create database scaling_ds_12;
```

DistSQLs in proxy:
```
ADD RESOURCE ds_2 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_10",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
), ds_3 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_11",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
), ds_4 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_12",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
);

ALTER SHARDING TABLE RULE t_order(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
), t_order_item(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
);
```

4. Update some records before incremental data sync starting.
Since dataset for testing is small, inventory data sync might be done quickly, so I set a breakpoint in proxy running in IDE
`OpenGaussWalDumper.initReplication()`:
```
    private MppdbDecodingPlugin initReplication() {
        try {
            DataSource pipelineDataSource = PipelineDataSourceCreatorFactory.getInstance( // breakpoint on this line
                    dumperConfig.getDataSourceConfig().getType()).createPipelineDataSource(dumperConfig.getDataSourceConfig().getDataSourceConfiguration());
            try (Connection connection = pipelineDataSource.getConnection()) {
                slotName = OpenGaussLogicalReplication.getUniqueSlotName(connection);
                OpenGaussLogicalReplication.createIfNotExists(connection);
                return new MppdbDecodingPlugin(new OpenGaussTimestampUtils(connection.unwrap(PgConnection.class).getTimestampUtils()));
            }
        } catch (final SQLException ex) {
            log.warn("Create replication slot failed!");
        }
        return null;
    }
```

5. Update some records, and then resume program
```
update t_order set status='ok1' where order_id=1;

update t_order set status='ok2' where order_id=2;

update t_order set status='ok3' where order_id=3;
```

6. Check scaling job result after past idle time is more than incremental-task-idle-second-threshold

Data consistency check failed.

Check t_order data in source (ds_0, ds_1) and target (ds_2, ds_3, ds_4).
```
MogDB=>create database scaling_db2;

MogDB=>\c scaling_db2
Password for user root:
Non-SSL connection (SSL connection is recommended when requiring high-security)
You are now connected to database "scaling_db2" as user "root".

MogDB=>ADD RESOURCE ds_2 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_10",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
), ds_3 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_11",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
), ds_4 (
    URL="jdbc:opengauss://127.0.0.1:15432/scaling_ds_12",
    USER=mogdb,
    PASSWORD=Enmo@123,
    PROPERTIES("maximumPoolSize"=50,"idleTimeout"="60000")
);
CREATE
MogDB=>CREATE SHARDING TABLE RULE t_order(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
), t_order_item(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
);
CREATE
MogDB=>preview select * from t_order;
 data_source_name |                        actual_sql
------------------+-----------------------------------------------------------
 ds_2             | select * from t_order_0 UNION ALL select * from t_order_3
 ds_3             | select * from t_order_1 UNION ALL select * from t_order_4
 ds_4             | select * from t_order_2 UNION ALL select * from t_order_5
(3 rows)

MogDB=>select * from t_order;
 order_id | user_id | status
----------+---------+--------
        6 |       5 | ok
        3 |       6 | ok
        1 |       2 | ok
        4 |       1 | ok
        2 |       4 | ok
        5 |       3 | ok
(6 rows)

MogDB=>\c scaling_db
Password for user root:
Non-SSL connection (SSL connection is recommended when requiring high-security)
You are now connected to database "scaling_db" as user "root".
MogDB=>preview select * from t_order;
 data_source_name |                        actual_sql
------------------+-----------------------------------------------------------
 ds_0             | select * from t_order_0 UNION ALL select * from t_order_2
 ds_1             | select * from t_order_1 UNION ALL select * from t_order_3
(2 rows)

MogDB=>select * from t_order;
 order_id | user_id | status
----------+---------+--------
        4 |       1 | ok
        6 |       5 | ok
        2 |       4 | ok2
        5 |       3 | ok
        1 |       2 | ok1
        3 |       6 | ok3
(6 rows)
```
Records in target (ds_2, ds_3, ds_4) was not udpated.
