### ISSUE TITLE
In some case ,Proxy cluster mode not available.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#16784]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.1.1 snapshot 
commit id 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Proxy A stop；Proxy B alive.
### Actual behavior
Proxy A stop；Proxy B dead.
### Reason analyze (If you can)
Can't
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Build Proxy
2. Rename Proxy to 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae
3. add MySQL connector to lib
4. Config server.yaml 
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: zklock
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-hint-enabled: false
  sql-show: false
  check-table-metadata-enabled: false
  show-process-list-enabled: false
    # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
    # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  check-duplicate-table-enabled: false
  proxy-frontend-executor-size: 0 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
    # Available options of proxy backend executor suitable: OLAP(default), OLTP. The OLTP option may reduce time cost of writing packets to client, but it may increase the latency of SQL execution
    # and block other clients if client connections are more than `proxy-frontend-executor-size`, especially executing slow SQL.
  proxy-backend-executor-suitable: OLAP
  proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
  sql-federation-enabled: false
    # Available proxy backend driver type: JDBC (default), ExperimentalVertx
  proxy-backend-driver-type: JDBC
```
5. Build another Proxy
```
cp -r 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae.bak
```
6. start Proxy A;stop Proxy B
```
cd 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae;./bin/start.sh 3333
cd 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae.bak;./bin/start.sh 4444
```
7. stop Proxy A 
```
cd 5aa2071bcb1d850b61b8e2b98ba77f2d12b683ae;./bin/stop.sh 3333
```
8. Then we can find Proxy B is dead.
