### ISSUE TITLE
Database selection error during SQL execution

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#16829]
# Question
- Shardingsphere proxy version 5.1.1
- configuration file
Zookeeper is used, and the configuration file is as follows

customer_delivery_dev datasources:
```yaml
ds_0:
  password: xxxxxxxxx
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.6:3306/customer_delivery_dev
  username: root
```

crawler2021 datasources:
```yaml
ds_0:
  password: xxxx
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.6:3306/crawler2021_0
  username: root
ds_1:
  password: xxxx
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.7:3306/crawler2021_1
  username: root
ds_2:
  password: xxxx
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.8:3306/crawler2021_2
  username: root
ds_3:
  password: xxxx
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.9:3306/crawler2021_3
  username: root

```

- error message

![error](https://raw.githubusercontent.com/novice-gamer/picture/master/9ef8013576763fdd87990356fe866e5.png)

The database queried is customer_ Delivery_ Dev, why from crawler2021_ 0 database?
There is no similar problem when using version 5.1.0. Why does this problem occur when updating to 5.1.1?
