### ISSUE TITLE
Version compatibility issues

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#16856]
## Question
The same nodes on zookeeper are used, and only data sources are configured without table splitting rules. After updating the version, the following problems occur;

- Shardingsphere proxy version 5.1.0
![error1](https://raw.githubusercontent.com/novice-gamer/picture/master/0f19db020ee34ac7e2eff5d285ab7e2.png)

- Shardingsphere proxy version 5.1.1
![error2](https://raw.githubusercontent.com/novice-gamer/picture/master/4fc8b987897ebbecee83d8904af88d5.png)

- Log of shardingsphere proxy
![error3](https://raw.githubusercontent.com/novice-gamer/picture/master/20220415153141.png)

- rules config:
```yaml
- !AUTHORITY
  provider:
    props:
      user-schema-mappings: root@=customer_delivery_dev
    type: SCHEMA_PRIVILEGES_PERMITTED
  users:
    - root@%:11111
- !TRANSACTION
  defaultType: XA
  providerType: Atomikos
```

- database resource
```yaml
ds_0:
  password: 11111
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  url: jdbc:mysql://192.168.1.6:3306/customer_delivery_dev
  username: root
```
