### ISSUE TITLE
SHOW TABLES the case of the table name problem

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#16960]
```
mysql> show tables;

+----------------------------------+------------+
| Tables_in_readwrite_splitting_db | Table_type |
+----------------------------------+------------+
| ORDER                            | BASE TABLE |
+----------------------------------+------------+
1 row in set (0.00 sec)
```

```
columns:
  order_id:
    caseSensitive: true
    dataType: 12
    generated: false
    name: order_id
    primaryKey: true
  price:
    caseSensitive: false
    dataType: 8
    generated: false
    name: price
    primaryKey: false
  name:
    caseSensitive: true
    dataType: 12
    generated: false
    name: name
    primaryKey: false
indexes:
  primary:
    name: PRIMARY
name: ORDER
```
