### ISSUE TITLE
OperationalError: (1997, 'Runtime exception: [Sequence ID of MySQL command packet must be `0`.]')

### ISSUE THREAD

**Issue by novice-gamer** [apache/shardingsphere#17015]
Sharding proxy version 5.1.0

Using Python to import data, an error is reported when it reaches one million:
Pymysql is used
```
OperationalError: (1997, 'Runtime exception: [Sequence ID of MySQL command packet must be `0`.]')
```
Props configuration information:

```yaml
proxy-frontend-executor-size: 0
proxy-frontend-flush-threshold: 128
allow.range.query.with.inline.sharding: true
proxy-frontend-max-connections: 0
check-duplicate-table-enabled: false
proxy-backend-query-fetch-size: -1
kernel-executor-size: 16
show-process-list-enabled: false
proxy-backend-executor-suitable: OLAP
proxy-hint-enabled: false
sql-show: true
proxy-opentracing-enabled: false
sql-federation-enabled: false
max-connections-size-per-query: 1
check-table-metadata-enabled: false
```

Rules configuration:

```yaml
- !SHARDING
  keyGenerators:
    csys_build_demand_sx61_snowflake:
      type: snowflake
    csys_company_demand_sx61_snowflake:
      type: snowflake
  tables:
    csys_build_demand_sx61:
      actualDataNodes: ds_0.csys_build_demand_sx61
      keyGenerateStrategy:
        column: id
        keyGeneratorName: csys_build_demand_sx61_snowflake
      logicTable: csys_build_demand_sx61
    csys_company_demand_sx61:
      actualDataNodes: ds_0.csys_company_demand_sx61
      keyGenerateStrategy:
        column: id
        keyGeneratorName: csys_company_demand_sx61_snowflake
      logicTable: csys_company_demand_sx61

```
