### ISSUE TITLE
ShardingSphereLock.tryLock try lock not take effect sometimes.

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#17388]
## Bug Report

When i test `RuleAlteredJobAPIImpl.stopClusterWriteDB` method
`lock.tryLock()` execute succeed, but the `lock.isLocked()` return false.

### Which version of ShardingSphere did you use?

master b4f748242ca44dc4d3319d9b5a8f5ada08765f8a

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

`lock.isLocked()`  return success.

### Actual behavior
<img width="954" alt="image" src="https://user-images.githubusercontent.com/101622833/167120472-ba08734b-ea5f-4ab3-9f92-c98b6e827f30.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

- Step 1
Start multiple proxy, they share the same zookeeperr configuration 
eg:
proxy one is on port 3307, proxy two is on port 3308
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/101622833/167120783-6aadbd9e-d723-4340-a16a-053f31517a7d.png">

server.yaml 
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: pg
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PRIVILEGES_PERMITTED
  - !SQL_PARSER
    sqlCommentParseEnabled: true
    sqlStatementCache:
      initialCapacity: 2000
      maximumSize: 65535
      concurrencyLevel: 4
    parseTreeCache:
      initialCapacity: 128
      maximumSize: 1024
      concurrencyLevel: 4

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-hint-enabled: false
  sql-show: true
  check-table-metadata-enabled: false
  show-process-list-enabled: false
    # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
    # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  check-duplicate-table-enabled: false
  proxy-frontend-executor-size: 0 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
    # Available options of proxy backend executor suitable: OLAP(default), OLTP. The OLTP option may reduce time cost of writing packets to client, but it may increase the latency of SQL execution
    # and block other clients if client connections are more than `proxy-frontend-executor-size`, especially executing slow SQL.
  proxy-backend-executor-suitable: OLAP
  proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
  sql-federation-enabled: false
    # Available proxy backend driver type: JDBC (default), ExperimentalVertx
  proxy-backend-driver-type: JDBC
  proxy-mysql-default-version: 5.7.22 # In the absence of schema name, the default version will be used.
  proxy-default-port: 3307 # Proxy default port.
  proxy-frontend-database-protocol-type: PostgreSQL
```

- Step 2
> make sure already install docker, IT test will use it.

open the class `org.apache.shardingsphere.integration.data.pipeline.cases.postgresql.PostgreSQLManualScalingIT`
edit run configuration. add `-Dit.cluster.env.type=native -Dit.env.postgresql.version=postgres:12` 

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/101622833/167121628-8f9e6d88-5685-4dd4-a687-31cab183feac.png">

then execute the IT test

The final problem was
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/101622833/167122112-ab44e4ee-2222-4654-8c6c-cffd4db8df58.png">
seems not lock succeed before.
