### ISSUE TITLE
Wrong route result when execute create schema statement in encrypt scenario

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17406]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/a2605cdf4680db08137c4b888d8b26de7eeaf4e2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Route `CREATE SCHEMA test_schema_1;` statement to all datasource.

### Actual behavior

Following is encrypt config:

```yaml
databaseName: encrypt_db

dataSources:
  ds_0:
    url: jdbc:opengauss://127.0.0.1:15432/encrypt_ds_0
    username: gaussdb
    password: Sphere@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:opengauss://127.0.0.1:15432/encrypt_ds_1
    username: gaussdb
    password: Sphere@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_order:
      columns:
        content:
          plainColumn: content_plain
          cipherColumn: content_cipher
          encryptorName: aes_encryptor
```

When I execute `CREATE SCHEMA test_schema_1;`, the route result is wrong.

```
[INFO ] 2022-05-07 11:04:40.319 [Connection-6-ThreadExecutor] ShardingSphere-SQL - Logic SQL: CREATE SCHEMA test_schema_1;
[INFO ] 2022-05-07 11:04:40.319 [Connection-6-ThreadExecutor] ShardingSphere-SQL - SQLStatement: OpenGaussCreateSchemaStatement(username=Optional.empty)
[INFO ] 2022-05-07 11:04:40.320 [Connection-6-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds_0 ::: CREATE SCHEMA test_schema_1;
```
