### ISSUE TITLE
New version metadata lost data after alterting sharding table rule

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#17427]
### Which version of ShardingSphere did you use?
master branch, commit 43a33ebda4b6c669e2fd35043fb130edeb939040

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Proxy, scaling enabled

### Expected behavior
New version metadata do not lose data when alterting sharding table rule.

### Actual behavior
Only altered table's rule is kept.

Version 0 metadata:
```
  autoTables:
    t_order:
      actualDataSources: ds_0,ds_1
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: t_order_snowflake
      logicTable: t_order
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_hash_mod
          shardingColumn: order_id
    t_order_item:
      actualDataSources: ds_0,ds_1
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: t_order_item_snowflake
      logicTable: t_order_item
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_item_hash_mod
          shardingColumn: order_id
```

After executing DistSQL:
```
ALTER SHARDING TABLE RULE t_order(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
);
```

Version 1 metadata:
```
  autoTables:
    t_order:
      actualDataSources: ds_2,ds_3,ds_4
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: t_order_snowflake
      logicTable: t_order
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_hash_mod
          shardingColumn: order_id
```

### Reason analyze (If you can)
Seems it's affected by #17088.

In `AlterShardingTableRuleStatementPreprocessor.preprocess`:
```
    public ShardingRuleConfiguration preprocess(final ShardingRuleConfiguration currentRuleConfig, final ShardingRuleConfiguration toBeAlteredRuleConfig) {
        ShardingRuleConfiguration result = new ShardingRuleConfiguration();
        result.setShardingAlgorithms(toBeAlteredRuleConfig.getShardingAlgorithms());
        result.setAutoTables(toBeAlteredRuleConfig.getAutoTables());
        result.setDefaultShardingColumn(currentRuleConfig.getDefaultShardingColumn());
        result.setDefaultTableShardingStrategy(currentRuleConfig.getDefaultTableShardingStrategy());
        result.setBindingTableGroups(currentRuleConfig.getBindingTableGroups());
        result.setDefaultDatabaseShardingStrategy(currentRuleConfig.getDefaultDatabaseShardingStrategy());
        result.setTables(toBeAlteredRuleConfig.getTables());
        result.setBroadcastTables(currentRuleConfig.getBroadcastTables());
        result.setDefaultKeyGenerateStrategy(currentRuleConfig.getDefaultKeyGenerateStrategy());
        result.setKeyGenerators(toBeAlteredRuleConfig.getKeyGenerators());
        result.setScalingName(currentRuleConfig.getScalingName());
        result.setScaling(currentRuleConfig.getScaling());
        return result;
    }
```
Part metadata of result is overwritten to toBeAlteredRuleConfig one, e.g `result.setAutoTables(toBeAlteredRuleConfig.getAutoTables());`.

Screenshot:
<img width="1400" alt="WX20220507-190045@2x" src="https://user-images.githubusercontent.com/42492540/167251536-3e88dd60-4e53-41e6-a246-50dcd15b8da4.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Alter part table sharding rule.
e.g. if there're autoTables `t_order` and `t_order_item`, then execute DistSQL:
```
ALTER SHARDING TABLE RULE t_order(
RESOURCES(ds_2,ds_3,ds_4),
SHARDING_COLUMN=order_id,
TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=6)),
KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
);
```
