### ISSUE TITLE
Metadata can't be loaded when executing `CREATE SCHEMA.TABLE` statement in encrypt scenario

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17449]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/3ebf5143c9bb818231b50da5b461d392d29ba4ff

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute `CREATE SCHEMA test_schema_1;`, and load encrypt metadata successfully.

### Actual behavior

Metadata can't be loaded when executing `CREATE SCHEMA.TABLE` statement in encrypt scenario.

Following is my encrypt config.

```yaml
databaseName: encrypt_db

dataSources:
  ds_0:
    url: jdbc:opengauss://127.0.0.1:15432/encrypt_ds_0
    username: gaussdb
    password: Sphere@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:opengauss://127.0.0.1:15432/encrypt_ds_1
    username: gaussdb
    password: Sphere@123
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_order:
      columns:
        content:
          plainColumn: content_plain
          cipherColumn: content_cipher
          encryptorName: aes_encryptor
```
