### ISSUE TITLE
Cross database query ,prompt:  schme not exist

### ISSUE THREAD

**Issue by q3056917665** [apache/shardingsphere#17482]
version

```
  <groupId>org.apache.shardingsphere</groupId>
  <artifactId>shardingsphere-jdbc-core</artifactId>
  <version>5.1.1</version>
```

When I cross database query，it prompt "schme not exist" for me.
So what configuration does it need？of course I didn't find this configuration,
or it not support Cross database query.

**Comment by TeslaCN** [comment]
You may configure data sources and `actualDataNodes` in sharding rule. Such as:

```yaml
dataSources:
  ds_0:
    url: xxx
  ds_1:
    url: xxx
rules:
  - !SHARDING
    bindingTables: []
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:
    keyGenerators:
      snowflake:
        props:
          worker-id: 123
        type: SNOWFLAKE
    tables:
      bmsql_config:
        actualDataNodes: ds_0.bmsql_config
```
