### ISSUE TITLE
 Insert statement does not support sharding table routing to multiple data nodes

### ISSUE THREAD

**Issue by StupidManYI** [apache/shardingsphere#17614]
when I save some data ,the console output 

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/50037510/168070610-2a93f5cf-0dde-4eea-aecf-5bec9e7cbe58.png">

pom.xml
```
        <shardingsphere.version>5.1.1</shardingsphere.version>
        <druid.version>1.2.8</druid.version>
        <mysql.version>8.0.17</mysql.version>
```

application.yml
```
spring:
  shardingsphere:
    mode:
      type: Memory
    datasource:
      names: master,slave0,slave1,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://101.35.182.169:8888/sharding_master1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: "123456"
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://101.35.182.169:8888/sharding_slave0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: "123456"
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://101.35.182.169:8888/sharding_slave1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: "123456"
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://101.35.182.169:8888/sharding_slave2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
        username: root
        password: "123456"
    rules:
      sharding:
#        autoTables:
#          user:
#            # 指定使用的数据源
#            actualDataSources: ds_${0..2}
#            shardingStrategy:
#              standard:
#                shardingColumn: id
#                shardingAlgorithmName: mod
#        shardingAlgorithms:
#          mod:
#            type: MOD
#            props:
#              # 指定分片数量
#              sharding-count: 3
        tables:
          user:
            actualDataNodes: slave0.user$->{0..1}
            tableStrategy:
              none:
            databaseStrategy:
              inline:
                shardingColumn: id
#                shardingAlgorithmName: SNOWFLAKE # 分片算法名称
                algorithmExpression: slave0.user$->{id % 2}
            keyGenerator:
              type: SNOWFLAKE
              column: id
  #            actualDataNodes: ds_${0..2}.user
  #            tableStrategy:
  #              standard:
  #                shardingColumn: id
  #            keyGenerateStrategy:
  #              column: id
  #              keyGeneratorName: SNOWFLAKE

  datasource:
    dynamic:
      datasource:
        master:
          username: root
          password: "123456"
          url: jdbc:mysql://101.35.182.169:8888/sharding_master1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
          driverClassName: com.mysql.jdbc.Driver
        test:
          username: root
          password: "123456"
          url: jdbc:mysql://101.35.182.169:8888/sharding_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
          driverClassName: com.mysql.jdbc.Driver
logging:
  level:
    com.baomidou: debug
    org.apache.shardingsphere: debug



```
