### ISSUE TITLE
How to set poolName for HikariPool ?

### ISSUE THREAD

**Issue by Glowdable** [apache/shardingsphere#17646]
It's necessary for monitoring every datasource.

**Comment by zjcnb** [comment]
The `poolName` is currently not supported, but we can consider support it.

**Comment by zjcnb** [comment]
When you use S`hardingSphere-Proxy`

```
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    customPoolProps:
      poolName: datasource-two
```

When you use ShardingSphere-JDBC

```
      ds_1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        poolName: datasource-two
```
