### ISSUE TITLE
Mybatis INSERT foreach case SQLSyntaxErrorException

### ISSUE THREAD

**Issue by wingkingbobo** [apache/shardingsphere#17870]
### Which version of ShardingSphere did you use?
5.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
The following INSERT statement can run normally when calling MySQL directly, but an exception is thrown after using Sharding-Proxy.
```
@Insert(value = {"<script>insert into ${tableName} (shapeid, userid, groupid, create_userid, name, type, name_alias, " +
		"stringvalue, doublevalue, intvalue, blobvalue, version, datasize, createtime, modifytime, deleted) values" +
		"<foreach item='item' index='index' collection='propertyExList' separator=','>" +
		"(#{item.builder.serverPID}, #{item.userID}, #{item.groupID}, #{item.userID}, " +
		"#{item.builder.fieldName}, #{item.builder.type}, #{item.builder.fieldName2}, " +
		"#{item.builder.stringValue}, #{item.builder.doubleValue}, #{item.builder.intValue}, " +
		"#{item.blobValue}, #{item.builder.version}, #{item.dataSize}, " +
		"#{item.builder.createTime}, #{item.builder.modifyTime}, #{item.builder.deleted})" +
		"</foreach></script>"})
@Options(useGeneratedKeys=true, keyProperty="propertyExList.builder.serverID", keyColumn="id")
boolean insertBatchProperty(@Param("tableName") String tableName,
	                            @Param("propertyExList") List<PropertyEx> propertyExList);
```

### Actual behavior
```
### Error updating database.  Cause: java.sql.SQLSyntaxErrorException: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
### The error may exist in xxx/cn/syncserver/dao/UploadShapeDao.java (best guess)
### The error may involve xxx.cn.syncserver.dao.UploadShapeDao.insertBatchProperty-Inline
### The error occurred while setting parameters
### SQL: insert into shape_property_simple (shapeid, userid, groupid, create_userid, name, type, name_alias, stringvalue, doublevalue, intvalue, blobvalue, version, datasize, createtime, modifytime, deleted) values  (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) , (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
### Cause: java.sql.SQLSyntaxErrorException: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
```

### Reason analyze (If you can)
I found that the following insert statement can be executed. The only difference between it and the previous statements with errors is that it does not contain ` (?,?,...)`.
```
[INFO ] 2022-05-23 15:20:37.162 [ShardingSphere-Command-0] ShardingSphere-SQL - Actual SQL: syncdb1 ::: insert into shape_simple (layerid, userid, create_userid, groupid, type, data, minlevel, maxlevel, version, datasize, legend, createtime, modifytime, deleted, create_version) values   (0, 10232, 10232, -1, 1, x'0a1b09c240214c1bc45c4011ee44a401170b4440190000000000000000', 0, 0, 15, 120.0, '', '2022-05-23 15:18:54', '2022-05-23 15:18:54', 0, 15)
```

**Comment by wingkingbobo** [comment]
A simple PrepareStatement will also report an error. I wonder if there is a problem with the support of PrepareStatement.
In this example, the sharding column is userid.
```java
        String jdbcUrl = "jdbc:mysql://localhost:3307/sharding_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai";
//        String jdbcUrl = "jdbc:mysql://localhost:3306/p1?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai";
        DriverManager.registerDriver(new Driver());
        Connection connection = DriverManager.getConnection(jdbcUrl, "root", "123456");

        String sql = "INSERT INTO remark(userid, content, `time`) values (?, ?, ?)";
        java.sql.Date date = new java.sql.Date(remark.getTime().getTime());
        PreparedStatement statement = connection.prepareStatement(sql);
        statement.setLong(1, remark.getUserId());
        statement.setString(2, remark.getContent());
        statement.setDate(3, date);
        statement.execute();
```
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1242)
```

**Comment by strongduanmu** [comment]
Hi @wingkingbobo, thank you for your feedback, can you provide your sharding configuration?

**Comment by wingkingbobo** [comment]
@strongduanmu 
* server.yaml
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: 192.168.0.161:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:123456
    provider:
      type: ALL_PRIVILEGES_PERMITTED
  - !TRANSACTION
    defaultType: LOCAL
    props:
      recoveryStoreUrl: jdbc:mysql://127.0.0.1:3306/jbossts
      recoveryStoreDataSource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      recoveryStoreUser: root
      recoveryStorePassword: 12345678
  - !SQL_PARSER
    sqlCommentParseEnabled: true
    sqlStatementCache:
      initialCapacity: 2000
      maximumSize: 65535
      concurrencyLevel: 4
    parseTreeCache:
      initialCapacity: 128
      maximumSize: 1024
      concurrencyLevel: 4

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  
  proxy-frontend-flush-threshold: 128  
  proxy-hint-enabled: false
  sql-show: true
  check-table-metadata-enabled: false
  show-process-list-enabled: false
  proxy-backend-query-fetch-size: -1
  check-duplicate-table-enabled: false
  proxy-frontend-executor-size: 0 
  proxy-backend-executor-suitable: OLAP
  proxy-frontend-max-connections: 0
  sql-federation-enabled: false
  proxy-backend-driver-type: JDBC

```

* config-sharding.yaml
```

schemaName: sharding_db

dataSources:
  mydb1:
    url: jdbc:mysql://localhost:3306/mydb1?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  mydb_p1:
    url: jdbc:mysql://localhost:3306/mydb_p1?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      layer_major:
        actualDataNodes: mydb1.layer_major,mydb_p$->{1..1}.layer_major
      layer_photo:
        actualDataNodes: mydb1.layer_photo,mydb_p$->{1..1}.layer_photo
      layer_simple:
        actualDataNodes: mydb1.layer_simple,mydb_p$->{1..1}.layer_simple
      layer_simple_group:
        actualDataNodes: mydb1.layer_simple_group,mydb_p$->{1..1}.layer_simple_group
      shpae_file_major:
        actualDataNodes: mydb1.shpae_file_major,mydb_p$->{1..1}.shpae_file_major
      shpae_file_photo:
        actualDataNodes: mydb1.shpae_file_photo,mydb_p$->{1..1}.shpae_file_photo
      shpae_file_simple:
        actualDataNodes: mydb1.shpae_file_simple,mydb_p$->{1..1}.shpae_file_simple
      shpae_file_simple_group:
        actualDataNodes: mydb1.shpae_file_simple_group,mydb_p$->{1..1}.shpae_file_simple_group
      shape_legend_major:
        actualDataNodes: mydb1.shape_legend_major,mydb_p$->{1..1}.shape_legend_major
      shape_legend_photo:
        actualDataNodes: mydb1.shape_legend_photo,mydb_p$->{1..1}.shape_legend_photo
      shape_legend_simple:
        actualDataNodes: mydb1.shape_legend_simple,mydb_p$->{1..1}.shape_legend_simple
      shape_legend_simple_group:
        actualDataNodes: mydb1.shape_legend_simple_group,mydb_p$->{1..1}.shape_legend_simple_group
      shape_major:
        actualDataNodes: mydb1.shape_major,mydb_p$->{1..1}.shape_major
      shape_photo:
        actualDataNodes: mydb1.shape_photo,mydb_p$->{1..1}.shape_photo
      shape_simple:
        actualDataNodes: mydb1.shape_simple,mydb_p$->{1..1}.shape_simple
      shape_simple_group:
        actualDataNodes: mydb1.shape_simple_group,mydb_p$->{1..1}.shape_simple_group
      shape_property_major:
        actualDataNodes: mydb1.shape_property_major,mydb_p$->{1..1}.shape_property_major
      shape_property_photo:
        actualDataNodes: mydb1.shape_property_photo,mydb_p$->{1..1}.shape_property_photo
      shape_property_simple:
        actualDataNodes: mydb1.shape_property_simple,mydb_p$->{1..1}.shape_property_simple
      shape_property_simple_group:
        actualDataNodes: mydb1.shape_property_simple_group,mydb_p$->{1..1}.shape_property_simple_group
      user_version:
        actualDataNodes: mydb1.user_version,mydb_p$->{1..1}.user_version
        databaseStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: database_id
    defaultDatabaseStrategy:
      standard:
        shardingColumn: userid
        shardingAlgorithmName: database_userid
    shardingAlgorithms:
      database_userid:
        type: INLINE
        props:
          algorithm-expression: $->{if(userid instanceof String) {userid = Long.valueOf(userid)};userid<800000?"mydb1":("mydb_p"+((int)((userid-800000)/100000)+1))}
      database_id:
        type: INLINE
        props:
          algorithm-expression: $->{if(id instanceof String) {id = Long.valueOf(id)};id<800000?"mydb1":("mydb_p"+((int)((id-800000)/100000)+1))}
```
