### ISSUE TITLE
About ShardingHere-Proxy Lock Wait Time Out Exceeded; try restarting transaction

### ISSUE THREAD

**Issue by bobogreentea** [apache/shardingsphere#17925]
### Which version of ShardingSphere did you use?
5.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Example codes for reproduce this issue (such as a github link).

```yaml
rules:
- !SHARDING
  tables:
    car_info:
      actualDataNodes: ds_0.car_info_${1..8}
      tableStrategy:
        standard:
          shardingColumn: city_id
          shardingAlgorithmName: car_info_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: carauto
  bindingTables:
    - car_info
  defaultTableStrategy:
    none:
  shardingAlgorithms:
    car_info_inline:
      type: INLINE
      props:
        algorithm-expression: car_info_${city_id}
  
  keyGenerators:
    carauto:
      type: CarautoKeyGen

  scalingName: default_scaling
  scaling:
    default_scaling:
      input:
        workerThread: 40
        batchSize: 1000
      output:
        workerThread: 40
        batchSize: 1000
      streamChannel:
        type: MEMORY
        props:
          block-queue-size: 10000
      completionDetector:
        type: IDLE
        props:
          incremental-task-idle-minute-threshold: 30
      dataConsistencyChecker:
        type: DATA_MATCH
        props:
          chunk-size: 1000
```

[ERROR] 2022-05-25 10:09:15.639 [Connection-2-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
com.mysql.cj.jdbc.exceptions.MySQLTransactionRollbackException: Lock wait timeout exceeded; try restarting transaction

Accumulated 100K+ files are all the same error

![3666](https://user-images.githubusercontent.com/27953104/170166320-6afc03f7-5855-46ac-815e-7e7d3bdfc7e2.png)

![336655](https://user-images.githubusercontent.com/27953104/170166401-f1f298ac-de10-4aa8-9cde-2947003dff15.png)
