### ISSUE TITLE
ALTER SHARDING TABLE RULE trigger refreshRules, but rules are not refreshed correctly

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#17933]
## Bug Report

After `ALTER SHARDING TABLE RULE `  executed, before `apply scaling`, the table rule seems not correct.
At first, the t_order is like this
<img width="326" alt="image" src="https://user-images.githubusercontent.com/101622833/170197405-c4d59239-2f9a-4d0b-a10f-017e27eec8c7.png">

then I execute, target and source have same resource.(i make sure scaling will replace tablename.)
```
ALTER SHARDING TABLE RULE t_order(RESOURCES(ds_0, ds_1),SHARDING_COLUMN=order_id,TYPE(NAME=hash_mod,PROPERTIES('sharding-count'=6)),KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake)));
```

### Which version of ShardingSphere did you use?

master 28d5dfdb89d27fd98dd0c5aedcf07d53538a8ff3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Before `apply scaling` execute, the table rule should use old.

### Actual behavior

The table rule isn't correct 

### Reason analyze (If you can)

<img width="1168" alt="image" src="https://user-images.githubusercontent.com/101622833/170195557-a29295c7-aa9d-4e8f-bb8c-7449e036723f.png">

the zookeeper data 
<img width="856" alt="image" src="https://user-images.githubusercontent.com/101622833/170197973-2bed185c-84af-40e1-9a3e-89942632ab86.png">

the metadata/sharding_db/versions/0/rules data is 
```
- !SHARDING
  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: database_inline
      shardingColumn: user_id
  defaultTableStrategy:
    none: ''
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
  scaling:
    default_scaling:
      dataConsistencyChecker:
        props:
          chunk-size: 1000
        type: DATA_MATCH
      input:
        batchSize: 1000
        shardingSize: 10000000
        workerThread: 4
      output:
        batchSize: 1000
        workerThread: 4
      streamChannel:
        props:
          block-queue-size: 10000
        type: MEMORY
  scalingName: default_scaling
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: ds_${user_id % 2}
      type: INLINE
    t_order_inline:
      props:
        algorithm-expression: t_order_${order_id % 2}
      type: INLINE
    t_order_item_inline:
      props:
        algorithm-expression: t_order_item_${order_id % 2}
      type: INLINE
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
      logicTable: t_order
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_inline
          shardingColumn: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
      logicTable: t_order_item
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_item_inline
          shardingColumn: order_id
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Use MySQL and proxy.

config-sharding.yaml
```
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 5
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 5
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/ds_2?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 5
    minPoolSize: 1
  ds_3:
    url: jdbc:mysql://127.0.0.1:3306/ds_3?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 5
    minPoolSize: 1
  ds_4:
    url: jdbc:mysql://127.0.0.1:3306/ds_4?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    maxPoolSize: 5
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE

  scalingName: default_scaling
  scaling:
    default_scaling:
      input:
        workerThread: 4
        batchSize: 1000
      output:
        workerThread: 4
        batchSize: 1000
      streamChannel:
        type: MEMORY
        props:
          block-queue-size: 10000
      dataConsistencyChecker:
        type: DATA_MATCH
        props:
          chunk-size: 1000
```

Remove scaling ds limit, allow target datasouce contain source datasource.
org.apache.shardingsphere.sharding.data.pipeline.ShardingRuleAlteredDetector#isNeedReShardingForLogicTable
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/101622833/170196354-5df20685-3163-41ae-b1e6-d2f8551e9536.png">

```
mysql>  CREATE TABLE t_order (order_id bigint NOT NULL, user_id int NOT NULL, status varchar(50) DEFAULT NULL, t_numeric numeric(10,2) DEFAULT NULL, PRIMARY KEY (order_id));
Query OK, 0 rows affected (3.97 sec)

mysql> preview select * from t_order;
+------------------+-----------------------------------------------------------+
| data_source_name | actual_sql                                                |
+------------------+-----------------------------------------------------------+
| ds_0             | select * from t_order_0 UNION ALL select * from t_order_1 |
| ds_1             | select * from t_order_0 UNION ALL select * from t_order_1 |
+------------------+-----------------------------------------------------------+
2 rows in set (0.05 sec)

mysql> ALTER SHARDING TABLE RULE t_order(RESOURCES(ds_0, ds_1),SHARDING_COLUMN=order_id,TYPE(NAME=hash_mod,PROPERTIES('sharding-count'=6)),KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake)));

Query OK, 0 rows affected (1.45 sec)

mysql> preview select * from t_order;
+------------------+---------------------------------------------------------------------------------------------+
| data_source_name | actual_sql                                                                                  |
+------------------+---------------------------------------------------------------------------------------------+
| ds_0             | select * from t_order_0 UNION ALL select * from t_order_2 UNION ALL select * from t_order_4 |
| ds_1             | select * from t_order_1 UNION ALL select * from t_order_3 UNION ALL select * from t_order_5 |
+------------------+---------------------------------------------------------------------------------------------+
2 rows in set (0.03 sec)
```
