### ISSUE TITLE
Can not query mysql system tables when I config information_schema logic database

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#17954]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/28345eb8748f70d5458f9805dbdca09f59b1d385

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute `select * from VIEWS;`, and then return results.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/10829171/170411083-0da299a4-9e8f-43e3-a913-a6ad60fe4411.png">

### Actual behavior

Following is my sharding configuration:

```yaml
schemaName: information_schema
dataSources:
  ds:
    url: jdbc:mysql://127.0.0.1:3306/information_schema?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:
```

When I execute `select * from VIEWS` in the `INFORMATION_SCHEMA` database, the result is empty.

<img width="1285" alt="image" src="https://user-images.githubusercontent.com/10829171/170410887-c1fd6c0e-f6bb-4727-bc48-e2f165c64ae2.png">
