### ISSUE TITLE
No sharding table insert bug

### ISSUE THREAD

**Issue by lcxywfe** [apache/shardingsphere#18071]
### Which version of ShardingSphere did you use?
5.1.2 SNAPSHOT built from master branch

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
SharidngSphere-Proxy

### Expected behavior
There is a no sharding table `noshardingtest` and I did not add it to yaml rules.

```
INSERT INTO `ProjectIndexRecord` (`project_id`, `super_project_id`, `deputy_project_id`, `project_name`, `project_config`, `job_type`, `state`, `ready`, `aoi_path`, `tile_path`, `is_registered_task`, `task_index_config`, `delivery_config`, `status`, `node_exit_status`, `node_exit_message`, `max_project_device`, `last_time`, `start_timestamp`, `end_timestamp`, `has_job_failure`, `dag_structure`, `dag_structure_id`, `trigger_nodes`, `workflow_params`, `workflow_node_config`, `hub_machine`, `enable_spot`, `aoi_generate_error`, `global_config`, `is_active`, `stage`, `freeze_code`, `monitor_config`, `task_config`, `max_processor_config`, `retry_count`, `workflow_idle_minutes`, `stepwise_execution`, `enable_retry`, `workflow_data_clean`, `workflow_status_code`, `workflow_status_message`, `workflow_output_result`) VALUES
(30006, -1, -1, 'test_sharding6', '', 'Repair', 0, 0, '', '', 0, '', '', 4, 0, '', '', '2022-05-30 11:57:38', '2022-04-28 08:55:24', '2022-04-28 09:04:37', 1, '', 704, '', '', '', 'hub', 1, 0, '', 0, 0, '', '', '', NULL, 0, 45, 0, 1, 1, 0, '', '');
```
Insert succeed and use auto increment

### Actual behavior
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'org.apache.shardingsphere.sharding.rewrite.token.pojo.ShardingInsertValuesToken@' at line 1

And if I uncomment the sharding rule of table, it works.

### Example codes for reproduce this issue (such as a github link).
yaml:
```
schemaName: yao
dataSources:
  ds_0:
    xxx
  ds_1:
    xxx
rules:
- !SHARDING
  # tables:
  #   ProjectIndexRecord:
  #     actualDataNodes: ds_0.ProjectIndexRecord
  #     keyGenerateStrategy:
  #       column: id
  #       keyGeneratorName: snowflake

  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: sharding_master
      shardingColumn: id

  keyGenerators:
    snowflake:
      props:
        max-vibration-offset: 19
        worker-id: 0
      type: SNOWFLAKE

  shardingAlgorithms:
    sharding_master:
      props:
        algorithm-expression: ds_0
      type: INLINE
    sharding_mod:
      props:
        algorithm-expression: ds_${id % 2}
      type: INLINE
```

Table create sql:
```
CREATE TABLE `ProjectIndexRecord` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `project_id` int(11) NOT NULL,
  `super_project_id` int(11) NOT NULL DEFAULT '-1',
  `deputy_project_id` int(11) NOT NULL DEFAULT '-1',
  `project_name` char(255) NOT NULL DEFAULT '',
  `project_config` varchar(2048) NOT NULL DEFAULT '',
  `job_type` char(30) NOT NULL DEFAULT '',
  `state` int(11) NOT NULL DEFAULT '0',
  `ready` tinyint(1) NOT NULL DEFAULT '0',
  `aoi_path` varchar(255) NOT NULL DEFAULT '',
  `tile_path` varchar(150) NOT NULL DEFAULT '',
  `is_registered_task` tinyint(1) NOT NULL,
  `task_index_config` varchar(2000) NOT NULL DEFAULT ' ',
  `delivery_config` text NOT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `node_exit_status` int(11) NOT NULL DEFAULT '0',
  `node_exit_message` varchar(2048) NOT NULL DEFAULT '',
  `max_project_device` varchar(3000) NOT NULL,
  `last_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `start_timestamp` varchar(32) NOT NULL DEFAULT '',
  `end_timestamp` varchar(32) NOT NULL DEFAULT '',
  `has_job_failure` tinyint(1) NOT NULL DEFAULT '0',
  `dag_structure` varchar(30000) NOT NULL DEFAULT '"{}"',
  `dag_structure_id` int(11) NOT NULL,
  `trigger_nodes` varchar(2000) NOT NULL DEFAULT ' ',
  `workflow_params` varchar(1000) NOT NULL,
  `workflow_node_config` text NOT NULL,
  `hub_machine` varchar(256) NOT NULL,
  `enable_spot` tinyint(4) NOT NULL DEFAULT '1',
  `aoi_generate_error` int(11) NOT NULL DEFAULT '0',
  `global_config` varchar(2000) NOT NULL DEFAULT '',
  `is_active` int(11) NOT NULL DEFAULT '0',
  `stage` int(11) NOT NULL DEFAULT '0',
  `freeze_code` varchar(1024) NOT NULL DEFAULT '',
  `monitor_config` text NOT NULL,
  `task_config` text NOT NULL,
  `max_processor_config` varchar(300) DEFAULT NULL,
  `retry_count` int(11) NOT NULL DEFAULT '0',
  `workflow_idle_minutes` int(11) NOT NULL DEFAULT '45',
  `stepwise_execution` tinyint(1) NOT NULL DEFAULT '0',
  `enable_retry` int(11) NOT NULL DEFAULT '1',
  `workflow_data_clean` int(11) NOT NULL DEFAULT '1',
  `workflow_status_code` int(11) NOT NULL DEFAULT '0',
  `workflow_status_message` text NOT NULL,
  `workflow_output_result` text NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `project_name_ProjectIndexRecord` (`project_name`),
  UNIQUE KEY `project_id_ProjectIndexRecord` (`project_id`),
  KEY `super_project_id_ProjectIndexRecord` (`super_project_id`),
  KEY `deputy_project_id_ProjectIndexRecord` (`deputy_project_id`)
) ENGINE=InnoDB AUTO_INCREMENT=738003154594955265 DEFAULT CHARSET=latin1
```
