### ISSUE TITLE
SHOW SHARDING TABLE RULES USED ALGORITHM not display tables used default strategy

### ISSUE THREAD

**Issue by lcxywfe** [apache/shardingsphere#18099]
### Which version of ShardingSphere did you use?
5.1.2-SNAPSHOT built from master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingProxy

### Expected behavior
SHOW SHARDING TABLE RULES USED ALGORITHM sharding_mod;

got:
table |  test_table

### Actual behavior
got:
Empty set

### Example codes for reproduce this issue (such as a github link).
yaml:
```
schemaName: yao
dataSources:
  ds_0:
    xxx
  ds_1:
    xxx
rules:
- !SHARDING
  tables:
    test_table:
      actualDataNodes: ds_${0..19}.test_table
      # databaseStrategy:
      #   standard:
      #     shardingAlgorithmName: sharding_mod
      #     shardingColumn: id
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingAlgorithmName: sharding_mod
      shardingColumn: id

  keyGenerators:
    snowflake:
      props:
        max-vibration-offset: 1
        worker-id: 0
      type: SNOWFLAKE

  shardingAlgorithms:
    sharding_mod:
      props:
        algorithm-expression: ds_${id % 2}
      type: INLINE
```
