### ISSUE TITLE
The proxy needs to be able to customize some parameters when using narayana

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18143]
### Describe the feature you would like.
When proxy uses narayana, some parameters cannot be customized, such as defaultTimeout. I hope that some more important parameters can be defined in the configuration file.

Here are some definitions in server.yaml.

```yaml
rules:

  - !TRANSACTION
    defaultType: XA
    providerType: Narayana
    props:
      recoveryStoreUrl: jdbc:mysql://127.0.0.1:3306/jbossts
      recoveryStoreDataSource: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
      recoveryStoreUser: root
      recoveryStorePassword: 12345678
      commitOnePhase: true
      transactionSync: false
      recoveryBackoffPeriod: 1
      defaultTimeout: 180
      expiryScanInterval: 12
      periodicRecoveryPeriod: 120
```
