### ISSUE TITLE
MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm uses Seconds_Behind_Master to determine replication delay, I hope to use custom SQL to determine replication delay

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18327]
### Describe the feature you would like.
The MySQLNormalReplicationDatabaseDiscoveryProviderAlgorithm uses Seconds_Behind_Master to judge the replication delay, but Seconds_Behind_Master may be inaccurate. I hope to use my own defined SQL to obtain the replication delay. If there is no definition or the table does not exist and other abnormal conditions, I will use Seconds_Behind_Master.

```
discoveryTypes:
    normal-replication:
    type: MySQL.NORMAL_REPLICATION
    props:
       delay-milliseconds-threshold: 10000
       delay-checked-sql: select abs(unix_timestamp(now())-unix_timestamp(max(Ftime))) as delay from dba.delay_monitor limit 1
```
