### ISSUE TITLE
Previlege configs for who can execut DistSQL querys

### ISSUE THREAD

**Issue by gnode7** [apache/shardingsphere#18365]
## User previlege configs for executing DistSQL (for security reason)

Currently all users can execute any DistSQL. It needs a way to config previleges of executing DistSQL querys, to prevent certain users from getting encrypt keys (simply by "SHOW ENCRYPT RULES FROM ...") or datasource access info of others, or just messing up rule configurations either accidentally or intensionally.

eg.: below only root can execute distsql (notice the last line):

```
    rules:
      - !AUTHORITY
        users:
          - root@%:root
          - sharding@:sharding
        provider:
          type: DATABASE_PERMITTED
          props:
            user-database-mappings: root@=ds1, sharding@=ds2
            distsql: root
```
`
