### ISSUE TITLE
DatabaseDiscovery keeps at least some replicas

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#18380]
### Describe the feature you would like.
If all replicas are disabled, using RandomReplicaLoadBalanceAlgorithm will throw an exception. I want to define a parameter 'min-enabled-replicas-threshold' in props of discoveryTypes, which means that at least a few replicas cannot be disabled. And the specific processing logic will be placed in the method 'updateStatus' of the class DatabaseDiscoveryRule.

**Comment by zjcnb** [comment]
@natehuangting Hi, i think it 's good idea. And can you attach the configuration for db-discovery?

**Comment by natehuangting** [comment]
The configuration for db-discovery.
```
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        type: Dynamic
        props:
          auto-aware-data-source-name: readwrite_ds

  - !DB_DISCOVERY
    dataSources:
      readwrite_ds:
        dataSourceNames:
          - ds_0
          - ds_1
          - ds_2
        discoveryTypeName: mysql_normal
        discoveryHeartbeatName: mysql-heartbeat
    discoveryHeartbeats:
      mysql-heartbeat:
        props:
          keep-alive-cron: '0/5 * * * * ?'
    discoveryTypes:
      mysql_normal:
        type: MySQL.NORMAL_REPLICATION
        props:
          delay-milliseconds-threshold: 10000
          min-enabled-replicas-threshold: 1
```
