### ISSUE TITLE
When use DistSQL excute 'preview select * from  e;'  ,Showing unexpected results

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#18434]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
we find java version: java8, full_version=1.8.0_312
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-7bfa655d42754ec1144d26af7089962703d840e6
Commit Message: Optimize sharding tables route logic when execute cursor statement (#18413)
Branch: 7bfa655d42754ec1144d26af7089962703d840e6
Build time: 2022-06-20T10:04:48+0800
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
```
sharding_db=>       preview select * from  e;
      preview select * from  f;
      preview select * from  g; data_source_name |    actual_sql
------------------+------------------
 ds_1             | select * from  e
(1 row)

sharding_db=>  data_source_name |    actual_sql
------------------+------------------
 ds_2            | select * from  f
(1 row)

sharding_db=>
 data_source_name |    actual_sql
------------------+------------------
 ds_3             | select * from  g
(1 row)
```
### Actual behavior
```
sharding_db=>       preview select * from  e;
      preview select * from  f;
      preview select * from  g; data_source_name |    actual_sql
------------------+------------------
 ds_1             | select * from  e
(1 row)

sharding_db=>  data_source_name |    actual_sql
------------------+------------------
 ds_1             | select * from  f
(1 row)

sharding_db=>
 data_source_name |    actual_sql
------------------+------------------
 ds_2             | select * from  g
(1 row)
```
### Reason analyze (If you can)
use yaml  Show the normal
but use distsql  'ALTER SQL_PARSER RULE SQL_COMMENT_PARSE_ENABLE=true;' ,Showing unexpected results
maybe distsql have  bug?

#### server.yaml
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 630_dzq
      server-lists: ip:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
    provider:
      type: ALL_PERMITTED

props:
  sql-show: true
```

####
sql
```
/* ShardingSphere hint: dataSourceName=ds_1 */ CREATE TABLE e(id int, name char);
INSERT INTO e(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_2 */ CREATE TABLE f(id int, name char);
INSERT INTO f(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_3 */ CREATE TABLE g(id int, name char);
INSERT INTO g(id, name) VALUES(1, '1'), (2, '2'), (3, '3');
```

**Comment by wsm12138** [comment]
# normal 
#### server.yaml 
```
rules:
  - !AUTHORITY
    users:
      - root@%:root
#      - sharding@:sharding
    provider:
      type: ALL_PERMITTED

  - !SQL_PARSER
    sqlCommentParseEnabled: true
    sqlStatementCache:
      initialCapacity: 2000
      maximumSize: 65535
    parseTreeCache:
      initialCapacity: 128
      maximumSize: 1024

props:
  sql-show: true
```
#### sql
```
/* ShardingSphere hint: dataSourceName=ds_1 */ CREATE TABLE e(id int, name char);
INSERT INTO e(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_2 */ CREATE TABLE f(id int, name char);
INSERT INTO f(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_3 */ CREATE TABLE g(id int, name char);
INSERT INTO g(id, name) VALUES(1, '1'), (2, '2'), (3, '3');
      preview select * from  e;
      preview select * from  f;
      preview select * from  g;
```
#### behavior
<img width="670" alt="image" src="https://user-images.githubusercontent.com/86462784/174529972-9c3da9f4-a49f-4e68-ad25-8e71c7302cbc.png">

# unnormal 
#### server.yaml
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 630_dzq
      server-lists: ip:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
    provider:
      type: ALL_PERMITTED

props:
  sql-show: true
```
#### sql
```
ALTER SQL_PARSER RULE SQL_COMMENT_PARSE_ENABLE=true;

/* ShardingSphere hint: dataSourceName=ds_1 */ CREATE TABLE e(id int, name char);
INSERT INTO e(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_2 */ CREATE TABLE f(id int, name char);
INSERT INTO f(id, name) VALUES(1, '1'), (2, '2'), (3, '3');

/* ShardingSphere hint: dataSourceName=ds_3 */ CREATE TABLE g(id int, name char);
INSERT INTO g(id, name) VALUES(1, '1'), (2, '2'), (3, '3');
      preview select * from  e;
      preview select * from  f;
      preview select * from  g;
```
#### behavior
<img width="538" alt="image" src="https://user-images.githubusercontent.com/86462784/174530281-ddb7dd03-01e8-46cb-9352-8abb0e9f103b.png">
