### ISSUE TITLE
Consider primary datasource provides query when all the replica are offline in Readwrite-Splitting Dynamic type

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#18441]
Hi community,

Execute the query throws an exception when we use `readwrite-splitting ` rule and` db-discovery` rule and all the replica are offline.

![image](https://user-images.githubusercontent.com/33742097/174536944-ae21edd6-e419-4b87-82db-a4f217a7bb61.png)

So, we consider add configuration switch in Dynamic `readwrite-splitting`, choose the primary data source by yourself to whether provide query when all the replica are offline.

**Comment by zjcnb** [comment]
`Configuration : `
```
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        type: Dynamic
        props:
          auto-aware-data-source-name: replication_delay_ds
          primary-data-source-allow-query: true  # Default Value are true, it represents provide query when all the replica are offline.
  - !DB_DISCOVERY
    dataSources:
      replication_delay_ds:
        dataSourceNames:
          - ds_0
          - ds_1
          - ds_2
        discoveryHeartbeatName: replication_delay_heartbeat
        discoveryTypeName: replication_delay
    discoveryHeartbeats:
      replication_delay_heartbeat:
        props:
          keep-alive-cron: '0/1 * * * * ?'
    discoveryTypes:
      replication_delay:
        type: MySQL.NORMAL_REPLICATION
        props:
          delay-milliseconds-threshold: 1000
```
