### ISSUE TITLE
Received invalid response to SSL negotiation when use psql to connect Proxy.

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#18578]
### Which version of ShardingSphere did you use?
ShardingSphere-Proxy https://github.com/apache/shardingsphere/commit/9431835379969bc64035b0e8944d5703646d3f79

### Expected behavior
Connect successful.

### Actual behavior
```
~ % psql -Uroot -h127.0.0.1  -p3307
psql: error: connection to server at "127.0.0.1", port 3307 failed: received invalid response to SSL negotiation: |
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Start Proxy just with server.yaml
```
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
```
2. Try to create a connection using psql
```
psql -Uroot -h127.0.0.1  -p3307
psql: error: connection to server at "127.0.0.1", port 3307 failed: received invalid response to SSL negotiation: v
```

**Comment by RaigorJiang** [comment]
After I set `proxy-frontend-database-protocol-type: PostgreSQL`, psql can make protocol connections.
This issue can be closed.

**Comment by wsm12138** [comment]
### ShardingSphere-Proxy version 
`e6328cb989cfb789189227892cb892740095d2d6`
### error
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/86462784/179154910-0d30317e-23b4-4cf1-90ad-e29e28576918.png">
<img width="977" alt="image" src="https://user-images.githubusercontent.com/86462784/179155441-e8563c56-50a7-469b-9728-1db64e757e71.png">

### how to reproduce
```
server.yaml
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 0715distsql
      server-lists: 192.168.10.21:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
- !AUTHORITY
  users:
    - root@%:root
    - sharding@:sharding
  provider:
    type: ALL_PERMITTED
- !SQL_PARSER
  sqlCommentParseEnabled: true
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

props:
  proxy-frontend-database-protocol-type: PostgreSQL
```

### about zk
<img width="499" alt="image" src="https://user-images.githubusercontent.com/86462784/179155260-d4a313dc-bf70-4cdd-bd95-8502c53e37f6.png">

### about proxy stoudt.log
<img width="1803" alt="image" src="https://user-images.githubusercontent.com/86462784/179155350-56c8d196-d0ba-4251-ba96-864bdd48b0e6.png">

### question
so,what can i do?that i can use `gsql` connect proxy？
