### ISSUE TITLE
How to configure only the sharding database without configuring the sharding table

### ISSUE THREAD

**Issue by azui007** [apache/shardingsphere#18651]
## Question
# environment：
Sharding-JDBC  5.1.1
I have two databases(ds1,ds2), ds1 save company A , ds2  save company B。 
Both databases have the same tables: **company_info1 - company_info1000**
# sharding-jdbc configuration：
```
spring:
  shardingsphere:
    enabled: true
    props:
      sql-show: true
    datasource:
      names: ds2,ds1
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ds1?useUnicode=true&characterEncoding=UTF-8
        username: postgres
        password: postgres
      ds2:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/ds2?useUnicode=true&characterEncoding=UTF-8
        username: postgres
        password: postgres
    rules:
      sharding:
        sharding-algorithms:
          database-inline:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.aaa.bbb.sharedingpheredemo.algorith.CompanyCodePreciseShardingAlgorithm
        tables:
          company_info1:
            actual-data-nodes: ds$->{1..2}.company_info1
            database-strategy:
              standard:
                sharding-column: company_code
                sharding-algorithm-name: database-inline
          company_info2:
            actual-data-nodes: ds$->{1..2}.company_info2
            database-strategy:
              standard:
                sharding-column: company_code
                sharding-algorithm-name: database-inline
        default-database-strategy:
          standard:
            sharding-column: company_code
            sharding-algorithm-name: database-inline
```

# Question
I configure sharding database rules for all tables , not need to configuring company_info1 to company_info1000 tables。
I try uesd **default-database-strategy**,but it not work for me.
can you help me 
thank you
