### ISSUE TITLE
sharding-jdbc 5.1.2  startup very slow

### ISSUE THREAD

**Issue by boot-vue** [apache/shardingsphere#18653]
`sharding-jdbc` : `5.1.2`

```xml
      <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core-spring-boot-starter</artifactId>
            <version>5.1.2</version>
        </dependency>
```

`tables` : `200+`

same config, with version `5.1.0` , application startup very fast

change to version `5.1.2`  , application start very slow......

**Comment by shanrenxj** [comment]
yes, rolling back to 5.1.1 is very fast

**Comment by boot-vue** [comment]
> What is your configuration and database type?

`mysql 8`

```yml
spring:
  shardingsphere:
    datasource:
      names: node1,node2
      node1:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://xxxxxxx:3307/oooo?characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: vvvv
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          pool-name: ccc1
          maximum-pool-size: 25
          max-lifetime: 900000
          validation-timeout: 2000
          idle-timeout: 60000
          minimum-idle: 15
      node2:
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: jdbc:mysql://oooooo:3308/oooo?characterEncoding=utf8&useSSL=false&autoReconnect=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
        username: root
        password: cccccc
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
          pool-name: vvvvv2
          maximum-pool-size: 25
          max-lifetime: 900000
          validation-timeout: 2000
          idle-timeout: 60000
          minimum-idle: 15
    rules:
      readwrite-splitting:
        data-sources:
          oooo:
            type: Static
            props:
              write-data-source-name: node1
              read-data-source-names: node2
              load-balancer-name: random
        load-balancers:
          random:
            type: RANDOM
```
