### ISSUE TITLE
ShardingSphere-Proxy cluster mode,can't create some namespace ?

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#18825]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
<img width="1834" alt="image" src="https://user-images.githubusercontent.com/86462784/177096466-99bb4d0e-a931-4ceb-a436-e886b1486b3f.png">

### Actual behavior
When use cluster mode,can't create a  namespace named `0704`.
<img width="845" alt="image" src="https://user-images.githubusercontent.com/86462784/177096337-f34c65aa-94d0-4301-b84c-6fddb06ad9e9.png">
### Reason analyze (If you can)
no
### Example codes for reproduce this issue (such as a github link).
1. start zk (version3.6.2)
2. use cluster mode to start proxy
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 0704
      server-lists: ip:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - user: root@%
        password: root
      - user: sharding
        password: sharding
    privilege:
      type: ALL_PERMITTED
```
