### ISSUE TITLE
When use ShardingSphere-Proxy  & MySQL MGR ，occurrence does not meet expectations

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#18847]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/86462784/177241980-c68d92ce-799c-4086-9440-762b233079d6.png">
### Actual behavior

<img width="1633" alt="image" src="https://user-images.githubusercontent.com/86462784/177242021-2f9d4cb7-63f9-4f39-902d-91dfac22502c.png">

##### server.yaml
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 0704_dynamic
      server-lists: ip:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - user: root@%
        password: root
      - user: sharding
        password: sharding
    privilege:
      type: ALL_PERMITTED
```
##### config-database.yaml
```
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://ip:33308/new1?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://ip:33307/new1?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://ip:33306/new1?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_10:
    url: jdbc:mysql://ip:33308/new2?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_11:
    url: jdbc:mysql://ip:33307/new2?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

  ds_12:
    url: jdbc:mysql://ip:33307/new2?serverTimezone=UTC&useSSL=false
    username: root
    password: passwd
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    autoTables:
      t_order:
        actualDataSources: source_readwrite
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: t_order_snowflake
        logicTable: t_order
        shardingStrategy:
          standard:
            shardingAlgorithmName: t_order_hash_mod
            shardingColumn: order_id
    shardingAlgorithms:
      t_order_inline:
        props:
          algorithm-expression: t_order_${order_id % 2}
        type: INLINE
      t_order_hash_mod:
        props:
          sharding-count: '2'
        type: hash_mod
    keyGenerators:
      snowflake:
        type: SNOWFLAKE

    scalingName: default_scaling
    scaling:
      default_scaling:
        input:
          workerThread: 40
          batchSize: 1000
        output:
          workerThread: 40
          batchSize: 1000
        streamChannel:
          type: MEMORY
          props:
            block-queue-size: 10000
        dataConsistencyChecker:
          type: DATA_MATCH
          props:
            chunk-size: 1000

  - !READWRITE_SPLITTING
    dataSources:
      source_readwrite:
        type: Dynamic
        props:
          auto-aware-data-source-name: source_replica_ds
      target_readwrite:
        type: Dynamic
        props:
          auto-aware-data-source-name: target_replica_ds

  - !DB_DISCOVERY
    dataSources:
      source_replica_ds:
        dataSourceNames:
          - ds_0
          - ds_1
          - ds_2
        discoveryHeartbeatName: mgr-heartbeat
        discoveryTypeName: mgr
      target_replica_ds:
        dataSourceNames:
          - ds_10
          - ds_11
          - ds_12
        discoveryHeartbeatName: mgr-heartbeat
        discoveryTypeName: mgr
    discoveryHeartbeats:
      mgr-heartbeat:
        props:
          keep-alive-cron: '0/5 * * * * ?'
    discoveryTypes:
      mgr:
        type: MySQL.MGR
        props:
          group-name: 558edd3c-02ec-11ea-9bb3-080027e39bd2
```
