### ISSUE TITLE
docker image throw error but Binary can work

### ISSUE THREAD

**Issue by qlql489** [apache/shardingsphere#18942]
## Question

the 5.1.2 proxy docker version and ShardingSphere-Proxy Binary 5.1.2，use the same config file , Binary is run success，docker throw exception:
```
Exception in thread "main" org.apache.shardingsphere.spi.exception.ServiceProviderNotFoundException: No implementation class load from SPI `org.apache.shardingsphere.authority.spi.AuthorityProvideAlgorithm` with type `ALL_PERMITTED`.
```
server.yaml rules:

```
rules:
  - !AUTHORITY
    users:
      - root@:1234
      - my_user@:pwd
    provider:
      type: ALL_PERMITTED
```
