### ISSUE TITLE
When "SHOW READWRITE_SPLITTING RULES;", "ERROR:  java.lang.IllegalStateException"

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#19084]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
```
7c67365b394d2e3ac562329b550c135c31ea764d
```
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
empty set
### Actual behavior
readwrite_splitting_db=> SHOW READWRITE_SPLITTING RULES;
ERROR:  java.lang.IllegalStateException
### Reason analyze (If you can)
can't
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
databaseName: readwrite_splitting_db

dataSources:
  write_ds:
    url: jdbc:opengauss://ip:5432/ds_0?serverTimezone=UTC&useSSL=false
    username: gaussdb
    password: passwd
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  read_ds_0:
    url: jdbc:opengauss://ip:5432/ds_1?serverTimezone=UTC&useSSL=false
    username: gaussdb
    password: passwd
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  read_ds_1:
    url: jdbc:opengauss://ip:5432/ds_2?serverTimezone=UTC&useSSL=false
    username: gaussdb
    password: passwd
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules: []
```
### Example codes for reproduce this issue (such as a github link).
1. start proxy
2. SHOW READWRITE_SPLITTING RULES;
