### ISSUE TITLE
Use `gsql` connect proxy throw exception 'Failed to get the server's version. resStatus=7 ERROR: ERROR:  org.apache.shardingsphere.proxy.backend.exception.RuleNotExistedException'

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#19214]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
`e6328cb989cfb789189227892cb892740095d2d6`
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
connect normal
### Actual behavior
cann't connect
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. use server.yaml to start proxy
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: 0715distsql
      server-lists: 192.168.10.21:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
- !AUTHORITY
  users:
    - root@%:root
    - sharding@:sharding
  provider:
    type: ALL_PERMITTED
- !SQL_PARSER
  sqlCommentParseEnabled: true
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

props:
  proxy-frontend-database-protocol-type: "openGauss"
```
2. use `gsql` connect proxy
