### ISSUE TITLE
Add new DistSQL RAL syntax `SHOW SQL_TRANSLATOR RULE`

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#19333]
### Configuration

` server.yaml`

```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
#  - !TRANSACTION
#    defaultType: XA
#    providerType: Atomikos
  - !SQL_PARSER
    sqlCommentParseEnabled: true
    sqlStatementCache:
      initialCapacity: 2000
      maximumSize: 65535
    parseTreeCache:
      initialCapacity: 128
      maximumSize: 1024
  - !SQL_TRANSLATOR
    type: MySQL
    useOriginalSQLWhenTranslatingFailed: true
```

### Expected behavior

`SHOW SQL_TRANSLATOR RULE` success.

### Actual behavior

mysql> SHOW SQL_TRANSLATOR RULE;
ERROR 1235 (42000): This version of ShardingSphere-Proxy doesn't yet support this SQL. 'You have an error in your SQL syntax'
