### ISSUE TITLE
Consider supporting limiting max rows of Proxy backend's statements

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#19347]
## Feature Request

Related to #19340.

### Is your feature request related to a problem?

OOM may occur if result of a query is huge and streaming result set is disabled.

### Describe the feature you would like.

Consider adding a new config `proxy-backend-query-max-rows` to limit max rows returns by ResultSet.
```yaml
props:
#  proxy-backend-query-fetch-size: -1
  proxy-backend-query-max-rows: 1000
```
