### ISSUE TITLE
ShardingSphere proxy config center not work. Some nodes not have config center configurations info like datasource, rule configurations

### ISSUE THREAD

**Issue by herbxu** [apache/shardingsphere#19461]
## Bug Report
ShardingSphere Proxy config center not work. some nodes not have config center configurations info like datasource, rule configurations

### Which version of ShardingSphere did you use?
5.1.2 （helm cluster）
docker images url: apache/shardingsphere-proxy:5.1.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
All cluster some nodes have some config center configurations info like datasource, rule configurations

### Actual behavior
ShardingSphere Proxy Cluster some nodes not have config center configurations info like datasource, rule configurations

### Environment Configurations
helm values below: 
```
governance:
  enabled: true
  zookeeper:
    enabled: true
    replicaCount: 3
    persistence:
      enabled: false
      storageClass: ""
      accessModes:
        - ReadWriteOnce
      size: 20Gi
    resources:
      limits: {}
      requests:
        memory: 256Mi
        cpu: 250m


compute:
  image:
    repository: "apache/shardingsphere-proxy"
    pullPolicy: IfNotPresent
    ## Overrides the image tag whose default is the chart appVersion.
    ##
    tag: 5.1.2
  imagePullSecrets: []
  resources:
    limits: {}
    requests:
      memory: 2Gi
      cpu: 200m
  replicas: 3
  service:
    type: ClusterIP
    port: 3307
  ## MySQL connector Configuration
  ## ref: https://shardingsphere.apache.org/document/current/en/quick-start/shardingsphere-proxy-quick-start/
  ## @param compute.mysqlConnector.version MySQL connector version
  ##
  mysqlConnector:
    version: "5.1.49"
  startPort: 3307
  serverConfig:
    authority:
      privilege:
        type: ALL_PRIVILEGES_PERMITTED
      users:
        - password: root
          user: test@%
    mode:
      overwrite: false
      repository:
        props:
          maxRetries: 3
          namespace: governance_ds
          operationTimeoutMilliseconds: 5000
          retryIntervalMilliseconds: 500
          server-lists: "shardingsphere-proxy-zookeeper:2181"
          timeToLiveSeconds: 600
        type: ZooKeeper
      type: Cluster
```

one proxy node execute command below:
```
create database ss_test;

ADD RESOURCE ds_0 (
  HOST=127.0.0.1,
  PORT=3306,
  DB=test_db,
  USER=test_db,
  PASSWORD=test123
),ds_1 (
  HOST=127.0.0.1,
  PORT=3306,
  DB=test_db,
  USER=test_db2,
  PASSWORD=test123
);

CREATE SHARDING TABLE RULE t_order(
  RESOURCES(ds_0,ds_1),
  SHARDING_COLUMN=order_id,
  TYPE(NAME=hash_mod,PROPERTIES("sharding-count"=4)),
  KEY_GENERATE_STRATEGY(COLUMN=order_id,TYPE(NAME=snowflake))
);

CREATE TABLE `t_order` (
  `order_id` int NOT NULL,
  `user_id` int NOT NULL,
  `status` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


INSERT INTO `t_order` (`order_id`, `user_id`, `status`) VALUES(0,0,"aaa"),(1,1,"bbbb"),(2,2,"cccc");
```

this node can see the configurations below:
![image](https://user-images.githubusercontent.com/58198659/180357046-fd12efe5-1745-4a6c-8841-4cbc1f6a4437.png)

other nodes in this cluser not see the  configurations below:
![image](https://user-images.githubusercontent.com/58198659/180357220-ed3b1837-2e82-4dfa-98d3-dcf239a40869.png)
