### ISSUE TITLE
[jdbc]how to use Distributed Primary Key

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#19541]
spring boot config:
```
rules:
      sharding:
        tables:
          t_order: 
            actual-data-nodes: ds$->{0..1}.t_order_$->{1..31}
            database-strategy: 
              standard:
                sharding-column: phone 
                sharding-algorithm-name: database-class-base 
            table-strategy: 
              standard:
                sharding-column: logtime
                sharding-algorithm-name: table-class-base
            key-generate-strategy: 
              column: order_id 
              key-generator-name: snowflake 
        sharding-algorithms:
          database-class-base:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.lhx.shardingjdbcdemo.MyShardingAlgorithm
          table-class-base:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.lhx.shardingjdbcdemo.MyShardingAlgorithm11
        key-generators:
          snowflake:
            type: SNOWFLAKE 
```
How do I specify the primary key column value when I insert a piece of data using MyBatis?
example:
    `insert into t_order(order_id, logtime, phone) values (#{orderId}, #{logtime}, #{phone})`
    How do I get #{orderId} with the Snowflake algorithm

**Comment by TeslaCN** [comment]
Hi @PeiMouRen 
You don't need to specify `orderId`. Just
```sql
insert into t_order (logtime, phone) values (#{logtime}, #{phone})
```

**Comment by PeiMouRen** [comment]
Hi @TeslaCN 
This is the result of not specifying a primary key
![image](https://user-images.githubusercontent.com/46043280/180905369-891f0d7c-b3ab-479a-b0d4-659bf992e643.png)

**Comment by TeslaCN** [comment]
Could you try putting a breakpoint into `org.apache.shardingsphere.sharding.rule.ShardingRule` and checking the configurations?

**Comment by PeiMouRen** [comment]
![image](https://user-images.githubusercontent.com/46043280/180937600-8a14c784-aa0b-4851-b129-e486b4d88a7c.png)
As you can see, the configuration is read, but it does not take effect。

**Comment by PeiMouRen** [comment]
![image](https://user-images.githubusercontent.com/46043280/181150138-5bd96f9a-c51b-42c7-bf07-61aca97f8e1d.png)
This method is not called when executing INSERT, can someone help to solve this problem？

**Comment by PeiMouRen** [comment]
**Environment:**
jdk:1.8
spring boot:2.6.4
shardingsphere-jdbc:5.1.2
postgresql:12.6
---
**spring boot config:**
```yaml
spring:
  shardingsphere:
    database:
      name:
    mode:
      type: Standalone
      repository:
        type: File
        props:
          path: .shardingsphere
      overwrite: true
    datasource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/shard1?stringtype=unspecified
        username: root
        password: 123
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/shard2?stringtype=unspecified
        username: root
        password: 123
    rules:
      sharding:
        tables:
          t_order: 
            actual-data-nodes: ds$->{0..1}.t_order_$->{0..1}
            database-strategy:
              standard:
                sharding-column: user_id
                sharding-algorithm-name: database-inline
            table-strategy:
              standard:
                sharding-column: order_id 
                sharding-algorithm-name: t-order-inline
            key-generate-strategy: 
              column: order_id 
              key-generator-name: snowflake
        sharding-algorithms:
          database-inline:
            type: INLINE 
            props:
              algorithm-expression: ds$->{user_id % 2}
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: t_order_$->{order_id % 2}
        key-generators:
          snowflake: 
            type: SNOWFLAKE 
    props:
      sql-show: true


```
---
**DDL:**
```sql
# ds0
create table t_order_0(order_id bigint, user_id int, remark varchar(200));
create table t_order_1(order_id bigint, user_id int, remark varchar(200));
# ds1
create table t_order_0(order_id bigint, user_id int, remark varchar(200));
create table t_order_1(order_id bigint, user_id int, remark varchar(200));
```
---
**sql:**
```java

...
   @Insert("insert into t_order(user_id, remark) values ( #{userId}, #{remark})")
    void add4(@Param("userId") int userId, @Param("remark") String remark);
...

orderDao.add4(100, "test");
```
---
**error:**
Because no order_id was generated.
this error disappeared when I switched the data source to mysql.
```
org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: java.lang.IllegalStateException: Insert statement does not support sharding table routing to multiple data nodes.
### The error may exist in com/lhx/shardingjdbcdemo/dao/OrderDao.java (best guess)
### The error may involve com.lhx.shardingjdbcdemo.dao.OrderDao.add4-Inline
### The error occurred while setting parameters
### SQL: insert into t_order(user_id, remark) values ( ?, ?)
```
