### ISSUE TITLE
Read-write split configuration supports Cartesian product

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#19693]
### Describe the feature you would like.

I recently found that I need to configure a lot when configuring read-write separation.
For example, the following configuration, there are only two, if there are 100, then the configuration file is very large

``` yaml
readwrite_ds_0:
  staticStrategy:
    writeDataSourceName: ds_write_0
    readDataSourceNames:
      - ds_read_0
  loadBalancerName: randomreadwrite_ds_1:
  staticStrategy:
    writeDataSourceName: ds_write_1
    readDataSourceNames:
      - ds_read_1
  loadBalancerName: random
```

So I want to optimize this configuration by cartesian product. The optimized configuration is as follows.
``` yaml
readwrite_ds_${0..9}:
  staticStrategy:
    writeDataSourceName: ds_write_${0..9}
    readDataSourceNames:
      - ds_read_${0..9}
  loadBalancerName: random
```
