### ISSUE TITLE
`SQL_PARSER` configuration shouldn't persist metadata node when use `ShardingSphere-JDBC` cluster mode

### ISSUE THREAD

**Issue by zjcnb** [apache/shardingsphere#19713]
### Which version of ShardingSphere did you use?

`master` https://github.com/apache/shardingsphere/commit/a696de87196885f532b07c9a5b5c2b2bc95c8e06

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-JDBC`

### Expected behavior

`SQL_PARSER` configuration shouldn't persist metadata node when use `ShardingSphere-JDBC` cluster mode

### Actual behavior

persist metadata node

```
spring:
  shardingsphere:
    mode:
      type: Cluster
      repository:
        type: ZooKeeper
        props:
          namespace: governance_ds
          server-lists: localhost:2181
          retryIntervalMilliseconds: 500
          timeToLiveSeconds: 60
          maxRetries: 3
          operationTimeoutMilliseconds: 500
      overwrite: false

    dataSource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/ds0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        jdbcUrl: jdbc:mysql://localhost:3306/ds1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
    rules:
      sharding:
        tables:
          t_order:
            actual-data-nodes: ds$->{0..1}.t_order$->{0..1}
            table-strategy:
              standard:
                sharding-algorithm-name: table-inline
                sharding-column: user_id
            database-strategy:
              standard:
                sharding-algorithm-name: database-inline
                sharding-column: order_id
        sharding-algorithms:
          table-inline:
            type: INLINE
            props:
              algorithm-expression: t_order$->{user_id % 2}
          database-inline:
            type: INLINE
            props:
              algorithm-expression: ds$->{order_id % 2}
      sql-parser:
        sql-comment-parse-enabled: true
    props:
      sql-show: true
server:
  port: 8899
```
