### ISSUE TITLE
Extract YamlJobProgress.YamlIncremental and JobProgress.IncrementalTaskProgress, add realted swapper

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19748]
Part of #19421.

Purpose:
- Use dividual incremental progress classes, then they could be reused in other types of jobs.

1, Currently, `YamlIncremental` means part of incremental progress. Related code of `YamlJobProgress`:
```
    private Map<String, YamlIncremental> incremental;

    @Getter
    @Setter
    public static final class YamlIncremental {
        
        private String position;
        
        private IncrementalTaskDelay delay;
    }
```
We could add YamlIncrementalTaskProgress class, YamlJobProgress just reference it: `private IncrementalTaskProgresses incremental;`

Possible changes:
- `Map<String, YamlIncremental> incremental;` could be simplified to `YamlIncremental incremental;`, and add `dataSourceName` in `YamlIncremental`;
- Add `YamlIncrementalTaskProgresses`;
- Update `YamlJobProgress` reference of `YamlIncrementalTaskProgresses`;

2, In JobProgress:
```
    private Map<String, IncrementalTaskProgress> incrementalTaskProgressMap;
```
We could add IncrementalTaskProgresses, JobProgress just reference it: `private IncrementalTaskProgresses incremental;`

3, Add YamlIncrementalTaskProgressSwapper

**Comment by sandynz** [comment]
An job progress example in registry center:
```
incremental:
  ds_0:
    delay:
      lastEventTimestamps: 0
      latestActiveTimeMillis: 0
    position: mysql-bin.000012#237010997
inventory:
  finished:
  - ds_0.sbtest1#2
  unfinished:
    ds_0.sbtest1#1: 13666944,20000000
    ds_0.sbtest1#0: 3689472,10000000
sourceDatabaseType: MySQL
status: EXECUTE_INVENTORY_TASK
```
