### ISSUE TITLE
Extract YamlJobProgress.YamlInventory and JobProgress.InventoryTaskProgress, add related swapper

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#19754]
Part of #19421.

Purpose:
- Extract dividual inventory progress classes, then they could be reused in other types of jobs.

1, Extract YamlJobProgress.YamlInventory as dividual class, with name `YamlInventoryTaskProgress`

2, In JobProgress:
```
    private Map<String, InventoryTaskProgress> inventoryTaskProgressMap;
```
We could refactor InventoryTaskProgress structure, JobProgress just reference `private InventoryTaskProgress inventory;`

Possible changes:
- Put `private Map<String, InventoryTaskProgressItem> inventoryTaskProgressItemMap;` in `InventoryTaskProgress`.
- Extract `getInventoryPosition` and `getInventoryFinishedPercentage` from `JobProgress` into `IncrementalTaskProgress`.
- Update `JobProgress` reference of `InventoryTaskProgress`

3, Add YamlInventoryTaskProgressSwapper

**Comment by huangdx0726** [comment]
I will try

**Comment by huangdx0726** [comment]
May be add dataSourceName in IncrementalTaskProgress class right?

**Comment by sandynz** [comment]
> May be add dataSourceName in IncrementalTaskProgress class right?

It's inventory task progress here, incremental task progress refactoring will be in another issue.

**Comment by sandynz** [comment]
> I will try

Thanks. Just assigned to you.

**Comment by sandynz** [comment]
An example job progress in registry center:
```
incremental:
  ds_0:
    delay:
      lastEventTimestamps: 0
      latestActiveTimeMillis: 0
    position: mysql-bin.000012#237010997
inventory:
  finished:
  - ds_0.sbtest1#2
  unfinished:
    ds_0.sbtest1#1: 13666944,20000000
    ds_0.sbtest1#0: 3689472,10000000
sourceDatabaseType: MySQL
status: EXECUTE_INVENTORY_TASK
```
