### ISSUE TITLE
Invalid binding table configuration in ShardingRuleConfiguration

### ISSUE THREAD

**Issue by fenghua0621** [apache/shardingsphere#19906]
code:
![image](https://user-images.githubusercontent.com/42227273/183058350-1ed96a18-5f04-4170-8ee7-05e21f8dfa69.png)
![image](https://user-images.githubusercontent.com/42227273/183058460-0bb1a3fe-39ad-411d-b200-d11a83e2a0e8.png)

ocnfig:
![image](https://user-images.githubusercontent.com/42227273/183057928-23eef796-5358-48e5-9a0a-1642d6edb9a7.png)

result:
![image](https://user-images.githubusercontent.com/42227273/183058031-2d75c42d-a5f5-4b44-9d01-45d402f07a5b.png)

Why was the table name intercepted?
And the order of the table doesn't matter?

**Comment by terrymanu** [comment]
What is your version?

**Comment by userhujiong** [comment]
> What is your version?

5.1.2, But I found that 5.1.1 also has this problem

**Comment by strongduanmu** [comment]
Hi @userhujiong, can you provide your sharding configuration in markdown? I will try to reproduce this exception.

**Comment by userhujiong** [comment]
> Hi @userhujiong, can you provide your sharding configuration in markdown? I will try to reproduce this exception.

config
```yaml
spring:
  shardingsphere:
    props:
      sql-show: true
    datasource:
      common:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 6
        min-idle: 3
        maxActive: 20
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        #validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        filters: stat,wall,slf4j
        connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
        wall:
          multi-statement-allow: true
      names: master
      master:
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/ga_app_attendance?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        password: root
        username: root
    rules:
      sql_translator:
        type: NATIVE
      sharding:
        binding-tables:
          - ga_app_attendance,ga_app_attendance_department
        tables:
          ga_app_attendance:
            actual-data-nodes: master.ga_app_attendance_2022_0$->{1..8},master.ga_app_attendance_2021_0$->{1..8}
            table-strategy:
              standard:
                sharding-column: checkin_sharding
                sharding-algorithm-name: attendance-table-inline
          ga_app_attendance_department:
            actual-data-nodes: master.ga_app_attendance_department_2022_0$->{1..8},master.ga_app_attendance_department_2021_0$->{1..8}
            table-strategy:
              standard:
                sharding-column: checkin_sharding
                sharding-algorithm-name: attendance_dept_table-inline
        sharding-algorithms:
          attendance-table-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.jrsoft.ga.business.attendance.config.MonthStandardAlgorithm
          attendance_dept_table-inline:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.jrsoft.ga.business.attendance.config.MonthStandardAlgorithm
```

This problem occurs when there are two expressions
master.ga_app_attendance_2022_0$->{1..8},master.ga_app_attendance_2021_0$->{1..8}   `false`
master.ga_app_attendance_2022_0$->{1..8}   `true`
