### ISSUE TITLE
Oracle SQLParser Error

### ISSUE THREAD

**Issue by jinyingxiong** [apache/shardingsphere#20000]
### Which version of ShardingSphere did you use?
*5.1.2*
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
*ShardingSphere-JDBC*
### Expected behavior
*I'm using Quartz(2.3.2) in oracle, And use ShardingSphere-JDBC for encrypt some log record, but some simple SQL(generated by Quartz) can't parse by SQLParser and throw Exception*

### Reason analyze (If you can)
I don't know why
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
*See test case*
#### Test Case
``` java
package com.ccesun.pipmp.sql.test;

import org.antlr.v4.runtime.Parser;
import org.antlr.v4.runtime.atn.PredictionMode;
import org.antlr.v4.runtime.misc.ParseCancellationException;
import org.apache.shardingsphere.sql.parser.api.parser.SQLParser;
import org.apache.shardingsphere.sql.parser.core.ParseASTNode;
import org.apache.shardingsphere.sql.parser.core.SQLParserFactory;
import org.apache.shardingsphere.sql.parser.core.database.parser.DatabaseTypedSQLParserFacadeFactory;
import org.apache.shardingsphere.sql.parser.spi.DatabaseTypedSQLParserFacade;

/**
 * @author ZYB
 * @since 2022/8/8 18:28:06
 **/
public class OracleParseTest {

    public static void main(String[] args) {
        String databaseType = "Oracle"; //change to mysql can correct pass sql parse test
        String sqls[] = new String[]{
                "INSERT INTO QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA, PRIORITY)  VALUES('IpmpQuartzScheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",
                "SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'IpmpQuartzScheduler' AND TRIGGER_STATE = ? AND NEXT_FIRE_TIME <= ? AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= ?)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC",
                "SELECT A.TRIGGER_NAME, A.TRIGGER_GROUP, A.NEXT_FIRE_TIME, A.PRIORITY FROM QRTZ_TRIGGERS A WHERE SCHED_NAME = 'IpmpQuartzScheduler' AND TRIGGER_STATE = ? AND NEXT_FIRE_TIME <= ? AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= ?)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC",
                "SELECT * FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'IpmpQuartzScheduler' ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC",
        };
        for (String sql : sqls) {
            parseSQLTest(databaseType, sql);
        }
    }

    /**
     * Test code copy from @{@link org.apache.shardingsphere.sql.parser.core.database.parser.SQLParserExecutor#twoPhaseParse(String)}
     * @param databaseType
     * @param sql
     */
    private static void parseSQLTest(String databaseType, String sql) {
        ParseASTNode parse = null;
        DatabaseTypedSQLParserFacade sqlParserFacade = DatabaseTypedSQLParserFacadeFactory.getInstance(databaseType);
        SQLParser sqlParser = SQLParserFactory.newInstance(sql, sqlParserFacade.getLexerClass(), sqlParserFacade.getParserClass());
        Throwable t = null;
        try {
            ((Parser) sqlParser).getInterpreter().setPredictionMode(PredictionMode.SLL);
            parse = (ParseASTNode) sqlParser.parse();
        } catch (final ParseCancellationException ex) {
            t = ex;
            ((Parser) sqlParser).reset();
            ((Parser) sqlParser).getInterpreter().setPredictionMode(PredictionMode.LL);
            try {
                parse = (ParseASTNode) sqlParser.parse();
            } catch (final ParseCancellationException e) {
                t = e;
            }
        }
        if(parse != null){
            System.out.println(parse.getRootNode().toStringTree((Parser) sqlParser));
        }else{
            System.err.println(String.format("%s - %s", t.getCause().getClass().getName(), sql));
        }
    }
}

```
### Test case run output:
```
org.antlr.v4.runtime.NoViableAltException - INSERT INTO QRTZ_TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP, JOB_NAME, JOB_GROUP, DESCRIPTION, NEXT_FIRE_TIME, PREV_FIRE_TIME, TRIGGER_STATE, TRIGGER_TYPE, START_TIME, END_TIME, CALENDAR_NAME, MISFIRE_INSTR, JOB_DATA, PRIORITY)  VALUES('IpmpQuartzScheduler', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
org.antlr.v4.runtime.NoViableAltException - SELECT TRIGGER_NAME, TRIGGER_GROUP, NEXT_FIRE_TIME, PRIORITY FROM QRTZ_TRIGGERS WHERE SCHED_NAME = 'IpmpQuartzScheduler' AND TRIGGER_STATE = ? AND NEXT_FIRE_TIME <= ? AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= ?)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC
org.antlr.v4.runtime.NoViableAltException - SELECT A.TRIGGER_NAME, A.TRIGGER_GROUP, A.NEXT_FIRE_TIME, A.PRIORITY FROM QRTZ_TRIGGERS A WHERE SCHED_NAME = 'IpmpQuartzScheduler' AND TRIGGER_STATE = ? AND NEXT_FIRE_TIME <= ? AND (MISFIRE_INSTR = -1 OR (MISFIRE_INSTR != -1 AND NEXT_FIRE_TIME >= ?)) ORDER BY NEXT_FIRE_TIME ASC, PRIORITY DESC
(select (selectSubquery (queryBlock SELECT (selectList (unqualifiedShorthand *)) (selectFromClause FROM (fromClauseList (fromClauseOption (selectTableReference (queryTableExprClause (queryTableExpr (queryTableExprSampleClause (queryTableExprTableClause (tableName (name (identifier QRTZ_TRIGGERS))))))))))) (whereClause WHERE (expr (booleanPrimary (booleanPrimary (predicate (bitExpr (simpleExpr (columnName (name (identifier SCHED_NAME))))))) (comparisonOperator =) (predicate (bitExpr (simpleExpr (literals (stringLiterals 'IpmpQuartzScheduler'))))))))) (orderByClause ORDER BY (orderByItem (columnName (name (identifier NEXT_FIRE_TIME))) ASC)) rowLimitingClause))

```

### ShardingSphere config file
``` yml
props:
    sql-show: true

dataSources:
    #names: unique_ds
    unique_ds:
        dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
        driver-class-name: oracle.jdbc.OracleDriver
        filters: mylog,stat,wall
        initialSize: 5
        maxActive: 50
        maxWait: 60000
        minEvictableIdleTimeMillis: 300000
        minIdle: 5
        password: test
        poolPreparedStatements: true
        testOnBorrow: false
        testOnReturn: false
        testWhileIdle: true
        timeBetweenEvictionRunsMillis: 60000
        url: jdbc:oracle:thin:@192.168.0.1:1521:orcl
        username: test
        validationQuery: SELECT 1 FROM DUAL
rules:
- !ENCRYPT
    tables:
        PIPMP_QUARTZ_EXEC_LOG:
            columns:
                JOB_CLASS_NAME:
                    plainColumn: JOB_CLASS_NAME
                    cipherColumn: JOB_CLASS_NAME_ENC
                    encryptorName: def-encryptor
            queryWithCipherColumn: true
    encryptors:
        def-encryptor:
            type: SM4
            props:
                sm4-key: '337E6B39466F756F2344257858235071' #'3~k9Fouo#D%xX#Pq'
                sm4-mode: CBC
                sm4-iv: '39405C433D52407E3B392B2F29745E76' #'9@\C=R@~;9+/)t^v'
                sm4-padding: PKCS5Padding
```
