### ISSUE TITLE
Properties of VolumeBasedRangeShardingAlgorithm VOLUME_RANGE is not clear

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#20058]
## Question

My scenario is range sharding.

ID distributes in [1, 32]

Range sharding into 4 data sources:
ds_0: [1, 8]
ds_1: [9, 16]
ds_2: [17, 24]
ds_3: [25, 32]

I thought the configuration was:
```yaml
    shardingAlgorithms:
      warehouse:
        type: VOLUME_RANGE
        props:
          range-lower: 1
          range-upper: 33
          sharding-volume: 8
```

But the proper configuration is the following:
```yaml
    shardingAlgorithms:
      warehouse:
        type: VOLUME_RANGE
        props:
          range-lower: 9
          range-upper: 25
          sharding-volume: 8
```

The properties may confuse users.
