### ISSUE TITLE
JDBC connection Exception: Unknown system variable 'query_cache_size'

### ISSUE THREAD

**Issue by Bingai077** [apache/shardingsphere#20075]
Which version of ShardingSphere did you use?
ghcr.io/apache/shardingsphere-proxy:c9cc117c8f4b42c220f89c92851bf945c40c71b0  （helm cluster）

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

Expected behavior
JDBC connection is normal.

Actual behavior
java.sql.SQLException: Unknown system variable 'query_cache_size'
![image](https://user-images.githubusercontent.com/51192624/184082438-f5cfd40b-d56b-4861-bd8e-892bfabe8133.png)

Environment Configurations
```
props:
  check-duplicate-table-enabled: false
  check-table-metadata-enabled: true
  kernel-executor-size: 16
  max-connections-size-per-query: 1
  proxy-backend-driver-type: JDBC
  proxy-backend-executor-suitable: OLAP
  proxy-backend-query-fetch-size: -1
  proxy-frontend-executor-size: 0
  proxy-frontend-flush-threshold: 128
  proxy-frontend-max-connections: 0
  proxy-hint-enabled: true
  proxy-opentracing-enabled: false
  show-process-list-enabled: false
  sql-federation-enabled: false
  sql-show: true
  proxy-mysql-default-version: 8.0.21
```
My mysql cloud server version is `8.0.21-5` 

I need a little help.
