### ISSUE TITLE
Refactored Shadow API to replace sourceDataSourceName with productionDataSourceName

### ISSUE THREAD

**Issue by soulasuna** [apache/shardingsphere#20391]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

Refactor the shadow API configuration items to make them concise and consistent with the name.

`sourceDataSourceName` replace with `productionDataSourceName`

### Describe the feature you would like.

Before refactoring:
```yaml
rules:
- !SHADOW
  dataSources:
    shadowDataSource:
      sourceDataSourceName: ds
      shadowDataSourceName: shadow_ds
  ...
```

After refactoring
```yaml
rules:
- !SHADOW
  dataSources:
    shadowDataSource:
      productionDataSourceName: ds
      shadowDataSourceName: shadow_ds
  ...
```
