### ISSUE TITLE
Sometimes `schema` in proxy  case sensitive,sometimes `schema` in proxy  not case sensitive？

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#20491]
### Which version of ShardingSphere did you use?

```
/bin/java
we find java version: java8, full_version=1.8.0_312, full_path=/bin/java
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: d2f8159f0329a6fc88bcae8ba383cce8e11c44cf
Commit Message: Basic support migration to different database type (#20479)
Branch: d2f8159f0329a6fc88bcae8ba383cce8e11c44cf
Build time: 2022-08-24T15:26:07+0800
```

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Proxy handle `schema` have same strategy.

### Actual behavior
Proxy handle `schema` have different strategy.

##### server.yaml

```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: mig_pg
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true

rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
    provider:
      type: ALL_PERMITTED
props:
  proxy-frontend-database-protocol-type: PostgreSQL
```

1. start proxy
2. create database test;
3. \c test
4. create schema SYSTEM;
5. create table system.acmg_t_cust_info_base(cust_no varchar(32) not null);
6. drop schema SYSTEM;
### Example codes for reproduce this issue (such as a github link).
- step 4-5
<img width="494" alt="image" src="https://user-images.githubusercontent.com/86462784/186379200-a5496dc0-179b-46ec-8ca8-e6169de7d3a9.png">
- step 6
<img width="465" alt="image" src="https://user-images.githubusercontent.com/86462784/186379154-513abe6d-6d1a-461c-9baf-b122a0a9ec2d.png">
- stdout.log
<img width="1282" alt="image" src="https://user-images.githubusercontent.com/86462784/186379075-dc71922c-d039-41bd-94ff-accca7be82f6.png">

- zk
<img width="651" alt="image" src="https://user-images.githubusercontent.com/86462784/186379308-6a284d31-a24e-4986-9291-d19370484fac.png">
