### ISSUE TITLE
Consider remove overwrite parameter of mode

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#20552]
Hi community,

Now, ShardingSphere mode is divided into `Standalone` mode and `Cluster` mode. We will adjustment load and persistent rules and datasource logic. Load rules, datasources、props、tables if governance center already exists they. Similarly local configuration are persisted to the governance center if the governance center does not exist.

We can also create or alter our rules, data sources, metadata etc by `DistSQL` `RDL`, `RQL`, `RAL`, `RUL`.

`Standalone mode : `

```
mode:
  type: Standalone
  repository:
    type: H2
  overwrite: false
```

`Cluster mode : `

```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```
