### ISSUE TITLE
With binding table configuration ，Failed to start proxy，“Invalid binding table configuration in ShardingRuleConfiguration”

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#20746]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_292
ShardingSphere-5.1.3-SNAPSHOT
Commit ID: dirty-635d9db1bc423ad1d55d6f986d71bc2b47acf922
Commit Message: Fix RUL DistSQL execution failure in transaction(#19831) (#19834)
Tag: 5.2.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
With binding table configuration ，Start proxy normally；

### Actual behavior
With binding table configuration ，Failed to start proxy；

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
![9QK9_UJFF9 6SMETQOSJJC6](https://user-images.githubusercontent.com/97432411/188262057-2ff2af8e-d16f-41a2-aa8e-f0636c941ec6.png)

9dd0d3990c849d50c17c6dc7c92ec2d4ce0ad7e5 is normal：
![_%0NWDF$I IDZ P$%VDA`%2](https://user-images.githubusercontent.com/97432411/188262068-141ac126-3ff2-4c83-af2c-0888027f3da4.png)

### Example codes for reproduce this issue (such as a github link).
```
rules:
- !SHARDING
  tables:
    t_single:
      actualDataNodes: ds1_0.t_single
    t_ssdb_tb:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb_inline
    t_ssdb_tb_view:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb_view_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb_view_inline
    t_ssdb:
      actualDataNodes: ds1_${0..1}.t_ssdb
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
    t_ssdb_view:
      actualDataNodes: ds1_${0..1}.t_ssdb_view
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
    t_ssdb_tb1:
      actualDataNodes: ds1_${0..1}.t_ssdb_tb1_${0..1}
      databaseStrategy:
        standard:
          shardingAlgorithmName: ds1_database_inline
          shardingColumn: id
      tableStrategy:
        standard:
          shardingColumn: c_id
          shardingAlgorithmName: ts_t_ssdb_tb1_inline

  broadcastTables:
    - t_broadcast
    - t_broadcast_view
  bindingTables:
    - t_ssdb_tb, t_ssdb_tb1
    - t_ssdb_tb, t_ssdb_tb_view
  defaultTableStrategy:
    none:
  defaultDatabaseStrategy:
    none:
  shardingAlgorithms:
    ds1_database_inline:
      type: INLINE
      props:
        algorithm-expression: ds1_${id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb_${c_id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb1_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb1_${c_id % 2}
        allow-range-query-with-inline-sharding: true
    ts_t_ssdb_tb_view_inline:
      type: INLINE
      props:
        algorithm-expression: t_ssdb_tb_view_${c_id % 2}
        allow-range-query-with-inline-sharding: true
```
