### ISSUE TITLE
After executing the "create sharding binding table rules (t_ssdb_tb_view, t_ssdb_tb);" statement, an error will be reported when the next SQL statement is executed

### ISSUE THREAD

**Issue by peilinqian** [apache/shardingsphere#21013]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
we find java version: java8, full_version=1.8.0_342, full_path=/home/peilq_sharding/bisheng-jdk1.8.0_342//bin/java
ShardingSphere-5.2.1-SNAPSHOT
Commit ID: dirty-f1cab653542d80b9a2b7a5cb4d39c3277862ecda
Commit Message: fix alter view rename bug. (#20979)
Branch: f1cab653542d80b9a2b7a5cb4d39c3277862ecda
Build time: 2022-09-16T14:31:19+0800

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
After executing the "create sharding binding table rules (t_ssdb_tb_view, t_ssdb_tb);" statement, the next SQL statement is executed normally

### Actual behavior
After executing the "create sharding binding table rules (t_ssdb_tb_view, t_ssdb_tb);" statement, an error will be reported when the next SQL statement is executed

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
drop view if exists t_ssdb_tb_view;
drop view if exists t_ssdb_tb_view_new;
drop table if exists t_ssdb_tb;
create table t_ssdb_tb(id int,c_id int,a int,b char(10));
insert into t_ssdb_tb values (1,1,10,'test11'),(1,2,10,'Test12'),(1,2,null,'test12'),
(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),
(3,3,null,'test3'),(3,3,null,'test3'),(4,4,40,'test4'),(5,5,50,'Test5');
show sharding binding table rules;
create sharding binding table rules (t_ssdb_tb_view, t_ssdb_tb);
select pg_sleep(2);
```

```
drop view if exists t_ssdb_tb_view;
DROP VIEW
drop view if exists t_ssdb_tb_view_new;
DROP VIEW
drop table if exists t_ssdb_tb;
DROP TABLE
create table t_ssdb_tb(id int,c_id int,a int,b char(10));
CREATE TABLE
insert into t_ssdb_tb values (1,1,10,'test11'),(1,2,10,'Test12'),(1,2,null,'test12'),
(2,1,20,'test21'),(2,2,20,'test22'),(2,3,null,'Test22'),
(3,3,null,'test3'),(3,3,null,'test3'),(4,4,40,'test4'),(5,5,50,'Test5');
INSERT 0 10

show sharding binding table rules;
 sharding_binding_tables
-------------------------
(0 rows)

create sharding binding table rules (t_ssdb_tb_view, t_ssdb_tb);
SUCCESS
select pg_sleep(2);
ERROR:  java.lang.NullPointerException
```

background log

```
[INFO ] 2022-09-16 15:39:04.601 [Connection-3-ThreadExecutor] ShardingSphere-SQL - Logic SQL: select pg_sleep(2);
[INFO ] 2022-09-16 15:39:04.601 [Connection-3-ThreadExecutor] ShardingSphere-SQL - SQLStatement: OpenGaussSelectStatement(super=SelectStatement(super=AbstractSQLStatement(parameterCount=0, parameterMarkerSegments=[], commentSegments=[]), projections=ProjectionsSegment(startIndex=7, stopIndex=17, projections=[ExpressionProjectionSegment(startIndex=7, stopIndex=17, text=pg_sleep(2), expr=FunctionSegment(startIndex=7, stopIndex=17, functionName=pg_sleep, parameters=[LiteralExpressionSegment(startIndex=16, stopIndex=16, literals=2)], text=pg_sleep(2), owner=null), alias=Optional.empty)], distinctRow=false), from=null, where=Optional.empty, groupBy=Optional.empty, having=Optional.empty, orderBy=Optional.empty, combines=[]), limit=Optional.empty, lock=Optional.empty, window=Optional.empty)
[INFO ] 2022-09-16 15:39:04.601 [Connection-3-ThreadExecutor] ShardingSphere-SQL - Actual SQL: ds1_1 ::: select pg_sleep(2);
[ERROR] 2022-09-16 15:39:04.601 [Connection-3-ThreadExecutor] o.a.s.p.f.c.CommandExecutorTask - Exception occur:
java.lang.NullPointerException: null
        at org.apache.shardingsphere.transaction.xa.XAShardingSphereTransactionManager.isInTransaction(XAShardingSphereTransactionManager.java:73)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.isInTransaction(JDBCBackendDataSource.java:118)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.createConnection(JDBCBackendDataSource.java:109)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:80)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.datasource.JDBCBackendDataSource.getConnections(JDBCBackendDataSource.java:53)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.JDBCBackendConnection.createNewConnections(JDBCBackendConnection.java:96)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.JDBCBackendConnection.getConnections(JDBCBackendConnection.java:87)
        at org.apache.shardingsphere.infra.executor.sql.prepare.driver.DriverExecutionPrepareEngine.group(DriverExecutionPrepareEngine.java:88)
        at org.apache.shardingsphere.infra.executor.sql.prepare.AbstractExecutionPrepareEngine.prepare(AbstractExecutionPrepareEngine.java:62)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:187)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:153)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:147)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:130)
        at org.apache.shardingsphere.proxy.backend.handler.data.impl.UnicastDatabaseBackendHandler.execute(UnicastDatabaseBackendHandler.java:76)
        at org.apache.shardingsphere.proxy.frontend.opengauss.command.query.simple.OpenGaussComQueryExecutor.execute(OpenGaussComQueryExecutor.java:77)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:78)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
```

**Comment by FlyingZC** [comment]
Will this operation cause the data source to be closed, which will cause the transaction manager to be closed. @zhaojinchao95

**Comment by FlyingZC** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/19788130/190595597-b32d0989-cf8a-4493-b536-48b8d27d14ad.png">

**Comment by FlyingZC** [comment]
Sorry, I can't reproduce the bug,version: f1cab653542d80b9a2b7a5cb4d39c3277862ecda, cluster mode. @peilinqian 
<img width="808" alt="image" src="https://user-images.githubusercontent.com/19788130/190937624-3400a084-afee-4653-8932-b59a4880415c.png">
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/19788130/190937687-191d3e29-d153-47dc-bdce-750daa01911e.png">

**Comment by FlyingZC** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/19788130/190945744-2d2d07ca-f0a9-4be8-97ec-15fdc99b62d8.png">

**Comment by peilinqian** [comment]
rules:
- !SHARDING
  tables:
    lineitem:
      actualDataNodes: ds_${0..1}.lineitem_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: l_partkey
          shardingAlgorithmName: lineitem-database-inline
      tableStrategy:
        standard:
          shardingColumn: l_orderkey
          shardingAlgorithmName: lineitem-table-inline
    customer:
      actualDataNodes: ds_${0..1}.customer_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: c_custkey
          shardingAlgorithmName: customer-database-inline
      tableStrategy:
        standard:
          shardingColumn: c_nationkey
          shardingAlgorithmName: customer-table-inline
    nation:
      actualDataNodes: ds_${0..1}.nation_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: n_nationkey
          shardingAlgorithmName: nation-database-inline
      tableStrategy:
        standard:
          shardingColumn: n_regionkey
          shardingAlgorithmName: nation-table-inline
    orders:
      actualDataNodes: ds_${0..1}.orders_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: o_orderkey
          shardingAlgorithmName: orders-database-inline
      tableStrategy:
        standard:
          shardingColumn: o_custkey
          shardingAlgorithmName: orders-table-inline
    part:
      actualDataNodes: ds_${0..1}.part_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: p_partkey
          shardingAlgorithmName: part-database-inline
      tableStrategy:
        standard:
          shardingColumn: p_size
          shardingAlgorithmName: part-table-inline
    partsupp:
      actualDataNodes: ds_${0..1}.partsupp_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: ps_partkey
          shardingAlgorithmName: partsupp-database-inline
      tableStrategy:
        standard:
          shardingColumn: ps_suppkey
          shardingAlgorithmName: partsupp-table-inline
    region:
      actualDataNodes: ds_${0..1}.region
      databaseStrategy:
        standard:
          shardingColumn: r_regionkey
          shardingAlgorithmName: region-database-inline
    supplier:
      actualDataNodes: ds_${0..1}.supplier_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: s_suppkey
          shardingAlgorithmName: supplier-database-inline
      tableStrategy:
        standard:
          shardingColumn: s_nationkey
          shardingAlgorithmName: supplier-table-inline
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    lineitem-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${l_partkey % 2}
    lineitem-table-inline:
      type: INLINE
      props:
        algorithm-expression: lineitem_${l_orderkey % 2}
    customer-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${c_custkey % 2}
    customer-table-inline:
      type: INLINE
      props:
        algorithm-expression: customer_${c_nationkey % 2}
    nation-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${n_nationkey % 2}
    nation-table-inline:
      type: INLINE
      props:
        algorithm-expression: nation_${n_regionkey % 2}
    orders-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${o_orderkey % 2}
    orders-table-inline:
      type: INLINE
      props:
        algorithm-expression: orders_${o_custkey % 2}
    part-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${p_partkey % 2}
    part-table-inline:
      type: INLINE
      props:
        algorithm-expression: part_${p_size % 2}
    partsupp-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${ps_partkey % 2}
    partsupp-table-inline:
      type: INLINE
      props:
        algorithm-expression: partsupp_${ps_suppkey % 2}
    region-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${r_regionkey % 2}
    supplier-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${s_suppkey % 2}
    supplier-table-inline:
      type: INLINE
      props:
        algorithm-expression: supplier_${s_nationkey % 2}

**Comment by peilinqian** [comment]
```
rules:
- !SHARDING
  tables:
    lineitem:
      actualDataNodes: ds_${0..1}.lineitem_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: l_partkey
          shardingAlgorithmName: lineitem-database-inline
      tableStrategy:
        standard:
          shardingColumn: l_orderkey
          shardingAlgorithmName: lineitem-table-inline
    customer:
      actualDataNodes: ds_${0..1}.customer_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: c_custkey
          shardingAlgorithmName: customer-database-inline
      tableStrategy:
        standard:
          shardingColumn: c_nationkey
          shardingAlgorithmName: customer-table-inline
    nation:
      actualDataNodes: ds_${0..1}.nation_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: n_nationkey
          shardingAlgorithmName: nation-database-inline
      tableStrategy:
        standard:
          shardingColumn: n_regionkey
          shardingAlgorithmName: nation-table-inline
    orders:
      actualDataNodes: ds_${0..1}.orders_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: o_orderkey
          shardingAlgorithmName: orders-database-inline
      tableStrategy:
        standard:
          shardingColumn: o_custkey
          shardingAlgorithmName: orders-table-inline
    part:
      actualDataNodes: ds_${0..1}.part_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: p_partkey
          shardingAlgorithmName: part-database-inline
      tableStrategy:
        standard:
          shardingColumn: p_size
          shardingAlgorithmName: part-table-inline
    partsupp:
      actualDataNodes: ds_${0..1}.partsupp_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: ps_partkey
          shardingAlgorithmName: partsupp-database-inline
      tableStrategy:
        standard:
          shardingColumn: ps_suppkey
          shardingAlgorithmName: partsupp-table-inline
    region:
      actualDataNodes: ds_${0..1}.region
      databaseStrategy:
        standard:
          shardingColumn: r_regionkey
          shardingAlgorithmName: region-database-inline
    supplier:
      actualDataNodes: ds_${0..1}.supplier_${0..1}
      databaseStrategy:
        standard:
          shardingColumn: s_suppkey
          shardingAlgorithmName: supplier-database-inline
      tableStrategy:
        standard:
          shardingColumn: s_nationkey
          shardingAlgorithmName: supplier-table-inline
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    lineitem-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${l_partkey % 2}
    lineitem-table-inline:
      type: INLINE
      props:
        algorithm-expression: lineitem_${l_orderkey % 2}
    customer-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${c_custkey % 2}
    customer-table-inline:
      type: INLINE
      props:
        algorithm-expression: customer_${c_nationkey % 2}
    nation-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${n_nationkey % 2}
    nation-table-inline:
      type: INLINE
      props:
        algorithm-expression: nation_${n_regionkey % 2}
    orders-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${o_orderkey % 2}
    orders-table-inline:
      type: INLINE
      props:
        algorithm-expression: orders_${o_custkey % 2}
    part-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${p_partkey % 2}
    part-table-inline:
      type: INLINE
      props:
        algorithm-expression: part_${p_size % 2}
    partsupp-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${ps_partkey % 2}
    partsupp-table-inline:
      type: INLINE
      props:
        algorithm-expression: partsupp_${ps_suppkey % 2}
    region-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${r_regionkey % 2}
    supplier-database-inline:
      type: INLINE
      props:
        algorithm-expression: ds_${s_suppkey % 2}
    supplier-table-inline:
      type: INLINE
      props:
        algorithm-expression: supplier_${s_nationkey % 2}

- !READWRITE_SPLITTING
  dataSources:
    ds_0:
      staticStrategy:
        writeDataSourceName: write_0
        readDataSourceNames:
          - read0_0
          - write_0
      loadBalancerName: roundRobin
    ds_1:
      staticStrategy:
        writeDataSourceName: write_1
        readDataSourceNames:
          - read1_0
          - write_1
      loadBalancerName: roundRobin
  loadBalancers:
    roundRobin:
      type: ROUND_ROBIN
```
