### ISSUE TITLE
use `overwrite=true` & yaml, replace logic db in zk

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#21066]
### Which version of ShardingSphere did you use?
91d2d46cf9ea4d139478c2c9c6de8734ade7d4a1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
show real table in logic db now
### Actual behavior
show tables in logic db before

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. start proxy in cluster mode
```
USE encrypt_db;
ADD RESOURCE ds (
    HOST="127.0.0.1",
    PORT=13309,
    DB="before",
    USER="root",
    PASSWORD="test"
);
```
2. stop proxy
3. start proxy with yaml
```
databaseName: encrypt_db
dataSources:
  ds_0:
    password: test
    url: jdbc:mysql://127.0.0.1:13309/after?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    connectionTimeoutMilliseconds: 30000
    maxLifetimeMilliseconds: 1800000
    readOnly: false
    idleTimeoutMilliseconds: 60000
    maxPoolSize: 50
rules:
- !SINGLE {}
- !ENCRYPT
  encryptors:
    aes_encryptor:
      props:
        aes-key-value: 123456abc
      type: AES
  queryWithCipherColumn: false
  tables:
    sbtest1:
      columns:
        pad:
          cipherColumn: pad_encrypt
          encryptorName: aes_encryptor
          logicColumn: pad
          plainColumn: pad
      name: sbtest1
```
overwrite=true
4.export database config;& show tables in `encrypt_db`

<img width="861" alt="image" src="https://user-images.githubusercontent.com/86462784/190983447-f3a12610-57cc-4adb-8924-b0afb3252b69.png">

<img width="872" alt="image" src="https://user-images.githubusercontent.com/86462784/190983552-140a32de-80e1-4815-a6cf-16dbf464240c.png">

5. refresh table metadata;

<img width="327" alt="image" src="https://user-images.githubusercontent.com/86462784/190983605-d34b14bc-a87a-4284-9709-f47491b73cef.png">
