### ISSUE TITLE
query not include sharding column

### ISSUE THREAD

**Issue by 13145512239** [apache/shardingsphere#21079]
## Question
When a DQL not include sharding column, it will quert table one by one and then merge, I want to know if this process is sing threaded or multi-threaded. Looking forward to your reply.

**Comment by TeslaCN** [comment]
This relates to the following props:
```yaml
props:
  max-connections-size-per-query:
  kernel-executor-size:
```
