### ISSUE TITLE
Proxy increases access control

### ISSUE THREAD

**Issue by natehuangting** [apache/shardingsphere#21300]
## Feature Request

The current permission control available for the proxy is basically `type: ALL_PERMITTED`. Can it be designed to be similar to 
the following permission control to intercept various operations at the proxy layer.

The following configuration is in server.yaml.
```
rules:
  - !AUTHORITY
    users:
      - root@%:root
      - sharding@:sharding
  - provider:
      type: DEFINE_PERMITTED
      props:
        user-permitted:
          root: super@all
          sharding: delete,dump,update@logic_db1,logic_db2
```
