### ISSUE TITLE
investigation : is it possible to set up a global constant cross all workflows

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#21402]

**Comment by taojintianxia** [comment]
there is one way could share the constant between workflows:
1. store environment variables in an .env file like this:
```
FOO=bar
```

2. Then you can write code to append data from that file to `$GITHUB_ENV`:

```
name: CI

on:
  workflow_dispatch:

jobs:
  foo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cat .env >> $GITHUB_ENV

      - name: Use the value
        run: echo $FOO
```
3. You'll need to do cat .env >> $GITHUB_ENV (and use actions/checkout) for each job where you need to access env vars from that file.
