### ISSUE TITLE
ServiceProviderNotFoundException

### ISSUE THREAD

**Issue by 1210958801** [apache/shardingsphere#21422]
When I use shardingjdbc find this bug.

![img_v2_42eb1929-e683-4ab5-b558-33074061824g](https://user-images.githubusercontent.com/34763201/194749043-82fbb1e1-cd9c-4af8-bab1-4f35ef495a75.jpg)

help

remarks,the table 'user_team_role_relation' is not shard table config.

**Comment by TeslaCN** [comment]
Have you shaded jars of ShardingSphere?

**Comment by 1210958801** [comment]
> Have you shaded jars of ShardingSphere?

Thank you for your reply, But I've never done that before

**Comment by 1210958801** [comment]
@TeslaCN

**Comment by 1210958801** [comment]
`yaml`
- !SHARDING
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: rosetta_task_$->{project_id%4}
      type: INLINE
    history_table_inline:
      props:
        algorithm-expression: task_history_$->{task_id%4}
      type: INLINE
    task_table_inline:
      props:
        algorithm-expression: task_info_$->{project_id%3}
      type: INLINE
  tables:
    task_info:
      actualDataNodes: rosetta_task_$->{0..3}.task_info_$->{0..2}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_info
      tableStrategy:
        standard:
          shardingAlgorithmName: task_table_inline
          shardingColumn: project_id
    task_history:
      actualDataNodes: rosetta_task_$->{0..3}.task_history_$->{0..3}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_history
      tableStrategy:
        standard:
          shardingAlgorithmName: history_table_inline
          shardingColumn: task_id

**Comment by 1210958801** [comment]
`
- !SHARDING
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: rosetta_task_$->{project_id%4}
      type: INLINE
    history_table_inline:
      props:
        algorithm-expression: task_history_$->{task_id%4}
      type: INLINE
    task_table_inline:
      props:
        algorithm-expression: task_info_$->{project_id%3}
      type: INLINE
  tables:
    task_info:
      actualDataNodes: rosetta_task_$->{0..3}.task_info_$->{0..2}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_info
      tableStrategy:
        standard:
          shardingAlgorithmName: task_table_inline
          shardingColumn: project_id
    task_history:
      actualDataNodes: rosetta_task_$->{0..3}.task_history_$->{0..3}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_history
      tableStrategy:
        standard:
          shardingAlgorithmName: history_table_inline
          shardingColumn: task_id

`

**Comment by 1210958801** [comment]
```
- !SHARDING
  shardingAlgorithms:
    database_inline:
      props:
        algorithm-expression: rosetta_task_$->{project_id%4}
      type: INLINE
    history_table_inline:
      props:
        algorithm-expression: task_history_$->{task_id%4}
      type: INLINE
    task_table_inline:
      props:
        algorithm-expression: task_info_$->{project_id%3}
      type: INLINE
  tables:
    task_info:
      actualDataNodes: rosetta_task_$->{0..3}.task_info_$->{0..2}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_info
      tableStrategy:
        standard:
          shardingAlgorithmName: task_table_inline
          shardingColumn: project_id
    task_history:
      actualDataNodes: rosetta_task_$->{0..3}.task_history_$->{0..3}
      databaseStrategy:
        standard:
          shardingAlgorithmName: database_inline
          shardingColumn: project_id
      logicTable: task_history
      tableStrategy:
        standard:
          shardingAlgorithmName: history_table_inline
          shardingColumn: task_id

```
