### ISSUE TITLE
Wrong SQL rewrite result occurs when part of logical table name of the binding table is consistent with the actual table name, and some are inconsistent

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#21594]
### Which version of ShardingSphere did you use?

https://github.com/apache/shardingsphere/commit/155b86e7ff8d7b247e0261c2b9135059bb12ccca

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

SQL rewrite successfully.

```
mysql> preview select * from t_order o inner join t_order_item i on o.user_id = i.user_id where o.user_id = 1;
+------------------+------------------------------------------------------------------------------------------------+
| data_source_name | actual_sql                                                                                     |
+------------------+------------------------------------------------------------------------------------------------+
| ds_1             | select * from t_order o inner join t_order_item_test i on o.user_id = i.user_id where o.user_id = 1 |
+------------------+------------------------------------------------------------------------------------------------+
1 row in set (0.83 sec)
```

### Actual behavior

<img width="960" alt="image" src="https://user-images.githubusercontent.com/10829171/195998089-32ce760b-1ac8-4941-8063-a59af08e90d0.png">

```
mysql> preview select * from t_order o inner join t_order_item i on o.user_id = i.user_id where o.user_id = 1;
+------------------+------------------------------------------------------------------------------------------------+
| data_source_name | actual_sql                                                                                     |
+------------------+------------------------------------------------------------------------------------------------+
| ds_1             | select * from t_order o inner join t_order_item i on o.user_id = i.user_id where o.user_id = 1 |
+------------------+------------------------------------------------------------------------------------------------+
1 row in set (0.83 sec)
```

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/10829171/195997124-bd1a397e-ab84-403d-97fa-ec5b737c7ab0.png)

The TableTokenGenerator class determines whether the logical table name and the actual table name are consistent, and skips the rewriting if they are consistent, while the binding table is rewritten depending on the primary table, which will cause other tables in the binding table to be unable to be rewritten and an execution error will occur.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Config yaml like following:

```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_test
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
```

And execute init sql:

```sql
CREATE TABLE `t_order_item` (
  `item_id` int(11) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `content` varchar(100) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE `t_order` (
  `order_id` int(11) DEFAULT NULL,
  `user_id` int(11) DEFAULT NULL,
  `content` varchar(100) DEFAULT NULL
) ENGINE=InnoDB;
```

Then execute `select * from t_order o inner join t_order_item i on o.user_id = i.user_id where o.user_id = 1`.
