### ISSUE TITLE
[Feature Request] Replace jdbcUrl to url in jdbc examples data source properties

### ISSUE THREAD

**Issue by sandynz** [apache/shardingsphere#21700]
### Is your feature request related to a problem?
No

### Describe the feature you would like.

Currently, data source properties support ShardingSphere standard properties and also underlying data source pool properties, e.g. `url` in ShardingSphere and `jdbcUrl` in Hikari.
`url` is defined in `ConnectionPropertySynonyms`:
```
    static {
        STANDARD_PROPERTY_KEYS.add("url");
        STANDARD_PROPERTY_KEYS.add("username");
        STANDARD_PROPERTY_KEYS.add("password");
    }
```

The proxy example configuration file already use `url`, e.g. `config-sharding.yaml` in `shardingsphere-proxy-bootstrap` module:
```
#dataSources:
#  ds_0:
#    url: jdbc:postgresql://127.0.0.1:5432/demo_ds_0
#    username: postgres
#    password: postgres
```

It still use `jdbcUrl` in JDBC core example, e.g. `sharding-auto-tables.yaml` in `sharding-raw-jdbc-example` module:
```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password:
```

Could we replace `jdbcUrl` to `url` in examples? Then there's unified data source property `url` and it's easier to understand for users.
And we'll try to unify other different data source properties between JDBC and PROXY later.

Hi @totalo , you've contributed much on standardized examples, could you help to investigate it?
