### ISSUE TITLE
关于在Springboot的web项目中通过DataSourceConfig配置分片规则不生效的问题

### ISSUE THREAD

**Issue by haiy1026** [apache/shardingsphere#21743]
关于在Springboot的web项目中通过DataSourceConfig配置分片规则不生效的问题。
场景环境：
    1. springboot版本：2.3.7.RELEASE
    2. shardingjdbc版本：4.0.0.RC1
    3.MySQL版本：8.0+
    4.mybatis-plus版本：3.3.2
    5. 项目类型：web
问题描述：
如果我通过application.yaml来配置分片规则（ComplexKeysShardingAlgorithm），那么我就可以根据分片规则来区分数据表，但是我不在application.yaml里做任何的配置，而是通过config目录下通过DataSourceConfig来配置分片规则，那么我的查询就没经过我自定义的分片规则。
1. 其中我的application配置文件如下：

```
spring:
  main:
    allow-bean-definition-overriding: true
  sharding-sphere:
    datasource:
      db1:
        url: jdbc:mysql://localhost:23306/db1?serverTime=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
      names: db1
    props:
      sql.show: true
    sharding:
      default-data-source-name: db1
      tables:
        employee:
          dynamic: true
          actualDataNodes: db1.his_employee_${20221018..20221019}
          databaseStrategy:
            none:
          tableStrategy:
            complex:
              sharding-columns: biz_date
              algorithm-class-name: com.lbc.split.config.ComplexShardingAlgo
```

然后我的分片规则：

```
@Component
public class ComplexShardingAlgo implements ComplexKeysShardingAlgorithm<String> {
    /**
     *
     * @param collection 加载配置文件时的解析规则,逻辑表规则
     * @param complexKeysShardingValue SQL中对应的Value
     * @return
     */
    @Override
    public Collection<String> doSharding(Collection<String> collection, ComplexKeysShardingValue<String> complexKeysShardingValue) {

        log.info("获取集合{} 和复合分片的值序列：{}",collection,complexKeysShardingValue);
        return collection;
    }
}
```

我通过方法是以上是没有任何问题的，也就是说会执行我的分片规则。
但是如果我注释applicaton.yaml里的内容，然后通过配置DataSourceConfig的形式初始化我的数据库连接，那么我设定的分片规则就没执行到（可以初始化，但是我debug的时候没有经过分片规则）
做法和代码如下：

```
@Configuration
public class DataSourceConfig {

    public Map<String, DataSource> createDataSourceMap() {
        DruidDataSource dataSource1 = new DruidDataSource();
        dataSource1.setDriverClassName("com.mysql.jdbc.Driver");
        dataSource1.setUrl("jdbc:mysql://localhost:23306/db1?serverTime=UTC&useUnicode=true&characterEncoding=utf-8");
        dataSource1.setUsername("root");
        dataSource1.setPassword("root");
        Map<String, DataSource> result = new HashMap<>(5);
        result.put("db1", dataSource1);
        return result;
    }

    TableRuleConfiguration getTableRuleConfiguration() {
        TableRuleConfiguration result = new TableRuleConfiguration("employee","db1.his_employee_$->{20221018..20221020}");
        // 通过注入的形式也不执行到
        result.setTableShardingStrategyConfig(new ComplexShardingStrategyConfiguration("biz_date",new ComplexShardingAlgo()));
        return result;
    }

    @Bean
    DataSource shardingDataSource() throws SQLException {
        ShardingRuleConfiguration shardingRuleConfig = new ShardingRuleConfiguration();
        shardingRuleConfig.getTableRuleConfigs().add(getTableRuleConfiguration());

        Properties properties = new Properties();
       // 这里生效了，但是分片规则不生效，debug的时候，也没有进入到ComplexShardingAlgo类里。
        properties.setProperty("sql.show","true");
        return ShardingDataSourceFactory.createDataSource(createDataSourceMap(),shardingRuleConfig,properties);
    }
```

请问是我在DataSourceConfig里配置不正确的原因导致吗？那么我该如何修改和设置？
