### ISSUE TITLE
SQL check failed, error message: Not allow DML operation without sharding conditions.

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#21884]
### Which version of ShardingSphere did you use?

master - 3a640cc9f5fd7e6cebd890c4c53f0fc612a73084

But this may affect 5.2.0 and 5.2.1.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

No error occur.

### Actual behavior

The sharding conditions did existed. But error still occurred.
```
SQL check failed, error message: Not allow DML operation without sharding conditions.
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Just execute prepared statement with parameters.

```sql
SELECT c_discount, c_last, c_credit, w_tax     FROM bmsql_customer     JOIN bmsql_warehouse ON (w_id = c_w_id)     WHERE c_w_id = ? AND c_d_id = ? AND c_id = ?
```
```
parameters = {ArrayList@10429}  size = 3
 0 = {Integer@13673} 10
 1 = {Integer@13674} 2
 2 = {Integer@13675} 1231
```

```yaml
rules:
  - !SHARDING
    auditors:
      sharding_key_required_auditor:
        type: DML_SHARDING_CONDITIONS
    tables:
      bmsql_warehouse:
        actualDataNodes: ds_${0..3}.bmsql_warehouse
        databaseStrategy:
          standard:
            shardingColumn: w_id
            shardingAlgorithmName: warehouse
        auditStrategy:
          auditorNames:
            - sharding_key_required_auditor
          allowHintDisable: true
      bmsql_customer:
        actualDataNodes: ds_${0..3}.bmsql_customer
        databaseStrategy:
          standard:
            shardingColumn: c_w_id
            shardingAlgorithmName: warehouse
```
