### ISSUE TITLE
mysql limit sql rewrite question for masterslave

### ISSUE THREAD

**Issue by 300682** [apache/shardingsphere#21946]
## Question
version: 4.1.1
sharding config: 
```
spring:
  shardingsphere:
    datasource:
      names: 'basic,order1,order2'
    sharding:
      default-data-source-name: basic
      master-slave-rules:
        order1:
          master-data-source-name: order1
          slave-data-source-names: basic
        order2:
          master-data-source-name: order2
          slave-data-source-names: basic
        basic:
          master-data-source-name: basic
          slave-data-source-names: basic
      tables:
        xxxx_record:
          actual-data-nodes: >-
            order$->{1..2}.xxxx_record
          database-strategy:
            complex:
              sharding-columns: 'pk_id'
              algorithm-class-name: >-
                com.xxxx.sharding.jdbc.config.xxxDatabaseShardingAlgorithm
```
Logic SQL: `select xxx from xxx_table WHERE  xxx  and exit_time >= ? and exit_time <= ? order by exit_time desc LIMIT 10,10`

routeContext routeMapper [ logicName : actualName ] -> {"order1":"basic","order2":"basic"}

executeRewrite return  executionUnits size 1 basic.

Actual SQL: `select xxx from xxx_table WHERE  xxx  and exit_time >= ? and exit_time <= ? order by exit_time desc LIMIT 0,20`

resultMerger queryResults size 1，no merge

execute return rows size 20 ,  expect rows 10
