### ISSUE TITLE
panic: pq: No value specified for parameter 1. when using Golang XORM

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#22501]
### Which version of ShardingSphere did you use?

master - e71e94d7e1b71694402829ea0074cb085129069e

This issue may be caused by https://github.com/apache/shardingsphere/pull/13692

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy PostgreSQL

### Expected behavior

Query returned correct result.

### Actual behavior

```
panic: pq: No value specified for parameter 1.
```

### Reason analyze (If you can)

![image](https://user-images.githubusercontent.com/20503072/204470841-e9ae17c9-bb8c-4d90-8489-8d0cbead962b.png)

![image](https://user-images.githubusercontent.com/20503072/204470888-7b2d807b-7657-4cd2-a44e-41082e5a36dd.png)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```yaml
schemaName: postgres
dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/postgres?prepareThreshold=1
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 3000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 32
    minPoolSize: 0

rules: []
```
