### ISSUE TITLE
sharding proxy thread pool type is fixed

### ISSUE THREAD

**Issue by hua74ni** [apache/shardingsphere#22517]
### Is your feature request related to a problem?

Start the proxy using yaml configuration, there is no configuration to modify the datasourcePool. Sharding-proxy create a thread pool type is fixed -- "com.zaxxer.hikari.HikariDataSource" 

![image](https://user-images.githubusercontent.com/27909365/204695563-b632dba2-36ef-4c43-bb16-f31162d0b12e.png)

![image](https://user-images.githubusercontent.com/27909365/204695990-00f5e6b2-18fd-4356-b6d1-f32fabc1e38a.png)

### Describe the feature you would like.

Start the proxy using yaml configuration, hoping that the configuration can modify the datasourcePool

**Comment by strongduanmu** [comment]
Hi @hua74ni thank you for your feedback. Currently Proxy uses hikari as the default connection pool. Do you have a need to replace the connection pool?

**Comment by hua74ni** [comment]
> Hi @hua74ni thank you for your feedback. Currently Proxy uses hikari as the default connection pool. Do you have a need to replace the connection pool?

Hybrid Architecture,Proxy uses hikari as the default connection pool,JDBC can only be hikari as well.
Or I don't understand it right?

**Comment by sandynz** [comment]
> Hybrid Architecture,Proxy uses hikari as the default connection pool,JDBC can only be hikari as well. Or I don't understand it right?

Yes, looks it's true.
`dataSourceClassName: com.zaxxer.hikari.HikariDataSource` is persisted in logic database metadata. e.g.
```
ds_1:
  password: root
  minPoolSize: '1'
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  idleTimeoutMilliseconds: '60000'
  maxPoolSize: '20'
  url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
  username: root
```
