### ISSUE TITLE
Agent + SS-JDBC，can't show metrics by prometheus.

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#22550]
### Which version of ShardingSphere did you use?
7e6d00dbfab5f016fae7736f805c34df469a2907
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC or ShardingSphere-Proxy
### Expected behavior
ShardingSphere-JDBC & ShardingSphere-Proxy have same behave.
### Actual behavior
```
[root@localhost 1130]# cat agent/conf/agent.yaml  | grep -v ^#

plugins:
  metrics:
    Prometheus:
      host:  "localhost"
      port: 9999
      props:
        jvm-information-collector-enabled: "true"
```
Use same `agent.yaml` ，proxy can show metrics，but ss-jdbc can't.
### Reason analyze (If you can)
If i want ss-jdbc  + agent have metric,i must start `logging`.
```
plugins:
  logging:
    BaseLogging:
      props:
        level: "INFO"
  metrics:
    Prometheus:
      host:  "localhost"
      port: 9999
      props:
        jvm-information-collector-enabled: "true"
```
