### ISSUE TITLE
[New Feature] Implement new data masking feature for users with security needs

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#22759]
## Background

With the promulgation of various security laws, many community users have requested for data masking feature. Data masking can realize the special shielding, encryption, and hiding of the data returned by the production database according to the user's role, responsibility and other IT definition rules without any change to the data in the production database.

![image](https://user-images.githubusercontent.com/10829171/206631893-b1e13e04-7d01-48ab-a98f-7629c5180efa.png)

## Mask Rule

Based on the pluggable architecture of ShardingSphere, we can easily add a Mask Rule. `MASK RULE` is used to specify mask rules. First, the user needs to specify the data source in dataSources, and then configure mask rules in tables under `- !MASK`. 

Data masking does not store data, and only performs mask calculations when users query. Since the data is calculated in real time, when users change the mask algorithm, they do not need to wash the data, and can directly modify the mask algorithm in the Rule.

The main configuration properties of `MASK RULE` are as follows:

- maskAlgorithm: Specifies the mask algorithm, and mask feature performs data processing according to the masking algorithm;

The YAML configuration of the mask feature is as follows:

```yaml
databaseName: mask_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
        
# MASK rule configuration：
rules:
- !MASK
  tables:
    t_user:
      columns:
        telephone:
          maskAlgorithm: index_based_replace_mask
        address:
          maskAlgorithm: md5_mask

  maskAlgorithms:
    md5_mask:
      type: MD5
    index_based_replace_mask:
      type: INDEX_BASED_REPLACE
      props:
        start-index: 3
        stop-index: 8
        replace-char: *
```

Positioning of MASK RULE in the kernel:
- Data Mask Rule belongs to DatabaseRule, which is mainly used for data mask processing, and needs to be implemented in the merge engine in the kernel process;
- The processing order of Mask Rule and Encrypt Rule is as follows, and these functions can be mixed and used;

![image](https://user-images.githubusercontent.com/10829171/206627847-99abcad3-d17e-43d0-8a19-c8d3edc0a2cd.png)

## Merge Engine Modification

Add ResultDecoratorEngine subclass for Mask Rule, newInstance method returns MaskDQLResultDecorator class:

```java
/**
 * Result decorator engine.
 *
 * @param <T> type of rule
 */
public interface ResultDecoratorEngine<T extends ShardingSphereRule> extends ResultProcessEngine<T> {
    
    /**
     * Create new instance of result decorator.
     * 
     * @param database database
     * @param rule rule
     * @param props configuration properties
     * @param sqlStatementContext SQL statement context
     * @return created instance
     */
    ResultDecorator<?> newInstance(ShardingSphereDatabase database, T rule, ConfigurationProperties props, SQLStatementContext<?> sqlStatementContext);
}
```

`MaskDQLResultDecorator` can be implemented by referring to `EncryptDQLResultDecorator` and `EncryptMergedResult`. When obtaining the result set, it is judged whether the current column is configured with a mask rule. If so, the mask algorithm is obtained for mask processing.

```java
@Override
public boolean next() throws SQLException {
    return mergedResult.next();
}

@SuppressWarnings({"rawtypes", "unchecked"})
@Override
public Object getValue(final int columnIndex, final Class<?> type) throws SQLException {
    Optional<EncryptContext> encryptContext = metaData.findEncryptContext(columnIndex);
    if (!encryptContext.isPresent() || !metaData.isQueryWithCipherColumn(encryptContext.get().getTableName(), encryptContext.get().getColumnName())) {
        return mergedResult.getValue(columnIndex, type);
    }
    Optional<StandardEncryptAlgorithm> encryptAlgorithm = metaData.findEncryptor(encryptContext.get().getTableName(), encryptContext.get().getColumnName());
    if (!encryptAlgorithm.isPresent()) {
        return mergedResult.getValue(columnIndex, type);
    }
    Object cipherValue = mergedResult.getValue(columnIndex, Object.class);
    return null == cipherValue ? null : encryptAlgorithm.get().decrypt(cipherValue, encryptContext.get());
}
```

### Mask Algorithm Inteface

```java
/**
 * Mask algorithm.
 * 
 * @param <I> type of plain value
 * @param <O> type of mask value
 */
public interface MaskAlgorithm<I, O> {
    
    /**
     * Mask.
     *
     * @param plainValue plain value
     * @return mask value
     */
    O mask(I plainValue);
}
```

#### MD5

- Algorithm name: MD5
- Input parameter: Salt value
- Implementation logic: refer to MD5EncryptAlgorithm

#### MD5

- Algorithm name: MD5
- Input parameter: Salt value
- Implementation logic: refer to MD5EncryptAlgorithm

#### KEEP_FIRST_N_LAST_M

- Algorithm name: KEEP_FIRST_N_LAST_M
- Input parameters: n, m, replacement character
- Implement logic: TODO

#### KEEP_FROM_X_TO_Y

- Algorithm name: KEEP_FROM_X_TO_Y
- Input parameters: x, y, replacement character
- Implement logic: TODO

#### MASK_FIRST_N_LAST_M

- Algorithm name: MASK_FIRST_N_LAST_M
- Input parameters: n, m, replacement character
- Implement logic: TODO

#### MASK_FROM_X_TO_Y

- Algorithm name: MASK_FROM_X_TO_Y
- Input parameters: x, y, replacement character
- Implement logic: TODO

#### MASK_BEFORE_SPECIAL_CHAR

- Algorithm name: MASK_BEFORE_SPECIAL_CHAR
- Input parameters: special characters
- Implement logic: TODO

#### MASK_AFTER_SPECIAL_CHAR

- Algorithm name: MASK_AFTER_SPECIAL_CHAR
- Input parameters: special characters
- Implement logic: TODO

#### PERSONAL_IDENTITY_NUMBER_RANDOM_REPLACE

- Algorithm name: PERSONAL_IDENTITY_NUMBER_RANDOM_REPLACE
- Input parameters: administrative division random code table
- Implement logic: TODO

#### MILITARY_IDENTITY_NUMBER_RANDOM_REPLACE

- Algorithm name: MILITARY_IDENTITY_NUMBER_RANDOM_REPLACE
- Input parameters: type code random code table
- Implement logic: TODO

#### LANDLINE_NUMBER_RANDOM_REPLACE

- Algorithm name: LANDLINE_NUMBER_RANDOM_REPLACE
- Input parameters: administrative division random code table
- Implement logic: TODO

#### TELEPHONE_RANDOM_REPLACE

- Algorithm name: TELEPHONE_RANDOM_REPLACE
- Input parameters: network number
- Implement logic: TODO

#### UNIFIED_CREDIT_CODE_RANDOM_REPLACE

- Algorithm name: UNIFIED_CREDIT_CODE_RANDOM_REPLACE
- Input parameters: random code table for registration department, random code table for category code, random code table for administrative division
- Implement logic: TODO

#### GENERIC_TABLE_RANDOM_REPLACE

- Algorithm name: GENERIC_TABLE_RANDOM_REPLACE
- Input parameters: uppercase letter random code, lowercase letter random code, digital random code, special random code
- Implement logic: TODO

#### ADDRESS_RANDOM_REPLACE

- Algorithm name: ADDRESS_RANDOM_REPLACE
- Input parameters: administrative division random code table
- Implement logic: TODO

## Dev tasks

- [x] Add new mask module in features module @strongduanmu 
- [x] init mask rule configuration and mask rule @zzzwjZhang 
- [x] Implement ResultDecoratorEngine for MaskRule and add mask processing logic @gxxiong 
- [x] Implement the mask algorithm
  - [x] MD5 @strongduanmu 
  - [x] KEEP_FIRST_N_LAST_M @zzzwjZhang 
  - [x] KEEP_FROM_X_TO_Y @zzzwjZhang 
  - [x] MASK_FIRST_N_LAST_M @lushaorong 
  - [x] MASK_FROM_X_TO_Y @lushaorong 
  - [x] MASK_BEFORE_SPECIAL_CHAR @gxxiong 
  - [x] MASK_AFTER_SPECIAL_CHAR @gxxiong 
  - [x] PERSONAL_IDENTITY_NUMBER_RANDOM_REPLACE @liushangqing9803 
  - [x] MILITARY_IDENTITY_NUMBER_RANDOM_REPLACE @lushaorong 
  - [x] LANDLINE_NUMBER_RANDOM_REPLACE @lushaorong
  - [x] TELEPHONE_RANDOM_REPLACE @gxxiong 
  - [x] UNIFIED_CREDIT_CODE_RANDOM_REPLACE @lushaorong 
  - [x] GENERIC_TABLE_RANDOM_REPLACE @lushaorong 
  - [ ] ADDRESS_RANDOM_REPLACE
- [x] Add new DistSQL for mask(Need @RaigorJiang to help design DistSQL syntax)
- [x] Add unit test @strongduanmu @zzzwjZhang @gxxiong @lushaorong 
- [x] Add integration test
  - [x] Add single mask integration test @gxxiong
  - [x] Add mask and encrypt integration test @gxxiong 
  - [x] Add mask and sharding integration test @gxxiong
  - [x] Add mask, encrypt and sharding integration test @gxxiong
- [x] Add example for mask @totalo 
- [x] Add document for mask @strongduanmu
