### ISSUE TITLE
5.3.0 How to import config file by Nacos(config) in SpringCloud

### ISSUE THREAD

**Issue by zt9788** [apache/shardingsphere#22790]
## Question
ShardingShpere-JDBC 5.3.0

the url: jdbc:shardingsphere:classpath:db.yml
file:
```
....
rules:
  - !READWRITE_SPLITTING 
  ....
```
How can. i use the Nacos import the db.yml
```
spring:
   config:
      import:
        - nacos:db.yml # it is will be error about (can not read...   - !READWRITE_SPLITTING ...)
```
