### ISSUE TITLE
Make actualDataNodes expose SPI that can define expression with custom rules and add GraalVM Truffle implementation

### ISSUE THREAD

**Issue by linghengqian** [apache/shardingsphere#22899]
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

- Refer to https://github.com/apache/shardingsphere/issues/22884, https://github.com/linghengqian/graalvm-trace-metadata-smoketest/issues/1 and https://github.com/apache/shardingsphere/issues/21347 .

### Describe the feature you would like.

- Since it is impossible for most people to understand the syntax of Groovy in the first place, issues like https://github.com/apache/shardingsphere/issues/22884 can always be mentioned repeatedly, and the initiators of those issues have misunderstood the final results generated by certain Groovy expressions, similar results can actually be verified at https://groovyconsole.appspot.com/ .
- If we can expose SPI for `actualDataNodes`, users can define special rules for expressions by implementing SPI, which will obviously help reduce some misunderstandings.

- The significance of this issue for https://github.com/apache/shardingsphere/issues/21347 is that using `GroovyShell` directly means an additional class loader, which means that if single tests involving `GroovyShell` are directly executed under GraalVM Native Image, all are bound to fail. I've opened https://github.com/oracle/graal/issues/5522 and provided common unittests in ShardingSphere using GroovyShell.

- Once the SPI of actualDataNodes is exposed, we can introduce the implementation of GraalVM Truffle in the master branch of ShardingSphere, which should allow us to use JavaScript, Python, R, Ruby, and LLVM Language in `actualDataNodes`. And because of the use of GraalVM Truffle, we can imagine completing the nativeTest of ShardingSphere under GraalVM Native Image. 

- For Groovy, I think it can be used unchanged, but we can also try to transfer the Groovy method call to Truffle's implementation of Espresso, which will distinguish the host JVM process from the guest JVM process to ensure that the nativeTest under GraalVM Native Image passes . But it is worth mentioning that Espresso is more limited than other Truffle API implementations.

- I assume the YAML henceforth should be configured as such.
```yaml
rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: 
          type: ORIGIN_GROOVY
          props:  
           expression: ds-0.t_order_$->{20221123..20221125}
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: lingh-interval
    shardingAlgorithms:
      lingh-interval:
        type: INTERVAL
        props:
          datetime-pattern: "yyyy-MM-dd HH:mm:ss.SSS"
          datetime-lower: "2022-11-23 00:00:00.000"
          datetime-upper: "2022-11-26 00:00:00.000"
          sharding-suffix-pattern: "_yyyyMMdd"
          datetime-interval-amount: 1
          datetime-interval-unit: "DAYS"
```
- The interface corresponding to SPI should be similar to.
```java
import org.apache.shardingsphere.infra.util.spi.lifecycle.SPIPostProcessor;
import org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPI;
import java.util.Properties;

public interface ShardingSphereExpressionParser extends TypedSPI, SPIPostProcessor {

   /**
     * Replace all inline expression placeholders.
     * 
     * @return result inline expression with placeholders
     */
   String handlePlaceHolder();

   /**
     * Split and evaluate inline expression.
     *
     * @return result list
     */
   List<String> splitAndEvaluate();

   /**
     * Get inline expression with placeholders by properties.
     *
     * @return properties
     */
    Properties getProps();
}
```

**Comment by RaigorJiang** [comment]
When sharding by interval, it's really not easy for new users to understand the meaning of Groovy expressions. 
Looking forward to further discussion!

**Comment by linghengqian** [comment]
- For a long time no one gave an opinion. Let me expand on this issue a bit. Considering sharding by date, we should not limit the expression, but directly build an algorithmic SPI.
```java
import org.apache.shardingsphere.infra.util.spi.lifecycle.SPIPostProcessor;
import org.apache.shardingsphere.infra.util.spi.type.typed.TypedSPI;
import java.util.Properties;

public interface AbstractActualdataNodes extends TypedSPI, SPIPostProcessor {
   /**
     *
     * @return result real table list
     */
   List<String> getActualDataNodes();

   /**
     * Get properties.
     *
     * @return properties
     */
    Properties getProps();
}
```
- We should only consider the `java.util.List` of the final real table. For the simplest case of sharding by date, the configuration of the simplest implementation class using JSR 310 should be similar to the following.
```yaml
rules:
   - !SHARDING
     tables:
       t_order:
         actualDataNodes:
           type: SINGLE_TABLE
           props:
            table-prefix: t_order # The prefix of the real table
            datetime-lower: 2022-10-01 # lower limit of time
            datetime-upper: 2022-12-31 # time upper limit
            datetime-pattern: yyyy-MM-dd # A string conforming to the format of java.time.format.DateTimeFormatter, used to convert datetime-lower and datetime-upper
            table-suffix-pattern: _yyyyMM # The suffix of the real table, also follows the format of java.time.format.DateTimeFormatter
            datetime-interval-amount: 1 # time interval
            datetime-interval-unit: MONTHS # follow java.time.temporal.ChronoUnit
```
- It should end up producing an ArrayList containing `[t_order_202210,t_order_202211,t_order_202212]`.
- Let's assume a simple function to do this conversion.
```java
import org.junit.jupiter.api.Test;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoField;
import java.time.temporal.ChronoUnit;
import java.time.temporal.TemporalAccessor;
import java.util.List;
import java.util.stream.LongStream;

public class DateTest {
    @Test
    void testDate() {
        DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        TemporalAccessor start = dateTimeFormatter.parse("2022-10-01");
        TemporalAccessor end = dateTimeFormatter.parse("2022-12-31");
        if (!start.isSupported(ChronoField.NANO_OF_DAY) && start.isSupported(ChronoField.EPOCH_DAY)) {
            LocalDate startTime = start.query(LocalDate::from);
            LocalDate endTime = end.query(LocalDate::from);
            List<String> actualDataNodes = LongStream.range(0, ChronoUnit.MONTHS.between(startTime, endTime.plusMonths(1)))
                    .mapToObj(startTime::plusMonths)
                    .map(localDate -> "t_order" + localDate.format(DateTimeFormatter.ofPattern("_yyyyMM")))
                    .toList();
            assert actualDataNodes.equals(List.of("t_order_202210", "t_order_202211", "t_order_202212"));
        }
    }
}
```
