### ISSUE TITLE
May I ask when will maven central repository push shardingsphere-jdbc-core-spring-boot-starter 5.3.0？

### ISSUE THREAD

**Issue by chenws1012** [apache/shardingsphere#22962]
<img width="1521" alt="image" src="https://user-images.githubusercontent.com/17613152/208341638-f5c187c5-95be-4f8c-9665-50618b50b9bb.png">

**Comment by FlyingZC** [comment]
The springboot configuration has been removed in version 5.3.0, you can use the yaml configuration of shardingsphere.

**Comment by TeslaCN** [comment]
You may refer to:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

**Comment by pengxianggui** [comment]
> You may refer to: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

This way of integrating springboot makes it difficult to overwrite environment variables. 
For example：
```
spring:
  datasource:
    url: jdbc:shardingsphere:classpath:application-sharding.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
```
application-sharding.yml:
```
dataSources:
  db0: 
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource 
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.schema-name:asoco_alarm_platform}?${spring.datasource.suffix} 
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
```
How these variables are overridden by environment variables is a big problem. How could I override such as `${spring.datasource.host}`?
