### ISSUE TITLE
Can we provide a DIstSQL to alter `authority rule` ?

### ISSUE THREAD

**Issue by wsm12138** [apache/shardingsphere#23137]
### Is your feature request related to a problem?
no
### Describe the feature you would like.
After `overwrite` in server.yaml had been removed.
This part can't be updated. Unless manually modify values in Zookeeper.

```
authority:
  privilege:
    type: ALL PERMITTED
  users:
  - password: root
    user: root@%
```
So can we provide a DistSQL to alter `authority rule` ?
