### ISSUE TITLE
The server version in Proxy is incorrect

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23166]
### Which version of ShardingSphere did you use?
master f2307320

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The server version in Proxy is correct

### Actual behavior
The version printed in the Proxy startup information is inconsistent with the version obtained by the client

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
1. Start Proxy with MySQL data sources, and MySQL version is 8.0.13
```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```
2. In startup information, the database version is `8.0.13`
```sql
o.a.s.p.v.ShardingSphereProxyVersion - Database name is `MySQL`, version is `8.0.13`, database name is `sharding_db`
```
3. Use a client to connect to Proxy, the welcome message show database type is `5.7.22`
```sql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.22-ShardingSphere-Proxy 5.3.1-SNAPSHOT-f230732 MySQL Community Server - GPL
```
4. Execute `select version();`, the result is also `5.7.22`
```
mysql> select version();
+----------------------------------------------------+
| version()                                          |
+----------------------------------------------------+
| 5.7.22-ShardingSphere-Proxy 5.3.1-SNAPSHOT-f230732 |
+----------------------------------------------------+
```
