### ISSUE TITLE
Some problems of the integration of shardingphere-jdbc-5.3.0 and springboot

### ISSUE THREAD

**Issue by pengxianggui** [apache/shardingsphere#23283]
> The official way to do it is: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/spring-boot/

This way of integrating springboot makes it difficult to overwrite environment variables. 
For example：
```
spring:
  datasource:
    url: jdbc:shardingsphere:classpath:application-sharding.yml
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
```
application-sharding.yml:
```
dataSources:
  db0: # 单数据库节点无意义，当存在多个时用于区分
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource # 数据库连接池全类名
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.schema-name:asoco_alarm_platform}?${spring.datasource.suffix} # 拼接的连接url, 无需变动
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
```
How these variables are overridden by environment variables is a problem.

**Comment by RaigorJiang** [comment]
Hi @pengxianggui 
There is currently no support for such a configuration, do you have any suggestions on how to achieve it?

**Comment by pengxianggui** [comment]
> Hi @pengxianggui There is currently no support for such a configuration, do you have any suggestions on how to achieve it?

There seems to be no better way, with or without container delivery, deployment now requires overrides of environment variables. The official recommended approach, while concise enough, creates headaches for deployment. I might give up on this and manually assemble (but I have no idea, just manually register a ShardingSphereDataSource is enough? I think it will take quite a while). Of course, I prefer to use traditional spring boot integration, such as the original shardingsphere-jdbc-core-spring-boot-starter.

似乎没有更好的办法了，无论是否容器交付，现在的部署都需要用到环境变量的覆盖。官方推荐的方法虽然足够简洁，但却给部署带来了麻烦。我可能会放弃这个，手动装配(但是我没有思路，只需要手动注册一个ShardingSphereDataSource就够了吗？我想这可能又会耽误不少时间)。当然，我更喜欢使用传统的spring引导集成，比如最初的shardingsphere-jdbc-core-spring-boot-starter, I miss it

**Comment by RaigorJiang** [comment]
Here is an example for Java API:
https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/java-api/rules/sharding/#sample

**Comment by Comven** [comment]
The use of spring-boot is becoming more and more complex, and the prompt disappears after canceling the starter. The configuration of each version is almost changed, and every release feels like it is configuring something new. I hope the community can be optimized later.

**Comment by linghengqian** [comment]
@pengxianggui 

- One possible idea is that we can change the existing process of reading YAML, and try to read environment variables once text in the format of `${}` such as `${SELF_JDBC_URL}` is detected.

- Even now, there is a less intuitive way of doing it.  Since shardingsphere-jdbc-core comes with SnakeYAML 1.33, you can pre-write a YAML file or Template file that contains a series of `${}`, and then use SnakeYAML to read and replace this part of `${}` with other self-  Environment variable values ​​read with functions, and then serialized into YAML files required by shardingsphere-jbdc-core.  The process I am talking about is somewhat similar to the way nginx's docker image reads environment variables, refer to https://hub.docker.com/_/nginx .

- I'm assuming you have another plan for submitting a PR.

**Comment by linghengqian** [comment]
> The use of spring-boot is becoming more and more complex, and the prompt disappears after canceling the starter. The configuration of each version is almost changed, and every release feels like it is configuring something new. I hope the community can be optimized later.

@Comven 

- We could consider implementing a Jetbrains IntelliJ plugin like https://twitter.com/Yuriy_Artamonov/status/1562521707319271429?s=19 .  Since the IntelliJ plugin has a considerable degree of freedom, we can even avoid the embarrassment that some configurations cannot be automatically prompted due to the limitations of Spring Boot's own mechanism like https://github.com/apache/shardingsphere/issues/13002.  

- Since Jetbrains IntelliJ is almost certainly written in Kotlin, and the corresponding test JDK is JDK17, this solution almost certainly needs to apply to the mailing list to create a new Git repository.  I'm assuming you want to do this.

**Comment by linghengqian** [comment]
- Feel free to test what https://shardingsphere.apache.org/document/current/cn/user-manual/shardingsphere-jdbc/yaml-config/jdbc-driver/known-implementation/ mentions.
```yaml
ds_1:
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  driverClassName: $${FIXTURE_DRIVER_CLASS_NAME::org.h2.Driver}
  jdbcUrl: $${FIXTURE_JDBC_URL::jdbc:h2:mem:foo_ds_do_not_use}
  username: $${FIXTURE_USERNAME::}
  password: $${FIXTURE_PASSWORD::}

```
