### ISSUE TITLE
Can't connect when delete zookeeper namespace with ShardingSphere-Proxy instance reload.

### ISSUE THREAD

**Issue by Byeongcheol-Kim** [apache/shardingsphere#23353]
## Bug Report

**For English only**, other languages will not accept.
```
Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!
```
### Which version of ShardingSphere did you use?

`shardingsphere-proxy 5.2.1`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

`ShardingSphere-Proxy`

### Expected behavior
```
[zk: localhost:2181(CONNECTED) 196] ls /order_ds07
[metadata, nodes, rules, sys_data, worker_id]
```
### Actual behavior
```
[zk: localhost:2181(CONNECTED) 174] ls /order_ds07
[metadata, rules]
```
In addition
When ordery applicaiton connect on proxy instance, we meet Access denied error. even we connect from instance local env.
`ERROR 1045 (28000): Access denied for user 'stg_ro'@'127.0.0.1' (using password: YES)`

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

We have 2 ShardingSphere-Proxy(ssp-1, ssp2) instances, and 3 Zookeeper instance. 
and set server.yaml like below 
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: order_ds07
      server-lists: staging-ssp-zk1.staging.in,staging-ssp-zk2.staging.in,staging-ssp-zk3.staging.in
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
  overwrite: true
ssp-1, ssp2
authority:
  users:
    - user: stg_ro
      password: xxxxxxxx
  privilege:
    type: ALL_PERMITTED
```
I tested the scenario of changing `dataSource` in the following procedure.

1. delete namespace on zookeeper cli 
    - deleteall /order_ds07

2. update `conf.yaml` on proxy instance and 2 ShardingSphere-Proxy instance restart 
    - /opt/shardingsphere-proxy/bin/stop.sh
    - /opt/shardingsphere-proxy/bin/start.sh 3306
3. And there are any node info on zookeeper
