### ISSUE TITLE
What configuration can be resolved to GlobalRuleConfiguration

### ISSUE THREAD

**Issue by pengbiaobeyond** [apache/shardingsphere#23500]
What configuration can be resolved to GlobalRuleConfiguration

**Comment by pengbiaobeyond** [comment]
<img width="866" alt="1673421737(1)" src="https://user-images.githubusercontent.com/46187883/211742751-714eaf3b-9837-41d3-b407-5ab86be4e868.png">

**Comment by RaigorJiang** [comment]
`GlobalRuleConfiguration` is an interface and all its implementations are contained in.

**Comment by pengbiaobeyond** [comment]
<img width="516" alt="1673435366(1)" src="https://user-images.githubusercontent.com/46187883/211791503-d44f06c5-db5b-4654-8ca7-6fd617d15bee.png">
<img width="555" alt="1673435393(1)" src="https://user-images.githubusercontent.com/46187883/211791611-3dc93613-3ad4-4a36-b2c2-da95e3694b88.png">

**Comment by pengbiaobeyond** [comment]
How to configure in sharding-jdbc-springboot

**Comment by RaigorJiang** [comment]
> How to configure in sharding-jdbc-springboot

The picture you posted is for yaml configuration, correct.

https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/transaction/

**Comment by pengbiaobeyond** [comment]
The document is the configuration of server.yaml，but I want the configuration of springboot yaml

**Comment by pengbiaobeyond** [comment]
I want to init the implement of GlobalRuleConfiguration, Please give me an example

**Comment by RaigorJiang** [comment]
> https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/transaction/

It's the document of ShardingSphere-JDBC, not for server.yaml of Proxy.

**Comment by pengbiaobeyond** [comment]
![image](https://user-images.githubusercontent.com/46187883/212023932-c73b1209-3590-4f86-9263-b2a92c776499.png)
![image](https://user-images.githubusercontent.com/46187883/212024038-fcb535ee-0042-4a09-aa05-8f9a010138b7.png)

**Comment by pengbiaobeyond** [comment]
这两种方式都不对，应该怎样配置
Neither of these two methods is correct. How to configure

**Comment by pengbiaobeyond** [comment]
![image](https://user-images.githubusercontent.com/46187883/212029738-b939c927-c8bc-4311-86d4-1ada0f8a0395.png)

**Comment by pengbiaobeyond** [comment]
This configuration is also wrong. The project cannot be started

**Comment by RaigorJiang** [comment]
Here is an example
```yaml
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    maxPoolSize: 10
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    maxPoolSize: 10
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_2?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    maxPoolSize: 10

rules:
- !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_$->{0..1}.t_order_$->{0..1}
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake_generator
      t_order_item:
        actualDataNodes: ds_$->{0..1}.t_order_item_$->{0..1}
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_item_inline
        keyGenerateStrategy:
          column: order_item_id
          keyGeneratorName: snowflake_generator
    bindingTables:
      - t_order,t_order_item
    broadcastTables:
      - t_address
    defaultDatabaseStrategy:
      standard:
        shardingColumn: user_id
        shardingAlgorithmName: database_inline

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${user_id % 2}
          
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order_$->{order_id % 2}
      t_order_item_inline:
        type: INLINE
        props:
          algorithm-expression: t_order_item_$->{order_id % 2}
    keyGenerators:
      snowflake_generator:
        type: SNOWFLAKE

- !TRANSACTION
  defaultType: XA
  providerType: Atomikos

props:
  sql-show: true
```
