### ISSUE TITLE
Lower case like operator execute error in PG when using encrypt.

### ISSUE THREAD

**Issue by tuichenchuxin** [apache/shardingsphere#23770]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
 master - 4dd1d436dca6af1ceec330d9587fee33e5abb1a4

### Actual behavior
```
rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
    like_encryptor:
      type: CHAR_DIGEST_LIKE
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          likeQueryColumn: user_like
          assistedQueryColumn: user_assisted
          encryptorName: aes_encryptor
          assistedQueryEncryptorName: aes_encryptor
          likeQueryEncryptorName: like_encryptor
        order_id:
          cipherColumn: order_cipher
          plainColumn: order_plain
          encryptorName: md5_encryptor
```

```
encrypt_db=> select * from t_encrypt;
 id | user_id |             order_id             | name
----+---------+----------------------------------+------
  2 | 2       | c81e728d9d4c2f636f067f89cc14862c | b
  1 | 1       |                                  | a
(2 rows)

encrypt_db=> select * from t_encrypt where user_id like '2';
 id | user_id | order_id | name
----+---------+----------+------
(0 rows)

```
