### ISSUE TITLE
The result of convert sharding table rule is incorrect

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#23823]
### Which version of ShardingSphere did you use?
master ae722dbf

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
The DistSQL obtained by convert yaml is correct

### Actual behavior
`CREATE SHARDING TABLE RULE` statement is incorrect when the table strategy is `none`.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
- test.yaml
```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_${0..1}.t_order
        databaseStrategy:
          complex:
            shardingColumns: order_id, user_id
            shardingAlgorithmName: complex_test
        tableStrategy:
          none:
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake
    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:
    
    shardingAlgorithms:
      complex_test:
        type: COMPLEX_INLINE
        props:
          algorithm-expression: ds_${(order_id + user_id) % 2}
    
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
          worker-id: 123
```

- DistSQL
```sql
CONVERT YAML CONFIGURATION FROM FILE '/xxx/test.yaml'
```

- Result
```sql
CREATE DATABASE sharding_db;
USE sharding_db;

REGISTER STORAGE UNIT ds_0 (
URL='jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true',
USER='root',
PASSWORD='123456',
PROPERTIES('minPoolSize'='1', 'connectionTimeoutMilliseconds'='30000', 'maxLifetimeMilliseconds'='1800000', 'idleTimeoutMilliseconds'='60000', 'maxPoolSize'='50')
), ds_1 (
URL='jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true',
USER='root',
PASSWORD='123456',
PROPERTIES('minPoolSize'='1', 'connectionTimeoutMilliseconds'='30000', 'maxLifetimeMilliseconds'='1800000', 'idleTimeoutMilliseconds'='60000', 'maxPoolSize'='50')
);

CREATE SHARDING TABLE RULE t_order (
DATANODES('ds_${0..1}.t_order'),
DATABASE_STRATEGY(TYPE='complex', SHARDING_COLUMNS=order_id, user_id, SHARDING_ALGORITHM(TYPE(NAME='complex_inline', PROPERTIES('algorithm-expression'='ds_${(order_id + user_id) % 2}')))),
,
KEY_GENERATE_STRATEGY(COLUMN=order_id, TYPE(NAME='snowflake', PROPERTIES('worker-id'='123')))
); 
```
