### ISSUE TITLE
Logic db can't use

### ISSUE THREAD

**Issue by koala775** [apache/shardingsphere#23840]
version: shardingsphere-proxy.5.2.1
phenomenon: Use the same zookeeper with two proxy，for example,the proxy ip is 192.168.1.1,192.168.1.2. After a period of time，the client can't connect the proxy 192.168.1.1 and the proxy have no any error logs,but can connect the proxy 192.168.1.2.When restart the proxy 192.168.1.1 ,clent can  connect the proxy 192.168.1.1.

**Comment by RaigorJiang** [comment]
@koala775 
Sorry, the information you provided is not helpful to investigate this issue, please follow the issue template to provide enough information.

**Comment by koala775** [comment]
There are two proxy with the same zk address,so the two proxy have the same config.But have a strange phenomenon,one proxy have the process,but client can't connect and have a 30s timeout exception.The other proxy can connect.

**Comment by koala775** [comment]
1.The proxy have no error logs
2.The client throw a exception:Connection is not avaliable,request timeout after 30000ms.
3.server.yml:
```
mode:
    type: Cluster
    repository:
    type: ZooKeeper
    props:
        namespace: proxy_mysql_cluster
        server-lists: ip1:2181,ip2:2181,ip3:2181
        retryIntervalmilliseconds: 5000
        timeToLiveSeconds: 60
        maxRetries: 29
        operationTimeoutMilliseconds: 20000
rules:
  - !AUTHORITY
     users:
        - root@%: root
        - sharding@:sharding
     provider:
        type: ALL_PERMITTED
  -!TRANSACTION
      defaultType: XA
      providerType: Atomikos
props:
    max-connections-size-per-query: 100
    kernel-executor-size: 2048 
    proxy-frontend-flush-threshold: 128 
    proxy-hint-enabled: false
    sql-show: true
    check-table-metadata-enabled: false
    proxy-backend-query-fetch-size: -1
    proxy-frontend-executor-size: 2048 
    proxy-backend-executor-suitable: OLTP
    proxy-frontend-max-connections: 0 
    proxy-backend-driver-type: JDBC
    proxy-mysgl-default-version: 8.0.9 
    proxy-default-port: 3307 
```
