### ISSUE TITLE
`None` sharding strategy type cannot be config by yaml

### ISSUE THREAD

**Issue by Qianyi951015** [apache/shardingsphere#24074]
### Which version of ShardingSphere did you use?
master 7847cd42019044901b996fde8e49ec0bb9f4e306
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
proxy
### Expected behavior
`None` sharding strategy type can be config by yaml correctly
### Actual behavior
`None` sharding strategy type cannot be config by yaml

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
- prepare a yaml file with `None` sharding strategy type
![77901675916549_ pic](https://user-images.githubusercontent.com/57847965/217757017-c300c9ff-a046-40fb-8b4b-0b1443d78ea6.jpg)
- run Proxy with the yaml file, then you can see that the `None` sharding strategy type was not stored in ZK
![77891675916549_ pic](https://user-images.githubusercontent.com/57847965/217757564-94a21f4e-e325-4b24-aaa6-c3bd93273401.jpg)

**Comment by sandynz** [comment]
Hi @Qianyi951015 , could you supply the text of sharding yaml file?

**Comment by Qianyi951015** [comment]
> Hi @Qianyi951015 , could you supply the text of sharding yaml file?

sure,
```
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/db0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/db1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      databaseStrategy:
        none:
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
      auditStrategy:
        auditorNames:
          - sharding_key_required_auditor
        allowHintDisable: true
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
  defaultAuditStrategy:
    auditorNames:
      - sharding_key_required_auditor
    allowHintDisable: true

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE

  auditors:
    sharding_key_required_auditor:
      type: DML_SHARDING_CONDITIONS
```
