### ISSUE TITLE
rules.tables,What about too many tables

### ISSUE THREAD

**Issue by zhoubin7** [apache/shardingsphere#24115]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.
shardingsphere: 5.3.0
mysql: 8.0
```
dataSources:
  ds_jnmt:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds_jnmt
    username: root
    password: root
  ds_jnmt_ymlj:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds_jnmt_ymlj
    username: root
    password: root

rules:
- !SHARDING
  tables:
    sys_user:
      actualDataNodes: ds_${['jnmt','jnmt_ymlj']}.sys_user
    sys_dept:
        actualDataNodes: ds_${['jnmt','jnmt_ymlj']}.sys_dept
    sys_role:
        actualDataNodes: ds_${['jnmt','jnmt_ymlj']}.sys_role
    sys_user_role:
        actualDataNodes: ds_${['jnmt','jnmt_ymlj']}.sys_user_role
  bindingTables:
    - t_orders,t_order_item
  broadcastTables:
    - sys_tenant
    - qrtz_blob_triggers
    - qrtz_calendars
    - qrtz_cron_triggers
    - qrtz_fired_triggers
    - qrtz_job_details
    - qrtz_locks
    - qrtz_paused_trigger_grps
    - qrtz_scheduler_state
    - qrtz_simple_triggers
    - qrtz_simprop_triggers
    - qrtz_triggers
  defaultDatabaseStrategy:
    standard:
      shardingColumn: tenant_id
      shardingAlgorithmName: database-inline
  defaultTableStrategy:
    none:
  defaultShardingColumn: tenant_id

  shardingAlgorithms:
    database-inline:
      type: CLASS_BASED
      props:
        strategy: STANDARD
        algorithmClassName: com.my.DatabasePreciseShardingAlgorithm

  keyGenerators:
      snowflake:
          type: SNOWFLAKE
props:
  sql-show: true
  sql-simple: true

```
I have over 200 shard tables. Do I have to configure them here? It's too low level
