### ISSUE TITLE
Authentication method does not match the Authority rule configuration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#24155]
### Which version of ShardingSphere did you use?
master c236c86d

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Use user-level `authenticationMethodName` for authentication

### Actual behavior
Only `defaultAuthenticator` can be used

### Reason analyze (If you can)
Take the MySQL protocol as an example:
In `MySQLAuthenticationEngine`, when calling `AuthenticatorFactory.newInstance`, the new `ShardingSphereUser` is always passed in. Compared with the configuration in AuthorityRule, this object lacks `authenticationMethodName`.

<img width="1659" alt="image" src="https://user-images.githubusercontent.com/5668787/218666585-113e4c89-57bc-47b4-a748-d6eac1172dd4.png">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
- server.yaml
```yaml
authority:
  users:
    - user: root@%
      password: root
      authenticationMethodName: native
    - user: sharding
      password: sharding
  authenticators:
    native:
      type: NATIVE
    clear_text:
      type: CLEAR_TEXT
  defaultAuthenticator: clear_text
```
- login
When logged in as root, the client is required to interact with `CLEAR_TEXT`
