### ISSUE TITLE
Content error in Shadow algorithm configuration Document

### ISSUE THREAD

**Issue by xybert** [apache/shardingsphere#24191]
## Bug Report

In the YAML Configuration of the User Manual, the shadow algorithm configuration([link](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/algorithm/#shadow-db)) is wrong, loadBalancers should be changed to shadowAlgorithms.
The Chinese document also has the same error.

### Which version of ShardingSphere did you use?

Latest

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

```yaml
shadowAlgorithms:
  # shadowAlgorithmName is specified by users, and its property has to be consistent with that of shadowAlgorithmNames in shadow DB rules.
  <shadowAlgorithmName>:
    # type and props, please refer to the built-in shadow DB algorithm: https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/shadow/
    type: xxx
    props:
      xxx: xxx
```

### Actual behavior

![image](https://user-images.githubusercontent.com/44190260/219299267-caaf8d46-58ec-44f2-8e36-e9392379bb98.png)

```yaml
loadBalancers:
  # shadowAlgorithmName is specified by users, and its property has to be consistent with that of shadowAlgorithmNames in shadow DB rules.
  <shadowAlgorithmName>:
    # type and props, please refer to the built-in shadow DB algorithm: https://shardingsphere.apache.org/document/current/en/user-manual/common-config/builtin-algorithm/shadow/
    type: xxx
    props:
      xxx: xxx
```

### Reason analyze (If you can)

Typing error

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Check out : [link](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/algorithm/#shadow-db)
