### ISSUE TITLE
Implement more authenticator types for MySQL and PostgreSQL

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#24322]
Hi community,

Now Proxy already supports specifying different password authentication methods for users, which provides users with more choices.

We have implemented:
- [MySQL](https://github.com/apache/shardingsphere/blob/master/proxy/frontend/type/mysql/src/main/java/org/apache/shardingsphere/proxy/frontend/mysql/authentication/authenticator/MySQLAuthenticatorType.java)
  - mysql_native_password
  - mysql_clear_password
  - caching_sha2_password
- [PostgreSQL](https://github.com/apache/shardingsphere/blob/master/proxy/frontend/type/postgresql/src/main/java/org/apache/shardingsphere/proxy/frontend/postgresql/authentication/authenticator/PostgreSQLAuthenticatorType.java)
  - md5
  - password
- [openGauss](https://github.com/apache/shardingsphere/blob/master/proxy/frontend/type/opengauss/src/main/java/org/apache/shardingsphere/proxy/frontend/opengauss/authentication/authenticator/OpenGaussAuthenticatorType.java)
  - md5
  - scram-sha-256

Now, there are still the following to be added, and everyone is welcome to participate:
- MySQL
  - [ ] mysql_old_password
  - [ ] authentication_windows_client
- PostgreSQL
  - [ ] scram-sha-256

The configuration in #24313 can be used as a reference:
```yaml
authority:
  users:
    - user: root@%
      password: root
      authenticationMethodName: md5
    - user: sharding
      password: sharding
  authenticators:
    md5:
      type: MD5

props:
  proxy-frontend-database-protocol-type: openGauss
```

### Refenence
- [MySQL Authentication Plugins](https://dev.mysql.com/doc/refman/8.0/en/authentication-plugins.html)
- [Protocol of MySQL Authentication Methods](https://dev.mysql.com/doc/dev/mysql-server/latest/page_protocol_connection_phase_authentication_methods.html)
- [PostgreSQL Password Authentication](https://www.postgresql.org/docs/15/auth-password.html)
