### ISSUE TITLE
How can I improve the performance of proxy?

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#24369]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Recently，I'm using sysbench testing shardingsphere-proxy，maxscale，and dble，I would like to compare the read/write splitting performance between several products。

Now, I used 3  8C 16G machines to form mysql 1 master and 2 slaves。

Then，I use syebench oltp_read_write to test.

this is sysbench run code:
```
sysbench oltp_read_write  --mysql-user=root --mysql-password=root --mysql-host=sharding-ip --mysql-port=3307 --mysql-db=s1_sbtest --histogram=on --report-interval=1 --time=300  --db-ps-mode=disable  --threads=300 --tables=250 --table_size=25000  --report-interval=1 --percentile=95 --skip-trx=on --mysql-ignore-errors=1062  --forced-shutdown=1 run
```

When I use sysbench to directly press mysql，tps is 2250 per sec. 
When I use sysbench to directly press shardingsphere-proxy, tps is only 2300 per sec.
But when I use sysbench directly press dble/maxscale， tps have 2600 per sec.

Now, shardingsphere-proxy is 16C16G,  dble is 8C8G, maxscale is 4C4G.

I compared and found that the network traffic of the shardingsphere-proxy can only run to 750M。
dble and maxscale can run to 900M。

so， I use arthas run profile，sharding1.html is first run shardingsphere-proxy‘s resutl. sharding-2.html is I change server.yaml proxy-frontend-executor-size to 500 result

[sharding.zip](https://github.com/apache/shardingsphere/files/10846434/sharding.zip)

Now, I don't know how to improve the performance, plase help me

**Comment by FlyingZC** [comment]
@TeslaCN Hi, please have a look.

**Comment by TeslaCN** [comment]
Please remove the `--db-ps-mode=disable`.

**Comment by dobet** [comment]
> 
I remove the --db-ps-mode, but the tps was not improve

**Comment by TeslaCN** [comment]
Could you try using MySQL JDBC Driver 5.1.49 instead of 8.x?

**Comment by dobet** [comment]
> 

I use mysql jdbc driver 5.1.49 instead of 8.x , the result is still the same.
And I change the cpu-cores to 24 cores, now cpu used 40%, but also run 750M

**Comment by dobet** [comment]
This is my config

server.yaml:
```
sqlParser:
  sqlCommentParseEnabled: false
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

props:
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  proxy-hint-enabled: false
  sql-show: false
  check-table-metadata-enabled: false
    # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
    # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  proxy-frontend-executor-size: 1000 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
    # Available options of proxy backend executor suitable: OLAP(default), OLTP. The OLTP option may reduce time cost of writing packets to client, but it may increase the latency of SQL execution
    # and block other clients if client connections are more than `proxy-frontend-executor-size`, especially executing slow SQL.
  proxy-backend-executor-suitable: OLTP
  proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
    # Available sql federation type: NONE (default), ORIGINAL, ADVANCED
  sql-federation-type: NONE
  proxy-mysql-default-version: 5.7.30 # In the absence of schema name, the default version will be used.
  proxy-default-port: 3307 # Proxy default port.
  proxy-netty-backlog: 1024 # Proxy netty backlog.
```

other config is defalut in server.yaml


and, I use distsql to create readwrite_splitting rules
```
1. create database s1_sbtest;
2. use s1_sbtest;
3. register storage unit write_ds ( URL="jdbc:mysql://master_ip:3306/sbtest?useSSL=false&useUnicode=true&characterEncoding=UTF-8", USER="root", PASSWORD=password, PROPERTIES("maxPoolSize"=600, "minPoolSize"=600));
4. register storage unit read_ds_1 ( URL="jdbc:mysql://slave1ip:3306/sbtest?useSSL=false&useUnicode=true&characterEncoding=UTF-8", USER="root", PASSWORD=password, PROPERTIES("maxPoolSize"=600, "minPoolSize"=600));
5. register storage unit read_ds_2 ( URL="jdbc:mysql://slave2ip:3306/sbtest?useSSL=false&useUnicode=true&characterEncoding=UTF-8", USER="root", PASSWORD=password, PROPERTIES("maxPoolSize"=600, "minPoolSize"=600));
6. create readwrite_splitting rule group_0 ( write_storage_unit=write_ds, read_storage_units(read_ds_1, read_ds_2), type(name="random") );
```

I don't change other config.

No, 16 cpu-cores used 70%， how to reduce ？
 
Place give me some suggest。 tks
