### ISSUE TITLE
Index `user_id_idx` does not exist occurs when execute `DROP INDEX user_id_idx ON t_order;`

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#24516]
### Which version of ShardingSphere did you use?

[9e4ed51](https://github.com/apache/shardingsphere/commit/9e4ed51f9bf31ed61e4f7ec33b03931068809aec)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Execute `DROP INDEX user_id_idx ON t_order;` successfully.

### Actual behavior

```
ERROR 20008 (42S02): Index `user_id_idx` does not exist.
mysql> DROP INDEX user_id_idx ON t_order;
ERROR 20008 (42S02): Index `user_id_idx` does not exist.
mysql>
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_0.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    user_id_idx_inline:
      type: INLINE
      props:
        algorithm-expression: user_id_idx_${user_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```

And then execute following sqls:

```sql
CREATE TABLE `t_order` (
  `order_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `user_id` int(10) DEFAULT NULL,
  `status` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE INDEX user_id_idx ON t_order(user_id, order_id);

DROP INDEX user_id_idx ON t_order;
```
