### ISSUE TITLE
how can i refresh the DataNodes when i add a new dataSources

### ISSUE THREAD

**Issue by zigaai** [apache/shardingsphere#24562]
## Question

**For English only**, other languages will not accept.

1. i find the solution in 5.1.0 version [how to config actual-data-nodes while my actual-data-nodes tables is dynamic](https://github.com/apache/shardingsphere/issues/16725)
but in 5.3.1 version, AlgorithmProvidedShardingRuleConfiguration is not found, can i refresh the datanodes in shardingjdbc interface without sharding-proxy?

2. when i want to sharding database only, it not work, i see the code, when i dont config the rules.tables, it return the ShardingIgnoreRoutingEngine; i want to config the defaultDatabaseStrategy then can make all tables invoke this DatabaseStrategy, how can i config it?

**Comment by RaigorJiang** [comment]
1. JDBC does not provide an API for dynamically modifying rules. Currently, using JDBC + Proxy DistSQL is the only official way. In the future, JDBC may also support DistSQL.
2. Even if you use DatabaseStrategy only, you need to declare which tables are sharding tables in the sharding rule. The following method is feasible:
```yaml
rules:
- !SHARDING
   tables: # list sharding tables
     table_a:
       actualDataNodes: xxx
     table_b:
       actualDataNodes: xxx
     table_c:
       actualDataNodes: xxx
   #...
   defaultDatabaseStrategy:
     standard:
       shardingColumn: order_id
       shardingAlgorithmName: database_inline
   defaultTableStrategy:
     none:
   shardingAlgorithms:
     database_inline:
       type: INLINE
       props:
         algorithm-expression: xxx
```
