### ISSUE TITLE
Authenticator has a bug maybe.

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#24592]
### Which version of ShardingSphere did you use?

master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Reason analyze (If you can)
AuthenticatorFactory.getAuthenticatorType caught an exception but was ignored

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
server.yaml like following:
```
authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED
```
try to connect to the proxy:
<img width="926" alt="image" src="https://user-images.githubusercontent.com/76552510/224950045-d0d3cf2f-6a5a-42b7-9091-1c00800f49a9.png">

got exception:
![image](https://user-images.githubusercontent.com/76552510/224950253-4729862a-f588-4923-904e-8085b997fef6.png)

```
java.lang.invoke.LambdaConversionException: Invalid receiver type class java.lang.Enum; not a subtype of implementation type interface org.apache.shardingsphere.proxy.frontend.authentication.AuthenticatorType
```

I will try to analyze the cause and if I find a fix, I will propose pr
