### ISSUE TITLE
Merge sharding cache rule into sharding rule

### ISSUE THREAD

**Issue by TeslaCN** [apache/shardingsphere#24778]
## Refactor

Related to #24363.

Sharding cache rule is an plugin for sharding rule. But sharding cache rule could not be used without sharding rule. I'm going to merge it into sharding rule.

Before:
```yaml
rules:
  - !SHARDING_CACHE
    allowedMaxSqlLength: 512
    routeCache:
      initialCapacity: 65536
      maximumSize: 262144
      softValues: true
```

After:
```yaml
rules:
  - !SHARDING
    tables:
    shardingAlgorithms:
    # ...
    shardingCache:
      allowedMaxSqlLength: 512
      routeCache:
        initialCapacity: 65536
        maximumSize: 262144
        softValues: true
```
