### ISSUE TITLE
refactor the E2E-SQL to combine different rules in one matrix

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#24872]
there are 4 process in E2E-SQL
  - build-image
  - e2e-empty-rule
  - e2e-single-rule
  - e2e-mixture-rule

besides the build-image job, the rest are maily same, just execute different scenario.
the original design of separating the E2E-SQL to 3 parts because of the matrix contains too much scenario, this will touch the limitation of matrix.

however, the github action provide the `max-parallel` usage for matrix to limit the max parallel job:

```yaml
jobs:
  example_matrix:
    strategy:
      max-parallel: 2
      matrix:
        version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
```

so refactor the E2E-SQL by max-parallel .
