### ISSUE TITLE
Read-Write  loadbalancer not right

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#24922]
##  function description
```
one master 
   write
three slaves  
 read_0
 read_1
 read_2

springboot2.3.12+sharding5.3.1+spring-data-jpa
```

## version 5.3.1 
```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.3.1</version>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>1.33</version>
        </dependency>
    </dependencies>
```

## yaml config 
```yaml
dataSources:
  write:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.164:3306/db_brand?serverTimezone=UTC
    username: root
    password: rootroot
  read_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.164:3307/db_brand?serverTimezone=UTC
    username: root
    password: rootroot
  read_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.164:3308/db_brand?serverTimezone=UTC
    username: root
    password: rootroot
  read_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.164:3309/db_brand?serverTimezone=UTC
    username: root
    password: rootroot
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds: 
      staticStrategy: 
        writeDataSourceName: write 
        readDataSourceNames:  
         - read_0
         - read_1
         - read_2
      loadBalancerName: random
  loadBalancers:
    random: 
      type: ROUND_ROBIN  

```

## application.yml
```yaml
server:
  port: 8888
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:aaa.yaml
```

## controller
![image](https://user-images.githubusercontent.com/24687986/229076488-394b9068-1602-4bc3-88bf-8931b19ef566.png)

## question 
```
setting the rule is  ROUND_ROBIN  and   method in controller  not  In transactional  Every query is the master   not  is slave why?
```
