### ISSUE TITLE
When the rule has dependencies, there is a verification exception in the imported database configuration

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#24974]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

Proxy

### Expected behavior

Imported successfully

### Actual behavior

config.yaml

```YAML
databaseName: sharding_db
dataSources:
  ds_0:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test
  ds_1:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test
rules:
- !SHARDING
  autoTables:
    t_user:
      actualDataSources: group_user
      keyGenerateStrategy:
        column: id
        keyGeneratorName: user_snowflake
      shardingStrategy:
        standard:
          shardingAlgorithmName: user_hash_mod
          shardingColumn: userid
  keyGenerators:
    user_snowflake:
      type: snowflake
  shardingAlgorithms:
    user_hash_mod:
      type: hash_mod
      props:
        sharding-count: '512'
      
- !READWRITE_SPLITTING
  dataSources:
    group_user:
      loadBalancerName: group_user_random
      staticStrategy:
        readDataSourceNames:
        - ds_0
        writeDataSourceName: ds_1
  loadBalancers:
    group_user_random:
      type: random

```

```
IMPORT DATABASE CONFIGURATION FROM FILE '/xxx/config.yaml';
```
Finally, it will prompt that the `group_user` data source is invalid.
