### ISSUE TITLE
Consider refactor readwrite-splitting configuration

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#25002]
Hi community,

  Now,  we are consider simplify `readwrite-splitting` api, because because we removed `db-discovery` feature not long ago, you can refer to #24486 So, we don't need to `staticStrategy` anymore.

Before adjustment :

```
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      staticStrategy:
        writeDataSourceName: primary_ds
        readDataSourceNames:
          - replica_ds_0
          - replica_ds_1
      loadBalancerName: random
  loadBalancers:
    random:
      type: RANDOM
```

After adjustment:

```
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      writeDataSourceName: primary_ds
      readDataSourceNames:
          - replica_ds_0
          - replica_ds_1
    loadBalancerName: random
  loadBalancers:
    random:
      type: RANDOM
```
.
