### ISSUE TITLE
Shardingsphere does not support foreign table syntax for openGauss

### ISSUE THREAD

**Issue by congzhou2603** [apache/shardingsphere#25103]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere: commit id : e874093e16e4a7779ef1b2bdc3b98297196289d8
openGauss: 5.0.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
Create foreigin table successfully.
### Actual behavior
![image](https://user-images.githubusercontent.com/27768675/231090154-7ee53e88-c5ca-4a32-9294-1652bce8d4a5.png)

### Reason analyze (If you can)
This syntax is not supported.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sql: 
```sql
create foreign table t_order (user_id int, order_name varchar(30));
```
config-sharding.yaml:
```yaml
dataSources:
  ds_0:
    connectionTimeoutMilliseconds: 3600000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 410
    minPoolSize: 400
    password: XXX
    url: jdbc:opengauss://XXX:XXX/tpccdb?serverTimezone=UTC&useSSL=false&connectTimeout=60&batchMode=on&loggerLevel=OFF
    username: tpccuser
  ds_1:
    connectionTimeoutMilliseconds: 3600000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 410
    minPoolSize: 400
    password: XXX
    url: jdbc:opengauss://XXX:XXX/tpccdb?serverTimezone=UTC&useSSL=false&connectTimeout=60&batchMode=on&loggerLevel=OFF
    username: tpccuser
```
### Example codes for reproduce this issue (such as a github link).
