### ISSUE TITLE
Cannot create property=rules for JavaBean=org.apache.shardingsphere.infra.yaml.config.pojo.YamlRootConfiguration@2c8f294

### ISSUE THREAD

**Issue by lefthand250** [apache/shardingsphere#25191]
Hi, I have some question about ShardingSphere-JDBC
this is my dependency

```
<dependency>
	    <groupId>org.apache.shardingsphere</groupId>
	    <artifactId>shardingsphere-jdbc-core</artifactId>
	    <version>5.3.0</version>
	    
	</dependency>
	<!-- DataSource pool -->
	<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>druid</artifactId>
        <version>1.1.23</version>
    </dependency>
    <!-- Overriding spring-start-web managed version 1.17 for snakeyaml-->
	<dependency>
        <groupId>org.yaml</groupId>
        <artifactId>snakeyaml</artifactId>
        <version>1.33</version>
    </dependency>

```

this is my application.yml
```
spring:
  application:
    name: hos-inventory
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:datasource.yml
```

this is my datasource.yml
```
databaseName: master
mode:
  type: Standalone
  repository:
    type: JDBC
dataSources:
  master:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: xxxx
    username: xxxx
    password: xxxx
rules:
- !SHARDING
  tables:
    hos_receipt:
      actualDataNodes: master.hos_receipt${0..1}
      tableStrategy:
        inline:
          shardingColumn: id
          algorithmExpression: hos_receipt${id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: id
    hos_receipt_detail:
      actualDataNodes: master.hos_receipt_detail${0..1}
      tableStrategy:
        inline:
          shardingColumn: fk_receipt_id
          algorithmExpression: hos_receipt_detail${fk_receipt_id % 2}
  bindingTables:
    - hos_receipt,hos_receipt_detail
  defaultDataSourceName: master
  defaultTableStrategy:
    none:
  defaultKeyGenerator:
    type: SNOWFLAKE
    column: id
props:
  sql.show: true

```
this is my logs

Cannot create property=rules for JavaBean=org.apache.shardingsphere.infra.yaml.config.pojo.YamlRootConfiguration@2c8f294
 in 'reader', line 1, column 1:
    databaseName: master
    ^
Cannot create property=tables for JavaBean=org.apache.shardingsphere.sharding.yaml.config.YamlShardingRuleConfiguration@20cdc1ca
 in 'reader', line 14, column 3:
    - !SHARDING
      ^
Cannot create property=tableStrategy for JavaBean=org.apache.shardingsphere.sharding.yaml.config.rule.YamlTableRuleConfiguration@7f1a2307
 in 'reader', line 17, column 7:
          actualDataNodes: master.hos_rece ... 
          ^
Cannot create property=inline for JavaBean=org.apache.shardingsphere.sharding.yaml.config.strategy.sharding.YamlShardingStrategyConfiguration@63d2d419
 in 'reader', line 19, column 9:
            inline:
            ^
Unable to find property 'inline' on class: org.apache.shardingsphere.sharding.yaml.config.strategy.sharding.YamlShardingStrategyConfiguration
 in 'reader', line 20, column 11:
              shardingColumn: id
              ^

 in 'reader', line 19, column 9:
            inline:
            ^

 in 'reader', line 16, column 5:
        hos_receipt:
        ^

 in 'reader', line 14, column 1:
    - !SHARDING
    ^

I don't know where is wrong.
Can you please help me figure it out. I would be really grateful.

**Comment by TeslaCN** [comment]
It seems that your format is incorrect. Here is an example of my configuration.

```yaml
rules:
- !SHARDING
  tables:
    t_order_item:
      actualDataNodes: ds.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline

  shardingAlgorithms:
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}
```
