### ISSUE TITLE
dynamic-readwrite-split is not right 

### ISSUE THREAD

**Issue by liruhui** [apache/shardingsphere#25204]
```
mysql:  one master  three slave  

datasourcediscovery+dynamic-readwrite-split

shardingsphere-jdbc 5.3.1 
````

## 1. yaml-config 
```yaml

dataSources:
  write:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.122:3306/aaa?serverTimezone=UTC
    username: root
    password: 11111
  read_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.122:3307/aaa?serverTimezone=UTC
    username: root
    password: 11111
  read_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.122:3308/aaa?serverTimezone=UTC
    username: root
    password: 11111
  read_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://192.168.191.122:3309/aaa?serverTimezone=UTC
    username: root
    password: 11111


rules:
- !READWRITE_SPLITTING
  dataSources:
    abc:
      dynamicStrategy:
        autoAwareDataSourceName: xyz
      loadBalancerName: balancer
  loadBalancers:
    balancer:
      type: ROUND_ROBIN
- !DB_DISCOVERY
  dataSources:
    xyz:
      dataSourceNames:
        - write
        - read_0
        - read_1
        - read_2
      discoveryHeartbeatName: myBeart
      discoveryTypeName: myType
  discoveryHeartbeats:
    myBeart:
      props:
        keep-alive-cron: '0/5 * * * * ?'
  discoveryTypes:
    myType:
      type: MySQL.NORMAL_REPLICATION
      props:
        delay-milliseconds-threshold: 3000

````

## 2: problem description
```
When the slave machine is down, it will also query the down slave machine. 

```

## 3. Official document
![image](https://user-images.githubusercontent.com/24687986/232663508-2dd30be2-eb3d-4118-bfec-5c21b2608a42.png)
