### ISSUE TITLE
Sharding feature can not pass through null sharding condition to sharding algorithm

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#25208]
### Which version of ShardingSphere did you use?

[6295a07](https://github.com/apache/shardingsphere/commit/6295a0723b65d23a4e8e2123fd6623d2898744b2)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

When I execute `INSERT INTO t_order(status, merchant_id, remark, creation_date) VALUES('NOT OK', 21, NOW());`, sharding feature can pass through null sharding condition to sharding algorithm, then I can handle null value to special datasource.

### Actual behavior

```sql
mysql> INSERT INTO t_order(status, merchant_id, remark, creation_date) VALUES('NOT OK', 21, NOW());
ERROR 20087 (44000): Please check your sharding conditions `ShardingConditions(conditions=[ShardingCondition(values=[], startIndex=0)], sqlStatementContext=org.apache.shardingsphere.infra.binder.statement.dml.InsertStatementContext@7021ede5, rule=org.apache.shardingsphere.sharding.rule.ShardingRule@3e359b56, subqueryContainsShardingCondition=true)` to avoid same record in table `t_order` routing to multiple data nodes.
mysql>
```

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:

  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}
```

Then execute following sqls:

```sql
CREATE TABLE `t_order` (
  `order_id` bigint(20) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` varchar(50) NOT NULL,
  `merchant_id` int(11) NOT NULL,
  `remark` varchar(50) NOT NULL,
  `creation_date` date NOT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT INTO t_order(status, merchant_id, remark, creation_date) VALUES('NOT OK', 21, NOW());
```
