### ISSUE TITLE
Inline sharding algorithms expression `%s` and sharding column `%s` do not match.

### ISSUE THREAD

**Issue by Soora33** [apache/shardingsphere#25425]
Why can't we query by id when using id as the sharding column? Similarly, when I switch to age as the sharding column, age cannot be used as the query condition either. Here is my configuration.

```
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/sora33?serverTimezone=UTC
        username: root
        password: root
    rules:
      sharding:
        tables:
          user:
            actual-data-nodes: ds0.sora_user0$->{1..2}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: user-inline
        sharding-algorithms:
          user-inline:
            type: INLINE
            props:
              algorithm-expression: sora_user0$->{id % 2 + 1}
        keyGenerators:
          snowflake:
            type: SNOWFLAKE
        props:
          sql-show: true
```
