### ISSUE TITLE
Consider refactoring the encryption API to reduce the cost of understanding

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#25521]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Currently, the encrypt feature includes a lot of column configurations in the column property, making it difficult for users to understand them. 

To reduce user understanding costs, we expect to be able to categorize by column type, and the latest API is shown below. `cipher` is used to configure the encryption columns and encryption algorithms, `assistedQuery` is used to configure the assisted query columns and algorithms, and likeQuery is used to configure the like query columns and algorithms.

```yaml
rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    char_digest_like_encryptor:
      type: CHAR_DIGEST_LIKE
      props:
        delta: 2
    md5_assisted_encryptor:
      type: MD5_ASSISTED
      props:
        salt: 121212
    
  tables:
    t_encrypt:
      columns:
        user_id:
          cipher:
            name: user_cipher
            encryptorName: aes_encryptor
          assistedQuery:
            name: user_cipher
            encryptorName: char_digest_like_encryptor
          likeQuery:
            name: user_cipher
            encryptorName: md5_assisted_encryptor
```

To ensure compatibility, we also retain compatibility with older versions of the API, configured via the `COMPATIBLE_ENCRYPT` tag.

```yaml
rules:
- !COMPATIBLE_ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptorName: aes_encryptor
        order_id:
          cipherColumn: order_cipher
          encryptorName: md5_encryptor
```
