### ISSUE TITLE
select last_insert_in() is not work

### ISSUE THREAD

**Issue by bigno-feng** [apache/shardingsphere#25679]
version: 5.3.2

![image](https://github.com/apache/shardingsphere/assets/37724987/cb74c127-f04d-48b8-825c-e7210f3e9950)
![image](https://github.com/apache/shardingsphere/assets/37724987/fb4f5e04-c388-41a1-b3e7-6741d3bc0f9e)

**Comment by FlyingZC** [comment]
@bigno-feng Hi, please check your configuration.I tested that the following configuration can be executed normally in version 5.3.2.
You can debug the method of `org.apache.shardingsphere.readwritesplitting.route.impl.ReadwriteSplittingDataSourceRouter#route`.
```yaml
databaseName: readwrite_splitting_db
  
dataSources:
  write_ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_write_ds?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    autoCommit: true
  read_ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_read_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    autoCommit: true
  read_ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_read_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    autoCommit: true

rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        staticStrategy:
          writeDataSourceName: write_ds
          readDataSourceNames:
            - read_ds_0
            - read_ds_1
        loadBalancerName: random
    loadBalancers:
      random:
        type: RANDOM
        props:
          transaction-read-query-strategy: FIXED_PRIMARY
      weight_lb:
        type: WEIGHT
        props:
          read_ds_0: 1
          read_ds_1: 1

```
