### ISSUE TITLE
\d throws parse error in the new logic database when proxy-frontend-database-protocol-type is not configured

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#25734]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
master d7b5bf6064a1de136186db8f7f0be507cdef67c3

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy with PostgreSQL

### Expected behavior
execute
```sql
create database test;

\c test 

\d
```
echo Did not find any relations.

### Actual behavior
<img width="825" alt="image" src="https://github.com/apache/shardingsphere/assets/37339007/1d115804-a669-4e45-993f-5bad3d791d52">

After I add config
```yaml
props:
  proxy-frontend-database-protocol-type: PostgreSQL
```
The error did not recur

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/demo_ds
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```
