### ISSUE TITLE
I can specify the data source through sql, right?

### ISSUE THREAD

**Issue by a1424132610** [apache/shardingsphere#25785]
Since there are many tables in the database, I am now divided into two libraries. If I do not configure the logical table, can I specify the name of the data source when querying the table in sql? For example, the following sql：

```yaml
dataSources:
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123456
  ds2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 123456
```

```sql
select * from ds1.user
```
