### ISSUE TITLE
[DistSQL] Support `transactionalReadQueryStrategy` in READWRITE_SPLITTING

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#25871]
For  #25744, #24804

Add `transactionalReadQueryStrategy` for DistSQL in READWRITE_SPLITTING

``` yaml
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      writeDataSourceName: write_ds
      readDataSourceNames:
        - read_ds_0
        - read_ds_1
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: random
  loadBalancers:
    random:
      type: RANDOM
```

YAML doc: https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/readwrite-splitting/

### Tasks
- [x] Update RDL
- [x] Update RQL
- [x] Update documents
- [x] Add test cases
