### ISSUE TITLE
The style of JDBC's global rule should be consistent with Proxy

### ISSUE THREAD

**Issue by Pace2Car** [apache/shardingsphere#25883]
Hi community,

Now the global rule configuration styles of Proxy and JDBC are not unified.
The configuration of Proxy is like this
```yaml
transaction:
  defaultType: LOCAL

sqlParser:
  sqlCommentParseEnabled: false
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

authority:
  users:
    - user: root@%
      password: roott
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED

logging:
  loggers:
  - loggerName: ShardingSphere-SQL
    additivity: true
    level: INFO
    props:
      enable: false

globalClock:
  enabled: false
  type: TSO
  provider: local

sqlTranslator:
  type: NATIVE
  useOriginalSQLWhenTranslatingFailed: false
```
The configuration of JDBC is like this
```yaml
rules:
- !AUTHORITY
  privilege:
    type: ALL_PERMITTED
  users:
  - password: root
    user: root@%
  - password: sharding
    user: sharding@%
- !TRANSACTION
  defaultType: LOCAL
- !SQL_PARSER
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024
  sqlCommentParseEnabled: false
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
- !SQL_TRANSLATOR
  type: NATIVE
  useOriginalSQLWhenTranslatingFailed: false
- !GLOBAL_CLOCK
  enabled: false
  provider: local
  type: TSO
- !LOGGING
  loggers:
  - additivity: true
    level: INFO
    loggerName: ShardingSphere-SQL
    props:
      enable: false
```

I recommend using the Proxy style uniformly.
