### ISSUE TITLE
Consider removing the ORIGINAL executor and refactoring the sql federation module

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26011]
### Is your feature request related to a problem?

No.

### Describe the feature you would like.

At present, the functions of the ADVANCED execution engine have been gradually improved, and there are basically no users using ORIGINAL, so it can be deleted.

In addition, after deleting the ORIGINAL executor, we can re-optimize the package structure of the sql federation module, remove useless optimizers and executors, and move them to the core module.

Following is the new module structure.

![image](https://github.com/apache/shardingsphere/assets/10829171/dbc0da08-ffe4-4ae3-a7c2-2b1e560c714e)

In addition, in order to simplify user configuration, we will remove the sql-federation-type: NONE attribute configuration and add a new sql federation rule.

```yaml
sqlFederation:
  # 是否开启联邦查询，默认关闭
  sqlFederationEnabled: false
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535
```
