### ISSUE TITLE
[proxy5.3.2] NullPointerException occurred during batch insert

### ISSUE THREAD

**Issue by PeiMouRen** [apache/shardingsphere#26342]
### Which version of ShardingSphere did you use?
5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Prox
### Description
Using the kettle to import data to the proxy, when the batch number is 10, it's ok, but when the batch number is 500 or more, a NullPointerException occurred.
![image](https://github.com/apache/shardingsphere/assets/46043280/885b3854-c171-4641-8242-5a3fcf3a45d9)

![image](https://github.com/apache/shardingsphere/assets/46043280/85a7050e-06c2-414e-9b63-fb3c1f2b8940)

### Expected behavior
successfully import data 
### Actual behavior
exception occurred

**Comment by PeiMouRen** [comment]
sharding rule:
```
rules:
- !SHARDING
  tables:
    T_Service_Order:
      actualDataNodes: ds_${0..7}.T_Service_Order
      databaseStrategy:
        standard:
          shardingColumn: Super_Account_No
          shardingAlgorithmName: database_mod
  shardingAlgorithms:
    database_mod:
      type: MOD
      props:
        sharding-count: 8
```

datasource:
```
dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/db0
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:postgresql://127.0.0.1:5432/db1
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:postgresql://127.0.0.1:5432/db2
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_3:
    url: jdbc:postgresql://127.0.0.1:5432/db3
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_4:
    url: jdbc:postgresql://127.0.0.1:5432/db4
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_5:
    url: jdbc:postgresql://127.0.0.1:5432/db5
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_6:
    url: jdbc:postgresql://127.0.0.1:5432/db6
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_7:
    url: jdbc:postgresql://127.0.0.1:5432/db7
    username: test
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```
