### ISSUE TITLE
REFRESH TABLE METADATA does not work

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#26354]
https://github.com/apache/shardingsphere/commit/ad3279cef4ce4700dc59814d5943c9ac9fdbfe87

`server.yaml :`

```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: governance_ds
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500

authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED
```

`DistSQL : `

```
REGISTER STORAGE UNIT ds_0 (
    HOST="127.0.0.1",
    PORT=33307,
    DB="test2",
    USER="root",
    PASSWORD="zjc@2021"
);
```
Tips : `test2` database not has table.

Execute `CREATE TABLE aa(id bigint(20));` in test2 actual database.

Execute `REFRESH TABLE METADATA ` in Proxy.
