### ISSUE TITLE
Add code coverage in codecov

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#26526]
as we could see on https://app.codecov.io/gh/apache/shardingsphere
there have been no code coverage updates in the last three months, please add the code coverage in codecov.io.

**Comment by Zhenye-Na** [comment]
I am assuming update the coverage need an access to the project in codecov and it could not be accessed without being part of the organization (apache) or contributor to this repo ?

If we dont need extra access for this, maybe I can pick this up since it sounds pretty straightforward to me.

**Comment by Zhenye-Na** [comment]
Hi @taojintianxia , I know you are busy, so I make another comment here to increase visibility.

Please feel free to let me know if I could pick up this task and if I need extra permission to update the coverage icon.

Thank you!

**Comment by Zhenye-Na** [comment]
Further investgation pointed out that if any maintainer of this repo could access repo settings > secrets and variable > actions and properly set the variable of `CODECOV_TOKEN=EXAMPLE`


I could make the following steps in the `nightly-check.yml` or other CI you proposed to enable this feature

```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v3
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
