### ISSUE TITLE
ShardingRule init logic should check ShardingAlgorithm type to avoid wrong usage

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26667]
### Which version of ShardingSphere did you use?

[675b20b](https://github.com/apache/shardingsphere/commit/675b20bc7ff60541ce3f55c62b1ec9778453ea68)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

When I config ShardingAutoTableAlgorithm `MOD` in `tables` config, it can throw exception.

```yaml
rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: t_order_item_inline
      keyGenerateStrategy:
        column: order_item_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
      
  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    t_order_inline:
      type: MOD
      props:
        sharding-count: 2
    t_order_item_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_item_${order_id % 2}

  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```

### Actual behavior

Start proxy successfully.

### Reason analyze (If you can)

Not check ShardingAlgorithm type when init ShardingRule.
