### ISSUE TITLE
SQL LIMIT  query problem

### ISSUE THREAD

**Issue by shenmadouyaowen** [apache/shardingsphere#26749]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
shardingsphere-proxy-bin-5.3.2
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy
### Expected behavior
I want to obtain the following SQL:

```
SELECT * FROM `a_0` WHERE  `zltype` = 1 LIMIT 10,10
```

### Actual behavior
But in reality:
 ```
SELECT * FROM `a_0` WHERE  `zltype` = 1 ORDER BY id ASC  LIMIT 0,20
```

### Reason analyze (If you can)
ShardingSphere Proxy received
 ```
SELECT * From ` a ` WHERE ` zltype `=1 LIMIT 10,10 
```
 , but after conversion, the limit became LIMIT 0,20

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
sql: 
`SELECT * From ` a ` WHERE ` zltype `=1 LIMIT 10,10`
 

sharding rule configuration :
```
shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${id % 2}
        allow-range-query-with-inline-sharding: true
    a_inline:
      type: INLINE
      props:
        algorithm-expression: a_${zlcode % 100}
        allow-range-query-with-inline-sharding: true
    a_item_inline:
      type: INLINE
      props:
        algorithm-expression: a_item_${zlcode % 100}
        allow-range-query-with-inline-sharding: true
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```
