### ISSUE TITLE
NPE occurs when I start proxy without autoTable shardingStrategy configuration

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#26750]
### Which version of ShardingSphere did you use?

[437c447](https://github.com/apache/shardingsphere/commit/437c447139e0367b043eeb7846ad58e2deb3f60e)

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-Proxy

### Expected behavior

Throw corrent exception instead of NPE.

### Actual behavior

![img_v2_470988a3-5dac-48c2-b1f6-6031922669bg](https://github.com/apache/shardingsphere/assets/10829171/fb3bcd05-3619-427d-91e9-21405eaf3ca8)

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Config like following:

```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SHARDING
  bindingTables:
    - bmsql_warehouse, bmsql_customer
    - bmsql_stock, bmsql_district, bmsql_order_line
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
  autoTables:
    bmsql_config:
      actualDataSources: ds_0
    bmsql_warehouse:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: w_id
          shardingAlgorithmName: mod_1
    bmsql_district:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: d_w_id
          shardingAlgorithmName: mod_1
    bmsql_customer:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: c_w_id
          shardingAlgorithmName: mod_1
    bmsql_item:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: i_id
          shardingAlgorithmName: mod_1
    bmsql_history:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: h_w_id
          shardingAlgorithmName: mod_1
    bmsql_oorder:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: o_w_id
          shardingAlgorithmName: mod_1
    bmsql_stock:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: s_w_id
          shardingAlgorithmName: mod_1
    bmsql_new_order:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: no_w_id
          shardingAlgorithmName: mod_1
    bmsql_order_line:
      actualDataSources: ds_${0..0}
      shardingStrategy:
        standard:
          shardingColumn: ol_w_id
          shardingAlgorithmName: mod_1
  shardingAlgorithms:
    mod_1:
      type: MOD
      props:
        sharding-count: 1
```
