### ISSUE TITLE
SQL state[99999]; code [0]. With rules config

### ISSUE THREAD

**Issue by Oliver-GMJ** [apache/shardingsphere#26922]
### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Reason analyze (If you can)
When rules was configured, run SQL wrong.

shardingConfig.yml
```
dataSources:
  master:
    driverClassName: org.postgresql.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:postgresql://localhost:5432/my_table
    password: 123
    username: root
props:
  sql-show: true
# Can't execute SQL with custom rules
rules:
- !SHARDING
  tables:
    tb_shard:
      actualDataNodes: master.tb_shard_error
      tableStrategy:
        complex:
          shardingAlgorithmName: my_complex_algorithm
          shardingColumns: col_1,col_2

  shardingAlgorithms:
    my_complex_algorithm:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.xxx.MyComplexShardingAlgorithm
```
MyComplexShardingAlgorithm.java
```Java
package com.xxx;

public class MyComplexShardingAlgorithm implements ComplexKeysShardingAlgorithm<String> {
    @Override
    public Collection<String> doSharding(Collection<String> databaseNames, ComplexKeysShardingValue<String> shardingValue) {
        return Collections.singletonList("tb_test");
    }
}
```
Exception:
This table is not sharding table.
```
Caused by: org.springframework.jdbc.UncategorizedSQLException: 
### Error querying database.  Cause: org.apache.shardingsphere.dialect.postgresql.exception.PostgreSQLException
### The error may exist in com/xxx/dao/mapper/DemoMapper.java (best guess)
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT   id,name   FROM tb_demo
### Cause: org.apache.shardingsphere.dialect.postgresql.exception.PostgreSQLException
; uncategorized SQLException; SQL state [99999]; error code [0]; null; nested exception is org.apache.shardingsphere.dialect.postgresql.exception.PostgreSQLException
```
It works success while I remove rules config.
```
INFO [main] INFO ShardingSphere-SQL - Actual SQL: master ::: SELECT  
id,name
  FROM tb_demo
<==    Columns: id, name
<==        Row: 1, 'xxx'
<==      Total: 1
```

**Comment by Oliver-GMJ** [comment]
It dosen't throw in 5.3.2, but 5.3.2 can't execute LIMIT OFFSET.
```
java.lang.ClassCastException: org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.BinaryOperationExpression 
cannot be cast to
org.apache.shardingsphere.sql.parser.sql.common.segment.dml.expr.simple.LiteralExpressionSegment
```

**Comment by Oliver-GMJ** [comment]
Throw org.apache.shardingsphere.dialect.exception.syntax.table.NoSuchTableException.
But this table is exists and run success in 5.3.x.
![image](https://github.com/apache/shardingsphere/assets/20814213/4fe66e64-d200-4660-8c9d-6890e314fae4)

**Comment by strongduanmu** [comment]
Please refer this document to config single table rule - https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/.

**Comment by Oliver-GMJ** [comment]
@strongduanmu Thanks.

1. It works after set `SINGLE TABLE`.
```yml
rules:
  - !SINGLE
    tables:
      - master.public.*
  - !SHARDING
  tables:
    tb_shard:
      actualDataNodes: master.tb_shard_error
      tableStrategy:
        complex:
          shardingAlgorithmName: my_complex_algorithm
          shardingColumns: col_1,col_2

  shardingAlgorithms:
    my_complex_algorithm:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: com.xxx.MyComplexShardingAlgorithm
```

2. But I can't use any "BinaryOperation" such as +-*/%
```
SELECT * FROM tb_demo ORDER BY id desc LIMIT #{pageSize} OFFSET (#{page} - 1) * #{pageSize}
```
Got SQL syntax error:
```
Cause: org.apache.shardingsphere.sql.parser.exception.SQLParsingException: You have an error in your SQL syntax:
    SELECT  
    id, name
    FROM tb_demo
    ORDER BY id desc
    LIMIT ? OFFSET (? - 1) * ?, no viable alternative at input '?-1)*?'
at line 5, position 30, near [@32,193:192='<EOF>',<-1>,5:30]
```
