### ISSUE TITLE
Single table loading may be incorrect when single tables with the same name exist in different storage units

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#27290]
### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

#### actual tables
```sql
mysql> show tables from demo_ds_0;
+---------------------+
| Tables_in_demo_ds_0 |
+---------------------+
| t_encrypt           |
| t_single            |
+---------------------+
2 rows in set (0.00 sec)

mysql> show tables from demo_ds_1;
+---------------------+
| Tables_in_demo_ds_1 |
+---------------------+
| t_order             |
| t_single            |
+---------------------+
2 rows in set (0.00 sec)
```

#### config-sharding.yaml
```yaml
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1

rules:
- !SINGLE
  tables:
    - ds_1.*
```

#### loaded single tables
```sql
mysql> show tables;
+-----------------------+
| Tables_in_sharding_db |
+-----------------------+
| t_order               |
+-----------------------+
1 row in set (0.10 sec)
```
`t_single` is lost.
