### ISSUE TITLE
in 5.4.0  a error happens on creating a single table

### ISSUE THREAD

**Issue by ulwx** [apache/shardingsphere#27358]
```
dataSources:
  ds_0:
      ....
  ds_1:
     ...
....
- !SINGLE
  tables:
    # MySQL 风格
    - ds_1.t_single # 加载指定单表
```

The above information is the configuration information. When I created a new table named "t_single" using the sharding JDBC data source for a single table, the table ended up in "ds_0" instead of "ds_1". it should be "ds_1".

![image](https://github.com/apache/shardingsphere/assets/78004279/e73d8d29-9da0-42fa-98b4-2982e9edd2bf)
