### ISSUE TITLE
How to config common properties on the yml

### ISSUE THREAD

**Issue by Waylon-Firework** [apache/shardingsphere#27368]
## Question
Version: 5.4.0

if I set some properties, the app cannot restart. Such as:

database_url: localhost:3306

and using it like this: ${database_url} .

I can't declare custom attributes

```
database_url: localhost:3306

dataSources:
  demo:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${database_url}/demo
```
