### ISSUE TITLE
The CSN value is a little confusing when using openGauss with GLT

### ISSUE THREAD

**Issue by azexcy** [apache/shardingsphere#27403]
## Question

When using openGauss with GLT, I find the change in the CSN value is not well understood, I'm not sure that's a problem, because everything else is fine.

When transactions are turned on manually, the CSN value is retrieved from redis. just like 

```
begin;
...
...
commit;
```

but when without transaction, the CSN value will not retrieved from redis.

As you can see in this screenshot below.

![39d60bf9-ba40-4e7d-be33-abafadd31b75](https://github.com/apache/shardingsphere/assets/101622833/18d40141-1466-415b-8f61-5c9ee14886c2)

![2be407d8-2cbc-409a-a4a9-ab929e3294bc](https://github.com/apache/shardingsphere/assets/101622833/2974a1fa-3836-4266-aff2-c5c3e78b08d8)

And I debug at local, When transactions are not manually turned on, they don't go to this method
![70469806-8163-497f-aa10-8772826e8621](https://github.com/apache/shardingsphere/assets/101622833/7c76e108-1b5c-4ccf-9ef4-a6facc1ac4bd)

Here is my config 
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: cdc_demo
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500

authority:
  users:
    - user: root@%
      password: root
  privilege:
    type: ALL_PERMITTED

transaction:
  defaultType: XA
  providerType: Atomikos

sqlParser:
  sqlCommentParseEnabled: false
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

globalClock:
  enabled: true
  type: TSO
  provider: redis
  props:
    host: 127.0.0.1
    port: 6379

logging:
  loggers:
  - loggerName: ShardingSphere-SQL
    additivity: true
    level: INFO
    props:
      enable: false

sqlFederation:
  sqlFederationEnabled: false
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535

props:
  system-log-level: INFO
  max-connections-size-per-query: 1
  kernel-executor-size: 16  # Infinite by default.
  proxy-frontend-flush-threshold: 128  # The default value is 128.
  # sql-show is the same as props in logger ShardingSphere-SQL, and its priority is lower than logging rule
  sql-show: false
  check-table-metadata-enabled: false
    # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
    # The default value is -1, which means set the minimum value for different JDBC drivers.
  proxy-backend-query-fetch-size: -1
  proxy-frontend-executor-size: 0 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
  proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
  proxy-default-port: 3307 # Proxy default port.
  proxy-netty-backlog: 1024 # Proxy netty backlog.
  cdc-server-port: 33071 # CDC server port
  proxy-frontend-ssl-enabled: false
  proxy-frontend-ssl-cipher: ''
  proxy-frontend-ssl-version: TLSv1.2,TLSv1.3
  proxy-frontend-database-protocol-type: openGauss
```

and I also add redis GLT dependency.
<img width="765" alt="image" src="https://github.com/apache/shardingsphere/assets/101622833/bfed523c-4ed2-4613-98a5-7dcf6218e21d">
<img width="954" alt="image" src="https://github.com/apache/shardingsphere/assets/101622833/7f0b4369-313b-49ed-acea-a30f544c4a8d">
