### ISSUE TITLE
ShardingSphere-jdbc:5.4.0  Can not get index from column label COUNT( * )

### ISSUE THREAD

**Issue by xuschang** [apache/shardingsphere#27878]
### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-JDBC

### Expected behavior
select count( * ) from table will return the correct value.

### Actual behavior
When using Oracle as a database, the translation of the query "select count( * ) from table." the result  would be
``` 
Error attempting to get column 'COUNT(*)' from result set.  Cause: java.sql.SQLFeatureNotSupportedException: Can not get index from column label `COUNT(*)`.\n; Can not get index from column label `COUNT(*)`.; nested exception is java.sql.SQLFeatureNotSupportedException: Can not get index from column label `COUNT(*)`.
```

### Reason analyze (If you can)

When using Oracle as a shardingDataSource, MyBatis will convert the selectCount statement to SELECT COUNT( * ) for execution. ColumnLabelAndIndexMap in ShardingResultSet stores the original column name and index value, which is [COUNT( * ),index]. However, Oracle returns the column name as COUNT(*), causing an error when retrieving the index.
![image](https://github.com/apache/shardingsphere/assets/19425207/fef8e053-0dc1-4e31-8f25-235d82399404)
![image](https://github.com/apache/shardingsphere/assets/19425207/fed60ed8-31b7-4fff-a100-63fa6c2f844e)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Select COUNT ( * ) from XXX.
### Example codes for reproduce this issue (such as a github link).
```
 QueryWrapper wrapper = new QueryWrapper<>();
 Integer countResult = mapper.selectCount(wrapper);
```
related config.yml example
```
mode:
  type: Standalone
  repository:
    type: JDBC

databaseName: db-1
dataSources:
  db-1:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@****:1521:orcl
    username: ****
    password: ****
  db-2:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@****:1521:orcl
    username: ****
    password: ****
rules:
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: db-1
  - !SHARDING
    tables:
      SOP_LEVEL:
        databaseStrategy:
          standard:
            shardingColumn: STUDY_DATETIME
            shardingAlgorithmName: my_alogrithm
      FILE_LEVEL:
        databaseStrategy:
          standard:
            shardingColumn: STUDY_DATETIME
            shardingAlgorithmName: my_alogrithm
    shardingAlgorithms:
      my_alogrithm:
        type: ***
props:
  sql-show: true
```
