### ISSUE TITLE
spring boot HikariDataSource create additional h2 datasource

### ISSUE THREAD

**Issue by clay-f** [apache/shardingsphere#28030]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingsphere-jdbc-core
### Expected behavior
1. only create one HikariDataSource pool but create three. it's imporant is h2 datasource that should not be created
2.  ShardingSphereConnection have waring log . ```Driver does not support get/set network timeout for connections. ```(getNetworkTimeout)
### Actual behavior

    2023-08-10T22:31:42.411+08:00  INFO 15624 --- [           main] com.f.sharedingjdbc.SharedingjdbcApp     : Starting SharedingjdbcApp using Java 17.0.7 with PID 15624 (D:\develop\project\java_project\learn_project\mybatis_sharedingjdbc\target\classes started by f in D:\develop\project\java_project\learn_project)
    2023-08-10T22:31:42.412+08:00  INFO 15624 --- [           main] com.f.sharedingjdbc.SharedingjdbcApp     : No active profile set, falling back to 1 default profile: "default"
    2023-08-10T22:31:42.906+08:00  INFO 15624 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8080 (http)
    2023-08-10T22:31:42.911+08:00  INFO 15624 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
    2023-08-10T22:31:42.911+08:00  INFO 15624 --- [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.11]
    2023-08-10T22:31:42.965+08:00  INFO 15624 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
    2023-08-10T22:31:42.967+08:00  INFO 15624 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 443 ms
    2023-08-10T22:31:43.231+08:00  INFO 15624 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8080 (http) with context path ''
    2023-08-10T22:31:43.235+08:00  INFO 15624 --- [           main] com.f.sharedingjdbc.SharedingjdbcApp     : Started SharedingjdbcApp in 1.005 seconds (process running for 1.278)
    2023-08-10T22:31:55.677+08:00  INFO 15624 --- [nio-8080-exec-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
    2023-08-10T22:31:55.677+08:00  INFO 15624 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
    2023-08-10T22:31:55.678+08:00  INFO 15624 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 1 ms
    2023-08-10T22:31:55.697+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
    2023-08-10T22:31:55.837+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Starting...
    2023-08-10T22:31:55.913+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-2 - Added connection conn0: url=jdbc:h2:mem:config user=SA
    2023-08-10T22:31:55.914+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Start completed.
    2023-08-10T22:31:55.958+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Starting...
    2023-08-10T22:31:56.091+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-3 - Added connection oracle.jdbc.driver.T4CConnection@1a497f9e
    2023-08-10T22:31:56.091+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-3 - Start completed.
    2023-08-10T22:31:56.927+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (getNetworkTimeout)
    2023-08-10T22:31:56.928+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Added connection org.apache.shardingsphere.driver.jdbc.core.connection.ShardingSphereConnection@251f9c
    2023-08-10T22:31:56.928+08:00  INFO 15624 --- [nio-8080-exec-1] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
    2023-08-10T22:31:56.930+08:00 DEBUG 15624 --- [nio-8080-exec-1] c.f.s.mapper.OrderMapper.list            : ==>  Preparing: SELECT * FROM T_ORDER
    2023-08-10T22:31:57.315+08:00 DEBUG 15624 --- [nio-8080-exec-1] c.f.s.mapper.OrderMapper.list            : ==> Parameters: 
    2023-08-10T22:31:57.332+08:00  INFO 15624 --- [nio-8080-exec-1] ShardingSphere-SQL                       : Logic SQL: SELECT * FROM T_ORDER
    2023-08-10T22:31:57.332+08:00  INFO 15624 --- [nio-8080-exec-1] ShardingSphere-SQL                       : Actual SQL: ds_0 ::: SELECT * FROM T_ORDER_0 UNION ALL SELECT * FROM T_ORDER_1
    2023-08-10T22:31:57.355+08:00 DEBUG 15624 --- [nio-8080-exec-1] c.f.s.mapper.OrderMapper.list            : <==      Total: 3

### Example codes for reproduce this issue (such as a github link).

this is learn project and not have many dependencies pom.xml all dependency
     
     <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-web</artifactId>
            </dependency>
            <dependency>
                <groupId>org.apache.shardingsphere</groupId>
                <artifactId>shardingsphere-jdbc-core</artifactId>
                <version>5.4.0</version>
            </dependency>
            <dependency>
                <groupId>org.mybatis.spring.boot</groupId>
                <artifactId>mybatis-spring-boot-starter</artifactId>
                <version>3.0.2</version>
            </dependency>
            <dependency>
                <groupId>com.zaxxer</groupId>
                <artifactId>HikariCP</artifactId>
            </dependency>
            <dependency>
                <groupId>com.oracle.database.jdbc</groupId>
                <artifactId>ojdbc11</artifactId>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-starter-test</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>4.0.0</version>
            </dependency>
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>4.0.0</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>javax.xml.bind</groupId>
                <artifactId>jaxb-api</artifactId>
                <version>2.3.1</version>
            </dependency>
            
            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>2.3.4</version>
            </dependency>
        </dependencies>

application.yml
```
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:config.yml

  main:
    banner-mode: off

mybatis:
  type-aliases-package: com.f.sharedingjdbc.domain
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    com.f.sharedingjdbc.mapper: debug
```

config.yml
```
mode:
  type: Standalone
  repository:
    type: JDBC

schemaName: SCOTT
databaseName: SCOTT

dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.OracleDriver
    jdbcUrl: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
    username: scott
    password: tiger

rules:
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: db_0
  - !SHARDING
    tables:
      T_ORDER:
        actualDataNodes: ds_0.T_ORDER_$->{0..1}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: T_ORDER_INLINE
    bindingTables:
      - T_ORDER
    defaultDatabaseStrategy:
      standard:
        shardingColumn: id
        shardingAlgorithmName: database_inline
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      database_inline:
        type: INLINE
        props:
          algorithm-expression: ds_0->{id % 2}
      T_ORDER_INLINE:
        type: INLINE
        props:
          algorithm-expression: T_ORDER_$->{id % 2}

props:
  sql-show: true

```
