### ISSUE TITLE
Does ShardingSphere support Prepared Statement?

### ISSUE THREAD

**Issue by tonyhu88** [apache/shardingsphere#28159]
### Which version of ShardingSphere did you use?
5.4.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

This statement can be executed normally:
```
db.Exec("INSERT INTO `account_asset` (`mch_id`,`user_id`,`credit`,`freeze_credit`,`created_at`,`updated_at`) VALUES (101,1001000,1001,1,'2023-08-18 07:59:58.449','2023-08-18 07:59:58.449')")
```
But this statement execution error:
```
db.Exec("INSERT INTO `account_asset` (`mch_id`,`user_id`,`credit`,`freeze_credit`,`created_at`,`updated_at`) VALUES (?, ?, ?, ?, ?, ?)", 100, 100100, 1, 2, time.Now(), time.Now())
```
The error info is :
```
Error 20081 (HY000): Routed target `nova_-1` does not exist, available targets are `[nova_0, nova_1]`.
```

The sharding rule is:
```
shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: 'nova_${[100].contains(mch_id) ? 0 : [101].contains(mch_id) ? 1 : -1}'
```
