### ISSUE TITLE
How to configure a custom fragmentation strategy for multiple tables

### ISSUE THREAD

**Issue by cwf404** [apache/shardingsphere#28365]
```
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/table?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
    props:
      sql-show: true
    rules:
      sharding:
        binding-tables: member,user
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
        sharding-algorithms:
          member-algorithm:
            props:
              strategy: standard
              algorithmClassName: org.jeecg.modules.block.algorithm.StandardMemberShardAlgorithm
            type: CLASS_BASED
          user-algorithm:
            props:
              strategy: standard
              algorithmClassName: org.jeecg.modules.block.algorithm.StandardUserShardAlgorithm
            type: CLASS_BASED
        tables:
          member:
            actual-data-nodes: ds0.member$->{0..2}
            table-strategy:
              standard:
                sharding-algorithm-name: member-algorithm
                sharding-column: id
          user:
            actual-data-nodes: ds0.user$->{0..2}
            table-strategy:
              standard:
                sharding-algorithm-name: user-algorithm
                sharding-column: id

```
