### ISSUE TITLE
For complex SQL nested queries, how can I manually specify the table name to avoid M*N queries.

### ISSUE THREAD

**Issue by qiuweilu** [apache/shardingsphere#28397]
For complex SQL nested queries, how can I manually specify the table name to avoid M*N queries.

part_cmnt_${bizFkid}
part_vote_${bizFkid}
part_vote_${bizFkid}

If I specify the table name programmatically, an error will be reported.

------------------------------------------------------------------------------------------------------------------------------------------------------

```
        SELECT out_cmnt.cmnt_id cmnt_id, out_cmnt.vote_num........
        FROM
        (
            SELECT cmnt_tab.* 
            FROM
            (
                <!-- 基础.评论数据 -->
                SELECT base_cmnt.* FROM part_cmnt_${bizFkid} base_cmnt
                WHERE base_cmnt.part_fkid = #{partFkid,jdbcType=BIGINT}
                LIMIT 2000
            ) cmnt_tab
            <!-- 评论.点赞数据 -->
            LEFT JOIN part_vote_${bizFkid} vote_bind_tab ON vote_bind_tab.bind_fkid = cmnt_tab.cmnt_id
            AND vote_bind_tab.part_fkid = #{partFkid,jdbcType=BIGINT}
            GROUP BY cmnt_tab.cmnt_id
        ) out_cmnt
        <!-- 评论.用户点赞 -->
            LEFT JOIN **part_vote_${bizFkid}** vote_user_tab ON vote_user_tab.bind_fkid = out_cmnt.cmnt_id
            AND vote_user_tab.part_fkid = #{partFkid,jdbcType=BIGINT}
            GROUP BY out_cmnt.cmnt_id

```

**Comment by strongduanmu** [comment]
Hi @qiuweilu, can you modify this issue accordint to issue template?

**Comment by qiuweilu** [comment]
base_cmnt.part_fkid
vote_bind_tab.part_fkid
vote_user_tab.part_fkid 

```
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline
      part_vote:
        actualDataNodes: ds_0.part_vote_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_vote_inline
```

If based on the table splitting strategy, M * N queries will be executed. But when I specify a data table name, the execution will report an error.

part_cmnt_${bizFkid}
part_vote_${bizFkid}
part_vote_${bizFkid}



> Hi @qiuweilu, can you modify this issue accordint to issue template?

part_cmnt
	-- base_cmnt.part_fkid

part_vote
	-- vote_bind_tab.part_fkid

part_vote
	-- vote_user_tab.part_fkid 

```
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline
      part_vote:
        actualDataNodes: ds_0.part_vote_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_vote_inline
```

If based on the table splitting strategy, M * N queries will be executed. But when I specify a data table name, the execution will report an error.

part_cmnt_${bizFkid}
part_vote_${bizFkid}
part_vote_${bizFkid}

**Comment by qiuweilu** [comment]
> Hi @qiuweilu, can you modify this issue accordint to issue template?

part_cmnt
	-- base_cmnt.part_fkid

part_vote
	-- vote_bind_tab.part_fkid

part_vote
	-- vote_user_tab.part_fkid 

```
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline
      part_vote:
        actualDataNodes: ds_0.part_vote_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_vote_inline
```

If based on the table splitting strategy, M * N queries will be executed. But when I specify a data table name, the execution will report an error.

part_cmnt_${bizFkid}
part_vote_${bizFkid}
part_vote_${bizFkid}
