### ISSUE TITLE
Not support Joins Using the Plus (+) Sign in Oracle.

### ISSUE THREAD

**Issue by iamhucong** [apache/shardingsphere#28418]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
Master

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
All

### Expected behavior
Execute and return results normally.

### Actual behavior
NPE

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
``` sql
select p.name planet, m.name, m.radius, row_number() over ( order by radius desc ) as size_rank
from planets p,
     moons m
where p.name = m.planet_name(+)
  and p.name in ('Mars', 'Venus', 'Pluto', 'Mercury', 'Neptune')
order by size_rank;
```

``` yaml
rules:
- !ENCRYPT
  tables:
    planets:
      columns:
        name:
          cipher:
            name: name_cipher
            encryptorName: aes_encryptor
    moons:
      columns:
        planet_name:
          cipher:
            name: planet_name_cipher
            encryptorName: aes_encryptor 
```
