### ISSUE TITLE
sharding-proxy and mybatis to write to MySQL using multiple threads, the code for obtaining an auto-increment id uses SELECT LAST_INSERT_ID(), The return values of ID are partially duplicated

### ISSUE THREAD

**Issue by fanzw123** [apache/shardingsphere#28659]
# Which version of ShardingSphere did you use?
5.4.0
# Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
# Expected behavior
When using sharding-proxy and mybatis to write to MySQL using multiple threads, the code for obtaining an auto-increment id uses SELECT LAST_INSERT_ID(), The return values of ID are not duplicated.
# Actual behavior
When using sharding-proxy and mybatis to write to MySQL using multiple threads, the code for obtaining an auto-increment id uses SELECT LAST_INSERT_ID(), The return values of ID are partially duplicated.
# Reason analyze (If you can)
The write and auto-increment id query are queried in steps, resulting in inconsistent auto-increment id and write results when multiple threads are involved.
# Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Multi-threading writes data to the same table, queries the auto-increment id, and returns.
[![diff_if](https://github.com/apache/shardingsphere/assets/15103951/4c2dd787-bfbe-47b8-94bc-dc4c4bf5f933)
](url)
# Example codes for reproduce this issue (such as a github link).
## related java code
```
myOrderBakMapper.insert(myOrderBak);
Long orderId = myOrderBak.getOrderId()
```
## related mybatis xml
```
<insert id="insert" parameterType="com.aibaoxian.optimus.domain.entity.MyOrderBak">
    <selectKey keyProperty="orderId" order="AFTER" resultType="java.lang.Long">
      SELECT LAST_INSERT_ID()
    </selectKey>
    insert into my_order_bak
    <trim prefix="(" suffix=")" suffixOverrides=",">
      <if test="orderId != null">
        order_id,
      </if>
      <if test="orderNo != null">
        order_no,
      </if>
      <if test="title != null">
        title,
      </if>
	</trim>
    <trim prefix="values (" suffix=")" suffixOverrides=",">
      <if test="orderId != null">
        #{orderId,jdbcType=BIGINT},
      </if>
      <if test="orderNo != null">
        #{orderNo,jdbcType=VARCHAR},
      </if>
      <if test="title != null">
        #{title,jdbcType=VARCHAR},
      </if>
    </trim>
  </insert>
```
## related sharding config 
```
databaseName: czh_order
dataSources:
  ds_0:
    password: test001
    url: jdbc:mysql://xxxx:3307/test?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: test
    minPoolSize: 1
    connectionTimeoutMilliseconds: 30000
    maxLifetimeMilliseconds: 2100000
    readOnly: false
    idleTimeoutMilliseconds: 60000
    maxPoolSize: 50
```
