### ISSUE TITLE
Remove dataSourceProperties from the result set of ShowStorageUnitExecutor

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#28703]
When user uses the following data source configuration:

```yaml
databaseName: sharding_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
```

The result set of `ShowStorageUnitExecutor` is as follows
![image](https://github.com/apache/shardingsphere/assets/5668787/415c779d-3394-490b-83c1-6361f2e96244)

among which:
1. `dataSourceProperties` is not the content configured by the user, and the user does not need to care (these are the default values of the properties, and the user can learn about it from the documentation)
2. `queryProperties` are parameters configured by the user in jdbcUrl and need to be displayed

If we remove the display of `dataSourceProperties`, the result set will be consistent with the user configuration and more concise, so I recommend removing it.

### Tasks

- [ ] Refactor ShowStorageUnitExecutor
- [ ] Update test cases
- [ ] Add documentation to describe default `dataSourceProperties`
