### ISSUE TITLE
Table or view `part_cmnt_1` does not exist.

### ISSUE THREAD

**Issue by qiuweilu** [apache/shardingsphere#28872]
```
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
            <version>5.4.1</version>
        </dependency>
```

```
rules:
  - !SINGLE
    tables:
      - "*.*"
  - !SHARDING
    tables:
      part_cmnt:
        actualDataNodes: ds_0.part_cmnt_${0..9}
        tableStrategy:
          standard:
            shardingColumn: part_fkid
            shardingAlgorithmName: t_cmnt_inline


    shardingAlgorithms:
      t_cmnt_inline:
        type: INLINE
        props:
          algorithm-expression: part_cmnt_${part_fkid % 10}
```

```
    <select id="searchCmntList" parameterType="com.foxwish.dao.entity.ext.PartCmntExt" resultMap="BaseResultMap">
        select * from part_cmnt_1
    </select>
```

```
In certain complex scenarios, it is necessary to manually specify the table name; 
otherwise, it will execute M*N queries.

nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  
Cause: org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `part_cmnt_1` does not exist.
```
