### ISSUE TITLE
Lose sharding table rules and readwrite splitting rules after proxy restart

### ISSUE THREAD

**Issue by ifrit2000** [apache/shardingsphere#28908]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
1. Lose sharding table rules and readwrite splitting rules after proxy restart
2. Even though set `props.sql-show=true`, Proxy don't print any sql 

### Actual behavior
1. Retain all kind of rules after restart
2. Print sql log

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Proxy is deployed in k8s, and managed by helm.

### Example codes for reproduce this issue (such as a github link).
server.yaml
```
mode:
  type: Standalone
  repository:
    type: JDBC
    props: 
      provider: MySQL
      jdbc_url: jdbc:mysql://mysql-master:3306/sharding_metadata_db
      username: sharding_metadata
      password: sharding_metadata
authority:
  users:
    - user: app_user@%
      password: app_user
  privilege:
    type: ALL_PERMITTED
props:
  system-log-level: DEBUG
  sql-show: true
```
