### ISSUE TITLE
The bug of loading Single table in Oracle with shardingsphere 5.4.0

### ISSUE THREAD

**Issue by fanzhiyi0601** [apache/shardingsphere#29026]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
The single tables set in sharding.yml can be loaded succussfully which are used in datasource as expect.
### Actual behavior
throw null exception, the project doesn't load the single tables in initialization.
### Reason analyze (If you can)
- !SINGLE
    tables:
   The Configured table is added in lower case . But in Oracle, the tablename showed in actualNode is upper case.
So there is a conditon in SingleTableDataNodeLoader as follows:
if (configuredTablesForSchema.contains(SingleTableConstants.ASTERISK) || configuredTablesForSchema.contains(actualDataNode.getTableName())) {
                result.put(actualDataNode.getTableName(), entry.getValue());
            }
configuredTablesForSchema is lower case and the other one is upper case, therefore the condition is false so that the configured single  table cannot be loaded.
Another reason is the process of loading single table doesn't have TableNamesMapper which can compare value in same case. I dont know why it is different.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
  sharding.yml:
- !SINGLE
    tables:
      - ds0.test 
or
 - !SINGLE
    tables:
      - ds0.TEST.
    These two configuration rules are all loaded in lower case. And the default table name in Oracle is upper case!
sql: select *from TEST;

**Comment by strongduanmu** [comment]
@fanzhiyi0601 Thank you for your feedback. I will investigate this issue.

**Comment by strongduanmu** [comment]
Can you format your yaml config with markdown? It's hard to read now.

**Comment by fanzhiyi0601** [comment]
> Can you format your yaml config with markdown? It's hard to read now.

dataSources:
  ds0:
    # 下面为连接池的补充设置，应用到上面所有数据源中
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: 
    driverClassName: oracle.jdbc.OracleDriver
    platform: oracle
rules:
  - !SHARDING
    tables:
      CC_CLIENT_ASSET:
        actualDataNodes: ds0.CC_CLIENT_ASSET_$->{2020..2023}
        tableStrategy:
          standard:
            shardingColumn: section
            shardingAlgorithmName: table-algorithm

    shardingAlgorithms:
      table-algorithm:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: ShardingStandardAlgorithm

  - !BROADCAST
    tables:
      - CC_CONTENT
     
  - !SINGLE
    tables:
      - TEST
props:
  sql-show: true

**Comment by fanzhiyi0601** [comment]
> Can you format your yaml config with markdown? It's hard to read now.

`dataSources:
  ds0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:
    username: 
    password: 
    driverClassName: oracle.jdbc.OracleDriver
    platform: oracle
rules:
  - !SHARDING
    tables:
      CC_ASSET:
        actualDataNodes: ds0.CC_ASSET_$->{2020..2023}
        tableStrategy:
          standard:
            shardingColumn: section
            shardingAlgorithmName: table-algorithm

    shardingAlgorithms:
      table-algorithm:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: ShardingStandardAlgorithm

  - !BROADCAST
    tables:
      - CC_CONTENT
  - !SINGLE
    tables:
      - TEST
props:
  sql-show: true`

**Comment by fanzhiyi0601** [comment]
> Can you format your yaml config with markdown? It's hard to read now.

```
dataSources:
  ds0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:oracle:thin:
    username: 
    password: 
    driverClassName: oracle.jdbc.OracleDriver
    platform: oracle
rules:
  - !SHARDING
    tables:
      CC_ASSET:
        actualDataNodes: ds0.CC_ASSET_$->{2020..2023}
        tableStrategy:
          standard:
            shardingColumn: section
            shardingAlgorithmName: table-algorithm

    shardingAlgorithms:
      table-algorithm:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: ShardingStandardAlgorithm

  - !BROADCAST
    tables:
      - CC_CONTENT
  - !SINGLE
    tables:
      - TEST
props:
  sql-show: true
```
