### ISSUE TITLE
After upgrading from 5.4.0 to 5.4.1, the tableStrategy of the CLASS_BASED custom class has become invalid.

### ISSUE THREAD

**Issue by tiandihai** [apache/shardingsphere#29226]
After the upgrade from 5.4.0 to 5.4.1, the tableStrategy of CLASS_BASED custom classes becomes invalid.
My sub-library policy ds_sharding is introduced through SPI mode, and 5.4.0 and 5.4.1 are valid.
However, the subtable policy tb_sharding is introduced by type=CLASS_BASED custom class, which takes effect normally in 5.4.0, but becomes invalid after the upgrade to 5.4.1. Later, I changed it to be introduced by SPI as well as the above sublibrary policy, which does not take effect.
I wonder why?
In addition, I have four libraries, each with about 2000 tables. After the upgrade to 5.4.1, the service starts very slowly (the startup speed is about 2 minutes when shardingsphere is not introduced, the startup speed is about 5 minutes when shardingsphere 5.4.0 is introduced, and the startup speed reaches 20 minutes in 5.4.1).
After I delete a lot of tables, the startup speed is significantly improved), is there any way to speed up the scanning of tables?

My config :

`props:
  sql-show: false
dataSources:
  db-0:
    xxx
  db-1:
    xxx
  db-2:
    xxx
  db-3:
    xxx
sqlFederation:
  sqlFederationEnabled: true
  executionPlanCache:
    initialCapacity: 1000
    maximumSize: 1000
rules:
  - SQL_PARSER: {}
    sqlCommentParseEnabled: true
  - SINGLE: {}
    tables:
      - '*.*'
    defaultDataSource: db-0
  - SHARDING: {}
    tables:
      tlog_transnumber_repeat:
        actualDataNodes: db-${0..3}.tlog_transnumber_repeat
        databaseStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: ds_sharding
      tlog_header:
        actualDataNodes: db-0.tlog_header
        tableStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: tb_sharding
    bindingTables:
      - b_header,b_items
    shardingAlgorithms:
      ds_sharding:
        type: DATABASE-MOD-SHARDING
        props:
          database-sharding-ranges: db-0:0-15,db-1:16-31,db-2:32-47,db-3:48-63
      tb_sharding:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.yonghui.yh.rme.soc.stream.consumer.sharding.algorithm.TableShardingAlgorithm`

**Comment by RaigorJiang** [comment]
Hi @tiandihai 
The configuration format you provided is incorrect. Please use `markdown` to format it. Thank you.

**Comment by tiandihai** [comment]
props:
  sql-show: false
dataSources:
  db-0:
    xxx
  db-1:
    xxx
  db-2:
    xxx
  db-3:
    xxx
sqlFederation:
  sqlFederationEnabled: true
  executionPlanCache:
    initialCapacity: 1000
    maximumSize: 1000
rules:
  - SQL_PARSER: {}
    sqlCommentParseEnabled: true
  - SINGLE: {}
    tables:
      - '*.*'
    defaultDataSource: db-0
  - SHARDING: {}
    tables:
      tlog_transnumber_repeat:
        actualDataNodes: db-${0..3}.tlog_transnumber_repeat
        databaseStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: ds_sharding
      tlog_header:
        actualDataNodes: db-0.tlog_header
        tableStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: tb_sharding
    bindingTables:
      - b_header,b_items
    shardingAlgorithms:
      ds_sharding:
        type: DATABASE-MOD-SHARDING
        props:
          database-sharding-ranges: db-0:0-15,db-1:16-31,db-2:32-47,db-3:48-63
      tb_sharding:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.xxx.sharding.algorithm.TableShardingAlgorithm

**Comment by tiandihai** [comment]
> Hi @tiandihai The configuration format you provided is incorrect. Please use `markdown` to format it. Thank you.

```yaml
props:
  sql-show: false
dataSources:
  db-0:
    xxx
  db-1:
    xxx
  db-2:
    xxx
  db-3:
    xxx
sqlFederation:
  sqlFederationEnabled: true
  executionPlanCache:
    initialCapacity: 1000
    maximumSize: 1000
rules:
  - SQL_PARSER: {}
    sqlCommentParseEnabled: true
  - SINGLE: {}
    tables:
      - '*.*'
    defaultDataSource: db-0
  - SHARDING: {}
    tables:
      tlog_transnumber_repeat:
        actualDataNodes: db-${0..3}.tlog_transnumber_repeat
        databaseStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: ds_sharding
      tlog_header:
        actualDataNodes: db-0.tlog_header
        tableStrategy:
          standard:
            shardingColumn: trans_number
            shardingAlgorithmName: tb_sharding
    bindingTables:
      - b_header,b_items
    shardingAlgorithms:
      ds_sharding:
        type: DATABASE-MOD-SHARDING
        props:
          database-sharding-ranges: db-0:0-15,db-1:16-31,db-2:32-47,db-3:48-63
      tb_sharding:
        type: CLASS_BASED
        props:
          strategy: standard
          algorithmClassName: com.xxx.sharding.algorithm.TableShardingAlgorithm

```
