### ISSUE TITLE
postgresql org.apache.shardingsphere.infra.exception.UnknownColumnException: Unknown column 't' in 'field list'

### ISSUE THREAD

**Issue by Keanhua** [apache/shardingsphere#29371]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC 

### Expected behavior
the sql execute ok

### Actual behavior
the sql execute occur  exception
<img width="1028" alt="image" src="https://github.com/apache/shardingsphere/assets/31396902/4c553f2d-af8a-498d-a742-7440ed16709f">

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
```
SELECT a.recieve_account,a.recieve_account_no,a.recieve_account_bank,a.recieve_account_name,t.pay_channel_id,t.id,t.account_unit_id,t.account_unit_type,t.pay_account,t,balance,t.status,t.pay_type,t.pay_unit_id,t.pay_unit_type,a.name as pay_channel_name,t.only_sign,t.created_at,t.createby_id,t.updated_at,t.updateby_id FROM pay_account t INNER JOIN pay_channel a on a.id = t.pay_channel_id WHERE (t.org_id = ?) ORDER BY created_at DESC LIMIT ?
``` 

```
dataSources:
  master:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ip:port/aaaa?stringtype=unspecified
    username: root
    password: ********
    maxActive: 20
    initialSize: 1
    minIdle: 1
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
rules:
- !TRANSACTION
  defaultType: BASE
  providerType: Seata
- !SINGLE
  tables:
    - "*.*"
  defaultDataSource: master
- !ENCRYPT
  tables:
    r_record:
      columns:
        account:
          cipher:
            name: account
            encryptorName: aes_encryptor
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456
props:
  sql-show: false
```
