### ISSUE TITLE
When enable federated queries, all queries are supported to use federated queries

### ISSUE THREAD

**Issue by totalo** [apache/shardingsphere#29464]
## Feature Request

In order to easily distinguish which queries are supported by the kernel and which are supported by the federated query capabilities, the federated query scenarios are added to gradually improve the scenarios supported by shardingsphere federated query.

The main changes are as follows:

- Supported queries use federated queries by default when federated queries are enabled

- Add e2e federated query test scenario

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

Yes.

**Comment by strongduanmu** [comment]
@totalo This is a great idea and will help us increase support for SQL Federation.

**Comment by zihaoAK47** [comment]
Hello everyone, I am currently working on the first task and we need to discuss the name of the new configuration. This is the configuration name I am currently using, sqlFederationForceDecideEnable, which is used to control the decision logic switch for federated queries. When it is true, supported queries default to using federated queries.

configuration reference:
```
sqlFederation:
  sqlFederationEnabled: true
  sqlFederationForceDecideEnabled: true
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535
```

**Comment by zihaoAK47** [comment]
Corresponding statement modified by distSQL: ALTER SQL_FEDERATION RULE(SQL_FEDERATION_FORCE_DECIDE_ENABLED = boolean)

**Comment by strongduanmu** [comment]
Hi @zihaoAK47, thank you for your advice. But sqlFederationForceDecideEnabled and sqlFederationEnabled seem confusing. How about the following props? 

```
# default false
allQueryUseSQLFederation: true
```
sql federation is currently a supplement to shardingsphere kernel that does not support select sql, and users can enable this parameter when they want all select statements to use sql federation.

**Comment by zihaoAK47** [comment]
Thank you for your suggestion. Here are the configurations for future use of this parameter:
```
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: poc_sharding
      server-lists: 127.0.0.1:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500

sqlFederation:
  sqlFederationEnabled: true
  allQueryUseSQLFederation: true
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535
```

DistSQL modified statement on status:
`ALTER SQL_FEDERATION RULE(ALL_QUERY_USE_SQL_FEDERATION = true)`
