### ISSUE TITLE
How do I skip sql checks and sql overwrites for non-sharded tables?

### ISSUE THREAD

**Issue by tough-pzg** [apache/shardingsphere#29471]
The info log:
```
logic SQL: insert into person(age,name,sex,deleted) values (?,?,?,?);
           insert into person(age,name,sex,deleted) values (?,?,?,?);
           
actual SQL: default ::: insert into person(age,name,sex,deleted) values (?, ?, ?, ?);
            insert into person(age,name,sex,deleted) values (?, ?, ?, ?); ::: [20, 050b53b2-50e6-4131-b217-248a38fbe89c, male, 0]
```

An error occurred when I performed a batch add operation：
Error updating database.  Cause: java.sql.SQLException: No value specified for parameter 5

My yaml file is configured：

```
  - !SINGLE
    tables:
      - default.person
```

**Comment by RaigorJiang** [comment]
Hi @tough-pzg 
There is no way to skip the process, are you using the latest version 5.4.1?

**Comment by tough-pzg** [comment]
Yes, I am using the latest version 5.4.1.

**Comment by tough-pzg** [comment]
If I can't skip this step, how do I handle my undivided tables using sql that is not supported by sharding-jdbc？If I use dynamic data sources to solve this problem, I feel too bloated, because sharding-jdbc can also configure multiple data sources.

**Comment by tough-pzg** [comment]
My complete yaml configuration is as follows：
```
dataSources:
  # 配置 一个数据源 名为   default
  default:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding-test?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456

rules:
  # 分片配置
  - !SHARDING
    tables:
      # user表分片
      user:
        # 真实表节点个数
        actualDataNodes: default.user_${0..1}
        # 分表策略
        tableStrategy:
          standard:
            # 分表字段
            shardingColumn: user_id
            # 逻辑表名称 （后续代码在的sql就使用这个表名）
            shardingAlgorithmName: user
      order_info:
        actualDataNodes: default.order_info_${['ABC','EFG']}
        tableStrategy:
          standard:
            shardingColumn: project_name
            shardingAlgorithmName: order_info
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: pzg-snowflake
          
    # 分片算法
    shardingAlgorithms:
      # 逻辑表 user 的分片算法
      user:
        # 类型为 inline 表达式
        type: INLINE
        props:
          # 分片的 inline 表达式
          algorithm-expression: user_${user_id % 2}
          allow-range-query-with-inline-sharding: true
      order_info:
        type: INLINE
        props:
          algorithm-expression: order_info_${project_name}
          allow-range-query-with-inline-sharding: true
    # 自增键生成器
    keyGenerators:
      # 自定义的名称
      pzg-snowflake:
        type: SNOWFLAKE
        props:
          # 雪花算法中的 机器id，取值 1~1024
          worker-id: 123
  # 单表配置（无需分表的表）
  - !SINGLE
    tables:
      # （mysql风格）加载 default 下所有的单表
#      - default.*
      - default.person
      # （pgsql风格）加载 default 下所有的单表
      #- default.public.*

# 全局属性配置
props:
  # 显示 sql
  sql-show: true
```
