### ISSUE TITLE
IMPORT DATABASE CONFIGURATION FROM FILE "xxxx" has metadata refresh delay problem

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#29574]
Excute `IMPORT DATABASE CONFIGURATION FROM FILE "/opt/config_sharding_db.yaml"` to restore metadata. It's not show all storage units when i execute `SHOW STORAGE UNITS;`, i have to wait some times or restart Proxy to show all storage units.

`config_sharding_db.yaml:`

```
databaseName: test
dataSources:
  ds_0:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_1:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_2:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_3:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_4:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_5:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_6:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_7:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_8:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_9:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_10:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_11:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_12:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_13:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_14:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_15:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_16:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_17:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_18:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_19:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_20:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
  ds_21:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    maxPoolSize: 50
```
