### ISSUE TITLE
jdbc url dynamic property not work in cluster mode

### ISSUE THREAD

**Issue by lancelothuxi** [apache/shardingsphere#29628]
## Bug Report

I have dynamic property in jdbc url as like :
```
jdbc:postgresql://localhost:5432/sharding_db01?ApplicationName=${HOSTNAME}
```
currently i run my application in docker container, the HOSTNAME is pod name, which is different for every pod,
it works fine in local mode, and the HOSTNAME is replaced by the pod name correctly, but in cluster mode(using zookeeper), the HOSTNAME
is keeping unchanged, I debuged the source code , find that the jdbc url is always replaced by the configure stored in zookeeper,

I also tried the following configure:
```yaml
  datasource:
      ds10: # 实例名称，自定义
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: org.postgresql.Driver
        jdbc-url: jdbc:postgresql://localhost:5432/sharding_db01
        password: mypassword
        username: myusername
        data-source-properties:
          "ApplicationName": ${HOSTNAME}
```
it works the same, is replaced with the config from zookeeper.
