### ISSUE TITLE
Wrong output when query contains  limit, group by and distinct combination

### ISSUE THREAD

**Issue by Afsalmc** [apache/shardingsphere#29841]
### Which version of ShardingSphere did you use?
5.4.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC
### Expected behavior
Query returns accurate results.
### Actual behavior
Actual Results, not number of rows returned depends on the limit specified after group by keyword.
### Reason analyze (If you can)
If the user entered query is :
`SELECT COUNT(distinct Id2),Id1 C1 FROM ACCOUNT GROUP BY Id1 LIMIT 10`

before querying in individual shards, the query gets converted into 
`SELECT distinct Id2,,Id1 C1 FROM ACCOUNT  LIMIT 10`

hence the combined output depends on the limit value, limit value no longer has just the control over the number of rows returned but it is influencing the actual data.
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
More than one Shards to reproduce the issue.

**Comment by strongduanmu** [comment]
Hi @Afsalmc, thank you for your feedback. Can you provide your configuration and table init sql to help us reproduce this bug?

**Comment by Afsalmc** [comment]
@strongduanmu 
```
dataSources:
  db0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.microsoft.sqlserver
    jdbcUrl: jdbc:sqlserver://db1.database.windows.net;databaseName=db1;loginTimeout=300;encrypt=false;
    username: adm
  db1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.microsoft.sqlserver
    jdbcUrl: jdbc:sqlserver://db11.database.windows.net;databaseName=db11;loginTimeout=300;encrypt=false;
    username: adm
rules:
  - !SQL_FEDERATION
    sqlFederationEnabled: true
    executionPlanCache:
      initialCapacity: 1000
      maximumSize: 4000
  - !SHARDING
    tables:
      ACCOUNT:
        actualDataNodes: dbo.Account,db1.Account
```
I haven't used any init SQL. The schema was already defined and I just connected using shardingsphere jdbc. I also noticed that  I'm only getting this weird behavior when the query contains Distinct keyword : 
`select count(DISTINCT accountid)
 as c,Stamp from dbo.Account 
group by stamp`

 Not when 
 `select count(accountid)
 as c,Stamp from Account 
group by stamp`
