### ISSUE TITLE
why binary operate does not rewrite to target table

### ISSUE THREAD

**Issue by ZmingZinnia** [apache/shardingsphere#29961]
## Question

The preview info:

![Screenshot 2024-02-02 at 13 29 20](https://github.com/apache/shardingsphere/assets/22904287/d2296e22-d464-4a6d-a8e1-3b4f178ae200)

My yaml file is configured:

```
rules:
  - !SHARDING
    tables:
      question_app:
        actualDataNodes: ds_0.question_app_${0..15}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: table_id_sharding
      question_step_app:
        actualDataNodes: ds_0.question_step_app_${0..15}
        tableStrategy:
          standard:
            shardingColumn: question_id
            shardingAlgorithmName: table_question_id_sharding
    bindingTables:
      - question_app
    shardingAlgorithms:
      table_id_sharding:
        type: INLINE
        props:
          algorithm-expression: question_app_${id % 16}
          allow-range-query-with-inline-sharding: true
      table_question_id_sharding:
        type: INLINE
        props:
          algorithm-expression: question_step_app_${question_id % 16}
          allow-range-query-with-inline-sharding: true
  - !SINGLE
    tables:
      - ds_0.user_app
      - ds_0.question_label
      - ds_0.question_step_label

```

Version: 5.4.1

I'm confused why `not table.deleted` doesn't rewrite to the subtable.
