### ISSUE TITLE
Can not create rule in standalone mode

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30046]
## Bug Report
### Which version of ShardingSphere did you use?
master d780817b1b89d40461e942cf84cfe39367535fb8

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Database config
```yaml
databaseName: test_db

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 5
    minPoolSize: 1
rules:
- !SINGLE
  tables:
    - "*.*"
```

### Execute DistSQL
```sql
mysql> show storage units;
+------+-------+-----------+------+-----------+---------------------------------+---------------------------+---------------------------+---------------+---------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| name | type  | host      | port | db        | connection_timeout_milliseconds | idle_timeout_milliseconds | max_lifetime_milliseconds | max_pool_size | min_pool_size | read_only | other_attributes                                                                                                                                                                                                                                                                                                                  |
+------+-------+-----------+------+-----------+---------------------------------+---------------------------+---------------------------+---------------+---------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| ds_0 | MySQL | 127.0.0.1 | 3306 | demo_ds_0 | 30000                           | 60000                     | 1800000                   | 5             | 1             | false     | {"healthCheckProperties":{},"initializationFailTimeout":1,"validationTimeout":5000,"keepaliveTime":0,"leakDetectionThreshold":0,"registerMbeans":false,"allowPoolSuspension":false,"autoCommit":true,"isolateInternalQueries":false,"queryProperties":{"allowPublicKeyRetrieval":"true","serverTimezone":"UTC","useSSL":"false"}} |
| ds_1 | MySQL | 127.0.0.1 | 3306 | demo_ds_1 | 30000                           | 60000                     | 1800000                   | 5             | 1             | false     | {"healthCheckProperties":{},"initializationFailTimeout":1,"validationTimeout":5000,"keepaliveTime":0,"leakDetectionThreshold":0,"registerMbeans":false,"allowPoolSuspension":false,"autoCommit":true,"isolateInternalQueries":false,"queryProperties":{"allowPublicKeyRetrieval":"true","serverTimezone":"UTC","useSSL":"false"}} |
+------+-------+-----------+------+-----------+---------------------------------+---------------------------+---------------------------+---------------+---------------+-----------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
2 rows in set (0.11 sec)

mysql> SHOW BROADCAST TABLE RULES;
Empty set (0.10 sec)

mysql> CREATE BROADCAST TABLE RULE t_province;
Query OK, 0 rows affected (0.09 sec)

mysql> SHOW BROADCAST TABLE RULES;
Empty set (0.01 sec)

mysql> CREATE BROADCAST TABLE RULE t_city;
Query OK, 0 rows affected (0.02 sec)

mysql> SHOW BROADCAST TABLE RULES;
Empty set (0.00 sec)
```
