### ISSUE TITLE
Unexpected line separator in convert result

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30042]
### Which version of ShardingSphere did you use?
master d780817b1b89d40461e942cf84cfe39367535fb8

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Description
When I use the following yaml to convert
```sql
CONVERT YAML CONFIGURATION FROM FILE "/xxx.yaml";
```

an unexpected line separator appears (see `t_order`).
 
- YAML
```yaml
databaseName: test_mysql
dataSources:
  ds_0:
    password: root
    dataSourceClassName: null
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    connectionTimeoutMilliseconds: 30000
    maxLifetimeMilliseconds: 1800000
    idleTimeoutMilliseconds: 60000
    maxPoolSize: 5
  ds_1:
    password: root
    dataSourceClassName: null
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    minPoolSize: 1
    connectionTimeoutMilliseconds: 30000
    maxLifetimeMilliseconds: 1800000
    idleTimeoutMilliseconds: 60000
    maxPoolSize: 5
rules:
- !SHARDING
  auditors:
    t_order_item_dml_sharding_conditions_0:
      type: DML_SHARDING_CONDITIONS
  autoTables:
    t_order:
      actualDataSources: ds_0,ds_1
      keyGenerateStrategy:
        column: another_id
        keyGeneratorName: t_order_snowflake
      logicTable: t_order
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_hash_mod
          shardingColumn: order_id
  keyGenerators:
    t_order_snowflake:
      type: snowflake
    t_order_item_snowflake:
      type: snowflake
  shardingAlgorithms:
    t_order_hash_mod:
      props:
        sharding-count: '4'
      type: hash_mod
    t_order_item_database_inline:
      props:
        algorithm-expression: ds_${user_id % 2}
      type: inline
    t_order_item_table_inline:
      props:
        algorithm-expression: t_order_item_${order_id % 2}
      type: inline
  tables:
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      auditStrategy:
        allowHintDisable: true
        auditorNames:
        - t_order_item_dml_sharding_conditions_0
      databaseStrategy:
        standard:
          shardingAlgorithmName: t_order_item_database_inline
          shardingColumn: user_id
      keyGenerateStrategy:
        column: another_id
        keyGeneratorName: t_order_item_snowflake
      logicTable: t_order_item
      tableStrategy:
        standard:
          shardingAlgorithmName: t_order_item_table_inline
          shardingColumn: order_id
```

- Result
<img width="869" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/da027fce-4371-4113-95e0-b37043cfbb6c">
