### ISSUE TITLE
MySQLStatementParser throws NullPointerException

### ISSUE THREAD

**Issue by godojoe** [apache/shardingsphere#30283]
I am trying to get started with ShardingSphere-Proxy, running against MySQL. I have used the config from the User Manual.
I am using IntelliJ DataGrip to successfully connect to the proxy, but cannot see my backend schemas.
I would expect DataGrip to show me the tables residing on my MySQL instances, but I only see system tables.
DataGrip reports this: 
`
Unknown column 'expression' in 'field list'. Unknown exception: Cannot invoke "org.antlr.v4.runtime.tree.TerminalNode.getText()" because the return value of "org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$IdentifierContext.IDENTIFIER_()" is null. Table or view `role_edges` does not exist. and 25 duplicate reports`

The Proxy logs are filed with messages like this:
```
java.lang.NullPointerException: Cannot invoke "org.antlr.v4.runtime.tree.TerminalNode.getText()" because the return value of "org.apache.shardingsphere.sql.parser.autogen.MySQLStatementParser$IdentifierContext.IDENTIFIER_()" is null
2024-02-25 11:53:46     at org.apache.shardingsphere.sql.parser.mysql.visitor.statement.MySQLStatementVisitor.visitFunctionName(MySQLStatementVisitor.java:365)
```

My config:
ShardingSphere-Proxy:5.4.1
MySql 8.3.0
driver under ext-lib/ : mysql-connector-java-8.0.28-8.3p2

**_server.yaml:_**
```
authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
```
	  

**_global.yaml:_**
```
sql-show: true
sqlParser:
  sqlStatementCache:
    initialCapacity: 2000
    maximumSize: 65535
  parseTreeCache:
    initialCapacity: 128
    maximumSize: 1024

transaction:
  defaultType: XA
  providerType: Atomikos

    
sqlTranslator:
  type:
  useOriginalSQLWhenTranslatingFailed:

sqlFederation:
  sqlFederationEnabled: true
  allQueryUseSQLFederation: false
  executionPlanCache:
    initialCapacity: 2000
    maximumSize: 65535
```

**_config-sharding:_**
```
schemaName: sharding_risk_db

dataSources:
  ds_0:
    url: jdbc:mysql://h2_risk-mysql0-1:3306/risk
    username: riskuser
    password: *
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_1:
    url: jdbc:mysql://h2_risk-mysql1-1:3306/risk
    username: riskuser
    password: *
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds_2:
    url: jdbc:mysql://h2_risk-mysql2-1:3306/risk
    username: riskuser
    password: *
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```
