### ISSUE TITLE
Incorrect result for convert single rule configuration

### ISSUE THREAD

**Issue by RaigorJiang** [apache/shardingsphere#30618]
Related to #30496, #30544

### Which version of ShardingSphere did you use?
master 540453f6d00ff4c325edcb347ae3f738f2b82021

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
When convert single rule configuration, the generated DistSQL statement is correct

#### YAML
```yaml
databaseName: sharding_db
dataSources:
  ds_0:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    maxPoolSize: 10
  ds_1:
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    maxPoolSize: 10
rules:
- !SHARDING
  autoTables:
    t_order:
      actualDataSources: ds_0,ds_1
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: t_order_snowflake
      logicTable: t_order
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_mod
          shardingColumn: order_id
  keyGenerators:
    t_order_snowflake:
      type: snowflake
  shardingAlgorithms:
    t_order_mod:
      props:
        sharding-count: '4'
      type: mod
- !SINGLE
  tables:
  - ds_0.t_address
  - ds_0.sbtest1
```

#### Convert result
<img width="767" alt="image" src="https://github.com/apache/shardingsphere/assets/5668787/ef6c2707-8c5d-4036-b744-f9fe1ca026ca">
