### ISSUE TITLE
org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `t_template_2` does not exist

### ISSUE THREAD

**Issue by Basil1991** [apache/shardingsphere#30740]
## Bug Report
org.apache.shardingsphere.infra.exception.TableNotExistsException: Table or view `t_template_2` does not exist

### Which version of ShardingSphere did you use?

5.4.1 
springboot 2.7.18

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

shardingsphere

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
``` yaml
dataSources:
  ds_master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://192.168.35.194:19922/template?currentSchema=service_a
    username: x
    password: x
  ds_slave:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://192.168.35.194:19922/template?currentSchema=service_a_read
    username:  x
    password:  x
  # Configure other data sources
rules:
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        writeDataSourceName: ds_master
        readDataSourceNames:
          - ds_slave
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: random
    loadBalancers:
      random:
        type: RANDOM
  - !SINGLE
    tables:
      - "*.*.*"
    defaultDataSource: ds_master 

props:
  sql-show: true
```
