### ISSUE TITLE
database-strategy:none not working

### ISSUE THREAD

**Issue by sui6666666** [apache/shardingsphere#30818]
spring boot 2.3.7.RELEASE + sharding-jdbc 5.2.1 + mybatis plus 3.5.3.1

application.yml
```

spring:
  shardingsphere:
    mode:
      type: Standalone
      repository:
        type: JDBC
    datasource:
      names: master,ds0,ds1,dss0,dss1
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_0?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_1?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      dss0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_2?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root
      dss1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/ds_3?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
        username: root
        password: root


    rules:
      sharding:

        tables:
          user:
            actual-data-nodes: ds$->{0..1}.user,dss$->{0..1}.user
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
          suilang:
            actual-data-nodes: master.suilang
            database-strategy:
              none: null
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        broadcast-tables: sys_dic
        default-database-strategy:
          standard:
            sharding-column: id
            sharding-algorithm-name: database-precise-algorithm
#          hint:
#            sharding-algorithm-name: database-hint-algorithm
        sharding-algorithms:
          database-precise-algorithm:
            type: CLASS_BASED
            props:
              strategy: STANDARD
              algorithmClassName: com.cxytiandi.sharding.algorithm.CustomPreciseShardingAlgorithm
          database-hint-algorithm:
            type: CLASS_BASED
            props:
              strategy: HINT
              algorithmClassName: com.cxytiandi.sharding.algorithm.CustomHintShardingAlgorithm
        key-generators:
          snowflake:
            type: SNOWFLAKE
    props:
      sql-show: true




```

CustomPreciseShardingAlgorithm.java
```
public class CustomHintShardingAlgorithm implements HintShardingAlgorithm<String> {


	@Override
	public Collection<String> doSharding(Collection<String> collection, HintShardingValue<String> hintShardingValue) {
		Collection<String> values = hintShardingValue.getValues();
		String dbName = values.stream().findFirst().orElseThrow(() -> new IllegalArgumentException("发生异常"));
		return values;
	}

	@Override
	public Properties getProps() {
		return null;
	}

	@Override
	public void init(Properties properties) {

	}
}
```

the single talbe suilang only exsit in database master;
when I excute insert statement to suilang table,

When I execute the insert statement  to table suilang, even though I have configured the suilang table database sharding to be None, it still goes to the default database sharding algorithm
