### ISSUE TITLE
AutoTables doesn't work as expected

### ISSUE THREAD

**Issue by gejing1108** [apache/shardingsphere#30998]
## Bug Report

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please answer these questions before submitting your issue. Thanks!

Which version of ShardingSphere did you use?
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc-core</artifactId>
           <version>5.4.1</version>
        </dependency>

Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

Expected behavior
my config file is like this:
```
mode: # 不配置则默认单机模式
  type: Standalone # 运行模式类型。可选配置：Standalone、Cluster
  repository:
    type: JDBC # 持久化仓库类型 如果你选择集群方式，那么可以使用zk、nacos等注册中心

dataSources:
  ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/cms?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding1?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding2?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456

rules:
  - !SINGLE
    tables:
      - ds.* # Load specified single table
    defaultDataSource: ds # The default data source is used when executing CREATE TABLE statement to create a single table. The default value is null, indicating random unicast routing.

  - !SHARDING
    tables:
      t_order:
        actualDataNodes: ds_${0..1}.t_order_${0..2}
        databaseStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_db_inline
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: t_order_inline
        keyGenerateStrategy:
          column: order_id
          keyGeneratorName: snowflake
        auditStrategy:
          auditorNames:
            - sharding_key_required_auditor
          allowHintDisable: true
    autoTables: # 自动分片表规则配置
      t_user: # 逻辑表名称
        actualDataSources: ds_${0..1} # 数据源
        shardingStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: t_user_auto_hashmod
        keyGenerateStrategy:
          column: user_id
          keyGeneratorName: snowflake
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      t_user_auto_hashmod:
        type: MOD
        props:
          sharding-count: 3
      t_order_db_inline:
        type: INLINE
        props:
          algorithm-expression: ds_${order_id % 2}
      t_order_inline:
        type: INLINE
        props:
          algorithm-expression: t_order_${order_id % 3}
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
    auditors:
      sharding_key_required_auditor:
        type: DML_SHARDING_CONDITIONS

props:
  sql-show: true
```

using database ds_0 and ds_1 for sharding, each of the database has six tables: t_order_0, t_order_1, t_order_2, t_user_0, t_user_1, t_user_2, and use the INLINE type for t_order_XXX, and use the MOD type(autoTables) for t_user_XXX, and I try to insert 100 records each for t_order_XXX and t_user_XXX

btw, in this article 
https://shardingsphere.apache.org/blog/cn/material/oct_12_6_autotable_your_butler-like_sharding_configuration_tool
it suggests 8 database and 4 tables each, the sharding-count should be 8 * 4  = 32, while actually, in my case, 2 database and 3 tables each, I should set the  sharding-count 2 * 3  = 6, but if I do it, I'll get the error message:

Caused by: java.sql.SQLSyntaxErrorException: Table 'sharding2.t_user_5' doesn't exist
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)

so I've to set the sharding-count to 3

Actual behavior
for the table t_order_XXX, I get the right result, the 100 records will be restored in 6 tables according to my databaseStrategy and tableStrategy
while for the table t_user_XXX,  I can only find the 100 records in ds_0.t_user_0, ds_0.t_user_2 and ds_1.t_user_1

Two issues:
1. the blog above is written by official member of shardingsphere
https://shardingsphere.apache.org/blog/cn/material/oct_12_6_autotable_your_butler-like_sharding_configuration_tool
but why the sharding-count can not be 2 * 3 = 6 in my case?
2. how should I modify the config if I want the t_user_XXX has the same sharding behavior with t_order_XXX, as I want to use the autoTables config?
