### ISSUE TITLE
Unknown column error with ENCRYPT

### ISSUE THREAD

**Issue by gejing1108** [apache/shardingsphere#31095]
### Which version of ShardingSphere did you use?
5.4.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
I've a table named t_fans in database cms, I wanna try for the encrypt function in shardingsphere, the config file is like this:
```
mode: # 不配置则默认单机模式
  type: Standalone # 运行模式类型。可选配置：Standalone、Cluster
  repository:
    type: JDBC # 持久化仓库类型 如果你选择集群方式，那么可以使用zk、nacos等注册中心

dataSources:
  ds:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/cms?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding1?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/sharding2?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: g@123456

rules:
  - !SINGLE
    tables:
      - ds.* # Load specified single table
    defaultDataSource: ds # The default data source is used when executing CREATE TABLE statement to create a single table. The default value is null, indicating random unicast routing.

  - !SHARDING
    tables:
      ....  ignore, nothing to do with t_fans

  - !ENCRYPT
    tables:
      t_fans:
        columns:
          fans_name:
            cipher:
              name: fans_name
              encryptorName: aes_encryptor
            assistedQuery:
              name: fans_name_assist
              encryptorName: assisted_encryptor
            likeQuery:
              name: fans_name_like
              encryptorName: like_encryptor
          password:
            cipher:
              name: password
              encryptorName: aes_encryptor
    encryptors:
      aes_encryptor:
        type: AES
        props:
          aes-key-value: gesanri
      assisted_encryptor:
        type: MD5
      like_encryptor:
        type: CHAR_DIGEST_LIKE
props:
  sql-show: true
```
### Actual behavior
the insert operation works, the data has been inserted into the table successfully
<img width="1015" alt="image" src="https://github.com/apache/shardingsphere/assets/126172599/04fe3109-170c-403d-abee-1669fab2227d">
while, when I try to query record from the database
```
@Service
public class FansServiceImpl extends ServiceImpl<FansMapper, FansEntity> implements FansService {

  @Override
  public FansEntity getFansInfo(Long fansId) {
    return lambdaQuery().eq(FansEntity::getFansId, fansId).one();
  }
}
```
I get this error:
`Caused by: org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.infra.exception.UnknownColumnException: Unknown column 'fans_name_assist' in 'field list'.`
I've no idea why I get this error, as the column exists in the table
