### ISSUE TITLE
shardingsphere jdbc 5.2.1 custom standard sharding not available

### ISSUE THREAD

**Issue by stqf** [apache/shardingsphere#31105]
### Development environment

![image](https://github.com/apache/shardingsphere/assets/33819174/ede4e5ca-e47c-4ab8-ac9d-fae739996fca)

application.yml

```yml
server:
  port: 15086
spring:
  shardingsphere:
    enabled: true
    mode:
      type: Standalone
    props:
      sql-show: true
      sql-simple: true
      kernel-executor-size: 8
    database:
      name: hello
    datasource:
      names: hello
      amps:
        username: root
        password: *******
        jdbc-url: jdbc:mysql://127.0.0.1:3306/hello?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
        type: com.zaxxer.hikari.HikariDataSource
        poolName: HikariPool
        minPoolSize: 4
        maxPoolSize: 8
        maxLifetimeMilliseconds: 120000
    rules:
      sharding:
        tables:
          asm_hist:
            logic-table: tbl_esm_hist
            actual-data-nodes: hello.tbl_esm_hist
            database-strategy:
              none:
            table-strategy:
              standard:
                sharding-column: 'ts'
                sharding-algorithm-name: asm_hist_algo
        #default-database-strategy:
        #  none:
        #default-table-strategy:
        #  none:
        sharding-algorithms:
          asm_hist_algo:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.anian.hello.swm.alpha.handler.EventStandardShardingHandler
```

EventStandardShardingHandler.java

![image](https://github.com/apache/shardingsphere/assets/33819174/c783cdc2-d367-45ae-84b7-9a3e9a07de81)

main

![image](https://github.com/apache/shardingsphere/assets/33819174/24ab2274-feb7-49a7-8b5a-1dfb9bf2d580)

logger

![image](https://github.com/apache/shardingsphere/assets/33819174/c2a60caf-ea33-4710-ae54-64752370ebbd)
