### ISSUE TITLE
Optimize the number of node record rows with JDBC repository in Standalone mode

### ISSUE THREAD

**Issue by zhaojinchao95** [apache/shardingsphere#31372]
global.yaml：

```
mode:
  type: Standalone
  repository:
    type: JDBC
    props:
      provider: MySQL
      jdbc_url: jdbc:mysql://localhost:3306/test
      username: root
      password: 123456
```

DistSQL：

```
REGISTER STORAGE UNIT ds_0 (
    HOST="127.0.0.1",
    PORT=3306,
    DB="test",
    USER="root",
    PASSWORD="123456"
);

CREATE MASK RULE t_mask (
COLUMNS(
(NAME=phone_number,TYPE(NAME='MASK_FROM_X_TO_Y', PROPERTIES("from-x"=1, "to-y"=2, "replace-char"="*"))),
(NAME=address,TYPE(NAME='MD5'))
));

DROP MASK RULE t_mask;
```

<img width="839" alt="image" src="https://github.com/apache/shardingsphere/assets/33742097/828147d9-e689-44a9-89d7-93bdd9736b2e">

According to the picture above, there are still many remaining node records that have not been cleared.
