### ISSUE TITLE
ShardingSphere-Proxy: Error Code: 1146. Table '*' doesn't exist

### ISSUE THREAD

**Issue by 280780363** [apache/shardingsphere#31589]
- db: mysql 8.0
 - sharding sphere version ,docker image: apache/shardingsphere-proxy:5.5.0
 - bug description: 
 when execute this sql response this error: Error Code: 1146. Table 'eqms_sharding_test.feature_data' doesn't exist
 ```sql
select count(*) from feature_data  where  date_stamp < '2017-03-16 09:07:23' and date_stamp > '2017-03-15 09:07:23';
```

but execute this sql is ok.
```sql
select * from feature_data limit 1;
```

this is my config `config-eqms_sharding_test.yaml`:
```yaml
databaseName: eqms_sharding_test
dataSources:
  eqms_sharding_test:
    url: jdbc:mysql://*/eqms_sharding_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: ***

rules:
  - !SHARDING
    tables:
      feature_data:
        actualDataNodes: eqms_sharding_test.feature_data_${201706..201713}
        tableStrategy:
          standard:
            shardingColumn: date_stamp
            shardingAlgorithmName: week-algorithms
        keyGenerateStrategy:
          column: feature_data_id
          keyGeneratorName: snowflake
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
    shardingAlgorithms:
      week-algorithms:
        type: INTERVAL
        props:
          datetime-pattern: "yyyy-MM-dd HH:mm:ss" # 分片字段格式
          datetime-lower: "2024-01-01 00:00:00" # 范围下限
          datetime-upper: "2024-06-30 23:59:59" # 范围上限
          sharding-suffix-pattern: "yyyyww" # 分片名后缀，可以是MM，yyyyMMdd等。
          datetime-interval-amount: 1 # 分片间隔，这里指一个月
          datetime-interval-unit: "WEEKS" # 分片间隔单位

```

this is my sharding table , it's contains many data.
![image](https://github.com/apache/shardingsphere/assets/20083278/7df4684d-dc44-41ab-9b95-5cdff3abfecd)
