### ISSUE TITLE
 "partition by"  get unexpected rows

### ISSUE THREAD

**Issue by 280780363** [apache/shardingsphere#31608]
- db: mysql 8.0
 - sharding sphere version ,docker image: apache/shardingsphere-proxy:5.5.0
- sharding rule config:
```yaml
- !SHARDING
  tables:
    feature_data:
      actualDataNodes: eqms_sharding_test.feature_data_${201706..201713}
      tableStrategy: 
        standard:
          shardingColumn: date_stamp
          shardingAlgorithmName: week-algorithms
      keyGenerateStrategy:
        column: feature_data_id
        keyGeneratorName: snowflake
    waveform_data:
      actualDataNodes: eqms_sharding_test.waveform_data_${201706..201713}
      tableStrategy: 
        standard:
          shardingColumn: date_stamp
          shardingAlgorithmName: week-algorithms
      keyGenerateStrategy:
        column: waveform_data_id
        keyGeneratorName: snowflake
    operation_data:
      actualDataNodes: eqms_sharding_test.operation_data_${201706..201713}
      tableStrategy: 
        standard:
          shardingColumn: date_stamp
          shardingAlgorithmName: week-algorithms
      keyGenerateStrategy:
        column: operation_data_id
        keyGeneratorName: snowflake
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
  shardingAlgorithms:
    week-algorithms:
      type: INTERVAL
      props:
        datetime-pattern: "yyyy-MM-dd HH:mm:ss"  # 分片字段格式
        datetime-lower: "2017-01-01 00:00:00"  # 范围下限
        datetime-upper: "2038-12-30 23:59:59"  # 范围上限
        sharding-suffix-pattern: "yyyyww"  # 分片名后缀，可以是MM，yyyyMMdd等。
        datetime-interval-amount: 1  # 分片间隔，这里指一个月
        datetime-interval-unit: "WEEKS" # 分片间隔单位
```
 - bug description: 
 when i use "partition by" in select field, i got unexpected rows, my shading rule is by "WEEKS", and this query should be use tables "feature_data_201710/feature_data_201711/operation_data_201710/operation_data_201711"

this is my expected rows from really table:
![image](https://github.com/apache/shardingsphere/assets/20083278/ab101e6e-00bf-4317-9d61-79744492b494)
but i got  only one row from sharding table:
![image](https://github.com/apache/shardingsphere/assets/20083278/20f30c9f-4ece-4696-aeea-ee8a3ac537bf)

this is sql log:
![image](https://github.com/apache/shardingsphere/assets/20083278/8cfc7c2a-4707-4181-9efe-15a61e73b5f1)

It is interesting that if use rownumber() can be got expected rows:
![image](https://github.com/apache/shardingsphere/assets/20083278/3ec32342-2bb1-4424-bf89-2a0cd16160ea)

I guess it's because the aggregate function and the patition by grouping caused the result to only return the first item.
