### ISSUE TITLE
How to configure shardingsphere to support BASE transaction model with Seata?

### ISSUE THREAD

**Issue by bobbyz007** [apache/shardingsphere#31667]
## Question
There's no official sample of this kind, I have configured the following but can't rollback, so could anyone provide a sample? thx.
shardingsphere: 5.5.0
seata: 2.1.0
```
...
transaction:
  defaultType: BASE
  providerType: Seata

#打印sql
props:
  sql-show: true
```
