### ISSUE TITLE
config by yaml，how to refrence to dataSource by spring xml（or spring boot）

### ISSUE THREAD

**Issue by minshiwu** [apache/shardingsphere#31702]
In the official documentation, Configure sharding-Jdbc through yaml.  dataSource must define in shardingSphere yaml 。
if my project(spring xml or spring boot) have already define some dataSource.  when integrate sharding-Jdbc by yaml configuration way, can refrence  to already  exsted dataSource?   what should I do?

The following is the official sample for config dataSource in yaml.
```yaml
dataSources:
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds_1
    username: root
    password:
  ds_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/ds_2
    username: root
    password:
```
