### ISSUE TITLE
insert into cipherTable select from plainTable is not support

### ISSUE THREAD

**Issue by xigongxiaoche** [apache/shardingsphere#31776]
## Bug Report
Insert the query results of the plaintext table into the ciphertext table, but only plaintext is inserted
sql:
INSERT INTO TEST_INSERT(NAME) SELECT NAME NAME FROM TEST_SELECT

database:
    oracle11g
    mysql8.0.33
encrypt rule:
```
rules:
  - !ENCRYPT
    tables:
      TEST_INSERT:
        columns:
          name:
            cipher:
              name: NAME
              encryptorName: aes_encryptor
    encryptors:
      aes_encryptor:
        type: AES
        props:
          aes-key-value: 123456abc
```

### Which version of ShardingSphere did you use?
5.3.2 5.4.1 5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
ciphertext in TEST_INSERT 
### Actual behavior
plaintext in TEST_INSERT 
### Reason analyze (If you can)
EncryptInsertValuesTokenGenerator.isGenerateSQLToken() return false 
because of (((InsertStatementContext) sqlStatementContext).getSqlStatement()).getValues().isEmpty() return true
**Select insert SQL does not have actual data in this format of SQL**
