### ISSUE TITLE
ShardingJDBC is not supported p6spy driver，add p6spy driver support to ShardingJDBC infra

### ISSUE THREAD

**Issue by lcjing** [apache/shardingsphere#31782]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.5.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
can normal connection to the database

### Actual behavior
org.apache.shardingsphere.infra.database.core.exception.UnsupportedStorageTypeException: Unsupported storage type of URL 'jdbc:p6spy:mysql://xxx:3306?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8'.

### Reason analyze (If you can)
ShadingJDBC jbdcUrl prefix not supproted jdbc:p6spy:mysql://

### Example codes for reproduce this issue (such as a github link).
```yaml
dataSources:
  db_test:
    dataSourceClassName: org.apache.tomcat.jdbc.pool.DataSource
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:mysql://xxx:3306?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8
    username: u_dev
    password: xxx
```
