### ISSUE TITLE
Table or view `t_ent_order` does not exist

### ISSUE THREAD

**Issue by v8v6** [apache/shardingsphere#31836]
Hello,Thank you for helping me with this issue

version：5.4.1
springboot：2.5.15
snakeyaml：1.33

```
dataSources:
  ds0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds0?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root
  ds3:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/ds3?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&useTimezone=true
    username: root
    password: root

rules:
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: ds0
  - !SHARDING
    tables:
      t_ent_order:
        actualDataNodes: ds0.t_ent_order_${0..2}
        databaseStrategy:
          complex:
            shardingColumns: id,ent_id
            shardingAlgorithmName: hash-slot-algorithm
      t_ent_order_detail:
        actualDataNodes: ds0.t_ent_order_detail_${0..2}
        databaseStrategy:
          complex:
            shardingColumns:  id,ent_id
            shardingAlgorithmName: hash-slot-algorithm
      t_ent_order_item:
        actualDataNodes: ds0.t_ent_order_item_${0..7}
        tableStrategy:
          complex:
            shardingColumns: id,ent_id
            shardingAlgorithmName: hash-slot-table-algorithm
    bindingTables:
      - t_ent_order,t_ent_order_detail

    shardingAlgorithms:
      hash-slot-algorithm:
        type: CLASS_BASED
        props:
          strategy: complex
          algorithmClassName: cn.javayong.shardingjdbc5.spring.common.sharding.HashSlotAlgorithm
      hash-slot-table-algorithm:
        type: CLASS_BASED
        props:
          strategy: complex
          algorithmClassName: cn.javayong.shardingjdbc5.spring.common.sharding.HashSlotAlgorithm
          directIndex: true


props:
  sql-show: true
```
