### ISSUE TITLE
change authority config and restart shardingsphere-proxy, not work

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#31900]
## Question

**For English only**, other languages will not accept.

I change global.yaml authority config
```
authority:
  users:
    - user: root
      password: Qwer1234
```

```
authority:
  users:
    - user: root
      password: Qwer@123
```

but only root Qwer1234 can connect to shardingsphere-proxy.

How to do can change authority?

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

shardingsphere-proxy: 5.5.0
zookeeper:  3.9.2
