### ISSUE TITLE
hintManager.addTableShardingValue ，No effect

### ISSUE THREAD

**Issue by robben009** [apache/shardingsphere#32056]
shardingsphere-jdbc  5.5.0 version

```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: *
    username: *
    password: *

rules:
  - !SINGLE
    tables:
      - "*.*"
    defaultDataSource: ds_0
  - !SHARDING
    tables:
      test_order:
        actualDataNodes: ds_0.test_order_${0..1}
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: OrderShardingRules
    bindingTables:
      - test_order
    shardingAlgorithms:
      OrderShardingRules:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: *
```

Then I use the following code

```
    @PostMapping("/order")
    public TestOrder order() {
        HintManager hintManager = HintManager.getInstance();
        hintManager.addTableShardingValue("test_order", 100);

        TestOrder t = testOrderService.getOne(new LambdaQueryWrapper<TestOrder>()
                .eq(TestOrder::getUserId, "100")
                .eq(TestOrder::getOrderStatus, 40), false);
        hintManager.clear();

        return t;
    }
```

I found that no matter how " hintManager.addTableShardingValue("test_order", 100);"   is written, data can be found,It's like a full table scan

Why is this？
