### ISSUE TITLE
Recursive query logic table times error：Table or view 'tmp' does not exist.

### ISSUE THREAD

**Issue by yyyyyyyysssss** [apache/shardingsphere#32189]
version:
```
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc</artifactId>
            <version>5.5.0</version>
</dependency>
```

```
sharding.yaml：
mode:
  type: Standalone
  repository:
    type: JDBC
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ***
    password: ***
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 0
    keepaliveTime: 300000
    maxLifetime: 1800000
    minimumIdle: 5
    maximumPoolSize: 50
  slave0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/im?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false&useLegacyDatetimeCode=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: ***
    password: ***
    autoCommit: true
    connectionTimeout: 30000
    idleTimeout: 0
    keepaliveTime: 300000
    maxLifetime: 1800000
    minimumIdle: 5
    maximumPoolSize: 50

rules:
  - !SINGLE
    tables:
      - "*.*"
  - !READWRITE_SPLITTING
    dataSources:
      readwrite_ds:
        writeDataSourceName: master
        readDataSourceNames:
          - slave0
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: roundRobin
    loadBalancers:
      roundRobin:
        type: ROUND_ROBIN

props:
  sql-show: true
```

execute sql:
```
WITH RECURSIVE tmp as (
SELECT t.* FROM im_authority t WHERE t.id = #{}
UNION ALL
SELECT f.* FROM im_authority f INNER JOIN tmp on f.parent_id = tmp.id
) select * from tmp
```
