### ISSUE TITLE
The collected system metadata is not cleared when database is droped

### ISSUE THREAD

**Issue by jiangML** [apache/shardingsphere#32407]
## Feature Request

**For English only**, other languages will not be accepted.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

+ global.yaml
```yaml
mode:
  type: Cluster
  repository:
    type: ZooKeeper
    props:
      namespace: pg_test
      server-lists: localhost:2181
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500

authority:
  users:
    - user: root@%
      password: root
    - user: sharding
      password: sharding
  privilege:
    type: ALL_PERMITTED
  
props:
  proxy-default-port: 15432
  proxy-meta-data-collector-enabled: true
  proxy-frontend-database-protocol-type: PostgreSQL
```

Drop database _db and test_db_1, but do not clear the collected system metadat

+ Content of ZooKeeper
![image](https://github.com/user-attachments/assets/15ebe51f-fdb8-465c-8a35-f2c4f47dfaaa)

### Describe the feature you would like.

Clear the system metadata of the corresponding database
