### ISSUE TITLE
readwrite-splitting-problem

### ISSUE THREAD

**Issue by janlee151** [apache/shardingsphere#32804]
@terrymanu 
### springboot project
pom shardingsphere dependency: **shardingsphere-jdbc-core-spring-boot-starter  version5.2.0**
my application.yaml config file as follows：
```
spring:
  shardingsphere:
    datasource: #配置数据源
      names: master,slave1,slave2
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/master?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: ******
        initial-size: 1
        max-active: 20
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 50
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        min-idle: 1
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        validation-query: slect 1 from dual
        keep-alive: true
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave1?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: ******
        initial-size: 1
        max-active: 20
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 50
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        min-idle: 1
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        validation-query: slect 1 from dual
        keep-alive: true
      slave2:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/slave2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: root
        password: ******
        initial-size: 1
        max-active: 20
        max-open-prepared-statements: 20
        max-pool-prepared-statement-per-connection-size: 50
        max-wait: 60000
        min-evictable-idle-time-millis: 300000
        min-idle: 1
        pool-prepared-statements: true
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
        validation-query: slect 1 from dual
        keep-alive: true
    mode:
      type: Standalone
    database:
      name: readwrite_ds
    rules:
      readwrite-splitting:
        data-sources:
          readwrite_ds:
            load-balancer-name: round_robin
            static-strategy:
              read-data-source-names: slave1,slave2
              write-data-source-name: master
        load-balancers:
          round_robin:
            type: ROUND_ROBIN
    props:
      sql-show: true
```
here is my test case:
```
//**mybatis-plus**

 @Test
    public void readWriteSplitting() {
         TUser user = new TUser();
         user.setUserName("tom");
         user.setAge(20);
         userService.save(user);
   }
```
master database table t_user has data:

![image](https://github.com/user-attachments/assets/aeebb83e-8bc4-4017-a67a-054c149ba79f)
but slave1 and slave2 has no data:
![image](https://github.com/user-attachments/assets/af010f17-0da3-4b72-a6e1-0b57d763e5e3)
**master and slave has not sync data，i don't know where is wrong?**
