### ISSUE TITLE
ShardingProxy 5.5.0 version based on SQL Hint shadow library routing is not effective.

### ISSUE THREAD

**Issue by liuli12345** [apache/shardingsphere#33044]
Version 5.2.1 is good, but after upgrading to version 5.5.0, shadow library stress testing based on SQL Hint does not take effect, but data source transparency is good.

**The configuration of the database shadow.YAML in version 5.5.0 is as follows:**

```
databaseName: shadow_db
dataSources:
 ds:
   url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&useSSL=false
   username: root
   password: xxx
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 shadow_ds:
   url: jdbc:mysql://localhost:3306/user_shadow?serverTimezone=UTC&useSSL=false
   username: root
   password: xxx
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !SINGLE
 tables:
   - "*.*"
 defaultDataSource: ds
- !SHADOW
  dataSources:
    shadowDataSource:
      productionDataSourceName: ds
      shadowDataSourceName: shadow_ds
  defaultShadowAlgorithmName: sql_hint_algorithm
  shadowAlgorithms:
    sql_hint_algorithm:
      type: SQL_HINT
```

**Shadow library stress test SQL (not effective):**
```
/* SHARDINGSPHERE_HINT: SHADOW=true */ SELECT * FROM t_user;
```

**Data source transparent SQL (effective):**
```
/* SHARDINGSPHERE_HINT: DATA_SOURCE_NAME=shadow_ds*/ SELECT * FROM t_user;
```

Please help analyze where the problem lies. Thank you very much
