### ISSUE TITLE
ShardingProxy 5.5.0 version:  SQL cannot to be routed to the shadow database data source for execution.

### ISSUE THREAD

**Issue by liuli12345** [apache/shardingsphere#33045]
Version 5.2.1 is good, but after upgrading to version 5.5.0, SQL cannot to be routed to the shadow database data source for execution.

**database-shadow.YAML**
```
databaseName: shadow_db
dataSources:
 ds:
   url: jdbc:mysql://localhost:3306/user?serverTimezone=UTC&useSSL=false
   username: root
   password: xxx
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1
 shadow_ds:
   url: jdbc:mysql://localhost:3306/user_shadow?serverTimezone=UTC&useSSL=false
   username: root
   password: xxx
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
   minPoolSize: 1

rules:
- !SINGLE
 tables:
   - "*.*"
 defaultDataSource: ds
- !SHADOW
  dataSources:
    shadowDataSource:
      productionDataSourceName: ds
      shadowDataSourceName: shadow_ds
  defaultShadowAlgorithmName: sql_hint_algorithm
  shadowAlgorithms:
    sql_hint_algorithm:
      type: SQL_HINT
```

An example of using shadow SQL Hint:
```
/* SHARDINGSPHERE_HINT: SHADOW=true */ SELECT * FROM t_user;
```
