### ISSUE TITLE
org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables

### ISSUE THREAD

**Issue by WindShadowTrace** [apache/shardingsphere#33325]
version:
springboot + postgresql + shardingsphere5.3

```
dataSources:
    db_0:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://xx:5432/bss_center?currentSchema=qh_bsscenter_0971&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: qh_xx
        password: qh_xx
    db_1:
        dataSourceClassName: com.zaxxer.hikari.HikariDataSource
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://xx:5432/bss_center?currentSchema=qh_bsscenter_999&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
        username: qh_xx
        password: qh_xx
rules:
- !SHARDING
    tables:
        tb_eshop_order_oao_base: 
            actualDataNodes: db_$->{0..1}.tb_eshop_order_oao_base_$->{0..2}  
            databaseStrategy:
                standard:  
                    shardingColumn: fdb_city_code   
                    shardingAlgorithmName: his_city_code_sharding
            tableStrategy:
                standard:  
                    shardingColumn: order_number   
                    shardingAlgorithmName: his_ordernumber_sharding
    shardingAlgorithms:  
        his_city_code_sharding: 
            type: PRECISE_CITY_CODE_BASED
        his_ordernumber_sharding:
            type: PRECISE_ORDER_ORDERNUMBER_BASED
        defaule_sharding:
            type: PRECISE_DEFAULT_BASED
    keyGenerators:  
        snowflake:
            type: SNOWFLAKE
props:
    sql-show: true  
```

desc:
When performing an order by sorting query on the shard table, the following error is reported. When looking at the code, it is found that for PostgreSQL type databases, the default schema is public, and data is obtained in public based on the shard table name. However, schema.public

There's nothing in it, is there any special configuration to be made for the shard table

![图片](https://github.com/user-attachments/assets/38eda609-0dc6-41ae-acd0-9645200266ec)

Caused by: java.lang.NullPointerException: null
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitiveFromTables(OrderByValue.java:74)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.getOrderValuesCaseSensitive(OrderByValue.java:64)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByValue.<init>(OrderByValue.java:58)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.orderResultSetsToQueue(OrderByStreamMergedResult.java:56)
	at org.apache.shardingsphere.sharding.merge.dql.orderby.OrderByStreamMergedResult.<init>(OrderByStreamMergedResult.java:50)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.build(ShardingDQLResultMerger.java:100)
	at org.apache.shardingsphere.sharding.merge.dql.ShardingDQLResultMerger.merge(ShardingDQLResultMerger.java:71)
	at org.apache.shardingsphere.infra.merg
