### ISSUE TITLE
Enhance autoTables API to support more flexible sharding rules

### ISSUE THREAD

**Issue by strongduanmu** [apache/shardingsphere#33364]
### Is your feature request related to a problem?

#33341

### Describe the feature you would like.

In #33341, We temporarily removed the `ShardingRouteAlgorithmException` check logic to support storing different sharding tables in different database, but this may affect the normal check logic, for example: there is a problem with the sharding algorithm itself, resulting in routing to non-existent nodes.

A better way to support this is to refer to the existing autoTables usage and allow users to configure `actualDataNodes`. It is only necessary to ensure that the actual table name in actualDataNodes is globally unique, so that the sharding algorithm can directly find the corresponding database and table information based on actual table name. The traditional `databaseStrategy` and `tableStrategy` add more stringent configuration checks and do not allow irregular table sharding when it's under database sharding, because table sharding is based on database sharding logic.

The new configuration might look like this:

```yaml
- !SHARDING
  autoTables:
    t_order:
      actualDataNodes: ds_${0}.t_order_${0..3},ds_${1}.t_order_${4..7}
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: t_order_snowflake
      logicTable: t_order
      shardingStrategy:
        standard:
          shardingAlgorithmName: t_order_mod
          shardingColumn: order_id
```
