### ISSUE TITLE
The TPS (Transactions Per Second) of the proxy has decreased by half.

### ISSUE THREAD

**Issue by dobet** [apache/shardingsphere#33443]
## Question

**For English only**, other languages will not accept.

Before asking a question, make sure you have:

- Googled your question.
- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

use proxy 5.5.0 add a new module.
test
sysbench --> proxy --> mysql 
sysbench --> mysql

TPS，QPS decreased by half.

place help me see why ?

this is firegrpah, most in 
![image](https://github.com/user-attachments/assets/9436912e-9215-4724-be6e-5a240aae37a9)

my module only litte
![image](https://github.com/user-attachments/assets/20577b4c-074f-4b29-8de1-4d19a0a9ac1e)

this is global.yaml
```
props:
 system-log-level: INFO
 max-connections-size-per-query: 5
 kernel-executor-size: 16  # Infinite by default.
 proxy-frontend-flush-threshold: 128  # The default value is 128.
 # sql-show is the same as props in logger ShardingSphere-SQL, and its priority is lower than logging rule
 sql-show: false
 check-table-metadata-enabled: false
   # Proxy backend query fetch size. A larger value may increase the memory usage of ShardingSphere Proxy.
   # The default value is -1, which means set the minimum value for different JDBC drivers.
 proxy-backend-query-fetch-size: -1
 proxy-frontend-executor-size: 0 # Proxy frontend executor size. The default value is 0, which means let Netty decide.
 proxy-frontend-max-connections: 0 # Less than or equal to 0 means no limitation.
 proxy-default-port: 3307 # Proxy default port.
 proxy-netty-backlog: 1024 # Proxy netty backlog.
```

this is config.yaml datasources config
```
 connectionTimeoutMilliseconds: "30000"
        idleTimeoutMilliseconds: "60000"
        maxLifetimeMilliseconds: "1800000"
        maxPoolSize: 1000
        minPoolSize: 1000
```
