### ISSUE TITLE
 Does ShardingProxy support sharding queries based on time?

### ISSUE THREAD

**Issue by oxxdtscn** [apache/shardingsphere#33455]
I have an order table, which is sharded according to the year of creation. For example, if the creation time is 2023-12-12 23:59:59, then the table name is: t_order_2023.

```
CREATE TABLE `t_order_2023` (
  `id` int NOT NULL,
  `name` varchar(45) NOT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `order_id` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

I now want to build a sharding proxy to help me realize the automatic routing function when querying orders through mybatis in spring.
for example:
select * from t_order where create_time = '2023 01-01 00:00:00'

I use the official method of taking modulo based on ID and it works normally. But when I switched to time sharding, it was no longer available. I used mysqlworkbench to connect to the sharding_db database and did not see the mapped table. Using select query also prompts that the table does not exist.

Unavailable configurations are as follows:

```
databaseName: sharding_db

dataSources:
  ds0:
    url: jdbc:mysql://***:3306/ds0?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ***
    password: ***
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
  ds1:
    url: jdbc:mysql://***:3306/ds1?serverTimezone=GMT%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
    username: ***
    password: ***
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
  - !TRANSACTION
    defaultType: LOCAL
  - !SHARDING
    tables:
      balance:
        actualDataNodes: ds0.balance
      withdraw:
        actualDataNodes: ds1.withdraw
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: table_time_year
      payment_order:
        actualDataNodes: ds0.payment_order
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: table_time_year
      account:
        actualDataNodes: ds0.account
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: table_time_year
      member:
        actualDataNodes: ds0.member
        tableStrategy:
          standard:
            shardingColumn: create_time
            shardingAlgorithmName: table_time_year

    defaultDatabaseStrategy:
      none:
    defaultTableStrategy:
      none:

    shardingAlgorithms:
      table_time_year:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.YearStandardShardingAlgorithm
```
