### ISSUE TITLE
Why cannot I obtain the placeholder from the configuration file

### ISSUE THREAD

**Issue by robben009** [apache/shardingsphere#33626]
l hava a application.yml config file.  file have a config content is
```
dbPwd: 1234556

spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-dev.yml?placeholder-type=system_props
```

and  l hava a sharding-dev.yml file，config content is
```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: ***
    username: ***
    password: $${dbPwd::}
```

why $${dbPwd::} is not effect？
