### ISSUE TITLE
NPE  Caused by: java.lang.NullPointerException 	at org.apache.shardingsphere.sharding.merge.dql.groupby.GroupByMemoryMergedResult.getValueCaseSensitiveFromTables(GroupByMemoryMergedResult.java:135)

### ISSUE THREAD

**Issue by SHEN-Mr** [apache/shardingsphere#33637]
```
rules:
      sharding:
        tables:
       
          t_request_log:
            #start date 20240910 - end date 20240910
            actual-data-nodes: master.t_request_log_$->{(20241111..20301010).collect{t ->t.toString().padLeft(8,'0')}}_$->{1..10}
            table-strategy:
              complex:
                sharding-columns: seed,create_time
                sharding-algorithm-name: t_request_log_complex
        sharding-algorithms:
          t_request_log_complex:
            type: CLASS_BASED
            props:
              strategy: COMPLEX
              algorithmClassName: com.trusfort.xdid.config.LogComplexKeysShardingAlgorithm
```
According to the rules  actual-data-nodes，the first table is' t_request_rog_20241111_1'. If this table does not exist, a null pointer exception will be reported when querying。

```
org.apache.shardingsphere.infra.metadata.database.schema.util.SchemaMetaDataUtil.class

   Optional<DataNode> dataNode = dataNodes.getDataNodes(table).stream().filter((each) -> {
            return isSameDataSourceNameSchemaName(materials, each);
        }).findFirst();

```
This method will filter the logical table name t_request-log
