### ISSUE TITLE
how to use SHARDING ALGORITHM Type: INTERVAL  two database？

### ISSUE THREAD

**Issue by lvqibin123** [apache/shardingsphere#33635]
how to use SHARDING ALGORITHM Type: INTERVAL  two database？

`      app_user:
        actualDataNodes: <INTERVAL>P=ds0.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412 
        # 配置分表策略
        tableStrategy:
          standard:
            shardingColumn: updatetime
            shardingAlgorithmName: app_user_table_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake`
it work，but i have 2 database,I don't know how to configure it.
I have tried the following configurations, but none of them work:

><INTERVAL>P=ds0.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412 ,<INTERVAL>P=ds1.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412   

> <INTERVAL>P=ds${0..1}.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412

Can<INTERVAL>only be used for a single database?

**Comment by linghengqian** [comment]
- I'm just assuming you should actually read https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks first. Your code blocks aren't displaying properly.

**Comment by lvqibin123** [comment]
how to use SHARDING ALGORITHM Type: INTERVAL two database？

```
      app_user:
        actualDataNodes: <INTERVAL>P=ds0.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412 
        tableStrategy:
          standard:
            shardingColumn: updatetime
            shardingAlgorithmName: app_user_table_inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
```
it work，but i have 2 database,I don't know how to configure it.
I have tried the following configurations, but none of them work:
```
<INTERVAL>P=ds0.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412,<INTERVAL>P=ds1.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412
```
```
<INTERVAL>P=ds${0..1}.app_user_;SP=yyyyMM;DIA=1;DIU=Months;DL=202401;DU=202412 
```
Canonly be used for a single database?
