### ISSUE TITLE
Configuration not effective

### ISSUE THREAD

**Issue by paynezhuang** [apache/shardingsphere#33648]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.5.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?

ShardingSphere-JDBC

### Expected behavior

Normal working sharding

### Actual behavior

Not working

### Example codes for reproduce this issue (such as a github link).

```

SpringBoot version: 3.3.2
JDK version: 21

<dependency>
    <groupId>org.apache.shardingsphere</groupId>
    <artifactId>shardingsphere-jdbc</artifactId>
    <version>5.5.1</version>
</dependency>

<dependency>
    <groupId>org.yaml</groupId>
    <artifactId>snakeyaml</artifactId>
    <version>1.33</version>
</dependency>
```
application.yml 

```
spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/test?socketTimeout=60000&connectTimeout=30000&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
#    username: root
#    password: root

databaseName: db_0

mode:
  type: Standalone
  repository:
    type: JDBC

dataSources:
  db_0:
    type: com.zaxxer.hikari.HikariDataSource
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/test?socketTimeout=60000&connectTimeout=30000&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

rules:
#    - !SHARDING
  sharding:
    tables: # 数据分片规则配置
      sys_notice:
        actualDataNodes: db_0.sys_notice, db_0.sys_notice_1
        tableStrategy:
          standard:
            shardingColumn: id
            shardingAlgorithmName: notice-inline
        keyGenerateStrategy:
          column: id
          keyGeneratorName: snowflake
    keyGenerators:
      snowflake:
        type: SNOWFLAKE
    shardingAlgorithms:
      notice-inline:
        type: INLINE
        props:
          algorithm-expression: "sys_notice$->{id % 2 == 0 ? '' : '_1'}"
props:
  sql-show: true
```

After the project was launched, there were no relevant log prints, such as the output of the `ShardingSphere-SQL` keyword. 

When saving data, the data was not properly sharded. 

What am I still missing?

Thanks.
