### ISSUE TITLE
How to initialize connections in parallel

### ISSUE THREAD

**Issue by jdxia** [apache/shardingsphere#33824]
My project takes a long time to initialize the connection during startup
There are so many databases to connect to that it takes time to initialize them one by one during startup.

**Comment by terrymanu** [comment]
What is the version?

**Comment by jdxia** [comment]
> What is the version?

5.5.0

**Comment by terrymanu** [comment]
What is the configuration?

**Comment by jdxia** [comment]
> What is the configuration?

```
spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-jdbc/sharding-jdbc-${spring.profiles.active}.yaml
    hikari:
      pool-name: order-pool
      minimum-idle: 150
      maximum-pool-size: 2000
```

```
dataSources:
  trade_tidb:
    url: jdbc:mysql://172.30.97.58:4000/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&verifyServerCertificate=false&serverTimezone=Asia/Shanghai
    username: root
    password: ts*2-@9n8PUT40^3kR
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    validationTimeout: 5000
    connectionTimeout: 30000
    maximumPoolSize: 50
    minimumIdle: 1
    idleTimeout: 600000
    leakDetectionThreshold: 0
    keepaliveTime: 30000
    poolName: HikariPool-tidb
  trade_db:
    url: jdbc:mysql://172.30.97.50:3311/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false&verifyServerCertificate=false&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    validationTimeout: 5000
    connectionTimeout: 30000
    maximumPoolSize: 50
    minimumIdle: 1
    idleTimeout: 600000
    leakDetectionThreshold: 0
    keepaliveTime: 30000
  trade_db_slave:
    url: jdbc:mysql://172.30.97.51:3311/xx?useUnicode=true&characterEncoding=utf-8&useSSL=false&verifyServerCertificate=false&serverTimezone=Asia/Shanghai
    username: xxx
    password: xxx
    driverClassName: com.mysql.cj.jdbc.Driver
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    validationTimeout: 5000
    connectionTimeout: 30000
    maximumPoolSize: 50
    minimumIdle: 1
    idleTimeout: 600000
    leakDetectionThreshold: 0
    keepaliveTime: 30000

mode:
  type: Standalone

rules:
  .........
  
props:
  sql-show: true
```
