### ISSUE TITLE
TableNotFoundException

### ISSUE THREAD

**Issue by saintping** [apache/shardingsphere#33823]
## Question
I setup a simple example following user manual. And get an TableNotFoundException in select SQL like this:
org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 't_student' does not exist.

Is there anything wrong with the configuration?
Thanks.

## Environment
shardingsphere-jdbc 5.5.1
spring-boot 3.4.0

## Configuration
application.yaml:
```
spring:
  application:
    name: spring-boot-3
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-jdbc.yaml
  jpa:
    generate-ddl: false
```
sharding-jdbc.yaml:
```
databaseName: test
mode:
  type: Standalone
  repository:
    type: JDBC
props:
  sql-show: true
dataSources:
  test_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: "jdbc:mariadb://127.0.0.1:3306/test_1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    username: root
    password: '123456'
  test_2:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: org.mariadb.jdbc.Driver
    jdbcUrl: "jdbc:mariadb://127.0.0.1:3306/test_2?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true"
    username: root
    password: '123456'
rules:
- !SINGLE
  tables:
    - "*.*"
- !SHARDING
  tables:
    t_student:
      actualDataNodes: test_${0..1}.t_student_${0..1}
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
      databaseStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: database-inline-alg-test
      tableStrategy:
        standard:
          shardingColumn: id
          shardingAlgorithmName: table-inline-alg-student
  shardingAlgorithms:
    database-inline-alg-test:
      type: INLINE
      props:
        algorithm-expression: test_$->{id.intdiv(10) % 2 + 1}
    table-inline-alg-student:
      type: INLINE
        algorithm-expression: t_student_$->{id % 2 + 1}
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
```
