### ISSUE TITLE
Encryption TableNotFoundException: Table or view 'xxxx' does not exist.ms

### ISSUE THREAD

**Issue by aillamsun** [apache/shardingsphere#33879]
## Question

```java

<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc</artifactId>
            <version>5.5.1</version>
</dependency>  
```

## sharding-sphere.yaml 

```
      TR_USER_VEHICLE_AUTH: 
        columns:
          VIN: 
            cipher:
              name: VIN_CIPHER
              encryptorName: kms_encryptor
            assistedQuery:
              name: VIN_QUERY_CIPHER
              encryptorName: assisted_query_encryptor
          OWNER: 
            cipher:
              name: OWNER_CIPHER
              encryptorName: kms_encryptor
            assistedQuery:
              name: OWNER_QUERY_CIPHER
              encryptorName: assisted_query_encryptor
          VEHICLE_PLATE_NO: 
            cipher:
              name: VEHICLE_PLATE_NO_CIPHER
              encryptorName: kms_encryptor
            assistedQuery:
              name: VEHICLE_PLATE_NO_QUERY_CIPHER
              encryptorName: assisted_query_encryptor
```  

```SQL
SELECT count(0)
FROM TR_USER_VEHICLE_AUTH TRU
LEFT JOIN 
    (SELECT DISTINCT TVCI.AUTH_ID,
         TVCI.PIC_TYPE
    FROM TB_VEHICLE_CERTIFICATION_INFO TVCI
    WHERE TVCI.IS_DELETE = '0'
            AND TVCI.PIC_TYPE IN ('3', '7', '8', '10')) TVCI
    ON TRU.ID = TVCI.AUTH_ID
WHERE TRU.AUTH_STATUS IN ('0', '8', '9')
        AND TRU.IS_DELETE = '0' 
```

TB_VEHICLE_CERTIFICATION_INFO table no Encryption column.

## error 

```java

org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error preparing statement.  Cause: org.apache.shardingsphere.infra.exception.kernel.metadata.TableNotFoundException: Table or view 'TB_VEHICLE_CERTIFICATION_INFO' does not exist.ms

```

Not Supported LEFT JOIN SQL ?
