### ISSUE TITLE
Cann't load multiple schema from oracle database in the readwrite-splitting scenario

### ISSUE THREAD

**Issue by wuwenyao** [apache/shardingsphere#33921]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
5.51

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
load multiple schema from oracle database in the readwrite-splitting scenario

### Actual behavior
only load one schema(same as databaseName)

### Reason analyze (If you can)
Single Table only load the schema same as databaseName from oracle database.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
I tried every way I found from the [single table document](https://shardingsphere.apache.org/document/current/en/user-manual/shardingsphere-jdbc/yaml-config/rules/single/) , but every time the second schema don't load in the ShardingSphereDatabase. Is It my config error or a limitation on oracle ?

### Example codes for reproduce this issue (such as a github link).
```
databaseName: schema1
mode:
  type: Standalone
  repository:
    type: JDBC
dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:oracle:thin:@xx.xx.xx.xx:1521:xxxxxx
    username: schema1
    password: 
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 50
  slaver:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    jdbcUrl: jdbc:oracle:thin:@xx.xx.xx.xx:1521/xxxxx
    username: schema1
    password: 
    driverClassName: oracle.jdbc.OracleDriver
    maximumPoolSize: 50
rules:
  - !READWRITE_SPLITTING
    dataSourceGroups:
      readwrite_ds:
        writeDataSourceName: master
        readDataSourceNames:
          - slaver
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: random
    loadBalancers:
      random:
        type: RANDOM
  - !SINGLE
    tables:
      - "readwrite_ds.*"
#     - "readwrite_ds.schema1.*"
#     - "readwrite_ds.schema2.*"
#     - "readwrite_ds.*.*"
props:
  sql-show: true
```
