### ISSUE TITLE
How to make sure high availability for - !READWRITE_SPLITTING when readDataSource node down

### ISSUE THREAD

**Issue by 774886347** [apache/shardingsphere#34010]
Here is the sharding-jdbc version:
```
<dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>shardingsphere-jdbc</artifactId>
            <version>5.5.0</version>
</dependency>
```
Here is the config:
```
dataSources:
  slave:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  
    username:  
    password:  
  master:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url:  
    username:  
    password:  
rules:
- !READWRITE_SPLITTING
  dataSources:
    readwrite_ds:
      writeDataSourceName: master
      readDataSourceNames:
        - slave
        - master
      transactionalReadQueryStrategy: PRIMARY
      loadBalancerName: random

  loadBalancers:
    random:
        type: RANDOM
- !SINGLE
  tables:
    - readwrite_ds.system_config
 .......422 items.........
- !SHARDING
  tables: # 手动分片规则配置
    my_table_1:
      actualDataNodes: readwrite_ds.my_table_1_$->{0..31} 
      tableStrategy: # 切分策略
        complex:
          shardingColumns: GOAL_CONF_ID,COPY_RIGHT
          shardingAlgorithmName: my_table_1_inline # 分片算法名称
      keyGenerateStrategy:
        column: my_table_1_id
        keyGeneratorName: snowflake
    my_table_2:
      actualDataNodes: readwrite_ds.my_table_2_$->{0..31} # 数据源名称
      tableStrategy: # 切分策略
        standard:
          shardingColumn: my_table_2_id # 分片列名称
          shardingAlgorithmName: my_table_2_inline # 分片算法名称
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake

  shardingAlgorithms:
    my_table_2_inline:
      type: CLASS_BASED
      props:
        strategy: STANDARD
        algorithmClassName: xxx.StandardCustomShardingAlgorithm
    my_table_1_inline:
      type: CLASS_BASED
      props:
        strategy: COMPLEX
        algorithmClassName: xxx.SumAndModShardingAlgorithm
  keyGenerators:
    snowflake:
      type: custom_snowflake_id

props:
  sql-show: true
```
Question:
How to make sure  high availability when readDataSource node(mysql-14c64g) down(7000QPS)?
