### ISSUE TITLE
How to configure the generation strategy of primary key ID for a single table

### ISSUE THREAD

**Issue by poppop9** [apache/shardingsphere#34101]
This is the official document regarding the configuration of a single table:
```
rules:
- !SINGLE
  tables:
    # MySQL 风格
    - ds_0.t_single # 加载指定单表
    - ds_1.* # 加载指定数据源中的全部单表
    - "*.*" # 加载全部单表
    # PostgreSQL 风格
    - ds_0.public.t_config
    - ds_1.public.*
    - ds_2.*.*
    - "*.*.*"
  defaultDataSource: ds_0 # 默认数据源，仅在执行 CREATE TABLE 创建单表时有效。缺失值为空，表示随机单播路由。
```

I need to configure the generation strategy for the primary key of a single table now. How should I configure it?
