### ISSUE TITLE
version 5.5.1 Sharding algorithm HASH_MOD initialization failed...

### ISSUE THREAD

**Issue by zt9788** [apache/shardingsphere#34161]
use version 5.5.1(Sharding-JDBC) the when program start there will be throw a exception.
the error is same too  #31964 

`Sharding algorithm HASH_MOD initialization failed, table xxx tables sharding configuration can not use auto sharding algorithm...`

I have table session, session_0 ...session_15
it is can work in version 5.3.2 

the config is:
```

            sharding:
              tables:
                session:
                  actual-data-nodes: session_${0..15}
                  table-strategy:
                    standard:
                      sharding-column: uid
                      sharding-algorithm-name: session_hash_mod                  
              sharding-algorithms:
                session_hash_mod:
                  type: HASH_MOD
                  props:
                    sharding-count: 16
```

i saw the code sharding-jdbc will check the shardingAlgorithm is `ShardingAutoTableAlgorithm`
i change the HASH_MOD to INLINE it is have no exception. 

```
private void checkManualShardingAlgorithm(String shardingAlgorithmName, String logicTable) {
        ShardingAlgorithm shardingAlgorithm = (ShardingAlgorithm)this.shardingAlgorithms.get(shardingAlgorithmName);
        ShardingSpherePreconditions.checkState(!(shardingAlgorithm instanceof ShardingAutoTableAlgorithm), () -> {
            return new AlgorithmInitializationException(shardingAlgorithm, "`%s` tables sharding configuration can not use auto sharding algorithm.", new Object[]{logicTable});
        });
    }
```

so how to fix it?
