### ISSUE TITLE
use openGauss: TableNotFOundException: Table or view 't_platform' does not exist

### ISSUE THREAD

**Issue by koradji2046** [apache/shardingsphere#34706]
**sharding.yaml**
```yaml
dataSources:
  db0:
    dataSourceClassName: com.alibaba.druid.pool.DruidDataSource

#    # this is ok
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.149.54:1521/orcl
#    username: qzkj_2ndc_dev
#    password: xxx
#    validation-query: select 1 from dual

#  # this is failed: TableNotFoundException: Table or view 't_tool_snowflake_generator' does not exist.
    driverClassName: org.opengauss.Driver
    url: jdbc:opengauss://192.168.149.113:5432/qzone_self_dev
    username: qzone_self_dev
    password: xxx
    validation-query: select 1

rules: 
- !SINGLE
  tables:
    - db0.t_sys_search_record
    - db0.t_platform
    - db0.t_sys_app
  defaultDataSource: db0

- !SHARDING
  tables:
    T_MESSAGE_INNER:
      actualDataNodes: db0.t_message_inner_202412,db0.t_message_inner_202501,db0.t_message_inner_202502
      tableStrategy:
        standard: 
          shardingColumn: createdate
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: id
        keyGeneratorName: snowflake
  shardingAlgorithms:
    table_inline:
      type: INTERVAL
      props:
        datetime-pattern: 'yyyy-MM-dd HH:mm:ss'
        datetime-lower: '2024-12-01 08:00:00'
        datetime-interval-unit: MONTHS
        sharding-suffix-pattern: yyyyMM
        datatime-interval-amount: 1
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
        workerId: 1
        dataCenterId: 1
```
The sharding.yaml above runs completely correctly, but replacing the database from Oracle to OpenGauss will throw an error:
```
TableNotFOundException: Table or view 't_platform' does not exist
```
After investigation, it was found that why was the metadata of public instead of qzone_stel_dev used for comparison? May I ask what settings are needed to solve this problem?
