### ISSUE TITLE
5.5.2 Same actual data node cannot be configured in multiple logic tables in same database

### ISSUE THREAD

**Issue by geekerzhou** [apache/shardingsphere#34889]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

5.5.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
jdbc

### Expected behavior
```
- !SHARDING
    tables:
      order_main:
        actualDataNodes: ds$->{0..2}.order_main_$->{0..999}
        databaseStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: custom-database-algorithm
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithmName: custom-order-id-algorithm
      order_main_hint:
        actualDataNodes: ds$->{0..2}.order_main_$->{0..999}
        databaseStrategy:
          hint:
            shardingAlgorithmName: custom-hint-algorithm
        tableStrategy:
          hint:
            shardingAlgorithmName: custom-hint-algorithm
```
this config works fine in 5.2.1, upgrade to 5.5.2 throw exception

### Actual behavior

Same actual data node cannot be configured in multiple logic tables in same database, logical table 'order_main_hint', actual data node 'ds0.order_main_0'.
