### ISSUE TITLE
Does Shardingsphere support adding datasource dynamically ?

### ISSUE THREAD

**Issue by able-wly** [apache/shardingsphere#35074]
## Question

**For English only**, other languages will not accept.

Currently we know that we can add datasource by yaml file like 
```
dataSources:
  ds_0:
    url: jdbc:postgresql://127.0.0.1:5432/demo_ds_0
    username: postgres
    password: postgres
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1
```

Is there any way to add the ds_0 by a REST API ? thanks in advance.
