### ISSUE TITLE
org.apache.shardingsphere.infra.exception.dialect.exception.syntax.database.UnknownDatabaseException

### ISSUE THREAD

**Issue by dingqianwen** [apache/shardingsphere#35195]
## org.apache.shardingsphere.infra.exception.dialect.exception.syntax.database.UnknownDatabaseException

```yml
dataSources:
  db_0:
    url: jdbc:mysql://localhost:3306/db_0
    username: root
    password: 123456
    ...
```

There are two databases in the system: db_0 and db_1. The current configuration works fine for querying db_0, but when trying to query db_1, it shows the aforementioned error. In reality, we only need to query one basic table in db_1, but it requires adding another data source for db_1, which occupies too many connections and isn't flexible enough. This issue doesn't exist in version 4+
