### ISSUE TITLE
How to Find YAML Configuration Parameters?

### ISSUE THREAD

**Issue by makssent** [apache/shardingsphere#35199]
**Hello everyone!**

I’m currently working on adding system table support to ShardingSphere and writing YAML configurations. I’ve looked at Postgres examples like this one [link](https://github.com/apache/shardingsphere/blob/a75a02a5413543fdec9cb2dce652cb941034883c/infra/database/type/postgresql/src/main/resources/schema/postgresql/pg_catalog/pg_aggregate.yaml#L4):
```yaml
# (Apache 2.0 license header)

name: pg_aggregate
columns:
  aggfnoid:
    caseSensitive: true
    dataType: 1111  
    generated: false
    name: aggfnoid
    primaryKey: true
    unsigned: false
    visible: true
  # ... other columns ...
indexes:
  pg_aggregate_fnoid_index:
    name: pg_aggregate_fnoid_index
```
Where can I find the full list of parameters for such configurations?
