### ISSUE TITLE
create table with foregin key error

### ISSUE THREAD

**Issue by GuiwenChen** [apache/shardingsphere#35245]
### Which version of ShardingSphere did you use?
5.5.2

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
Successfully created a table .

### Actual behavior
```
[create table customer] Query OK, 0 rows affected (0.04 sec)
[create table order_item] ERROR 1050 (42S01): Table 'customer' already exists
```
Create a table failed.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. add rules
```
databaseName: account_system

dataSources:
  ds:
    url: jdbc:mysql://127.0.0.1:3306/account_system?useSSL=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: root
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    minPoolSize: 1

rules:
- !SINGLE
  tables:
    - "*.*"
- !SHARDING
  tables:
    order_item:
      actualDataNodes: ds.order_item,ds.order_item_${0..2}
      tableStrategy:
        standard:
          shardingColumn: company_id
          shardingAlgorithmName: order_item_inline

  shardingAlgorithms:
    order_item_inline:
      type: INLINE
      props:
        algorithm-expression: order_item_${company_id.intdiv(50)}
```

2.create table customer,order_item
```
CREATE TABLE `customer` (
  `company_id` bigint(20) NOT NULL,
  `id` bigint(20) NOT NULL,
  `is_deleted` bit(1) NOT NULL,
  `synced_id` bigint(20) NOT NULL,
  PRIMARY KEY (`company_id`,`id`),
  KEY `idx_customer_synced_id` (`company_id`,`is_deleted`,`synced_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE `order_item` (
  `company_id` bigint(20) NOT NULL,
  `id` bigint(20) NOT NULL,
  `order_id` bigint(20) DEFAULT NULL,
  `customer_company_id` bigint(20) DEFAULT NULL,
  `customer_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`company_id`,`id`),
  KEY `idx_order_item_company_order_id` (`company_id`,`order_id`),
  KEY `FKg11wcg7bs8o3931hl5t2n44tr` (`customer_company_id`,`customer_id`),
  CONSTRAINT `FKg11wcg7bs8o3931hl5t2n44tr` FOREIGN KEY (`customer_company_id`, `customer_id`) REFERENCES `customer` (`company_id`, `id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
```

**Comment by terrymanu** [comment]
What is your database metadata, can you show result of `show tables`?

**Comment by GuiwenChen** [comment]
1. mysql 5.7.35
2. Create a database using ‘CREATE DATABASE xxx DEFAULT CHARSET utf8mb4;’.
3. Create two tables, the log：
```
mysql> show tables;
Empty set (0.01 sec)

mysql> CREATE TABLE `customer` (
    ->   `company_id` bigint(20) NOT NULL,
    ->   `id` bigint(20) NOT NULL,
    ->   `is_deleted` bit(1) NOT NULL,
    ->   `synced_id` bigint(20) NOT NULL,
    ->   PRIMARY KEY (`company_id`,`id`),
    ->   KEY `idx_customer_synced_id` (`company_id`,`is_deleted`,`synced_id`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
Query OK, 0 rows affected (0.04 sec)

mysql> show tables;
+---------------------------+
| Tables_in_account_system2 |
+---------------------------+
| customer                  |
+---------------------------+
1 row in set (0.00 sec)

mysql> CREATE TABLE `order_item` (
    ->   `company_id` bigint(20) NOT NULL,
    ->   `id` bigint(20) NOT NULL,
    ->   `order_id` bigint(20) DEFAULT NULL,
    ->   `customer_company_id` bigint(20) DEFAULT NULL,
    ->   `customer_id` bigint(20) DEFAULT NULL,
    ->   PRIMARY KEY (`company_id`,`id`),
    ->   KEY `idx_order_item_company_order_id` (`company_id`,`order_id`),
    ->   KEY `FKg11wcg7bs8o3931hl5t2n44tr` (`customer_company_id`,`customer_id`),
    ->   CONSTRAINT `FKg11wcg7bs8o3931hl5t2n44tr` FOREIGN KEY (`customer_company_id`, `customer_id`) REFERENCES `customer` (`company_id`, `id`)
    -> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
ERROR 1050 (42S01): Table 'customer' already exists
mysql> show tables;
+---------------------------+
| Tables_in_account_system2 |
+---------------------------+
| customer                  |
+---------------------------+
1 row in set (0.00 sec)
```

**Comment by terrymanu** [comment]
Thank you for reporting this issue! I've analyzed the problem where creating a table with foreign key constraints fails with "Table 'customer' already exists" error when using mixed SINGLE and SHARDING rules.

  Root Cause Analysis

  The issue occurs due to a bug in ShardingSphere's DDL routing logic when handling foreign key constraints:

  1. Rule Conflict: Your configuration has both SINGLE rule (*.*) and SHARDING rule (order_item), creating overlapping table coverage
  2. Foreign Key Processing Bug: When parsing CREATE TABLE with foreign keys, ShardingSphere incorrectly includes both the main table and referenced tables in the routing process
  3. Routing Engine Error: The system attempts to execute CREATE operations on both order_item (main table) and customer (referenced table), causing the "already exists" error

  Recommended Solutions

  1. Configuration Fix (Immediate Solution)

  Modify your rules configuration to avoid conflicts:

```yaml
  rules:
  - !SINGLE
    tables:
      - "customer"  # Explicitly specify SINGLE tables
      # Add other non-sharded tables here instead of "*.*"
  - !SHARDING
    tables:
      order_item:
        actualDataNodes: ds.order_item,ds.order_item_${0..2}
        tableStrategy:
          standard:
            shardingColumn: company_id
            shardingAlgorithmName: order_item_inline

    shardingAlgorithms:
      order_item_inline:
        type: INLINE
        props:
          algorithm-expression: order_item_${company_id.intdiv(50)}
```

  2. Workaround (Alternative)

  Create tables in two steps to avoid foreign key routing issues:

```sql
  -- Step 1: Create table without foreign key
  CREATE TABLE `order_item` (
    `company_id` bigint(20) NOT NULL,
    `id` bigint(20) NOT NULL,
    `order_id` bigint(20) DEFAULT NULL,
    `customer_company_id` bigint(20) DEFAULT NULL,
    `customer_id` bigint(20) DEFAULT NULL,
    PRIMARY KEY (`company_id`,`id`),
    KEY `idx_order_item_company_order_id` (`company_id`,`order_id`)
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

  -- Step 2: Add foreign key constraint separately
  ALTER TABLE `order_item`
  ADD CONSTRAINT `FKg11wcg7bs8o3931hl5t2n44tr`
  FOREIGN KEY (`customer_company_id`, `customer_id`)
  REFERENCES `customer` (`company_id`, `id`);
```

  Code Fix Required

  The core issue is in the DDL routing logic that needs to distinguish between:
  - Main table: The table being created (order_item)
  - Referenced tables: Existing tables referenced by foreign keys (customer)

  The fix should ensure that only the main table is processed for creation, while referenced tables are validated for existence without attempting to recreate them.

Here's what I should do:

  1. Fork the repository and create a new branch for this fix
  2. Locate the issue in the DDL routing logic (likely in CreateTableStatement and SingleRouteEngine classes)
  3. Implement the fix to properly handle foreign key referenced tables
  4. Add test cases to verify the fix works correctly
  5. Submit a pull request with detailed description of the changes

  The fix should ensure that when processing CREATE TABLE statements with foreign keys, only the main table is routed for creation operations, while referenced tables are properly validated without triggering recreation  attempts.

  Thank you again for bringing this important issue to our attention!
