### ISSUE TITLE
high latency for shardingsphere-jdbc initializing schema metadata in Single table rule

### ISSUE THREAD

**Issue by BourneD** [apache/shardingsphere#35500]
version: shardingsphere-jdbc-5.5.2
we have about 4500 tables in our database. and the rule configuration is as below. there are no other rules except the SINGLE one. The initialization latency is about 4 minutes.
```
rules:
  - !SINGLE
    tables:
      - "ds0.restful_message_b_table"
    defaultDataSource: ds0
```
I analyzed the initialization procedure and found it is blocked in `org.apache.shardingsphere.mode.metadata.persist.service.metadata.table.TableMetaDataPersistService::persist`.
Can we optimize the `persist` method by parallel execution.
