### ISSUE TITLE
Throw NPE when INSERT column and values mismatch

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#4784]
Throw NullPointException when INSERT column and values mismatch.
It is better to throw suitable SQLException for JDBC-driver and proxy.

The tasks are:
- [x] Throw suitable SQLException for JDBC-driver.
- [x] Report suitable error packet with MySQL proxy.
- [x] Report suitable error packet with PostgreSQL proxy.

**Comment by ranjeet-floyd** [comment]
@terrymanu  Can i take this ?. Thanks

**Comment by terrymanu** [comment]
Welcome, I just assigned to you. @ranjeet-floyd

**Comment by ranjeet-floyd** [comment]
@terrymanu Can you please help me to find issue.

**Comment by terrymanu** [comment]
@ranjeet-floyd You can write a wrong SQL with mismatched count of insert columns and values, and then you can find the NPE entry.

**Comment by ranjeet-floyd** [comment]
@terrymanu  Thanks but  Not able to find it. Can you please point to class.

**Comment by terrymanu** [comment]
Have you run the sharding-proxy already? 
Could you provided the SQL and exception info if `INSERT column and values mismatch`?

**Comment by ranjeet-floyd** [comment]
@terrymanu I modified test sql in class org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShadowPreparedStatementTest . Below is screen shot 

<img width="1375" alt="Screenshot 2020-04-02 at 9 47 57 PM" src="https://user-images.githubusercontent.com/1992972/78272860-ae81b100-752b-11ea-8c5e-c8a388e036c4.png">


<img width="1644" alt="Screenshot 2020-04-02 at 9 45 13 PM" src="https://user-images.githubusercontent.com/1992972/78272744-8db95b80-752b-11ea-8dc1-ac33622bc5dc.png">

**Comment by terrymanu** [comment]
You may startup Sharding-Proxy, and connect with MySQL client. Then input error SQL, then you can find the error message in backend.
From the error message, you can find the class entry.

**Comment by hk1997** [comment]
@terrymanu Is this issue still open?
If yes, can I try working on this?

**Comment by menghaoranss** [comment]
@hk1997 ,I have tried to track this issue use sharidng-proxy with mysql :
`yaml`:
```
rules:
- !!org.apache.shardingsphere.sharding.core.yaml.config.sharding.YamlShardingRuleConfiguration
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithm:
            type: INLINE
            props:
              algorithm.expression: t_order_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
    t_order_item:
      actualDataNodes: ds_${0..1}.t_order_item_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithm:
            type: INLINE
            props:
              algorithm.expression: t_order_item_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_item_id
  bindingTables:
    - t_order,t_order_item
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithm:
        type: INLINE
        props:
          algorithm.expression: ds_${user_id % 2}
  defaultTableStrategy:
    none:
```
`table`:
```
CREATE TABLE `t_order` (
  `order_id` bigint(20) NOT NULL,
  `user_id` int(11) NOT NULL,
  `status` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`order_id`)
) ENGINE=InnoDB DEFAULT

```
`case`:
```
mysql> insert into t_order(user_id, status) values(1);
ERROR 1136 (21S01): Column count doesn't match value count at row 1

mysql> insert into t_order(order_id, user_id, status) values(201,200);
ERROR 1136 (21S01): Column count doesn't match value count at row 1

mysql> insert into t_order(user_id, status) values(1, 2, '3');
ERROR 10002 (C1000): 2Unknown exception: [null]

mysql> insert into t_order values(201,200,2000,200);
ERROR 10002 (C1000): 2Unknown exception: [null]

mysql> insert into t_order values(201,200);
Query OK, 1 row affected (6.66 sec)

mysql> insert into t_order values(201);
ERROR 1136 (21S01): Column count doesn't match value count at row 1

```
there are 2 situations：
- use default cloumns
   - values num > columns num ：NPE
   - values num = columns num - generatedKey num ：OK
   - values num < columns num - generatedKey num ：excute ERROR
   
- designate columns
   - values num > columns num ：NPE
   - values num < columns num ：excute ERROR

And , i have debuged the source code , this is the code where NPE occured: 

```
InsertClauseShardingConditionEngine.class

private ShardingCondition createShardingCondition(final String tableName, final Iterator<String> columnNames, final InsertValueContext insertValueContext, final List<Object> parameters) {
        ShardingCondition result = new ShardingCondition();
        SPITimeService timeService = new SPITimeService();
        for (ExpressionSegment each : insertValueContext.getValueExpressions()) {
            //NPE here
            String columnName = columnNames.next();
            if (shardingRule.isShardingColumn(columnName, tableName)) {
                if (each instanceof SimpleExpressionSegment) {
                    result.getRouteValues().add(new ListRouteValue<>(columnName, tableName, Collections.singletonList(getRouteValue((SimpleExpressionSegment) each, parameters))));
                } else if (ExpressionConditionUtils.isNowExpression(each)) {
                    result.getRouteValues().add(new ListRouteValue<>(columnName, tableName, Collections.singletonList(timeService.getTime())));
                } else if (ExpressionConditionUtils.isNullExpression(each)) {
                    throw new ShardingSphereException("Insert clause sharding column can't be null.");
                }
            }
        }
        return result;
    }
```

I think some verification needs to be done after `SQLStatementContext` been instantiated：
```
DataNodeRouter.class

private RouteContext createRouteContext(final SQLStatement sqlStatement, final String sql, final List<Object> parameters) {
        try {
            SQLStatementContext sqlStatementContext = SQLStatementContextFactory.newInstance(metaData.getSchema().getSchemaMetaData(), sql, parameters, sqlStatement);
            // maybe need check here
            return new RouteContext(sqlStatementContext, parameters, new RouteResult());
            // TODO should pass parameters for master-slave
        } catch (final IndexOutOfBoundsException ex) {
            return new RouteContext(new CommonSQLStatementContext(sqlStatement), parameters, new RouteResult());
        }
    }
```

welcome to talk about here.
