### ISSUE TITLE
How to use the columns of the parent table to configure the child table fragments ？

### ISSUE THREAD

**Issue by fengyunhe** [apache/shardingsphere#5231]
## Question

If there is no user_id column in my order_item table, but there is a user_id column in the corresponding order table, and order_id in order_item corresponds to the id in order, how can I configure the user_id column to fragment the order_item table?

```yaml
shardingRule:
    tables:
        category:
            actualDataNodes: ds${4..6}.category
        user:
            actualDataNodes: ds${4..6}.user
            databaseStrategy:
                inline:
                    shardingColumn: id
                    algorithmExpression: ds${id%3+3}
        order:
            actualDataNodes: ds${4..6}.order${0..1}
            databaseStrategy:
                inline:
                    shardingColumn: user_id
                    algorithmExpression: ds${user_id%3+3}
            tableStrategy:
                inline:
                    shardingColumn: id
                    algorithmExpression: order${id%2}
            keyGenerator:
                type: SNOWFLAKE
                column: id
        order_item:
            actualDataNodes: ds${4..6}.order_item${0..1}
            databaseStrategy:
                inline:
                    shardingColumn: user_id
                    algorithmExpression: ds${user_id%3+3}
            tableStrategy:
                inline:
                    shardingColumn: id
                    algorithmExpression: order_item${order_id%2}
    bindingTables:
        - user,order,order_item
        
    broadcastTables:
        - category
```
