### ISSUE TITLE
When using mycli to connect, it is normal, but when using DataGrip to connect to sharding-proxy, the table is not fragmented, and the physical table is displayed

### ISSUE THREAD

**Issue by chen645800876** [apache/shardingsphere#5316]
#### Connect to the same `sharding-proxy`, but in` DataGrip`, the physical table is displayed instead of the logical table
![image](https://user-images.githubusercontent.com/24761804/80298726-eb0a9a80-87c1-11ea-88e3-6e9debf3e00d.png)
![image](https://user-images.githubusercontent.com/24761804/80298743-01185b00-87c2-11ea-9e05-4db1d192ff7c.png)

When using `DataGrip` connection, there is still an error
![image](https://user-images.githubusercontent.com/24761804/80298779-5eaca780-87c2-11ea-9f1f-75061afe8dcd.png)
```text
Error encountered when performing Introspect schema KotlinWeb: 2Unknown exception: [Cannot find table rule and default data source with logic table: 'table_constraints'].
2Unknown exception: [Cannot find table rule and default data source with logic table: 'table_constraints']
 (4 s 654 ms)
```
But I haven't created the table_constraints table

The following is my configuration, the version of `sharding-proxy` used is 4.0.1
```yaml
schemaName: KotlinWeb
dataSources:
  master0slave:
    password: root
    url: jdbc:mysql://mysql-master0-slave:3306/KotlinWeb?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
  master1slave:
    password: root
    url: jdbc:mysql://mysql-master1-slave:3306/KotlinWeb?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
  master0:
    password: root
    url: jdbc:mysql://mysql-master0:3306/KotlinWeb?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
  master1:
    password: root
    url: jdbc:mysql://mysql-master1:3306/KotlinWeb?autoReconnect=true&useUnicode=true&useSSL=false&characterEncoding=UTF8
    username: root
shardingRule:
  tables:
    userInfo:
      keyGenerator:
        column: userId
        type: SNOWFLAKE
      actualDataNodes: ds$->{0..1}.userInfo
      databaseStrategy:
        inline:
          shardingColumn: userId
          algorithmExpression: ds$->{userId % 2}
    userComment:
      keyGenerator:
        column: commentId
        type: SNOWFLAKE
      actualDataNodes: ds$->{0..1}.userComment
      databaseStrategy:
        inline:
          shardingColumn: commentId
          algorithmExpression: ds$->{commentId % 2}
    articleCategory:
      keyGenerator:
        column: articleCategoryId
        type: SNOWFLAKE
    userGroup:
      keyGenerator:
        column: groupId
        type: SNOWFLAKE
    article:
      tableStrategy:
        inline:
          shardingColumn: articleId
          algorithmExpression: article$->{articleId % 2}
      keyGenerator:
        column: articleId
        type: SNOWFLAKE
      actualDataNodes: ds$->{0..1}.article$->{0..1}
      databaseStrategy:
        inline:
          shardingColumn: userId
          algorithmExpression: ds$->{userId % 2}
    privateMessages:
      keyGenerator:
        column: messageId
        type: SNOWFLAKE
      actualDataNodes: ds$->{0..1}.privateMessages
      databaseStrategy:
        inline:
          shardingColumn: messageId
          algorithmExpression: ds$->{messageId % 2}
#    bindingTables:
#    - userInfo,article,userComment
#   - privateMessages
#   - userComment
  defaultDatabaseStrategy:
    inline:
      shardingColumn: userId
      algorithmExpression: ds${userId % 2}
  defaultTableStrategy:
    none:
  masterSlaveRules:
    ds0:
      masterDataSourceName: master0
      slaveDataSourceNames:
      - master0slave
    ds1:
      masterDataSourceName: master1
      slaveDataSourceNames:
      - master1slave
  broadcastTables:
  - articleCategory
  - userGroup

```
