### ISSUE TITLE
How to retrieve the Authentication username (defined in the Server.yaml) that is connected ?

### ISSUE THREAD

**Issue by ppourali** [apache/shardingsphere#5407]
Hi,

Assume that my server.yaml is:
```
authentication:
  users:
    postgresserver:
      password: 12345678

```

The question is how to get the "users" value in the runtime. Let's say a client connects to the Sharding Proxy using the username given in the Server.yaml. I need to know which user the client is connected to.

Thanks,
Parsa
