### ISSUE TITLE
The keyGenerator doesn't work in transaction-2pc-xa-raw-jdbc-example module when a oracle database used

### ISSUE THREAD

**Issue by TaoZhiMLND** [apache/shardingsphere#5421]
I have reproduced the behavior as @lvye351 says in #5383. The keyGenerator doesn't work in the transaction-2pc-xa-raw-jdbc sample module when a oracle database 12c and ojbdc8.jar used.

The log is as follows,
![image](https://user-images.githubusercontent.com/9602831/80979380-db422480-8e59-11ea-8043-0b38dedcad5b.png)

It seems that when table t_order created, its tableMetaData doesn't put into schemaMetaData.
I will try to find out the reason and fix it.

**Comment by TaoZhiMLND** [comment]
Although the table name what we created is lowercase, it stored in oracle is uppercase by default. Table name is case sensitive in oracle, TableMetaDataLoader#isTableExist will return false if we use the lowercase table name.

**Comment by TaoZhiMLND** [comment]
when configuration is as follows(actual table name use uppercase words), the issue above will absent,
```
shardingRule:
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.T_ORDER_${0..1}
      tableStrategy: 
        standard:
          shardingColumn: order_id
          shardingAlgorithm:
            type: INLINE
            props:
              algorithm.expression: T_ORDER_${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
        props:
          worker.id: 123
```
But when TableMetaDataLoader#isTableExist return true, there is another error occur from ColumnMetaDataLoader#load.
Java code is
```java
        try (ResultSet resultSet = connection.createStatement().executeQuery(generateEmptyResultSQL(table, databaseType))) {
            for (String each : columnNames) {
                isCaseSensitives.add(resultSet.getMetaData().isCaseSensitive(resultSet.findColumn(each)));
            }
        }
```

Exception cause is
```
Error : 933, Position : 38, Sql = SELECT * FROM "T_ORDER_0" WHERE 1 != 1;, OriginalSql = SELECT * FROM "T_ORDER_0" WHERE 1 != 1;, Error Msg = ORA-00933: SQL 命令未正确结束
```
And this sql can execute successfully in PL/SQL.
