### ISSUE TITLE
Connecting to multiple databases through sharding proxy fails

### ISSUE THREAD

**Issue by ppourali** [apache/shardingsphere#5482]
Hi,

I have question regarding sharding proxy in transparent mode. Can we connect to multiple databases at the same time in the transparent mode?

This is my configuration.yaml:
```
schemaName: pgadventureworks
dataSource:
  url: jdbc:postgresql://localhost:5432/Adventureworks?serverTimezone=UTC&useSSL=false&useUnicode=true&allowEncodingChanges=true
  username: postgres
  password: password
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50


schemaName: adventureworks
dataSource:
  url: jdbc:mysql://127.0.0.1:3306/adventureworks?serverTimezone=UTC&useSSL=false&useUnicode=true&allowEncodingChanges=true
  username: mysqluser
  password: password
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50

```

I have two rules: one for a mysql database and the other one for postgresql database. When I use mysql and psql from command line, only one of them works. Most of the times, I can connect to psql but the mysql fails.

Am I configuring them incorrectly? Let's say I have different databases on different DBMS types and I want them to be proxied by one instance of sharding proxy.

Any help would be appreciated,
Thanks
Parsa
