### ISSUE TITLE
The count(*) result from subquery is wrong

### ISSUE THREAD

**Issue by taoj555** [apache/shardingsphere#5586]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
both
### Expected behavior
Get the correct count(*) result from subquery
### Actual behavior
The result of count(*) from subquery is wrong
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
my sharding rule is:
```
shardingRule:
  tables:
    t_accountinfo:
      actualDataNodes: ds_${0..3}.t_accountinfo
      databaseStrategy:
        inline:
          shardingColumn: t_accountID
          algorithmExpression: ds_${t_accountID % 4}
```
SQL :
```
mysql> SELECT COUNT(*) FROM (SELECT * FROM t_accountinfo o) t;
+----------+
| COUNT(*) |
+----------+
|      319 |
+----------+
1 row in set (0.01 sec)
```
The result: (319) is not the real record number, the right result should be：
```
mysql> select count(*) from t_accountinfo;
+----------+
| count(*) |
+----------+
|     1277 |
+----------+
1 row in set (0.02 sec)
```
