### ISSUE TITLE
Orchestration module listens for exeception when have more ruleConfiguration

### ISSUE THREAD

**Issue by yu199195** [apache/shardingsphere#5847]
repetition，if config this , have shardingRuleConfig and   encryptorConfiguration
```
rules:
- !SHARDING
  tables:
    t_order:
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      keyGenerator:
        column: order_id
        type: SNOWFLAKE
      logicTable: t_order
      tableStrategy:
        standard:
          shardingAlgorithm:
            props:
              algorithm.expression: t_order_${order_id % 2}
            type: INLINE
          shardingColumn: order_id
- !ENCRYPT
  encryptors:
    encryptor_aes:
      props:
        aes.key.value: 123456xy
      type: aes
    encryptor_md5:
      type: md5
  tables:
    t_encrypt:
      columns:
        user_id:
          cipherColumn: user_cipher
          encryptor: encryptor_aes
          plainColumn: user_plain
        order_id:
          cipherColumn: order_cipher
          encryptor: encryptor_md5
```

in `org.apache.shardingsphere.orchestration.core.configcenter.listener.SchemaChangedListener` have listener exception,  Because now it's all SPI loading rule configuration.
