### ISSUE TITLE
When batch inserting, only the primary key of the first data is returned

### ISSUE THREAD

**Issue by jukai5501** [apache/shardingsphere#5858]
### Which version of ShardingSphere did you use?
4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior
When inserting in batch, return the primary key of each piece of data

### Actual behavior
When batch inserting, only the primary key of the first data is returned

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
Batch insert 2 pieces of data, only the first one returns the primary key. "carediaryid" is the primary key.
```
 <insert id="insertAll"
            parameterType="com.test.CareDiaryDO"
            useGeneratedKeys="true"
            keyProperty="careDiaryId">
        insert into care_diary (care_diary_type_cd, creator_type, description, status_cd, create_dt)
        values
        <foreach collection="list" item="item" index="index" separator=",">
            (#{item.careDiaryTypeCd,jdbcType=CHAR},
             #{item.creatorType,jdbcType=CHAR}, 
             #{item.description,jdbcType=VARCHAR}, 
             #{item.statusCd,jdbcType=CHAR},
             #{item.createDt,jdbcType=TIMESTAMP})
        </foreach>
    </insert>
```
```
spring:
    shardingsphere:
        sharding:
            default-data-source-name: ds
            tables:
                care_diary:
                key-generator:
                    column: care_diary_id
                    type: snowflake
```

**Comment by yu199195** [comment]
`care_diary_id` should be In your insert statement, If you use mybatis, you can set it to auto generate .

**Comment by jukai5501** [comment]
> `care_diary_id` should be In your insert statement, If you use mybatis, you can set it to auto generate .

I want to use shardingsphere's distributed primary key

**Comment by yu199195** [comment]
> I want to use shardingsphere's distributed primary key

i know,can you log sql?  it will contains `care_diary_id`
```
insert into care_diary (care_diary_id,care_diary_type_cd, creator_type, description, status_cd, create_dt)
```

**Comment by jukai5501** [comment]
@yu199195  It is the log sql. You can try to create a table, then insert data in batches, and see that each record has a return primary key.
```
2020-05-31 16:48:37.704  INFO 22293 [127.0.0.1:10101] --- [io-10101-exec-1] ShardingSphere-SQL                       : Actual SQL: ds ::: insert into care_diary (scare_diary_type_cd,
                                creator_type, description, status_cd,
                                create_dt, care_diary_id)
                values
            (?, ?, ?, ?, ?, ?), (?, ?, ?, ?, ?, ?) ::: [111, T, null, 00000, 2020-05-31 16:48:37.552, 473894769873911809, 111, T, null, 00000, 2020-05-31 16:48:37.554, 473894769869717504]
```

**Comment by yu199195** [comment]
@jukai5501  you want to collect List<PK> ,in you mybatis mapper?  for like this 

```
List<Strig> batchInsert(T  t)
```

**Comment by jukai5501** [comment]
@yu199195 This is my code ` int insertAll(List<CareDiaryDO> record);`, I want to get every ‘ careDiaryId’ in the parameter ‘record’, and 'careDiaryId' is generated through the distributed primary key of shardingsphere.

**Comment by yu199195** [comment]
@jukai5501  i know you mean,  batch insert data, and the primary key of sharing-shpere auto  generation , Later we need to verify that the problem exists, thanks.

**Comment by jukai5501** [comment]
@yu199195 You are welcome, waiting for your reply.

**Comment by yu199195** [comment]
@jukai5501  i test and debug This function of Distributed primary key generation，it work well， mybe you config have some error ，log sharding config on the console.,Here is the reference :(Please be careful to align ,In the configuration you mentioned above, there may be errors)

```
spring:
    shardingsphere:
        sharding:
              tables:
                  t_order:
                     actualDataNodes: ds_$->{0..1}.t_order
                     keyGenerator:
                          column: order_id
                          props:
                                 worker.id: '123'
                          type: SNOWFLAKE
```

**Comment by jukai5501** [comment]
@yu199195 I don't have a split table. I only use a distributed primary key for a table.

**Comment by yu199195** [comment]
@jukai5501  hi, distributed primary key  Designed for sharding table. if you not work,  could you show complete sharding configuration?

**Comment by jukai5501** [comment]
@yu199195 Hi,this is complete sharding configuration.
```
spring:
  shardingsphere:
    props:
      sql.show: true
      query.with.cipher.column: true
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:bs}?serverTimezone=Asia/Shanghai
        username: ${MYSQL_USER:bs}
        password: ${MYSQL_PASSWORD:bs12345}
        hikari:
          minimum-idle: 60
          maximum-pool-size: 60
          idle-timeout: 60000
          max-lifetime: 1800000
          connection-timeout: 3000
          pool-name: BabyshowHikariCP
          connection-test-query: SELECT 1
    sharding:
      default-data-source-name: ds
      tables:
        care_diary:
          key-generator:
            column: care_diary_id
            type: snowflake
        system_user:
          key-generator:
            column: system_user_id
            type: snowflake
      encrypt-rule:
        tables:
          system_user:
            columns:
              credential:
                encryptor: bs_encrypt
                cipherColumn: credential
        encryptors:
          bs_encrypt:
            type: aes
            props:
              aes.key.value: ${SHARDING_ENCRYPTOR_AES_PWD:2020$bs#0105}
```
