### ISSUE TITLE
"useServerPrepStmts=true" doesn't work

### ISSUE THREAD

**Issue by Simbafa** [apache/shardingsphere#5903]
### Which version of ShardingSphere did you use?
     apache-shardingsphere-4.1.0-sharding-proxy-bin.tar.gz
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
     ShardingSphere-Proxy
### Expected behavior
     can get data correctly
### Actual behavior
      if there are null values in a record, wrong data will be return .

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
  #3801 can be refered to create the test data.
  test.zip is the source file of a test project.
  yaml.zip includes the configuration files in conf folder.

### Example codes for reproduce this issue (such as a github link).
[test.zip](https://github.com/apache/shardingsphere/files/4722468/test.zip)
[yaml.zip](https://github.com/apache/shardingsphere/files/4722482/yaml.zip)

**Comment by tuohai666** [comment]
Please put these parameters in the datasource url of config-sharding.yaml.

`useServerPrepStmts=true&zeroDateTimeBehavior=convertToNull`

**Comment by Simbafa** [comment]
I put the parameters, the result is same.

Can you get correct data?

**Comment by tuohai666** [comment]
I can get null timestamp correctly. Please try to change the config like this:

```
schemaName: test

dataSources:
  test:
    url: jdbc:mysql://192.168.1.46:3306/test
    username: root
    password: test
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
```
