### ISSUE TITLE
how to set broadcastTables with multi-datasources

### ISSUE THREAD

**Issue by tony1991** [apache/shardingsphere#5919]
There are five datasources in my application. One datasource is A，Four datasource is B1 B2 B3 B4, I want to set a broadcastTables like tb_config in B1 B2 B3 B4, how to config?

**Comment by menghaoranss** [comment]
what's your sharding rule of the application？

**Comment by menghaoranss** [comment]
what's your sharding rule for the application？

**Comment by tony1991** [comment]
> what's your sharding rule for the application？
A is a outer db, no relation with B.
B1 B2 B3 B4 store biz data which is hashed by user_no.
now I just want to config a broadcastTables tb_config ,which need storeed same in each B(1,2,3,4)

my situation like this:
https://shardingsphere.apache.org/document/legacy/4.x/document/en/faq/#6-if-sharding-database-is-partial-should-tables-without-sharding-database--table-be-configured-in-sharding-rules

**Comment by terrymanu** [comment]
> > what's your sharding rule for the application？
> 
> A is a outer db, no relation with B.
> B1 B2 B3 B4 store biz data which is hashed by user_no.
> now I just want to config a broadcastTables tb_config ,which need storeed same in each B(1,2,3,4)
> 
> my situation like this:
> https://shardingsphere.apache.org/document/legacy/4.x/document/en/faq/#6-if-sharding-database-is-partial-should-tables-without-sharding-database--table-be-configured-in-sharding-rules

Yes, it is the correct solution.

**Comment by tony1991** [comment]
> solution



> > > what's your sharding rule for the application？
> > 
> > 
> > A is a outer db, no relation with B.
> > B1 B2 B3 B4 store biz data which is hashed by user_no.
> > now I just want to config a broadcastTables tb_config ,which need storeed same in each B(1,2,3,4)
> > my situation like this:
> > https://shardingsphere.apache.org/document/legacy/4.x/document/en/faq/#6-if-sharding-database-is-partial-should-tables-without-sharding-database--table-be-configured-in-sharding-rules
> 
> Yes, it is the correct solution.


No, i don't know how to do it. May you give me a example or demo?

**Comment by jacksparrow414** [comment]
you could config A as  defaultDataSource,and  config tb_config as the broadcast table for the other four databases.like this:
```yaml
dataSources:
names: ds0,ds1,ds2,ds3,de4,ds5
  ds0:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/A
    username: root
    password: 
  ds1: 
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:13306/B1
    username: root
    password: 
 ds2:
  url: jdbc:mysql://localhost:23306/B2
ds3:
url: jdbc:mysql://localhost:33306/B3
ds4:
url: jdbc:mysql://localhost:43306/B4
sharding:  
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds$->{id % 2}
      default-table-strategy:
        inline:
          sharding-column: age
          algorithm-expression: user_$->{age % 2}
      tables:
        user:
        # Configuration rules are not included database A
          actual-data-nodes: ds$->{1..5}.user_$->{1..5}
      default-data-source-name: ds0
      broadcast-tables: t_config
```
