### ISSUE TITLE
[New API] Automatic Sharding Strategies for Databases and Tables

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#5937]
Hi community,

As you know, ShardingSphere is not just a simple distributed database middleware. **We aim at providing transparent distributed database service to our end-users.**

Therefore, a new API is being considered to cover the detail of sharding databases and tables, making users view distributed database clusters as a single logical database. This new API looks like the below one (Please Notice the annotation),

```yaml
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false

rules:
- !SHARDING
  tables:
    t_new: # New one
      actualDataSources: ds_0, ds_1 # Notice1
      shardingStrategy: # Notice2
        standard:
          shardingColumn: order_id
          shardingAlgorithm:
            type: MOD
            props:
              mod.value: 5
    t_order: # Old one
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy:
        standard:
          shardingColumn: order_id
          shardingAlgorithm:
            type: INLINE
            props:
              algorithm.expression: t_order_${order_id % 2}
      dataBaseStrategy:
        standard:
          shardingColumn: user_id
          shardingAlgorithm:
            type: INLINE
            props:
              algorithm.expression: t_order_${user_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
```

Also, I schedule this task here, which is not an easy job, apparently. 
- [x] New API design
- [x] Configuration modification
- [x] New interface for automatic sharding algorithm
- [x] Implements the New interface
- [x] The conversation from configuration to sharding strategies
- [x] Changes for various clients, such as Spring, YAML, Proxy and so on
- [x] Tests
- [x] Move `HashShardingAlgorithm` and `ModuloShardingAlgorithm` to the new dir.
- [x] Add `init()` for `ShardingAlgorithm`
- [x] Review `@Ignore` for `rangeAlgorithm`
- [x] Make the props and partitions uniform for all algorithms
- [x] Update the old API
- [x] Remove todo in `StandardShardingStrategyConfiguration`
- [x] Remove `ShardingAutoTableAlgorithm` from `InlineShardingAlgorithm`
- [x] Remove `logic index tag` from sharding spring namespace

Notice: The new API is an enhancement for the old one, rather than replacement, i.e., **forward compatible.**

**Comment by tristaZero** [comment]
@terrymanu proposed another solution in mail list,

```yaml
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
  ds_1:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
  ds_2:
    url: jdbc:mysql://127.0.0.1:3306/demo_ds_1?serverTimezone=UTC&useSSL=false

rules:
  - !SHARDING
    mt_tables:
      t_order: # Old one
        actualDataNodes: ds_${0..1}.t_order_${0..1}
        tableStrategy:
          standard:
            shardingColumn: order_id
            shardingAlgorithm:
              type: INLINE
              props:
                algorithm.expression: t_order_${order_id % 2}
        dataBaseStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithm:
              type: INLINE
              props:
                algorithm.expression: t_order_${user_id % 2}
        keyGenerator:
          type: SNOWFLAKE
          column: order_id
    at_table:
      t_new: # New one
        actualDataSources: ds_0, ds_1 # Notice1
        shardingStrategy: # Notice2
          standard:
            shardingColumn: order_id
            shardingAlgorithm:
              type: MOD
              props:
                mod.value: 5
        keyGenerator:
          type: SNOWFLAKE
          column: order_id
```
