### ISSUE TITLE
sharding proxy route to unexpected shard

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#5964]
## Bug Report

**For English only**, other languages will not accept.

### Which version of ShardingSphere did you use?
shardingsphere 4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
shardingspehre proxy

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

Description :
here is the thing, I set up a proxy for sharding database with following configuration : 
config-sharding.yaml

```yaml
schemaName: sharding_db

dataSources:
 ds_0:
   url: jdbc:mysql://127.0.0.1:3306/target_schema_0?useSSL=false&socketTimeout=10000
   username: root
   password: root
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 5
 ds_1:
   url: jdbc:mysql://127.0.0.1:3306/target_schema_1?useSSL=false&socketTimeout=10000
   username: root
   password: root
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 5

shardingRule:
  tables:
    test_shard:
      actualDataNodes: ds_${0..1}.test
      databaseStrategy:
        inline:
          shardingColumn: f_user_id
          algorithmExpression: ds_${f_user_id % 2}
  defaultTableStrategy:
    none:
```
when I insert a data with f_user_id = 100003 through sharding proxy , I found that this data has been inserted into target_schema_0 , in another words `ds0` , that confused me , should that data inserted into ds 1 ?
