### ISSUE TITLE
Encrypt module upper and lower case cause error .

### ISSUE THREAD

**Issue by big-mountain-z** [apache/shardingsphere#6114]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
ShardingSphere-4.0.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
Sharding-jdbc

### Expected behavior
Don't match column is upper or lower case.
### Actual behavior
throw error.

### Reason analyze (If you can)
upper and lower case.
The issue like #5893 

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

```
spring: 
  shardingsphere:
    sharding: 
      encrypt-rule: 
        tables: 
          t_order: 
            columns: 
              phone:
                encryptor: encryptor_aes_salt
                plainColumn: PHONE
                assistedQueryColumn: PHONE_ASSISTED
                cipherColumn: PHONE_CIPHER
```
