### ISSUE TITLE
Describe table route error if table name arrangement not same on different schema.

### ISSUE THREAD

**Issue by chrissata** [apache/shardingsphere#6224]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.0

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy

### Expected behavior
desc table run well.

mysql> desc test;
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| id         | bigint      | NO   | PRI | NULL    | auto_increment |
| media_type | varchar(32) | NO   |     | NULL    |                |
| media_id   | bigint      | NO   |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
3 rows in set (0.03 sec)

### Actual behavior
mysql> desc test;
ERROR 1146 (42S02): Table 'base02.test_0' doesn't exist
mysql> desc test;
ERROR 1146 (42S02): Table 'base02.test_0' doesn't exist
mysql> desc test;
+------------+-------------+------+-----+---------+----------------+
| Field      | Type        | Null | Key | Default | Extra          |
+------------+-------------+------+-----+---------+----------------+
| id         | bigint      | NO   | PRI | NULL    | auto_increment |
| media_type | varchar(32) | NO   |     | NULL    |                |
| media_id   | bigint      | NO   |     | NULL    |                |
+------------+-------------+------+-----+---------+----------------+
3 rows in set (0.03 sec)
### Reason analyze (If you can)
For those DAL SQL, route engine find target error: always use the the first test_0 to query.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

    test:
      actualDataNodes: ds0.test_0, ds1.test_1

### Example codes for reproduce this issue (such as a github link).
just do desc table.

**Comment by kimmking** [comment]
where your all config rules, I guess something wrong in it.

**Comment by chrissata** [comment]
> where your all config rules, I guess something wrong in it.

The main config rule is listed already...

**test:
  actualDataNodes: ds0.test_0, ds1.test_1**

Other part rule is irrelevant with this issue.

**Comment by kimmking** [comment]
plz show all config, it's nessesary for profile this issue. @chrissata

**Comment by chrissata** [comment]
> plz show all config, it's nessesary for profile this issue. @chrissata
Hi,
The schema config is like below. Nothing special except the actualDataNodes.

```
schemaName: myschema
dataSources:
  ds0:
    url: jdbc:mysql://10.18.216.83:3306/myschema01?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: xx
    password: xxx#
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 100
  ds1:
    url: jdbc:mysql://10.18.216.84:3306/myschema02?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: xx
    password: xxx#
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 100

shardingRule:
  tables:
    test:
      actualDataNodes: ds0.test_${0..1},ds1.test_${2..3}
      databaseStrategy:
         standard:
           shardingColumn: id
           rangeAlgorithmClassName: com.hisense.shardingrule.algorithm.standard.PartitionRangeShardingDatabaseAlgorithm
           preciseAlgorithmClassName: com.hisense.shardingrule.algorithm.standard.PartitionPreciseShardingDatabaseAlgorithm
      tableStrategy:
        standard:
          shardingColumn: id
          rangeAlgorithmClassName: com.hisense.shardingrule.algorithm.standard.PartitionRangeShardingTableAlgorithm
          preciseAlgorithmClassName: com.hisense.shardingrule.algorithm.standard.PartitionPreciseShardingTableAlgorithm

  defaultDataSourceName: ds0

```
