### ISSUE TITLE
Cannot display logical table name

### ISSUE THREAD

**Issue by ericboy** [apache/shardingsphere#6334]
I have download apache-shardingsphere-4.1.1-sharding-proxy-bin.tar.gz by 
```
https://www.apache.org/dyn/closer.cgi/shardingsphere/4.1.1/apache-shardingsphere-4.1.1-sharding-proxy-bin.tar.gz
```
# Version：
sharding-proxy:4.1.0
mysql:5.7

# Configure
server.yaml
```
authentication:
 users:
   root:
     password: root
   sharding:
     password: sharding 
     authorizedSchemas: sharding_db
#
props:
 max.connections.size.per.query: 1
 acceptor.size: 16  # The default value is available processors count * 2.
 executor.size: 16  # Infinite by default.
 proxy.frontend.flush.threshold: 128  # The default value is 128.
#    # LOCAL: Proxy will run with LOCAL transaction.
#    # XA: Proxy will run with XA transaction.
#    # BASE: Proxy will run with B.A.S.E transaction.
 proxy.transaction.type: LOCAL
 proxy.opentracing.enabled: false
#  proxy.hint.enabled: false
#  query.with.cipher.column: true
 sql.show: false
#  allow.range.query.with.inline.sharding: false
```
config-sharding.yaml
```
schemaName: sharding_db

dataSources:
 ds_0:
   url: jdbc:mysql://192.168.50.111:3306/demo_ds_0?serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50
 ds_1:
   url: jdbc:mysql://192.168.50.111:3306/demo_ds_1?serverTimezone=UTC&useSSL=false
   username: root
   password: 123456
   connectionTimeoutMilliseconds: 30000
   idleTimeoutMilliseconds: 60000
   maxLifetimeMilliseconds: 1800000
   maxPoolSize: 50

shardingRule:
 tables:
   t_order:
     actualDataNodes: ds_${0..1}.t_order_${0..1}
     tableStrategy:
       inline:
         shardingColumn: order_id
         algorithmExpression: t_order_${order_id % 2}
     keyGenerator:
       type: SNOWFLAKE
       column: order_id
   t_order_item:
     actualDataNodes: ds_${0..1}.t_order_item_${0..1}
     tableStrategy:
       inline:
         shardingColumn: order_id
         algorithmExpression: t_order_item_${order_id % 2}
     keyGenerator:
       type: SNOWFLAKE
       column: order_item_id
 bindingTables:
   - t_order,t_order_item
 defaultDatabaseStrategy:
   inline:
     shardingColumn: user_id
     algorithmExpression: ds_${user_id % 2}
 defaultTableStrategy:
   none:
```
# Start
windows10 to start  <label style="color:red">start.bat</label>

# <label style="color:red">Quetion</label>
when I connection sharding-proxy , cannot see <label style="color:red">sharding_db</label>
and demos tables has create on dataSources, and I have check the configure , do not found question ,please help,
Thank you very much!
