### ISSUE TITLE
ShardingSphere-Proxy  Nested query exception in mysql data source

### ISSUE THREAD

**Issue by waterMeteors** [apache/shardingsphere#6376]
### Which version of ShardingSphere did you use?
      the version is 4.1.0.

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
      I user ShardingShpere-Proxy project.
### Expected behavior
     Return sql statement to query normal data
### Actual behavior
     Return statement is Table 'schemaName.tableName' doesn't exist. for example :'Table 'test.example_order' doesn't exist'.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
    The sharding rule file is :
------------
```
schemaName: test
dataSources:
  ds0:
    url: jdbc:mysql://ip地址:8809/test
    username: root
    password: 密码
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  ds1:
    url: jdbc:mysql://ip地址:8809/test
    username: root
    password: 密码
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
shardingRule:
  tables:
    example_order:
      actualDataNodes: ds${0..1}.example_order${0..1}
      tableStrategy:
        inline:
          shardingColumn: order_id
          algorithmExpression: example_order${order_id % 2}
      keyGenerator:
        type: SNOWFLAKE
        column: order_id
  bindingTables:
    - example_order
  defaultDatabaseStrategy:
    inline:
      shardingColumn: user_id
      algorithmExpression: ds${user_id % 2}
  defaultTableStrategy:
    none:
```
------------
The statement error when i execute "select * from (select * from example_order) aa " in navicat. if i execute "select * from example_order" that is ok.
