### ISSUE TITLE
Consider about use shortcut to config sharding algorithm for YAML

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#6486]
We are using algorithm name to config sharding strategy which has a little bit redundant.
I am consider about using sharding algorithm class name to config the yaml which can inline the configuration.
It is better to use shortcut to hide the sharding algorithm class name. The yaml config should be:

```yaml
tableStrategy:
  standard:
    shardingColumn: order_id
    !INLINE
      algorithmExpression: $->{xxx}
```
