### ISSUE TITLE
ComplexKeysShardingAlgorithm composite data types are not supported.

### ISSUE THREAD

**Issue by liyiorg** [apache/shardingsphere#6530]
Hello, When multiple shading columns are configured and the types are inconsistent, the data type conversion fails.

Version: 4.1.1

## Table

```SQL
CREATE TABLE `bin_order` (
	`transid` VARCHAR(50) NOT NULL,
	`trade_time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`transid`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;
```

## Table shading

```yaml
sharding:
        tables:
          bin_order:
            actual-data-nodes: ds.bin_order_2019,ds.bin_order_2020
            table-strategy:
              complex:
                 sharding_columns: transid,trade_time       # Multi column
                 algorithmClassName: TableComplexKeysShardingAlgorithm
```
## TableComplexKeysShardingAlgorithm
 
Only one type can be configured, but the types of the two fields are inconsistent.

```java

//There are two types of tile values, but only one can be configured.   （String, Date）
public class TableComplexKeysShardingAlgorithm  implements ComplexKeysShardingAlgorithm<String> {
    
    @Override
    public Collection<String> doSharding(Collection<String> collection, ComplexKeysShardingValue<String> complexKeysShardingValue) {
         // When get column value with [trade_time]  error, Can't convert date to string.
         complexKeysShardingValue.getColumnNameAndRangeValuesMap().get("trade_time").lowerEndpoint();
         return collection;
   }
}
```
