### ISSUE TITLE
Operation not allowed after ResultSet closed

### ISSUE THREAD

**Issue by cmonkey** [apache/shardingsphere#6606]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

upstream master commit 050f5c0ab329c5181700d900d990cfb02558ba45

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
no error
### Actual behavior
[ERROR] 12:15:52.262 [ShardingSphere-Command-8] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.sql.SQLException: Operation not allowed after ResultSet closed
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ResultSetImpl.checkClosed(ResultSetImpl.java:743)
	at com.mysql.jdbc.ResultSetImpl.checkRowPos(ResultSetImpl.java:787)
	at com.mysql.jdbc.ResultSetImpl.getObject(ResultSetImpl.java:4419)
	at com.zaxxer.hikari.pool.HikariProxyResultSet.getObject(HikariProxyResultSet.java)
	at org.apache.shardingsphere.infra.executor.sql.resourced.jdbc.queryresult.StreamQueryResult.getValue(StreamQueryResult.java:94)
	at org.apache.shardingsphere.infra.merge.result.impl.stream.StreamMergedResult.getValue(StreamMergedResult.java:47)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.getQueryData(JDBCDatabaseCommunicationEngine.java:177)
	at org.apache.shardingsphere.proxy.backend.text.query.QueryBackendHandler.getQueryData(QueryBackendHandler.java:62)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.getQueryData(MySQLComQueryPacketExecutor.java:140)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.getQueryData(MySQLComQueryPacketExecutor.java:55)
	at org.apache.shardingsphere.proxy.frontend.mysql.command.MySQLCommandExecuteEngine.writeQueryData(MySQLCommandExecuteEngine.java:89)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:111)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[ERROR] 12:15:59.657 [ShardingSphere-Command-4] o.a.s.p.f.c.CommandExecutorTask - Exception occur: 
java.util.ConcurrentModificationException: null
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:747)
	at com.google.common.collect.AbstractMapBasedMultimap.clear(AbstractMapBasedMultimap.java:288)
	at com.google.common.collect.LinkedHashMultimap.clear(LinkedHashMultimap.java:530)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.BackendConnection.releaseConnections(BackendConnection.java:322)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.BackendConnection.close(BackendConnection.java:276)
	at org.apache.shardingsphere.proxy.backend.communication.jdbc.connection.BackendConnection.close(BackendConnection.java:261)
	at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:83)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
test sql : select * from order limit 0, 10
route: all route 
test tootl : tsung

**Comment by tuohai666** [comment]
Hi @cmonkey , what's config-*.yaml and server.yaml ?

**Comment by tuohai666** [comment]
Hi @cmonkey , please also provide Connector/J version and MySQL server version.

**Comment by cmonkey** [comment]
config-sharding.yaml 
```yaml
schemaName: sharding_db

dataSourceCommon:
  username: root
  password: root
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000

dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_1:
    url: jdbc:mysql://127.0.0.1:3307/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_2:
    url: jdbc:mysql://127.0.0.1:3308/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_3:
    url: jdbc:mysql://127.0.0.1:3309/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_4:
    url: jdbc:mysql://127.0.0.1:3310/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_5:
    url: jdbc:mysql://127.0.0.1:3311/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_6:
    url: jdbc:mysql://127.0.0.1:3312/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_7:
    url: jdbc:mysql://127.0.0.1:3313/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_8:
    url: jdbc:mysql://127.0.0.1:3314/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_9:
    url: jdbc:mysql://127.0.0.1:3315/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_10:
    url: jdbc:mysql://127.0.0.1:3316/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_11:
    url: jdbc:mysql://127.0.0.1:3317/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_12:
    url: jdbc:mysql://127.0.0.1:3318/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_13:
    url: jdbc:mysql://127.0.0.1:3319/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_14:
    url: jdbc:mysql://127.0.0.1:3320/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_30:
    url: jdbc:mysql://127.0.0.1:3330/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_40:
    url: jdbc:mysql://127.0.0.1:3340/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_50:
    url: jdbc:mysql://127.0.0.1:3350/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true
  ds_60:
    url: jdbc:mysql://127.0.0.1:3360/product?serverTimezone=UTC&useSSL=false&rewriteBatchedStatements=true


rules:
- !SHARDING
  tables:
    order:
      actualDataNodes: ds_${[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,30,40,50,60]}.order
      databaseStrategy:
        complex:
          shardingColumns: instance_pk
          shardingAlgorithmName: order_detail_complex
      keyGenerateStrategy:
        column: ID
        keyGeneratorName: snowflake

  defaultTableStrategy:
    none:

  shardingAlgorithms:
    order_detail_complex:
      type: business
      props:
        dsList: ds_0,ds_1,ds_2,ds_3,ds_4,ds_5,ds_6,ds_7,ds_8,ds_9,ds_10,ds_11,ds_12,ds_13,ds_14,ds_30,ds_40,ds_50,ds_60

  keyGenerators:
      snowflake:
        type: SNOWFLAKE
        props:
            worker.id: 123
```
business algorithm return targetNames 

server.yaml 
```yaml
authentication:
  users:
    root:
      password: root
    sharding:
      password: sharding
      authorizedSchemas: sharding_db

props:
  max.connections.size.per.query: 1
  acceptor.size: 16  # The default value is available processors count * 2.
  executor.size: 16  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
    # LOCAL: Proxy will run with LOCAL transaction.
    # XA: Proxy will run with XA transaction.
    # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  proxy.cluster.enabled: false
  proxy.hint.enabled: false
  query.with.cipher.column: true
  sql.show: true
  allow.range.query.with.inline.sharding: false
  check.table.metadata.enabled: false
```
```properties
jdk version :
openjdk version "1.8.0_262"
OpenJDK Runtime Environment (build 1.8.0_262-b10)
OpenJDK 64-Bit Server VM (build 25.262-b10, mixed mode)

jvm args: default 
os version : Arch Linux x86_64
kernel version: 5.7.12-arch1-1
Mysql version: 5.7.29
Mysql Connector/J version: 8.0.19
```
