### ISSUE TITLE
Use name instead of namespace for orchestration configuration

### ISSUE THREAD

**Issue by menghaoranss** [apache/shardingsphere#6682]
Refer #6445

- [x] 1. Revise Yaml
- [x] 2. Revise SpringBoot
- [x] 3. Update examples
- [x] 4. Update documents

Yaml:
```
orchestration:
  name: orchestration_ds
  registryCenter:
    type: ZooKeeper
    serverLists: localhost:2181
    props:
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: false
```

SpringBoot:
```
spring.shardingsphere.orchestration.name=orchestration-spring-boot-demo
spring.shardingsphere.orchestration.overwrite=true

spring.shardingsphere.orchestration.registry-center.type=ZooKeeper
spring.shardingsphere.orchestration.registry-center.server-lists=localhost:2181

spring.shardingsphere.orchestration.additionalConfigCenter.type=ZooKeeper
spring.shardingsphere.orchestration.additionalConfigCenter.server-lists=localhost:2181
```
