### ISSUE TITLE
Add EncryptContext parameter to EncryptAlgorithm SPI method

### ISSUE THREAD

**Issue by WEIZIBIN** [apache/shardingsphere#6835]
### Is your feature request related to a problem?

not

### Describe the feature you would like.

In many commercial scenarios, the encryption and decryption of sensitive data requires different implementations of different fields in different tables, so the encryptor SPI should provide the context for developer (for example, table name, field name)

maybe add a parameter `EncryptContext` in EncryptAlgorithm#encrypt and EncryptAlgorithm#decrypt method?

https://github.com/apache/shardingsphere/blob/0cac7762f763ca1a2fb18ef9841ed4a246598b83/shardingsphere-features/shardingsphere-encrypt/shardingsphere-encrypt-api/src/main/java/org/apache/shardingsphere/encrypt/spi/EncryptAlgorithm.java#L34

**Comment by Lucas-307** [comment]
@WEIZIBIN HI, you can get these info from your rule config. and you can create different SPI implementations for each field that you want to encrypt.

**Comment by WEIZIBIN** [comment]
I only found algorithms that can define encryption and decryption on different fields. The actual scenario is like this. There is a key service that uses different keys to encrypt different fields in different tables. The current table name can be obtained in the encryption algorithm. The section name is useful.

> @WEIZIBIN HI, you can get these info from your rule config. and you can create different SPI implementations for each field that you want to encrypt.

I only found algorithms that can define static class name for different fields.

My actual scenario is like this. There is a remote service that store different secret for encrypting different fields.
Before encrypting, I must get the secret according to the field name . So, It is useful for me can obtained the current field name at the runtime.

**Comment by Lucas-307** [comment]
@WEIZIBIN show me your config.

**Comment by WEIZIBIN** [comment]
> @WEIZIBIN show me your config.

`  shardingsphere:
    datasource:
      names: master,slave0
      master:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url:
        username:
        password:
        maximumPoolSize: 10
        poolName: hikariPool-master
      slave0:
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        jdbc-url: 
        username: 
        password: 
        maximumPoolSize: 10
        poolName: hikariPool-slave0
    sharding:
      encrypt-rule:
        encryptors:
          my_encryptor:
            type: RemoteSecretStoreAESEncryptor
        tables:
          upms_user_t:
            columns:
              mobile:
                plainColumn: mobile
                cipherColumn: mobile_cipher
                encryptor: my_encryptor
              columns:
                address:
                  plainColumn: address
                  cipherColumn: address_cipher
                  encryptor: my_encryptor
      master-slave-rules:
        ds0:
          master-data-source-name: master
          slave-data-source-names: slave0
    props:
      query.with.cipher.column: false
      sql.show: true`

like this. thx!

**Comment by Lucas-307** [comment]
@WEIZIBIN you can create different encryptors for each, like this:
```yml
    sharding:
      encrypt-rule:
        encryptors:
          mobile_encryptor:
            type: MobileAESEncryptor
          address_encryptor:
            type: AddressAESEncryptor
        tables:
          upms_user_t:
            columns:
              mobile:
                plainColumn: mobile
                cipherColumn: mobile_cipher
                encryptor: mobile_encryptor
              address:
                plainColumn: address
                cipherColumn: address_cipher
                encryptor: address_encryptor
```

**Comment by tristaZero** [comment]
@WEIZIBIN Just a ping. What's your thought?
I think the `encrypt Rule` configuration will help you set the encrypt algorithm for specific tables and columns.

**Comment by WEIZIBIN** [comment]
> @WEIZIBIN you can create different encryptors for each, like this:
> 
> ```yaml
>     sharding:
>       encrypt-rule:
>         encryptors:
>           mobile_encryptor:
>             type: MobileAESEncryptor
>           address_encryptor:
>             type: AddressAESEncryptor
>         tables:
>           upms_user_t:
>             columns:
>               mobile:
>                 plainColumn: mobile
>                 cipherColumn: mobile_cipher
>                 encryptor: mobile_encryptor
>               address:
>                 plainColumn: address
>                 cipherColumn: address_cipher
>                 encryptor: address_encryptor
> ```

It works. but this means that an encrypted field requires a period of configuration, too many configuration for me.
If SPI method has a context would help me a lot.

**Comment by WEIZIBIN** [comment]
```
    sharding:
      encrypt-rule:
        encryptors:
          t_sample_member_name_encryptor:
            type: Remote
            props:
              table: t_sample_member
              column: name_cipher
        tables:
          t_sample_member:
            columns:
              name_cipher:
                cipherColumn: name_cipher
                encryptor: t_sample_member_name_encryptor
```
My current config use props to specific table and name is ok
