### ISSUE TITLE
4.1.0  DATA MASKING insert sql rewrite wrong

### ISSUE THREAD

**Issue by vinceLin054** [apache/shardingsphere#6881]
**When I execute the insert values containing SQL functions like now() in front of the mask field, the parameter position error occurs.**

Here is my configuration :

```
      tables:
        uc_users:
          columns:
            phone_number:
              plainColumn: phone_number
              cipherColumn: encryptor_phone_number
              encryptor: encryptor_aes
            given_name:
              plainColumn: given_name
              cipherColumn: encryptor_given_name
              encryptor: encryptor_aes
              logicColumn: given_name
```

Logic SQL:
```
INSERT INTO
         
        uc_users
     
        ( 
        created_at, updated_at, phone_number, given_name, avatar_url, password, password_strength 
     )
        VALUES
        ( 
        now(), now(), ?, ?, ?, ?, ?
     )

```
Actual SQL:
```
INSERT INTO
         
        uc_users
     
        ( 
        created_at, updated_at, encryptor_phone_number, phone_number, encryptor_given_name, given_name, avatar_url, password, pasword_strength 
     )
        VALUES
        (now(), now(), ?, ?, ?, ?, ?, ?, ?) ::: [123123123123, tom, M4RQIlytSdcEMugmk8N9qQ==, 123123123123, chd9v7LIHgzGCFAunDNSGA==, tom, 0]
```
