### ISSUE TITLE
get null table name in scaling

### ISSUE THREAD

**Issue by taojintianxia** [apache/shardingsphere#7164]
followings are my scaling configuration in postman : 

```yaml
{
   "ruleConfiguration": {
      "sourceDatasource": "sourceSchema: !!org.apache.shardingsphere.governance.core.common.yaml.config.YamlDataSourceConfiguration\n  dataSourceClassName: com.zaxxer.hikari.HikariDataSource\n  props:\n    jdbcUrl: jdbc:mysql://127.0.0.1:3306/source_schema?serverTimezone=UTC&useSSL=false\n    username: root\n    password: root\n    connectionTimeout: 30000\n    idleTimeout: 60000\n    maxLifetime: 1800000\n    maxPoolSize: 50\n    minPoolSize: 1\n    maintenanceIntervalMilliseconds: 30000\n    readOnly: false\n",
      "sourceRule": "defaultDatabaseStrategy:\n  none:\ntables:\n  t_test:\n    actualDataNodes: sourceSchema.t_test\n",
      "destinationDataSources": {
         "password": "root",
         "url": "jdbc:mysql://127.0.0.1:3306/target_schema?serverTimezone=UTC&useSSL=false",
         "username": "root"
      }
   },
   "jobConfiguration": {
      "concurrency": 3
   }
}
```

as a test demo , this config is quite simple , just migrate all data from sourceSchema to targetSchema . but I got the failed task as following screenshot ：

![image](https://user-images.githubusercontent.com/4112856/91680311-64096c80-eb7d-11ea-89cf-a41bce8a9262.png)

as we could see, the table name is null , and the task failed
