### ISSUE TITLE
spring boot nacos orchestration  problem

### ISSUE THREAD

**Issue by wencyGit** [apache/shardingsphere#7264]
- Spring boot choreography governance combined with Nacos to introduce which packages to see the document integration, was so integrated that I was about to vomit. Google search information basically failed to solve my problem
- I'm using shardingsphere version 4.1.1

**Comment by kimmking** [comment]
see this: https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-spring-boot/

**Comment by wencyGit** [comment]
- I think I should have read all the documents of sharding JDBC. It is necessary to import all jar packages. However, the following errors always occur. I don't know what jar packages I should need

![image](https://user-images.githubusercontent.com/21151964/92343109-6c215900-f0f5-11ea-8ad9-0a1f685b10f9.png)
![image](https://user-images.githubusercontent.com/21151964/92343134-7ba0a200-f0f5-11ea-95f4-7fc0b98f7700.png)
![image](https://user-images.githubusercontent.com/21151964/92343162-9115cc00-f0f5-11ea-9219-319b4ed62650.png)

**Comment by wencyGit** [comment]
@kimmking 
- Finally, we have finished the service management. With all due respect, the 4. X document is really a pit. Where to step on

![image](https://user-images.githubusercontent.com/21151964/92374124-e7086500-f131-11ea-8095-faccc3454b46.png)

```
orchestration:
  name: orchestration-sharding-data-source
  overwrite: false
  registry:
    type: zookeeper
    serverLists: localhost:2181
    namespace: sharding-sphere-orchestration
```
- The above configuration is the upper ghost. Nacos should write the following configuration

```
    orchestration:
      sharding:
        orchestrationType: config_center, registry_center
        instanceType: nacos
        serverLists: localhost:8848
        namespace: sharding
        props:
          overwrite: false
```
