### ISSUE TITLE
unconfigured table can not query with schema name because of missing rewrite 

### ISSUE THREAD

**Issue by chana71** [apache/shardingsphere#7437]
## Question

 I wish to not configure every no sharding table's actual nodes to ds0.  At version 4.1 there is one prop named `defaultDataSourceName`, after configuring it, if I query the table with its schema name `select * from schema.table` it will route to ds0 but not rewrite to ignore schema name and because of DB sharding, we actually have mapped schema  to `schema{0...3}`.

**Comment by menghaoranss** [comment]
@chana71 Please provide your configuration.

**Comment by chana71** [comment]
@menghaoranss Now I am testing on the master version. Please check.
```
schemaName: cust
dataSourceCommon:
  ...
dataSources:
  ds0:
    url: jdbc:mysql://192.168.1.175:3306/cust0?useSSL=false
  ds1:
    url: jdbc:mysql://192.168.1.175:3306/cust1?useSSL=false
  ds2:
    url: jdbc:mysql://192.168.1.186:3306/cust2?useSSL=false
  ds3:
    url: jdbc:mysql://192.168.1.186:3306/cust3?useSSL=false
rules:
  - !SHARDING
    tables:
      sched_job_extend:
        actualDataNodes: ds${0..3}.sched_job_extend
        databaseStrategy:
          standard:
            shardingAlgorithmName: database_mod
            shardingColumn: dbid
    defaultDatabaseStrategy:
      none:
    shardingAlgorithms:
      database_mod:
        type: MOD
        props:
          sharding.count: 4
```
Thx

**Comment by chana71** [comment]
@menghaoranss This is 4.1 version configuration. We have some table sharding across ds0-4 and others only exist at ds0
```
defaultDataSourceName: ds0
tables:
  
  t_order:
    actualDataNodes: ds${0..3}.t_order
    databaseStrategy:
      inline:
        algorithmExpression: ds${id% 4}
        shardingColumn: id
    logicTable: t_order
```
