### ISSUE TITLE
start proxy with no config Data Source and Sharding Configuration Instance fail

### ISSUE THREAD

**Issue by Zzshuo** [apache/shardingsphere#7501]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-Proxy
### Expected behavior
start proxy with no config Data Source and Sharding Configuration Instance and and set run Data Source and Sharding Configuration  by sharding-ui
### Actual behavior
start proxy fail
### Reason analyze (If you can)
when start proxy with start proxy with no config Data Source and Sharding Configuration Instance. ruleConfigs.isEmpty 
shardingOrchestrationFacade.init() will not set Authentication. then getAuthentication java.lang.NullPointerException

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

1. set server.yaml and not set config.yaml
```
orchestration:
  orchestration—test:
    orchestrationType: registry_center,config_center
    instanceType: zookeeper
    serverLists: 127.0.0.1:2181
    namespace: orchestration—test
    props:
      overwrite: true
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
#认证信息
authentication:
  users:
    root:
      password: root
#公用属性
props:
  max.connections.size.per.query: 1
  acceptor.size: 2  # The default value is available processors count * 2.
  executor.size: 1  # Infinite by default.
  proxy.frontend.flush.threshold: 128  # The default value is 128.
  # LOCAL: Proxy will run with LOCAL transaction.
  # XA: Proxy will run with XA transaction.
  # BASE: Proxy will run with B.A.S.E transaction.
  proxy.transaction.type: LOCAL
  proxy.opentracing.enabled: false
  proxy.hint.enabled: false
  query.with.cipher.column: true
  sql.show: true
  allow.range.query.with.inline.sharding: false
```

2. start proxy
3. start fail
![image](https://user-images.githubusercontent.com/12946820/93496726-2b6ddf00-f942-11ea-8065-3b9f5ef93af3.png)
