### ISSUE TITLE
when spring.jpa.generate-ddl: true ，jpa sometims report exception of table alread exitsts

### ISSUE THREAD

**Issue by leexiaominghub** [apache/shardingsphere#7578]
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?
4.1.1

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
JDBC

### Expected behavior
no error report

### Actual behavior
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table test_sharding_1 (account_no bigint not null, primary key (account_no)) engine=InnoDB" via JDBC Statement
Caused by: java.sql.SQLSyntaxErrorException: Table 'account_infor2' already exists

**strangely, sometime jpa will report this error, sometimes not.**

### Example codes for reproduce this issue (such as a github link).
this is appliciton.yaml:
```yaml
spring:
  shardingsphere:
    datasource:
      names: ds0, ds1
      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://10.64.136.133:3306/lxm
        username: root
        password: 
      ds1:
        type: com.zaxxer.hikari.HikariDataSource
        driver: com.p6spy.engine.spy.P6SpyDriver
        jdbc-url: jdbc:p6spy:mysql://10.62.13.33:3306/lxm1
        username: root
        password: 
    sharding:
      defaultDataSourceName: ds0
      tables:
        test_sharding_0:
          actualDataNodes: ds0.account_infor2
        test_sharding_1:
          actualDataNodes: ds1.account_infor2
  jpa:
    show-sql: true
    generate-ddl: true
```
And here are beans:
```java
@Entity
@Table(name = "test_sharding_1")
@Data
public class Account3 {

    @Id
    private Long accountNo;
}

@Entity
@Table(name = "test_sharding_0")
@Data
public class Account2 {

    @Id
    private Long accountNo;

}
```
