### ISSUE TITLE
How to configure no sharding schema in 5.0.0-RC1

### ISSUE THREAD

**Issue by lwtdev** [apache/shardingsphere#7731]
## How to configure no sharding schema in 5.0.0-RC1 ?

In 4.1.1, my configuration is like this:

```yaml
schemaName: spsqltest_nosharding
#
dataSources:
  ds_0:
    url: jdbc:mysql://127.0.0.1:3306/spsqltest_nosharding?serverTimezone=UTC&useSSL=false
    username: root
    password: root135
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
    
shardingRule:
  defaultDataSourceName: ds_0
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
```

In 5.0.0-RC1 :

```yaml
schemaName: spsqltest_nosharding
#
dataSourceCommon:
  username: root
  password: root135
  connectionTimeoutMilliseconds: 30000
  idleTimeoutMilliseconds: 60000
  maxLifetimeMilliseconds: 1800000
  maxPoolSize: 50
  minPoolSize: 1
  maintenanceIntervalMilliseconds: 30000
#
dataSources:
  ds_00:
    url: jdbc:mysql://127.0.0.1:3306/spsqltest_nosharding?serverTimezone=UTC&useSSL=false

#
rules:
- !SHARDING
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
```

But the effect is different for some SQL, such as the following:
```sql
ShardingProxy(4.1.1)No Sharding
dropTable[hasShardingKey:none];	 Support:true;	SQL: drop table customer;
ds_0|drop table customer|


ShardingProxy(5.0.0.RC1)No Sharding
dropTable[hasShardingKey:none];	 Support:false;	SQL: drop table customer;
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: This version of ShardingProxy doesn't yet support this SQL. 'Cannot find table rule with logic table: 'customer''
```
