### ISSUE TITLE
Tables without any rule configuration will be a simple and single table

### ISSUE THREAD

**Issue by tristaZero** [apache/shardingsphere#7733]
## Background
If users execute a SQL `create table t_order` without executing any RDL and no any preparative rule configuration, what will happen? I have no idea about this case, so this issue is to handle these particular cases.

## Tasks
1. Do some investigation to figure out the current process for this case (Sharding, encryption, masterSlave scenarios).

2. Support to create a table without any preparative rule configurations as a single table (See the next part).

### Basic bug-fix for single table to welcome 5.x-alpha

1. Modify `ShardingUnconfiguredTablesRoutingEngine` or create a new routing engine to get the target datasource with random algorithm, like `getRandomDataSourceName` in `ShardingUnicastRoutingEngine`.
- Just my draft idea, welcome your suggestions!

### A fantastic improvement for single table to prepare 5.x-beta

1. Create `singleTableStrategy` interface with the function like `String route(Collection<String> availableTargetNames)` using SPI way. (**Just an example, sparkle yourself!**)
- `single table` defines the tables without any rule configuration. Accordingly, `single table strategy` means which data source this type of table will be assigned to (It looks like a new table was born 😃 ).
- Please refer to `ShardingAutoTableAlgorithm` or `ShardingAlgorithm` for an example.

2. Provide some default implements for `singleTableStrategy`, like `RandomSingleTableStrategy` or `FirstSingleTableStrategy` .
- Familiar taste 😉 . We provide users some frequently-used strategies and allow users to develop their ideas!

3. Modify `ShardingUnconfiguredTablesRoutingEngine` or create a new routing engine using `singleTableStrategy` to get the target datasource name for single table.

4. Add `singleTableStrategy` YAML configuration item (**YAML API modification**). For instance,

```yaml
rules:
- !SHARDING
  tables:
    t_user:
      actualDataNodes: ds_${0..1}.t_user_${0..15}
      databaseStrategy: 
        complex:
          shardingColumns: region_id, user_id
          shardingAlgorithmName: complex_test
      tableStrategy: 
        complex:
          shardingColumns: region_id, user_id
          shardingAlgorithmName: complex_test
  bindingTables:
    - t_order, t_order_item
  broadcastTables:
    - t_config
  **singleTableStrategy: random**
  defaultDatabaseStrategy:
    standard:
      shardingColumn: order_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy: 
    none:
```
5. Add configuration item `single-table-strategy` in  `src/main/resources/META-INF/namespace/sharding.xsd`. 
- `defaultTableStrategy` could be a good reference (**Spring Namespace API modification**).

6. Create necessary tests to test creating and queries for single tables
- Test for interface and its implements of `singleTableStrategy`
- Test for routing single tables
- Test for YAML config API change
- Test for SpringNameSpace API change
- Test for SpringBoot
- Test for ShardingProxy

7. Add examples to `examples` module
8. Add documents for this feature (**The most important and key act!**)
9. Congrats! Top-notch! 👍
