### ISSUE TITLE
sql rewrite not work for select ... where  cipherColumn is null

### ISSUE THREAD

**Issue by liuchaoheliang** [apache/shardingsphere#7763]
release for 4.x
sql   case:   select * from user_info where mobile is null or mobile = ? 
rewrite result : SQL: select * from user_info where mobile is null or mobile_enc = ?
why the frist mobile column can not be rewrited?

**Comment by kimmking** [comment]
can you show your configuration?

**Comment by liuchaoheliang** [comment]
yes , very simple!
like this :
spring.shardingsphere.encrypt.encryptors.mobile_encryptor.type=mobile

spring.shardingsphere.props.query.with.cipher.column=true
spring.shardingsphere.props.sql.show=true
spring.shardingsphere.encrypt.tables.user_info.columns.mobile.cipherColumn=mobile_enc
spring.shardingsphere.encrypt.tables.user_info.columns.mobile.encryptor=mobile_encryptor



the mobile column is cipherColumn

**Comment by tristaZero** [comment]
Hi @liuchaoheliang I supposed we fixed this bug on the master branch.
```
 Logic SQL: select * from t_encrypt where user_id is null
[INFO ] 11:23:25.331 [ShardingSphere-Command-2] ShardingSphere-SQL - SQLStatement: org.apache.shardingsphere.sql.parser.sql.dialect.statement.mysql.dml.MySQLSelectStatement@3c0023c7
[INFO ] 11:23:25.331 [ShardingSphere-Command-2] ShardingSphere-SQL - Actual SQL: dataSource ::: select *  from t_encrypt where user_cipher is null
```
```yaml
rules:
- !ENCRYPT
  encryptors:
    aes_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
    md5_encryptor:
      type: MD5
  tables:
    t_encrypt:
      columns:
        user_id:
          plainColumn: user_plain
          cipherColumn: user_cipher
          encryptorName: aes_encryptor
        order_id:
          cipherColumn: order_cipher
          encryptorName: md5_encryptor
```
