### ISSUE TITLE
If i  want database sharding only,not tables。can I only set ‘defaultDatabaseStrategy’

### ISSUE THREAD

**Issue by fengshantao** [apache/shardingsphere#7786]
If i  want database sharding only,not tables。can I only set ‘defaultDatabaseStrategy’ without setting tables。PS,i am using sharding proxy

```
shardingRule:
  tables:
     t_order:
       actualDataNodes: ds${0..1}.t_order

  defaultDatabaseStrategy:
    inline:
      shardingColumn: tenet_id
      algorithmExpression: ds${tenet_id}
```

I tried，but it did not work right
