### ISSUE TITLE
shardingsphere-jdbc standard alg. initialization problem

### ISSUE THREAD

**Issue by piggytough** [apache/shardingsphere#7905]
### Which version of ShardingSphere did you use?
5.0.0-RC1-SNAPSHOT  

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### problem
standard sharding algorithm configuration not loaded

configuration below:

```
spring:
  shardingsphere:
    dataSources: 
      ...
    rules:
      sharding:
        tables:
          quantityaggregationdata:
            logicTable: quantityaggregationdata
            actualDataNodes: shardingdata.quantityaggregationdata_0_$->{0..7}
            tableStrategy:
              standard:
                shardingColumn: logtime
                shardingAlgorithmName: range-sharding
                tx: com.example.demosharding.strategy.ShardingAlgorithm
            keyGenerateStrategy:
              column: id
              keyGeneratorName: snowflake
        shardingAlgorithms:
          range-sharding:
            type: BOUNDARY_RANGE
            props:
              sharding-ranges: 0, 10, 20, 30, 40, 50, 60, 70
```

cause I cannot find some useful configuration example except for INLINE sharding, i'm not sure my config is properly set.

In my opinion, maybe the initation function's not called before doSharding. like this. 
![sharding config](https://user-images.githubusercontent.com/43106779/97069092-27e40c80-1600-11eb-86ea-3aa7ebc05baa.png)

## Maybe complex sharding's got the same problem as well.

thank you!
