### ISSUE TITLE
How to use jdbc and shardingproxy together with zookeeper?

### ISSUE THREAD

**Issue by lwtdev** [apache/shardingsphere#7944]
## Question
First , I use shardingsphere-proxy start with zookeeper. and create some schemas.

```bash
[zk: localhost:2181(CONNECTED) 31] ls /governance_ds/schemas
[ spsqltest_nosharding, spsqltest_sharding, test]
```
Then, I use shardingsphere-jdbc with zookeeper, but don't know **how to configure a init schema**.
Try to configure shardingshpere-jdbc like this:

```yaml
governance:
  name: governance_ds
  registryCenter:
    type: ZooKeeper
    serverLists: localhost:2181
  overwrite: false
```
but jdbc just use a default schema `logic_db`.

```bash
[zk: localhost:2181(CONNECTED) 32] ls /governance_ds/schemas
[logic_db, spsqltest_nosharding, spsqltest_sharding, test]
```
