### ISSUE TITLE
Can Sharding Proxy support cross databases join between sharding table and no sharding table?

### ISSUE THREAD

**Issue by XiaoleLee** [apache/shardingsphere#8025]
For example:
I have 3 databases :  `db1`, `db2`,  `db3` and 2 tables : `tb1`, `tb2`.
`tb1` is sharding table in `db1`, `db2` and `db3`.
`tb2` is no sharding table only in `db1`.

The config is almost like this : 

```
schemaName: db_test

.
.
.

shardingRule:
  tables:
    tb1:
      actualDataNodes: ds${1..3}.tb1
      databaseStrategy:
        standard:
          shardingColumn: xxx
          preciseAlgorithmClassName: xxx
          rangeAlgorithmClassName: xxx
      keyGenerator:
        type: UUID
        column: id
  defaultDataSourceName: ds1
  defaultDatabaseStrategy:
    none:
  defaultTableStrategy:
    none:
```

Then I will get a logical logic database `db_test` and 2 logic tables `tb1` , `tb2`.
Can  `tb1`  join with `tb2` ?

I have tried on Sharding Proxy 4.1.0. The log file print like  'db2.tb2 doesn`t exist'.
It seems that, sharding try to use `db2.tb2` to join with `db2.tb1`.

Can sharding use `db1.tb2` join with `db1.tb1` , `db2.tb1`, `db3.tb1` ?
And that, I may have many table used like `tb2` , so `broadcastTable`  is not suitable in this case.

Looking forward to someone answering me，thanks!
