### ISSUE TITLE
Redesign reg center persist structure of schema

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8119]
The configuredSchemaMetaData and unconfiguredSchemaMetaData are merged into same attributes in #8057.

It is necessary to adjust schema persist structure of reg center. The new structure should be:

```yaml
  tables:
    t_order:
      columns
        id:
          caseSensitive: false
          dataType: 0
          generated: false
          name: id
          primaryKey: trues
        order_id:
          caseSensitive: false
          dataType: 0
          generated: false
          name: order_id
          primaryKey: false
      indexs:
        t_user_order_id_index:
          name: t_user_order_id_index
      addressingDataSources:
        - ds_0
        - ds_1
```
