### ISSUE TITLE
How to configure "complex" table strategy in sharding-proxy-5.0.0?

### ISSUE THREAD

**Issue by ben905713861** [apache/shardingsphere#8183]
Hello professor:
I am using sharding-proxy-5.0.0,it is the newest version now.But I can not  custom configuration when I using complex table strategy.
I have build the custom jar file in "ext-lib" docoment.The class name is "com.demo.UserShardingAlgorithm".
It runs without any error,but the custom configuration is invalid.
```
rules:
- !SHARDING
  tables:

    wx_user:
      actualDataNodes: huodong-user.wx_user_${0..2}
      tableStrategy:
        complex:
          shardingColumns: wxId,openId
          shardingAlgorithmName: com.demo.UserShardingAlgorithm
```

**Comment by dongzl** [comment]
Hi @ben905713861 , can you provide the `UserShardingAlgorithm ` code?

**Comment by ben905713861** [comment]
thanks @dongzl I have slove this problem.In sharding-5+, we can not write classname in sharding config,we should use the newest SPI style to add a customer configuation in sharding-proxy-5.0.0
```
rules:
- !SHARDING
  tables:
    wx_user:
      actualDataNodes: huodong-user.wx_user_${0..2}
      tableStrategy:
        complex:
          shardingColumns: wxId,openId
          shardingAlgorithmName: wx_user_complex
      keyGenerateStrategy:
        column: wxUserId
        keyGeneratorName: snowflake
  shardingAlgorithms:
    wx_user_complex:
      type: WxUserShardingAlgorithm
```
Here is the demo to introduce how to use the SPI style in sharding-proxy-5.0.0:
[https://github.com/ben905713861/sharding5-spi-demo](url)
