### ISSUE TITLE
MySQLErrPacket  NullPointerException

### ISSUE THREAD

**Issue by xzpoul** [apache/shardingsphere#8318]
## Bug Report

**When 100 threads insert data into a table, Proxy keep throwing NullPointerException.**

**java.lang.NullPointerException: null**
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.MySQLErrPacketFactory.newInstance(MySQLErrPacketFactory.java:50)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.createErrorPacket(MySQLComQueryPacketExecutor.java:86)
	at org.apache.shardingsphere.shardingproxy.frontend.mysql.command.query.text.query.MySQLComQueryPacketExecutor.execute(MySQLComQueryPacketExecutor.java:76)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:93)
	at org.apache.shardingsphere.shardingproxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:71)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
### Which version of ShardingSphere did you use?
4.1.0
### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
 ShardingSphere-Proxy
### Expected behavior
no error
### Actual behavior
 NullPointerException
### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.
tables:
  CUSTOMER_INFO:
    actualDataNodes: ds0.CUSTOMER_INFO
    logicTable: CUSTOMER_INFO
  CUSTOMER_CARD:
    actualDataNodes: ds0.CUSTOMER_CARD
    keyGenerator:
      column: CARD_NO
      type: SNOWFLAKE
    logicTable: CUSTOMER_CARD
ds0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  properties:
    jdbcUrl: jdbc:mysql://192.168.11.11:3306/test?serverTimezone=UTC&useSSL=false
    username: 123
    password: 123
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
    readOnly: false

**Comment by tuohai666** [comment]
Hi @xzpoul If the thread count is 1, will this exception fire?

1. What is the shardingAlgorithmName?
2. Please provide the SQL.
3. Please provide server.yaml file.
4. Please set sql.show: true and provide the log.

**Comment by xzpoul** [comment]
When I insert 100 threads, I now see two phenomena. One is that during the insertion process, null pointer exceptions occur once or twice.
At this point it seems to be in a blocking state, with the CPU close to 0%. Table data is not growing either.After a while, it inserts normally.
The other is to keep throwing null Pointers.At this point, Instead of using 1 thread insert, the null pointer will also be reported.
But if the Proxy is restarted, 1 thread is fine.

1.
The shardingAlgorithmName is not used because it is a data source

2.
```
CREATE TABLE `customer_info` (
  `SYSID` bigint(20) NOT NULL AUTO_INCREMENT,
  `NAME_C` varchar(100) DEFAULT NULL,
  `NAME_P` varchar(100) DEFAULT NULL,
  `NAME_E` varchar(100) DEFAULT NULL,
  `GENDER` char(1) DEFAULT NULL,
  `CARDTYPE` char(4) DEFAULT NULL,
  `IDCARD` char(20) DEFAULT NULL,
  `MOBILE` char(20) DEFAULT NULL,
  `OFFICEPHONE` char(20) DEFAULT NULL,
  `HOMEPHONE` char(20) DEFAULT NULL,
  `MAILADDRESS` varchar(200) DEFAULT NULL,
  `HOMEADDRESS` varchar(200) DEFAULT NULL,
  `OFFICEADDRESS` varchar(200) DEFAULT NULL,
  `FLAG` char(1) DEFAULT 'Y',
  `OPENDATE` timestamp NULL DEFAULT NULL,
  `CLOSEDATE` timestamp NULL DEFAULT NULL,
  `MEMO` varchar(400) DEFAULT NULL,
  `CURMEM` int(11) DEFAULT NULL,
  `UPDATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SYSID`),
  KEY `CUSTOMER_INFO_UPDATETIME_IDX` (`UPDATETIME`)
) ENGINE=InnoDB AUTO_INCREMENT=220149 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `customer_card` (
  `SYSID` bigint(20) DEFAULT NULL,
  `NAME_P` varchar(100) DEFAULT NULL,
  `C_NO` bigint(20) NOT NULL AUTO_INCREMENT,
  `OPENDATE` timestamp NULL DEFAULT NULL,
  `TYPE` char(3) DEFAULT 'BNK',
  `EXPDATE` timestamp NULL DEFAULT NULL,
  `ACCOUNT` decimal(19,3) DEFAULT NULL,
  `CURMEM` smallint(6) DEFAULT NULL,
  `UPDATETIME` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`C_NO`),
  KEY `CUS_SYSID_IDX` (`SYSID`),
  KEY `UPDATETIME_IDX` (`UPDATETIME`)
) ENGINE=InnoDB AUTO_INCREMENT=538209984702316545 DEFAULT CHARSET=utf8mb4; 
```

[INFO ] 03:40:00.155 [ShardingSphere-Command-14] ShardingSphere-SQL - 
Actual SQL: ds0 ::: insert into CUSTOMER_INFO(SYSID, NAME_C, 
name_p, name_e, gender, cardtype, idcard, mobile,
 officephone, homephone, mailaddress, homeaddress, 
 officeaddress, flag, opendate) values(220148, '署', 
 'S', 'STS', 'F', 'NC', 10003853, '13810982345', 
 '01082312342', '01023231232', 'ixu@zcom', 
 'back log', 
'max_connect_errors', 'Y', '2020-11-25 16:39:59.937');

3.
```
executor.size: 16
allow.range.query.with.inline.sharding: false
proxy.transaction.type: LOCAL
sql.show: true
proxy.opentracing.enabled: false
query.with.cipher.column: false
proxy.frontend.flush.threshold: 128
acceptor.size: 16
max.connections.size.per.query: 1
proxy.hint.enabled: false


tables:
  CUSTOMER_INFO:
    actualDataNodes: ds0.CUSTOMER_INFO
    logicTable: CUSTOMER_INFO
  CUSTOMER_CARD:
    actualDataNodes: ds0.CUSTOMER_CARD
    keyGenerator:
      column: CARD_NO
      type: SNOWFLAKE
    logicTable: CUSTOMER_CARD

ds0: !!org.apache.shardingsphere.orchestration.core.configuration.YamlDataSourceConfiguration
  dataSourceClassName: com.zaxxer.hikari.HikariDataSource
  properties:
    jdbcUrl: jdbc:mysql://192.168.11.11:3306/test?serverTimezone=UTC&useSSL=false
    username: 123
    password: 123
    connectionTimeout: 30000
    idleTimeout: 60000
    maxLifetime: 1800000
    maxPoolSize: 50
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
    readOnly: false
```
4.
![image](https://user-images.githubusercontent.com/45033859/100209122-7446a300-2f44-11eb-92a2-1ba4a15a61b0.png)

![image](https://user-images.githubusercontent.com/45033859/100209174-845e8280-2f44-11eb-8f41-826aee43de0c.png)
