### ISSUE TITLE
Create DataSource using YamlOrchestrationShardingDataSourceFactory error

### ISSUE THREAD

**Issue by xtuer** [apache/shardingsphere#8435]
## Question
When loading configuration from Zookeeper follow the [orchestration doc](https://shardingsphere.apache.org/document/legacy/4.x/document/cn/manual/sharding-jdbc/configuration/config-yaml/#%E6%B2%BB%E7%90%86).

It throws error like:
Factory method 'dataSource' threw exception; nested exception is Cannot create property=orchestration
for JavaBean=org.apache.shardingsphere.shardingjdbc.orchestration.internal.yaml.YamlOrchestrationShardingRuleConfiguration@3aefae67
 in 'reader', line 2, column 1:
    orchestration:
    ^
No single argument constructor found for class org.apache.shardingsphere.orchestration.center.yaml.config.YamlCenterRepositoryConfiguration : null

Environment:
JDK: Java 8
Zookeeper 3.6.1
Sharding-JDBC 4.1.1

## What I did as follow:
1. import dependencies in build.gradle
```
dependencies {
	implementation (
			'org.springframework.boot:spring-boot-starter-web',
			'org.mybatis.spring.boot:mybatis-spring-boot-starter:2.1.1',
			'org.apache.shardingsphere:sharding-jdbc-core:4.1.1',

			'org.apache.shardingsphere:sharding-jdbc-orchestration:4.1.1',
	)

	implementation('org.apache.shardingsphere:sharding-orchestration-center-zookeeper-curator:4.1.1') {
		exclude group: 'org.apache.curator', module: 'curator-framework'
		exclude group: 'org.apache.curator', module: 'curator-recipes'
		exclude group: 'org.apache.curator', module: 'curator-client'
	}
	implementation(
			'org.apache.curator:curator-framework:3.3.0',
			'org.apache.curator:curator-recipes:3.3.0',
	)

	runtimeOnly('mysql:mysql-connector-java:5.1.46')

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
```

2. Sharding-JDBC yaml configuration
```
orchestration:
  name: orchestration-sharding-data-source
  overwrite: true
  registry:
    type: zookeeper
    serverLists: localhost:2181
    namespace: sharding-sphere-orchestration

dataSources:
  ds0: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0
    username: root
    password: root
  ds1: !!com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1
    username: root
    password: root

shardingRule:
  tables:
    user:
      actualDataNodes: ds${0..1}.user
      databaseStrategy:
        inline:
          shardingColumn: user_id
          algorithmExpression: ds${user_id % 2}
  defaultTableStrategy:
    none:
```

3. Create DataSource Using Java Code
```java
@Configuration
public class AppConfig {
    @Bean
    public DataSource dataSource() throws IOException, SQLException {
        File yamlCfg = new File(new ClassPathResource("sharding-jdbc.yml").getURI());
        DataSource dataSource = YamlOrchestrationShardingDataSourceFactory.createDataSource(yamlCfg);

        return dataSource;
    }
}
```

**Comment by menghaoranss** [comment]
@xtuer could you provide example codes for reproduce this issue (such as a github link).

**Comment by xtuer** [comment]
> @xtuer could you provide example codes for reproduce this issue (such as a github link).

Thank you for your reply, please access to the repo [sharding-jdbc-orchestration-test](https://github.com/xtuer/sharding-jdbc-orchestration-test) to download the project and run to reproduce the error.

**Comment by menghaoranss** [comment]
The 4.x document looks a little inconsistent, please try with the configuration below:

```
orchestration:
  demo_yaml_ds_sharding:
    orchestrationType: config_center,registry_center
    instanceType: zookeeper
    serverLists: localhost:2181
    namespace: orchestration-yaml-demo
    props:
      overwrite: true
```

And you can download the source code by [4.1.1-tag](https://github.com/apache/shardingsphere/releases/tag/4.1.1), 
there are  examples in the source code，thank you for your feedback!

**Comment by xtuer** [comment]
> The 4.x document looks a little inconsistent, please try with the configuration below:
> 
> ```
> orchestration:
>   demo_yaml_ds_sharding:
>     orchestrationType: config_center,registry_center
>     instanceType: zookeeper
>     serverLists: localhost:2181
>     namespace: orchestration-yaml-demo
>     props:
>       overwrite: true
> ```
> 
> And you can download the source code by [4.1.1-tag](https://github.com/apache/shardingsphere/releases/tag/4.1.1),
> there are examples in the source code，thank you for your feedback!

Thank you very much for you affords and follow the above configuration the Application can upload the configuration into Zookeeper and starts up successfully.

But when I **comment dataSources and shardingRule sections, and set overwrite as false** so that it can load the configurations from Zookeeper, unfortunately, it prompts errors:
```
Error creating bean with name 'dataSource' defined in class path resource [com/xtuer/AppConfig.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [javax.sql.DataSource]: Factory method 'dataSource' threw exception; nested exception is java.lang.reflect.InvocationTargetException
```

Below is the configuration above mentioned:
```
#dataSources:
#  ds0: !!com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0
#    username: root
#    password: root
#  ds1: !!com.zaxxer.hikari.HikariDataSource
#    driverClassName: com.mysql.jdbc.Driver
#    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1
#    username: root
#    password: root
#
#shardingRule:
#  tables:
#    user:
#      actualDataNodes: ds${0..1}.user
#      databaseStrategy:
#        inline:
#          shardingColumn: user_id
#          algorithmExpression: ds${user_id % 2}
#  defaultTableStrategy:
#    none:

orchestration:
  demo_yaml_ds_sharding:
    orchestrationType: config_center,registry_center
    instanceType: zookeeper
    serverLists: localhost:2181
    namespace: orchestration-yaml-demo
    props:
      overwrite: false
```
