### ISSUE TITLE
I want to know if I can just use apollo as config center without regester

### ISSUE THREAD

**Issue by fyuan1030** [apache/shardingsphere#8536]
## Question

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/shardingsphere/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response anymore and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which version of ShardingSphere did you use?

`        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-orchestration-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>`

### Which project did you use? ShardingSphere-JDBC or ShardingSphere-Proxy?
ShardingSphere-JDBC

### Expected behavior

I just want to know can I just use apollo as config center without regester

### Example codes for reproduce this issue (such as a github link).

**Comment by menghaoranss** [comment]
You can use ZK or etcd as registry center，and use apollo as config center：

```
orchestration:
  demo_apollo_yaml_ds_sharding:
    orchestrationType: config_center
    instanceType: apollo
    serverLists: localhost:8080
    namespace: namespace
    props:
      overwrite: true

  demo_zookeeper_yaml_ds_sharding:
    orchestrationType: registry_center
    instanceType: zookeeper
    serverLists: localhost:2181
    namespace: namespace
    props:
      overwrite: true
```
