### ISSUE TITLE
Support CREATE ENCRYPT RULE

### ISSUE THREAD

**Issue by terrymanu** [apache/shardingsphere#8616]
```sql
CREATE ENCRYPT RULE (
t_user pwd (cipher= 'pwdCipher', plain='pwdPlain', assist_query='pwdAssistQuery')  AES (aes-key-value='xxxxx'),
t_user other_pwd (cipher= 'otherPwdCipher')  MD5(xxx=xxxxx)
)
```

**Comment by tristaZero** [comment]
Hi how about the following  one?
```yaml
rules:
- !ENCRYPT
  tables:
    t_order:
      columns:
        status:
          cipherColumn: status
          encryptorName: status_encryptor
  encryptors:
    status_encryptor:
      type: AES
      props:
        aes-key-value: 123456abc
```

```sql
CREATE ENCRYPT RULE (
t_user (
pwd (cipher= 'pwdCipher', plain='pwdPlain', assist_query='pwdAssistQuery' AES (aes-key-value='xxxxx'),
other_pwd  (cipher= 'otherPwdCipher')  MD5(xxx=xxxxx)
),
t_order (
pwd (cipher= 'pwdCipher', plain='pwdPlain', assist_query='pwdAssistQuery' AES (aes-key-value='xxxxx'),
other_pwd  (cipher= 'otherPwdCipher')  MD5(xxx=xxxxx)
)
)
```
Or

```sql
CREATE ENCRYPT RULE (
t_user (
pwd=(cipher= 'pwdCipher', plain='pwdPlain', assist_query='pwdAssistQuery', encryptor=AES(aes-key-value='xxxxx')),
other_pwd= (cipher= 'otherPwdCipher', encryptor=MD5(xxx=xxxxx))
),
t_order (
pwd=(cipher= 'pwdCipher', plain='pwdPlain', assist_query='pwdAssistQuery', encryptor=AES(aes-key-value='xxxxx')),
other_pwd= (cipher= 'otherPwdCipher', encryptor=MD5(xxx=xxxxx))
)
)
```
