### ISSUE TITLE
spring.shardingsphere.datasource.common.是要获取什么配置信息？

### ISSUE THREAD

**Issue by liyuhang712** [apache/shardingsphere#8785]
DataSourceMapSetter.getDataSourceMap方法里需要获取spring.shardingsphere.datasource.common.前缀的配置信息。文档里没有和这个配置相关的信息。启动的时候就会报空指针

**Comment by liyuhang712** [comment]
这是我的配置文件，本意是想弄一个只分表不分库的单数据源策略.
```
spring:
  shardingsphere:
    datasource:
      names: ds
      ds:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/asb?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456!!
    rules:
      sharding:
        table:
          order:
            actual-data-nodes: ds.order_$->{0..1}
            table-strategy:
              standard:
                sharding-column: id
                sharding-algorithm-name: t-order-inline
            key-generate-strategy:
              column: id
              key-generator-name: snowflake
        binding-tables: order
        sharding-algorithms:
          t-order-inline:
            type: INLINE
            props:
              algorithm-expression: order_$->{id % 2}
        key-generators:
          snowflake:
            type: SNOWFLAKE
            props:
              worker-id: 123
```
