### ISSUE TITLE
Data desensitization  how to ignore case？

### ISSUE THREAD

**Issue by ywendy** [apache/shardingsphere#8892]
```yml
        crm_network_answer:
          columns:
            mobile:
              cipherColumn: mobile_encrypted
              encryptor: crm_encryptor

```

how to ignore case table name ？ when my project use 
INSERT INTO CRM_NETWORK_ANSWER(XXXXXX)VALUES(XXXXX)
