### ISSUE TITLE
Support "show replica_query rule"

### ISSUE THREAD

**Issue by jingshanglu** [apache/shardingsphere#8936]
## Feature Request
add support `show replica_query rule`

### Describe the feature you would like.
add support `show replica_query rule`, the result like this:

```
+-----------------------------+----------------------------------+----------------------------------+
|logicDataSourcename | primaryDataSourceName| replicaDataSourceNames|
+-----------------------------+----------------------------------+----------------------------------+
| xxxx                            | xxxxx                                | xxx                                    |
+-----------------------------+----------------------------------+----------------------------------+
```

**Comment by tristaZero** [comment]
```yaml
-rules:
- !REPLICA_QUERY
  dataSources:
    pr_ds:
      name: pr_ds
      primaryDataSourceName: primary_ds
      replicaDataSourceNames:
        - replica_ds_0
        - replica_ds_1

```
**Convert to **
```sql
name                         pr_ds
primaryDataSourceName        primary_ds
replicaDataSourceNames       replica_ds_0  replica_ds_1
```
