### ISSUE TITLE
parameter misalignment occurs when executing `case when`  in prepareStatement

### ISSUE THREAD

**Issue by odyssey1816** [apache/shardingsphere#9080]
## Question
sharding-jdbc is in the process of upgrading from 4.0.1 to 4.1.1,parameter misalignment occurs when executing `case when`  in prepareStatement
  4.0.1: sql can be executed normally
  4.1.1: Parameter misalignment after prepareStatement

### SQL
```sql
UPDATE product_sku   
SET seller_id = ( ( CASE WHEN sku_seq =? THEN ? END ) )   
WHERE  
 app_id = ?   
 AND product_seq = ?   
 AND sku_seq IN ( ? )  
```
### test program
```sql
    	String sql = "UPDATE product_sku\n" +
    	    "         set seller_id =((case when sku_seq=? then ? end))" +
    	    "        where\n" +
    	    "        app_id = ?\n" +
    	    "        and product_seq = ?\n" +
    	    "        and sku_seq in\n" +
    	    "         (  \n" +
    	    "            ?\n" +
    	    "         )";
    	try (
    	    Connection conn = dataSource.getConnection();
    	    PreparedStatement statement = conn.prepareStatement(sql)) {
    	    statement.setString(1, "seller_id1");
    	    statement.setString(2, "seller_id2");
    	    statement.setString(3, "app_id");
    	    statement.setString(4, "123456");
    	    statement.setString(5, "1234567");
    	    int i = statement.executeUpdate();
    	
    	    System.out.println("");
    	} catch (Exception e) {
    	    e.printStackTrace();
    	}
```

### sharding rule
```yml
defaultDataSourceName: product
defaultTableStrategy:
  complex:
    algorithmClassName: com.custom.sharding.algorithm.CustomShardingAlgorithm
    shardingColumns: product_seq
tables:
  product_sku:
    actualDataNodes: product.product_sku_${0..63}
    logicTable: product_sku
```
