### ISSUE TITLE
当我使用oracle 数据库并与 sharding-jdbc-spring-boot-starter 和 spring-boot 整合时，项目启动非常慢

### ISSUE THREAD

**Issue by LucienDon** [apache/shardingsphere#9431]
使用版本为4.1.1, oracle 一共有60张表,只进行了分表，我发现spring-boot 启动时, sharding-jdbc 会检索 oracle 元数据（metadata），与分表策略进行对比，这一过程非常慢（数据越多，启动越慢）,  所以我想知道如何关闭检索metadata这一过程
我的spring-boot 配置如下
```
# sharding jdbc 配置
spring:
  shardingsphere:
    datasource:
      names: ds0
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:oracle:thin:@xxxx:1521/OSSDB
        username: xxx
        password: xxx
        driver-class-name: oracle.jdbc.OracleDriver
    sharding:
      tables:
        patient:
          actual-data-nodes: ds0.PATIENT_$->{0..4}
          table-strategy:
            standard:
              precise-algorithm-class-name: djx.migratedata.config.strategy.PreciseAlgorithmForPatient
              sharding-column: PK
        exam:
          actual-data-nodes: ds0.EXAM_$->{0..4}
          table-strategy:
            complex:
              algorithm-class-name: djx.migratedata.config.strategy.ComplexAlgorithmForExam
              sharding-columns: HOSPITAL_ID,ACCESS_NUMBER
        study:
          actual-data-nodes: ds0.STUDY_$->{0..4}
          table-strategy:
            standard:
              precise-algorithm-class-name: djx.migratedata.config.strategy.PreciseAlgorithmForStudy
              sharding-column: STUDY_UID
        series:
          actual-data-nodes: ds0.SERIES_$->{0..4}
          table-strategy:
            standard:
              precise-algorithm-class-name: djx.migratedata.config.strategy.PreciseAlgorithmForStudy
              sharding-column: STUDY_UID
        inst:
          actual-data-nodes: ds0.INST_$->{0..9}
          table-strategy:
            standard:
              precise-algorithm-class-name: djx.migratedata.config.strategy.PreciseAlgorithmForStudy
              sharding-column: STUDY_UID
        files:
          actual-data-nodes: ds0.FILES_$->{0..9}
          table-strategy:
            standard:
              precise-algorithm-class-name: djx.migratedata.config.strategy.PreciseAlgorithmForStudy
              sharding-column: STUDY_UID

    props:
      check:
        table:
          metadata:
            enabled: false
```
