### ISSUE TITLE
Exception message more detail

### ISSUE THREAD

**Issue by GLBB** [apache/shardingsphere#9527]
in version: 5.0.0-RC1-SNAPSHOT

using yaml configuration, get exception message: "Exception in thread "main" java.lang.IllegalArgumentException: argument type mismatch", yaml has many lines and element, don't known which has error, hope has more detail exception, can know which line, column, element has error.

yaml configuration:
```
dataSources:
  ds_0:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: xxx
    password: 123
    autoCommit: false
  ds_1:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    jdbcUrl: jdbc:mysql://localhost:3306/demo_ds_1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: xxx
    password: 123
    autoCommit: false

rules:
- !SHARDING
  tables:
    t_order: 
      actualDataNodes: ds_${0..1}.t_order_${0..1}
      tableStrategy: 
        standard:
          shardingColumn: order_id
          shardingAlgorithmName: table_inline
      keyGenerateStrategy:
        column: order_id
        keyGeneratorName: snowflake
  defaultDatabaseStrategy:
    standard:
      shardingColumn: user_id
      shardingAlgorithmName: database_inline
  defaultTableStrategy:
    none:
  
  shardingAlgorithms:
    database_inline:
      type: INLINE
      props:
        algorithm-expression: ds_${user_id % 2}
    table_inline:
      type: INLINE
      props:
        algorithm-expression: t_order_${order_id % 2}
  
  keyGenerators:
    snowflake:
      type: SNOWFLAKE
      props:
          worker-id: 123

props:
  sql-show: false

```
situation 1:
password config error, hope give password element type mismatch instead of type mismatch.
![image](https://user-images.githubusercontent.com/24810876/109411147-e19e2000-79da-11eb-95ad-1f45d92667e3.png)

situation 2:
origin exception:
![image](https://user-images.githubusercontent.com/24810876/109411627-73f3f300-79de-11eb-9573-b2c19db37329.png)
display in console exception message:
![image](https://user-images.githubusercontent.com/24810876/109411683-d2b96c80-79de-11eb-9130-2f93b27e6069.png)
I think origin exception message "unkown database ds_0" better than "can not load table"
