### ISSUE TITLE
sharding tables error when insert

### ISSUE THREAD

**Issue by wavelet123** [apache/shardingsphere#9634]
Hi Team
We are using sharding proxy to shard 1000 tables in one database,but when we are running insert statement,we got the following errors,could you please advise?

[ERROR] 11:09:27.161 [ShardingSphere-Command-4] o.a.s.s.f.c.CommandExecutorTask - Exception occur: 
java.lang.IllegalStateException: no database route info

```yaml       
schemaName: test_friends

dataSources:
  ds_0:
    url: jdbc:mysql://xx.xx.xx.xx:3306/test_friends?serverTimezone=UTC&useSSL=false
    username: shardingadmin
    password: xxx
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 50
  shardingRule:
  tables:
    t_accountfriend:
      actualDataNodes:  ds_${0}.t_accountfriend_00${0..9},ds_${0}.t_accountfriend_0${10..99},ds_${0}.t_accountfriend_${100..999}
      tableStrategy:
        inline:
          shardingColumn: FFirstAccountID
          algorithmExpression: t_accountfriend_${FFirstAccountID % 1000}
  bindingTables:
    - t_accountfriend
  defaultDatabaseStrategy:
    inline:
      shardingColumn: FFirstAccountID
      algorithmExpression: ds_${FFirstAccountID % 1000}
  defaultTableStrategy:
    none:
  defaultDataSourceName: ds_0
```

Thanks
