### ISSUE TITLE
ShardingSphere 4.1.1 ,HintShardingAlgorithm  invalid

### ISSUE THREAD

**Issue by cnlinjie** [apache/shardingsphere#9695]
### Which version of ShardingSphere did you use?
```
 <dependency>
               <groupId>org.apache.shardingsphere</groupId>
               <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
               <version>4.1.1</version>
  </dependency>
```
### Expected behavior

config: 
```
spring:
  shardingsphere:
    datasource:
      names: db0,db1
      db0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3307/dbname
        username: root
        password: root
        initialSize: 10
        maxActive: 100
      db1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.0.10:3306/dbname
        username: root
        password: root
        initialSize: 10
        maxActive: 100
    props:
      sql:
        show: true
    sharding:
      default-data-source-name: db0
      default-database-strategy:
        hint:
          algorithm-class-name: a.b.c.d.DatabaseHintShardingAlgorithm

```

When executing sql,  enter the `doSharding` method of DatabaseHintShardingAlgorithm

### Actual behavior

Not Executed .

### Reason analyze (If you can)
![image](https://user-images.githubusercontent.com/3601638/111322212-a589e100-86a3-11eb-8bd4-84bf9497b301.png)

 
![image](https://user-images.githubusercontent.com/3601638/111322280-b9cdde00-86a3-11eb-9a3c-8300631de9ba.png)

**Comment by cnlinjie** [comment]
example: https://github.com/cnlinjie/shardingspheredemo

**Comment by cnlinjie** [comment]
@terrymanu 
@tristaZero

**Comment by tristaZero** [comment]
What's the SQL?

**Comment by cnlinjie** [comment]
> What's the SQL?
Use JPA ，That  generate the SQL : 
```
UserAppService -> save 
   insert into tb_user (username, pk_id) values (?, ?) 
UserAppService -> findAll 
    select user0_.pk_id as pk_id1_0_, user0_.username as username2_0_ from tb_user user0_


  ```

**Comment by tristaZero** [comment]
Hi Please set `sql.show` = `true`, so that we can get the parsing and routing info.

**Comment by tristaZero** [comment]
```
sharding:
      default-data-source-name: db0
      default-database-strategy:
        hint:
          algorithm-class-name: a.b.c.d.DatabaseHintShardingAlgorithm
```
There is no table-strategy?
