### ISSUE TITLE
Use the registry bug

### ISSUE THREAD

**Issue by mybug99** [apache/shardingsphere#9887]
It is normal to use sharding-jdbc

```
The jar introduced when using the registry is:
  <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>2.1.4</version>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.12</version>
        </dependency>
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>

        <!-- for spring boot -->
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-orchestration-spring-boot-starter</artifactId>
            <version>4.1.1</version>
        </dependency>
        <!--若使用zookeeper, 请加入下面Maven坐标-->
        <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-orchestration-center-zookeeper-curator</artifactId>
            <version>4.1.1</version>
        </dependency>
```

Springboot version: 2.2.9, 2.2.13, 2.3.3 versions have been tried

Master-slave configuration:

```
`spring:
  # 配置sharding-jdbc
  shardingsphere:
    datasource:
      names: datamaster0,dataslave0,dataslave1
      # 配置主节点信息
      datamaster0:
        type: com.zaxxer.hikari.HikariDataSource # 使用HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver # 使用驱动
        jdbc-url: jdbc:mysql://localhost:3306/db_mblog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true  # 连接的数据库
        username: root # 数据库用户名
        password: 123456 # 数据库密码
        connectionTimeoutMilliseconds: 30000 # 连接超时控制
        idleTimeoutMilliseconds: 60000 # 连接空闲时间设置
        maxPoolSize: 1 # 连接池中最大维持的连接数量
        minPoolSize: 1 # 连接池的最小连接数量
        maintenanceIntervalMilliseconds: 30000 # 连接维护的时间间隔 atomikos框架需求
      # 配置从节点信息
      dataslave0:
        type: com.zaxxer.hikari.HikariDataSource # 使用HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver  # 使用驱动
        jdbc-url: jdbc:mysql://localhost:3307/db_mblog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true  # 连接的数据库
        username: root # 数据库用户名
        password: 123456 # 数据库密码
        connectionTimeoutMilliseconds: 3000 # 连接超时控制
        idleTimeoutMilliseconds: 6000 # 连接空闲时间设置
        maintenanceIntervalMilliseconds: 30000 # 连接维护的时间间隔 atomikos框架需求
        maxPoolSize: 1 # 连接池中最大维持的连接数量
        minPoolSize: 1 # 连接池的最小连接数量
      dataslave1:
        type: com.zaxxer.hikari.HikariDataSource # 使用HikariDataSource
        driverClassName: com.mysql.cj.jdbc.Driver  # 使用驱动
        jdbc-url: jdbc:mysql://localhost:3308/db_mblog?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true  # 连接的数据库
        username: root # 数据库用户名
        password: 123456 # 数据库密码
        maxPoolSize: 1 # 连接池中最大维持的连接数量
        minPoolSize: 1 # 连接池的最小连接数量
        connectionTimeoutMilliseconds: 3000 # 连接超时控制
        idleTimeoutMilliseconds: 6000 # 连接空闲时间设置
        maintenanceIntervalMilliseconds: 3000 # 连接维护的时间间隔 atomikos框架需求
      props:
        sql.show: true #是否开启SQL显示，默认值: false
    masterslave:
      name: masterslave0 # 配置读写分离名称，唯一
      load-balance-algorithm-type: ROUND_ROBIN # 配置负载均衡方式
      master-data-source-name: datamaster0 # master节点
      slave-data-source-names: # 从节点信息
        - dataslave0
        - dataslave1
    orchestration:
      datamaster0:
        orchestrationType: registry_center
        instanceType: zookeeper
        serverLists: localhost:2181
        namespace: orchestration
        props:
          overwrite: false`
```

Error message: Property'sqlSessionFactory' or'sqlSessionTemplate' are required：
```
Caused by: java.lang.IllegalArgumentException: Property 'sqlSessionFactory' or 'sqlSessionTemplate' are required
	at org.springframework.util.Assert.notNull(Assert.java:201) ~[spring-core-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.mybatis.spring.support.SqlSessionDaoSupport.checkDaoConfig(SqlSessionDaoSupport.java:122) ~[mybatis-spring-2.0.6.jar:2.0.6]
	at org.mybatis.spring.mapper.MapperFactoryBean.checkDaoConfig(MapperFactoryBean.java:73) ~[mybatis-spring-2.0.6.jar:2.0.6]
	at org.springframework.dao.support.DaoSupport.afterPropertiesSet(DaoSupport.java:44) ~[spring-tx-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 30 common frames omitted
```

Now the solution: delete the following jar and it will work normally:
```

 <dependency>
            <groupId>org.apache.shardingsphere</groupId>
            <artifactId>sharding-jdbc-orchestration-spring-boot-starter</artifactId>
            <version>4.1.1</version>
  </dependency>
```
