### ISSUE TITLE
Why can't the primary key be a string?

### ISSUE THREAD

**Issue by HughWick** [apache/shardingsphere#9903]
When I use mybatis plus for data insertion, I get the following error:
```
### The error occurred while setting parameters
### SQL: INSERT INTO PING_LOGS  ( SERIAL_NO, IP, TIME, STATUS,   CREATE_DATE,     DELETE_FLAG )  VALUES  ( ?, ?, ?, ?,   ?,     ? )
### Cause: groovy.lang.MissingMethodException: No signature of method: java.lang.String.mod() is applicable for argument types: (java.lang.Integer) values: [3]
Possible solutions: drop(int), any(), find(), use([Ljava.lang.Object;), is(java.lang.Object), find(java.lang.CharSequence)
```
My entity class:
```
@Data
@TableName("PING_LOGS")
public class PingLogs2 {
    private long id;//
    @TableField("SERIAL_NO")
    private String serialNo;//
    @TableField("IP")
    private String ip;//
    @TableField("TIME")
    private double time;
    @TableField("STATUS")
    private int status;
    @TableField("REMARK")
    private String remark;
}
```
My yml configuration.
```
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.81:3306/device?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC
        username: root
        password: TH##123456$
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.81:3306/monitor_sharding?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=PRC
        username: root
        password: TH##123456$
    sharding:
      defaultDataSourceName: ds0
      tables:
        PING_LOGS:
          actualDataNodes: ds1.PING_LOGS_${0..2}
          keyGenerator:
            type: UUID
            column: SERIAL_NO
          tableStrategy:
            inline:
              shardingColumn: SERIAL_NO
              algorithmExpression: PING_LOGS_${SERIAL_NO % 3}
    props:
      sql.show: true
```
In between I also tried to use a custom primary key for the problem, but I still get the appeal error message
```
@Data
@Component
public class SimpleShardingKeyGenerator  implements ShardingKeyGenerator{

    private Properties properties = new Properties();

    @Override
    public Comparable<String> generateKey() {
        return IdSequence.snowflake();
    }

    @Override
    public String getType() {

        return "UUID";
    }
}
```
