### ISSUE TITLE
IT cannot build governance environment

### ISSUE THREAD

**Issue by JiekerTime** [apache/shardingsphere#9920]
In the JDBC governance module of the integrated testing framework, because the local zookeeper port is randomly mapped to the local, we cannot fill in the rules.xml information like the following:
```
governance:
  name: governance_ds
  registryCenter:
    type: ZooKeeper
    serverLists: zk:2181
    props:
      retryIntervalMilliseconds: 500
      timeToLiveSeconds: 60
      maxRetries: 3
      operationTimeoutMilliseconds: 500
  overwrite: true
```
We may have two ways to solve this problem.

1. Fix the local mapping port for zookeeper, but this goes against the idea of Container.
2. Implement the governance interface like Mysql, which may require code refactoring.
